<?php declare(strict_types=1);

namespace Shopware\Core\Checkout\DocumentV2\Generation;

use Shopware\Core\Checkout\Document\DocumentCollection;
use Shopware\Core\Checkout\Document\DocumentEntity;
use Shopware\Core\Checkout\Document\Renderer\RenderedDocument;
use Shopware\Core\Checkout\DocumentV2\Aggregate\DocumentFile\DocumentFileEntity;
use Shopware\Core\Checkout\DocumentV2\DocumentV2Exception;
use Shopware\Core\Checkout\DocumentV2\Renderer\DocumentRendererRegistry;
use Shopware\Core\Content\Media\MediaEntity;
use Shopware\Core\Content\Media\MediaService;
use Shopware\Core\Framework\Context;
use Shopware\Core\Framework\Log\Package;
use Symfony\Component\Filesystem\Filesystem;

/**
 * @internal
 */
#[Package('after-sales')]
final class DocumentArchiveGenerator
{
    public function __construct(
        private readonly MediaService $mediaService,
        private readonly Filesystem $filesystem,
        private readonly DocumentRendererRegistry $documentRendererRegistry,
    ) {
    }

    public function archive(DocumentCollection $documents, Context $context): ?RenderedDocument
    {
        $tempFile = tempnam(sys_get_temp_dir(), 'document-v2-');

        if ($tempFile === false) {
            throw DocumentV2Exception::documentArchiveFailed();
        }

        $archive = new \ZipArchive();

        if ($archive->open($tempFile, \ZipArchive::CREATE | \ZipArchive::OVERWRITE) !== true) {
            $this->filesystem->remove($tempFile);

            throw DocumentV2Exception::documentArchiveFailed();
        }

        try {
            $hasFiles = false;

            try {
                foreach ($documents as $document) {
                    $hasFiles = $this->writeDocumentFiles($archive, $document, $context) || $hasFiles;
                }
            } finally {
                $archive->close();
            }

            if (!$hasFiles) {
                return null;
            }

            return new RenderedDocument(
                name: $this->createArchiveName($documents),
                fileExtension: 'zip',
                contentType: 'application/zip',
                content: $this->filesystem->readFile($tempFile),
            );
        } finally {
            $this->filesystem->remove($tempFile);
        }
    }

    /**
     * Writes every file of a document, regardless if it was generated by the new document_file storage model (v2)
     * or the legacy document_media_file storage model (v1).
     * A document can hold files in both storage models, so media already written from document_file
     * is not added a second time.
     *
     * @return bool whether any files were written for this document
     */
    private function writeDocumentFiles(\ZipArchive $archive, DocumentEntity $document, Context $context): bool
    {
        $hasFiles = false;

        $mediaIds = [];
        $entryNames = [];
        foreach ($document->getDocumentFiles() ?? [] as $documentFile) {
            $media = $documentFile->getMedia();
            $entryName = $this->createEntryName($documentFile, $media, $document);
            $normalizedEntryName = strtolower($entryName);
            if (isset($entryNames[$normalizedEntryName])) {
                continue;
            }

            $content = $this->loadMediaContent($media, $context);

            if (!$archive->addFromString($entryName, $content)) {
                throw DocumentV2Exception::documentArchiveFailed();
            }

            $mediaIds[$media->getId()] = true;
            $entryNames[$normalizedEntryName] = true;
            $hasFiles = true;
        }

        foreach ([$document->getDocumentMediaFile(), $document->getDocumentA11yMediaFile()] as $media) {
            if ($media === null || isset($mediaIds[$media->getId()])) {
                continue;
            }

            $fileExtension = $media->getFileExtension();
            if ($fileExtension === null || $fileExtension === '') {
                continue;
            }

            $entryName = $this->createLegacyEntryName($media, $fileExtension, $document);
            $normalizedEntryName = strtolower($entryName);
            if (isset($entryNames[$normalizedEntryName])) {
                continue;
            }

            $content = $this->loadMediaContent($media, $context);

            if (!$archive->addFromString($entryName, $content)) {
                throw DocumentV2Exception::documentArchiveFailed();
            }

            $mediaIds[$media->getId()] = true;
            $entryNames[$normalizedEntryName] = true;
            $hasFiles = true;
        }

        return $hasFiles;
    }

    private function loadMediaContent(MediaEntity $media, Context $context): string
    {
        return $context->scope(
            Context::SYSTEM_SCOPE,
            fn (Context $scopedContext): string => $this->mediaService->loadFile($media->getId(), $scopedContext),
        );
    }

    private function createEntryName(DocumentFileEntity $documentFile, MediaEntity $media, DocumentEntity $document): string
    {
        $fileExtension = $media->getFileExtension() ?? $this->documentRendererRegistry->getFileExtension($documentFile->getDocumentFormat());

        if ($fileExtension === null) {
            throw DocumentV2Exception::documentFileExtensionUnavailable($document->getId(), $documentFile->getDocumentFormat());
        }

        $fileName = $media->getFileName() ?? $document->getId();

        return \sprintf('%s_%s.%s', $this->createOrderPrefix($document), $fileName, $fileExtension);
    }

    private function createLegacyEntryName(MediaEntity $media, string $fileExtension, DocumentEntity $document): string
    {
        $fileName = $media->getFileName() ?: $document->getId();

        return \sprintf('%s_%s.%s', $this->createOrderPrefix($document), $fileName, $fileExtension);
    }

    private function createOrderPrefix(DocumentEntity $document): string
    {
        return $document->getOrder()?->getOrderNumber() ?? $document->getOrderId();
    }

    private function createArchiveName(DocumentCollection $documents): string
    {
        if ($documents->count() !== 1) {
            return 'documents.zip';
        }

        $document = $documents->first();
        \assert($document !== null);

        $documentNumber = $document->getConfig()['documentNumber'] ?? null;
        $fileName = \is_string($documentNumber) && $documentNumber !== '' ? $documentNumber : $document->getId();

        return $fileName . '.zip';
    }
}
