<?php declare(strict_types=1);

namespace Shopware\Tests\Migration\Core\V6_7;

use Doctrine\DBAL\Connection;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\TestCase;
use Shopware\Core\Framework\Log\Package;
use Shopware\Core\Framework\Test\TestCaseBase\KernelLifecycleManager;
use Shopware\Core\Migration\V6_7\Migration1784812800RepairLegacyForeignKeys;

/**
 * @internal
 */
#[Package('framework')]
#[CoversClass(Migration1784812800RepairLegacyForeignKeys::class)]
class Migration1784812800RepairLegacyForeignKeysTest extends TestCase
{
    private Connection $connection;

    private Migration1784812800RepairLegacyForeignKeys $migration;

    protected function setUp(): void
    {
        $this->connection = KernelLifecycleManager::getConnection();
        $this->migration = new Migration1784812800RepairLegacyForeignKeys();
    }

    protected function tearDown(): void
    {
        // The migration's target state is the canonical schema, so re-running it restores
        // whatever a test broke on purpose.
        $this->migration->update($this->connection);
    }

    public function testGetCreationTimestamp(): void
    {
        static::assertSame(1784812800, $this->migration->getCreationTimestamp());
    }

    public function testCanonicalSchemaIsLeftUntouched(): void
    {
        $before = $this->fetchForeignKeys('product', 'product_manufacturer');

        $this->migration->update($this->connection);

        static::assertSame($before, $this->fetchForeignKeys('product', 'product_manufacturer'));
        static::assertSame(['fk.product.product_manufacturer'], \array_keys($before));
    }

    public function testRepairsAutoGeneratedConstraintName(): void
    {
        $this->dropForeignKeys('product', 'product_manufacturer');
        // Recreates the pre-PR-#14431 state: correct columns, auto-generated name (product_ibfk_N).
        $this->connection->executeStatement(
            'ALTER TABLE `product` ADD FOREIGN KEY (`product_manufacturer_id`, `product_manufacturer_version_id`)
             REFERENCES `product_manufacturer` (`id`, `version_id`) ON DELETE SET NULL ON UPDATE CASCADE'
        );

        $this->migration->update($this->connection);
        // Migrations must be idempotent.
        $this->migration->update($this->connection);

        $this->assertCanonicalManufacturerForeignKey();
    }

    public function testRepairsForeignKeyMissingVersionId(): void
    {
        $this->dropForeignKeys('order_line_item', 'product');
        // Recreates the oldest drift: the reference misses the version_id columns entirely.
        // MySQL 8.4 (restrict_fk_on_non_standard_key=ON) refuses to create such foreign keys,
        // so relax the guard; the variable does not exist on MariaDB.
        $previousGuard = $this->relaxFkGuard();

        try {
            $this->connection->executeStatement(
                'ALTER TABLE `order_line_item` ADD CONSTRAINT `fk.order_line_item.product`
                 FOREIGN KEY (`product_id`) REFERENCES `product` (`id`) ON DELETE SET NULL ON UPDATE CASCADE'
            );
        } finally {
            $this->restoreFkGuard($previousGuard);
        }

        $this->migration->update($this->connection);

        $foreignKeys = $this->fetchForeignKeys('order_line_item', 'product');
        static::assertArrayHasKey('fk.order_line_item.product', $foreignKeys);
        static::assertSame(
            [['product_id', 'id'], ['product_version_id', 'version_id']],
            $foreignKeys['fk.order_line_item.product']['columnPairs'],
            'the repaired foreign key must reference the complete (id, version_id) primary key'
        );
        static::assertSame('SET NULL', $foreignKeys['fk.order_line_item.product']['deleteRule']);
        static::assertSame('CASCADE', $foreignKeys['fk.order_line_item.product']['updateRule']);
    }

    public function testRecreatesMissingForeignKey(): void
    {
        $this->dropForeignKeys('product', 'product_manufacturer');

        $this->migration->update($this->connection);

        $this->assertCanonicalManufacturerForeignKey();
    }

    private function assertCanonicalManufacturerForeignKey(): void
    {
        $foreignKeys = $this->fetchForeignKeys('product', 'product_manufacturer');
        static::assertSame(['fk.product.product_manufacturer'], \array_keys($foreignKeys));
        static::assertSame(
            [['product_manufacturer_id', 'id'], ['product_manufacturer_version_id', 'version_id']],
            $foreignKeys['fk.product.product_manufacturer']['columnPairs']
        );
        static::assertSame('SET NULL', $foreignKeys['fk.product.product_manufacturer']['deleteRule']);
        static::assertSame('CASCADE', $foreignKeys['fk.product.product_manufacturer']['updateRule']);
    }

    /**
     * @return array<string, array{columnPairs: list<list<string>>, deleteRule: string, updateRule: string}>
     */
    private function fetchForeignKeys(string $table, string $referencedTable): array
    {
        $rows = $this->connection->fetchAllAssociative(
            'SELECT
                kcu.CONSTRAINT_NAME AS constraintName,
                kcu.COLUMN_NAME AS columnName,
                kcu.REFERENCED_COLUMN_NAME AS referencedColumnName,
                rc.DELETE_RULE AS deleteRule,
                rc.UPDATE_RULE AS updateRule
            FROM information_schema.KEY_COLUMN_USAGE kcu
            INNER JOIN information_schema.REFERENTIAL_CONSTRAINTS rc
                ON rc.CONSTRAINT_SCHEMA = kcu.CONSTRAINT_SCHEMA
                AND rc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME
                AND rc.TABLE_NAME = kcu.TABLE_NAME
            WHERE kcu.TABLE_SCHEMA = DATABASE()
                AND kcu.TABLE_NAME = :tableName
                AND kcu.REFERENCED_TABLE_NAME = :referencedTableName
            ORDER BY kcu.CONSTRAINT_NAME, kcu.ORDINAL_POSITION',
            ['tableName' => $table, 'referencedTableName' => $referencedTable]
        );

        $foreignKeys = [];
        foreach ($rows as $row) {
            $constraintName = (string) $row['constraintName'];
            $foreignKeys[$constraintName]['columnPairs'][] = [(string) $row['columnName'], (string) $row['referencedColumnName']];
            $foreignKeys[$constraintName]['deleteRule'] = (string) $row['deleteRule'];
            $foreignKeys[$constraintName]['updateRule'] = (string) $row['updateRule'];
        }

        return $foreignKeys;
    }

    private function dropForeignKeys(string $table, string $referencedTable): void
    {
        foreach (\array_keys($this->fetchForeignKeys($table, $referencedTable)) as $constraintName) {
            $this->connection->executeStatement(\sprintf(
                'ALTER TABLE `%s` DROP FOREIGN KEY `%s`',
                $table,
                $constraintName
            ));
        }
    }

    private function relaxFkGuard(): ?int
    {
        try {
            $previous = (int) $this->connection->fetchOne('SELECT @@SESSION.restrict_fk_on_non_standard_key');
        } catch (\Throwable) {
            return null;
        }

        $this->connection->executeStatement('SET SESSION restrict_fk_on_non_standard_key = OFF');

        return $previous;
    }

    private function restoreFkGuard(?int $previous): void
    {
        if ($previous === null) {
            return;
        }

        $this->connection->executeStatement(\sprintf('SET SESSION restrict_fk_on_non_standard_key = %d', $previous));
    }
}
