<?php declare(strict_types=1);

return [
    '71a916e745114d72abafbfdc51cbd9d0' => [
            'snippets' => [
                    'documents.index.DocumentIndexAdviceNet' => [
                            'value' => 'Please note: the recipient of the service is responsible for the tax.',
                            'origin' => 'Please note: the recipient of the service is responsible for the tax.',
                            'translationKey' => 'documents.index.DocumentIndexAdviceNet',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index.DocumentIndexComment' => [
                            'value' => 'Comment',
                            'origin' => 'Comment',
                            'translationKey' => 'documents.index.DocumentIndexComment',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index.DocumentIndexCurrency' => [
                            'value' => '
Euro Conversion factor: {$Order._currency.factor|replace:".":","}',
                            'origin' => '
Euro Conversion factor: {$Order._currency.factor|replace:".":","}',
                            'translationKey' => 'documents.index.DocumentIndexCurrency',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index.DocumentIndexCustomerID' => [
                            'value' => 'Customer No.:',
                            'origin' => 'Customer No.:',
                            'translationKey' => 'documents.index.DocumentIndexCustomerID',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index.DocumentIndexDate' => [
                            'value' => 'Date:',
                            'origin' => 'Date:',
                            'translationKey' => 'documents.index.DocumentIndexDate',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index.DocumentIndexDeliveryDate' => [
                            'value' => 'Delivery date:',
                            'origin' => 'Delivery date:',
                            'translationKey' => 'documents.index.DocumentIndexDeliveryDate',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index.DocumentIndexHeadAmount' => [
                            'value' => 'Gross total:',
                            'origin' => 'Gross total:',
                            'translationKey' => 'documents.index.DocumentIndexHeadAmount',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index.DocumentIndexHeadArticleID' => [
                            'value' => 'Art. No.',
                            'origin' => 'Art. No.',
                            'translationKey' => 'documents.index.DocumentIndexHeadArticleID',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index.DocumentIndexHeadName' => [
                            'value' => 'Description',
                            'origin' => 'Description',
                            'translationKey' => 'documents.index.DocumentIndexHeadName',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index.DocumentIndexHeadNet' => [
                            'value' => 'Net price:',
                            'origin' => 'Net price:',
                            'translationKey' => 'documents.index.DocumentIndexHeadNet',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index.DocumentIndexHeadNetAmount' => [
                            'value' => 'Net total:',
                            'origin' => 'Net total:',
                            'translationKey' => 'documents.index.DocumentIndexHeadNetAmount',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index.DocumentIndexHeadPosition' => [
                            'value' => 'Pos.',
                            'origin' => 'Pos.',
                            'translationKey' => 'documents.index.DocumentIndexHeadPosition',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index.DocumentIndexHeadPrice' => [
                            'value' => 'Gross price',
                            'origin' => 'Gross price',
                            'translationKey' => 'documents.index.DocumentIndexHeadPrice',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index.DocumentIndexHeadQuantity' => [
                            'value' => 'Quantity',
                            'origin' => 'Quantity',
                            'translationKey' => 'documents.index.DocumentIndexHeadQuantity',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index.DocumentIndexHeadTax' => [
                            'value' => 'VAT',
                            'origin' => 'VAT',
                            'translationKey' => 'documents.index.DocumentIndexHeadTax',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index.DocumentIndexInvoiceNumber' => [
                            'value' => 'Invoice No. {$Document.id}',
                            'origin' => 'Invoice No. {$Document.id}',
                            'translationKey' => 'documents.index.DocumentIndexInvoiceNumber',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index.DocumentIndexOrderID' => [
                            'value' => 'Order No.:',
                            'origin' => 'Order No.:',
                            'translationKey' => 'documents.index.DocumentIndexOrderID',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index.DocumentIndexPageCounter' => [
                            'value' => 'Page {$page+1} of {$Pages|@count}',
                            'origin' => 'Page {$page+1} of {$Pages|@count}',
                            'translationKey' => 'documents.index.DocumentIndexPageCounter',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index.DocumentIndexSelectedDispatch' => [
                            'value' => 'Selected shipping type',
                            'origin' => 'Selected shipping type',
                            'translationKey' => 'documents.index.DocumentIndexSelectedDispatch',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index.DocumentIndexSelectedPayment' => [
                            'value' => 'Selected payment method',
                            'origin' => 'Selected payment method',
                            'translationKey' => 'documents.index.DocumentIndexSelectedPayment',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index.DocumentIndexTax' => [
                            'value' => 'Plus {$key|tax} % VAT:',
                            'origin' => 'Plus {$key|tax} % VAT:',
                            'translationKey' => 'documents.index.DocumentIndexTax',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index.DocumentIndexTotal' => [
                            'value' => 'Total costs',
                            'origin' => 'Total costs',
                            'translationKey' => 'documents.index.DocumentIndexTotal',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index.DocumentIndexTotalNet' => [
                            'value' => 'Total costs net:',
                            'origin' => 'Total costs net:',
                            'translationKey' => 'documents.index.DocumentIndexTotalNet',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index.DocumentIndexUstID' => [
                            'value' => 'VAT registration number:',
                            'origin' => 'VAT registration number:',
                            'translationKey' => 'documents.index.DocumentIndexUstID',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index.DocumentIndexVoucher' => [
                            'value' => 'For the next purchase we will give you a  {$Document.voucher.value} {$Document.voucher.prefix}  voucher with the code "{$Document.voucher.code}".
',
                            'origin' => 'For the next purchase we will give you a  {$Document.voucher.value} {$Document.voucher.prefix}  voucher with the code "{$Document.voucher.code}".
',
                            'translationKey' => 'documents.index.DocumentIndexVoucher',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index_gs.DocumentIndexCreditNumber' => [
                            'value' => 'Credit No.',
                            'origin' => 'Credit No.',
                            'translationKey' => 'documents.index_gs.DocumentIndexCreditNumber',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index_ls.DocumentIndexInvoiceID' => [
                            'value' => 'For invoice',
                            'origin' => 'For invoice',
                            'translationKey' => 'documents.index_ls.DocumentIndexInvoiceID',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index_ls.DocumentIndexPageCounter' => [
                            'value' => 'Page {$page+1} of {$Pages|@count}',
                            'origin' => 'Page {$page+1} of {$Pages|@count}',
                            'translationKey' => 'documents.index_ls.DocumentIndexPageCounter',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index_ls.DocumentIndexShippingNumber' => [
                            'value' => 'Delivery note No.',
                            'origin' => 'Delivery note No.',
                            'translationKey' => 'documents.index_ls.DocumentIndexShippingNumber',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index_sr.DocumentIndexCancelationNumber' => [
                            'value' => 'Reversal invoice for invoice No. {$Document.bid}',
                            'origin' => 'Reversal invoice for invoice No. {$Document.bid}',
                            'translationKey' => 'documents.index_sr.DocumentIndexCancelationNumber',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index_sr.DocumentIndexPageCounter' => [
                            'value' => 'Page {$page+1} of {$Pages|@count}',
                            'origin' => 'Page {$page+1} of {$Pages|@count}',
                            'translationKey' => 'documents.index_sr.DocumentIndexPageCounter',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index_sr.DocumentIndexTax' => [
                            'value' => 'Plus {$key|tax} % VAT:',
                            'origin' => 'Plus {$key|tax} % VAT:',
                            'translationKey' => 'documents.index_sr.DocumentIndexTax',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index_sr.DocumentIndexTotal' => [
                            'value' => 'Total costs',
                            'origin' => 'Total costs',
                            'translationKey' => 'documents.index_sr.DocumentIndexTotal',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'documents.index_sr.DocumentIndexTotalNet' => [
                            'value' => 'Total costs net:',
                            'origin' => 'Total costs net:',
                            'translationKey' => 'documents.index_sr.DocumentIndexTotalNet',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                ],
        ],
    'b8d2230a7b324e448c9c8b22ed1b89d8' => [
            'snippets' => [
                    'documents.index.DocumentIndexAdviceNet' => [
                            'value' => 'Hinweis: Der Empfänger der Leistung schuldet die Steuer.',
                            'origin' => 'Hinweis: Der Empfänger der Leistung schuldet die Steuer.',
                            'translationKey' => 'documents.index.DocumentIndexAdviceNet',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index.DocumentIndexComment' => [
                            'value' => 'Kommentar:',
                            'origin' => 'Kommentar:',
                            'translationKey' => 'documents.index.DocumentIndexComment',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index.DocumentIndexCurrency' => [
                            'value' => '
Euro Umrechnungsfaktor: {$Order._currency.factor|replace:".":","}',
                            'origin' => '
Euro Umrechnungsfaktor: {$Order._currency.factor|replace:".":","}',
                            'translationKey' => 'documents.index.DocumentIndexCurrency',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index.DocumentIndexCustomerID' => [
                            'value' => 'Kunden-Nr.:',
                            'origin' => 'Kunden-Nr.:',
                            'translationKey' => 'documents.index.DocumentIndexCustomerID',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index.DocumentIndexDate' => [
                            'value' => 'Datum:',
                            'origin' => 'Datum:',
                            'translationKey' => 'documents.index.DocumentIndexDate',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index.DocumentIndexDeliveryDate' => [
                            'value' => 'Liefertermin:',
                            'origin' => 'Liefertermin:',
                            'translationKey' => 'documents.index.DocumentIndexDeliveryDate',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index.DocumentIndexHeadAmount' => [
                            'value' => 'Brutto Gesamt',
                            'origin' => 'Brutto Gesamt',
                            'translationKey' => 'documents.index.DocumentIndexHeadAmount',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index.DocumentIndexHeadArticleID' => [
                            'value' => 'Art-Nr.',
                            'origin' => 'Art-Nr.',
                            'translationKey' => 'documents.index.DocumentIndexHeadArticleID',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index.DocumentIndexHeadName' => [
                            'value' => 'Bezeichnung',
                            'origin' => 'Bezeichnung',
                            'translationKey' => 'documents.index.DocumentIndexHeadName',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index.DocumentIndexHeadNet' => [
                            'value' => 'Netto Preis',
                            'origin' => 'Netto Preis',
                            'translationKey' => 'documents.index.DocumentIndexHeadNet',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index.DocumentIndexHeadNetAmount' => [
                            'value' => 'Netto Gesamt',
                            'origin' => 'Netto Gesamt',
                            'translationKey' => 'documents.index.DocumentIndexHeadNetAmount',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index.DocumentIndexHeadPosition' => [
                            'value' => 'Pos.',
                            'origin' => 'Pos.',
                            'translationKey' => 'documents.index.DocumentIndexHeadPosition',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index.DocumentIndexHeadPrice' => [
                            'value' => 'Brutto Preis',
                            'origin' => 'Brutto Preis',
                            'translationKey' => 'documents.index.DocumentIndexHeadPrice',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index.DocumentIndexHeadQuantity' => [
                            'value' => 'Anz.',
                            'origin' => 'Anz.',
                            'translationKey' => 'documents.index.DocumentIndexHeadQuantity',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index.DocumentIndexHeadTax' => [
                            'value' => 'MwSt.',
                            'origin' => 'MwSt.',
                            'translationKey' => 'documents.index.DocumentIndexHeadTax',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index.DocumentIndexInvoiceNumber' => [
                            'value' => 'Rechnung Nr. {$Document.id}',
                            'origin' => 'Rechnung Nr. {$Document.id}',
                            'translationKey' => 'documents.index.DocumentIndexInvoiceNumber',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index.DocumentIndexOrderID' => [
                            'value' => 'Bestell-Nr.:',
                            'origin' => 'Bestell-Nr.:',
                            'translationKey' => 'documents.index.DocumentIndexOrderID',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index.DocumentIndexPageCounter' => [
                            'value' => 'Seite {$page+1} von {$Pages|@count}',
                            'origin' => 'Seite {$page+1} von {$Pages|@count}',
                            'translationKey' => 'documents.index.DocumentIndexPageCounter',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index.DocumentIndexSelectedDispatch' => [
                            'value' => 'Gewählte Versandart:',
                            'origin' => 'Gewählte Versandart:',
                            'translationKey' => 'documents.index.DocumentIndexSelectedDispatch',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index.DocumentIndexSelectedPayment' => [
                            'value' => 'Gewählte Zahlungsart',
                            'origin' => 'Gewählte Zahlungsart',
                            'translationKey' => 'documents.index.DocumentIndexSelectedPayment',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index.DocumentIndexTax' => [
                            'value' => 'zzgl. {$key|tax} % MwSt:',
                            'origin' => 'zzgl. {$key|tax} % MwSt:',
                            'translationKey' => 'documents.index.DocumentIndexTax',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index.DocumentIndexTotal' => [
                            'value' => 'Gesamtkosten:',
                            'origin' => 'Gesamtkosten:',
                            'translationKey' => 'documents.index.DocumentIndexTotal',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index.DocumentIndexTotalNet' => [
                            'value' => 'Gesamtkosten Netto:',
                            'origin' => 'Gesamtkosten Netto:',
                            'translationKey' => 'documents.index.DocumentIndexTotalNet',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index.DocumentIndexUstID' => [
                            'value' => 'USt-IdNr.:',
                            'origin' => 'USt-IdNr.:',
                            'translationKey' => 'documents.index.DocumentIndexUstID',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index.DocumentIndexVoucher' => [
                            'value' => 'Für den nächsten Einkauf schenken wir Ihnen einen {$Document.voucher.value} {$Document.voucher.prefix} Gutschein mit dem Code "{$Document.voucher.code}".
',
                            'origin' => 'Für den nächsten Einkauf schenken wir Ihnen einen {$Document.voucher.value} {$Document.voucher.prefix} Gutschein mit dem Code "{$Document.voucher.code}".
',
                            'translationKey' => 'documents.index.DocumentIndexVoucher',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index_gs.DocumentIndexCreditNumber' => [
                            'value' => 'Gutschrift Nr.',
                            'origin' => 'Gutschrift Nr.',
                            'translationKey' => 'documents.index_gs.DocumentIndexCreditNumber',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index_ls.DocumentIndexInvoiceID' => [
                            'value' => 'Zur Rechnung:',
                            'origin' => 'Zur Rechnung:',
                            'translationKey' => 'documents.index_ls.DocumentIndexInvoiceID',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index_ls.DocumentIndexPageCounter' => [
                            'value' => 'Seite {$page+1} von {$Pages|@count}',
                            'origin' => 'Seite {$page+1} von {$Pages|@count}',
                            'translationKey' => 'documents.index_ls.DocumentIndexPageCounter',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index_ls.DocumentIndexShippingNumber' => [
                            'value' => 'Lieferschein Nr.',
                            'origin' => 'Lieferschein Nr.',
                            'translationKey' => 'documents.index_ls.DocumentIndexShippingNumber',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index_sr.DocumentIndexCancelationNumber' => [
                            'value' => 'Stornorechnung zur Rechnung Nr. {$Document.bid}',
                            'origin' => 'Stornorechnung zur Rechnung Nr. {$Document.bid}',
                            'translationKey' => 'documents.index_sr.DocumentIndexCancelationNumber',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index_sr.DocumentIndexPageCounter' => [
                            'value' => 'Seite {$page+1} von {$Pages|@count}',
                            'origin' => 'Seite {$page+1} von {$Pages|@count}',
                            'translationKey' => 'documents.index_sr.DocumentIndexPageCounter',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index_sr.DocumentIndexTax' => [
                            'value' => 'zzgl. {$key|tax} % MwSt:',
                            'origin' => 'zzgl. {$key|tax} % MwSt:',
                            'translationKey' => 'documents.index_sr.DocumentIndexTax',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index_sr.DocumentIndexTotal' => [
                            'value' => 'Gesamtkosten:',
                            'origin' => 'Gesamtkosten:',
                            'translationKey' => 'documents.index_sr.DocumentIndexTotal',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'documents.index_sr.DocumentIndexTotalNet' => [
                            'value' => 'Gesamtkosten Netto:',
                            'origin' => 'Gesamtkosten Netto:',
                            'translationKey' => 'documents.index_sr.DocumentIndexTotalNet',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                ],
        ],
];
