<?php declare(strict_types=1);

return [
    '71a916e745114d72abafbfdc51cbd9d0' => [
        'snippets' => [
            'meta.author' => [
                'value' => '',
                'origin' => '',
                'translationKey' => 'meta.author',
                'author' => 'Shopware',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'meta.copyrightYear' => [
                'value' => '2014',
                'origin' => '2014',
                'translationKey' => 'meta.copyrightYear',
                'author' => 'Shopware',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'meta.descriptionStandard' => [
                'value' => '',
                'origin' => '',
                'translationKey' => 'meta.descriptionStandard',
                'author' => 'Shopware',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'meta.keywordsStandard' => [
                'value' => '',
                'origin' => '',
                'translationKey' => 'meta.keywordsStandard',
                'author' => 'Shopware',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'meta.revisit' => [
                'value' => '15 days',
                'origin' => '15 days',
                'translationKey' => 'meta.revisit',
                'author' => 'Shopware',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'meta.robots' => [
                'value' => 'index,follow',
                'origin' => 'index,follow',
                'translationKey' => 'meta.robots',
                'author' => 'Shopware',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'meta.xmlLang' => [
                'value' => 'en-GB',
                'origin' => 'en-GB',
                'translationKey' => 'meta.xmlLang',
                'author' => 'Shopware',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'detail.buyAddButton' => [
                'value' => 'Add to shopping cart',
                'origin' => 'Add to shopping cart',
                'translationKey' => 'detail.buyAddButton',
                'author' => 'user/admin',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'detail.configSubmit' => [
                'value' => 'Select',
                'origin' => 'Select',
                'translationKey' => 'detail.configSubmit',
                'author' => 'user/admin',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'detail.descriptionHeader' => [
                'value' => 'Product information',
                'origin' => 'Product information',
                'translationKey' => 'detail.descriptionHeader',
                'author' => 'user/admin',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'detail.descriptionMenuClose' => [
                'value' => 'Close menu',
                'origin' => 'Close menu',
                'translationKey' => 'detail.descriptionMenuClose',
                'author' => 'user/admin',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'detail.descriptionMoreInfo' => [
                'value' => 'Related links to',
                'origin' => 'Related links to',
                'translationKey' => 'detail.descriptionMoreInfo',
                'author' => 'user/fooBar',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'detail.descriptionMorePreview' => [
                'value' => ' more',
                'origin' => ' more',
                'translationKey' => 'detail.descriptionMorePreview',
                'author' => 'user/fooBar',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'detail.idLabel' => [
                'value' => 'Order number:',
                'origin' => 'Order number:',
                'translationKey' => 'detail.idLabel',
                'author' => 'Shopware',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'detail.priceInfo' => [
                'value' => ' VAT plus shipping costs',
                'origin' => ' VAT plus shipping costs',
                'translationKey' => 'detail.priceInfo',
                'author' => 'Shopware',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'detail.tabsDescription' => [
                'value' => 'Description',
                'origin' => 'Description',
                'translationKey' => 'detail.tabsDescription',
                'author' => 'Shopware',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'detail.taxExclusive' => [
                'value' => 'plus',
                'origin' => 'plus',
                'translationKey' => 'detail.taxExclusive',
                'author' => 'Shopware',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'detail.taxInclusive' => [
                'value' => 'incl.',
                'origin' => 'incl.',
                'translationKey' => 'detail.taxInclusive',
                'author' => 'Shopware',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
        ],
    ],
    'b8d2230a7b324e448c9c8b22ed1b89d8' => [
        'snippets' => [
            'meta.author' => [
                'value' => '',
                'origin' => '',
                'translationKey' => 'meta.author',
                'author' => 'Shopware',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'meta.copyrightYear' => [
                'value' => '2014',
                'origin' => '2014',
                'translationKey' => 'meta.copyrightYear',
                'author' => 'Shopware',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'meta.descriptionStandard' => [
                'value' => '',
                'origin' => '',
                'translationKey' => 'meta.descriptionStandard',
                'author' => 'Shopware',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'meta.keywordsStandard' => [
                'value' => '',
                'origin' => '',
                'translationKey' => 'meta.keywordsStandard',
                'author' => 'Shopware',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'meta.revisit' => [
                'value' => '15 days',
                'origin' => '15 days',
                'translationKey' => 'meta.revisit',
                'author' => 'Shopware',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'meta.robots' => [
                'value' => 'index,follow',
                'origin' => 'index,follow',
                'translationKey' => 'meta.robots',
                'author' => 'Shopware',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'meta.xmlLang' => [
                'value' => 'de-DE',
                'origin' => 'de-DE',
                'translationKey' => 'meta.xmlLang',
                'author' => 'Shopware',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'detail.buyAddButton' => [
                'value' => 'In den Warenkorb',
                'origin' => 'In den Warenkorb',
                'translationKey' => 'detail.buyAddButton',
                'author' => 'user/admin',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'detail.configSubmit' => [
                'value' => 'Auswahlen',
                'origin' => 'Auswahlen',
                'translationKey' => 'detail.configSubmit',
                'author' => 'user/admin',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'detail.descriptionHeader' => [
                'value' => 'Produktinformationen',
                'origin' => 'Produktinformationen',
                'translationKey' => 'detail.descriptionHeader',
                'author' => 'user/admin',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'detail.descriptionMenuClose' => [
                'value' => 'Menü schließen',
                'origin' => 'Menü schließen',
                'translationKey' => 'detail.descriptionMenuClose',
                'author' => 'user/admin',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'detail.descriptionMoreInfo' => [
                'value' => 'Weiterführende Links zu',
                'origin' => 'Weiterführende Links zu',
                'translationKey' => 'detail.descriptionMoreInfo',
                'author' => 'user/fooBar',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'detail.descriptionMorePreview' => [
                'value' => ' mehr',
                'origin' => ' mehr',
                'translationKey' => 'detail.descriptionMorePreview',
                'author' => 'user/fooBar',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'detail.idLabel' => [
                'value' => 'Artikel-Nr.:',
                'origin' => 'Artikel-Nr.:',
                'translationKey' => 'detail.idLabel',
                'author' => 'Shopware',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'detail.priceInfo' => [
                'value' => ' MwSt. zzgl. Versandkosten',
                'origin' => ' MwSt. zzgl. Versandkosten',
                'translationKey' => 'detail.priceInfo',
                'author' => 'Shopware',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'detail.tabsDescription' => [
                'value' => 'Beschreibung',
                'origin' => 'Beschreibung',
                'translationKey' => 'detail.tabsDescription',
                'author' => 'Shopware',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'detail.taxExclusive' => [
                'value' => 'zzgl.',
                'origin' => 'zzgl.',
                'translationKey' => 'detail.taxExclusive',
                'author' => 'Shopware',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'detail.taxInclusive' => [
                'value' => 'inkl.',
                'origin' => 'inkl.',
                'translationKey' => 'detail.taxInclusive',
                'author' => 'Shopware',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
        ],
    ],
];
