<?php declare(strict_types=1);

return [
    '71a916e745114d72abafbfdc51cbd9d0' => [
            'snippets' => [
                    'frontend.detail.data.priceDiscountInfo' => [
                            'value' => '',
                            'origin' => '',
                            'translationKey' => 'frontend.detail.data.priceDiscountInfo',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'frontend.detail.data.priceDiscountLabel' => [
                            'value' => '',
                            'origin' => '',
                            'translationKey' => 'frontend.detail.data.priceDiscountLabel',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'frontend.index.header.IndexMetaCopyright' => [
                            'value' => '',
                            'origin' => '',
                            'translationKey' => 'frontend.index.header.IndexMetaCopyright',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'meta.author' => [
                            'value' => '',
                            'origin' => '',
                            'translationKey' => 'meta.author',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'meta.descriptionStandard' => [
                            'value' => '',
                            'origin' => '',
                            'translationKey' => 'meta.descriptionStandard',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'meta.keywordsStandard' => [
                            'value' => '',
                            'origin' => '',
                            'translationKey' => 'meta.keywordsStandard',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'frontend.checkout.confirm.ConfirmUseForFutureOrders' => [
                            'value' => 'Use for future orders',
                            'origin' => 'Use for future orders',
                            'translationKey' => 'frontend.checkout.confirm.ConfirmUseForFutureOrders',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'frontend.detail.comment.DetailCommentInfoFillOutFields' => [
                            'value' => 'Please complete all fields marked in red.',
                            'origin' => 'Please complete all fields marked in red.',
                            'translationKey' => 'frontend.detail.comment.DetailCommentInfoFillOutFields',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'frontend.detail.config_step.DetailConfigActionSubmit' => [
                            'value' => 'Select',
                            'origin' => 'Select',
                            'translationKey' => 'frontend.detail.config_step.DetailConfigActionSubmit',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                ],
        ],
    'b8d2230a7b324e448c9c8b22ed1b89d8' => [
            'snippets' => [
                    'frontend.checkout.confirm.ConfirmUseForFutureOrders' => [
                            'value' => '',
                            'translationKey' => 'frontend.checkout.confirm.ConfirmUseForFutureOrders',
                            'author' => '',
                            'origin' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    'frontend.detail.comment.DetailCommentInfoFillOutFields' => [
                            'value' => '',
                            'translationKey' => 'frontend.detail.comment.DetailCommentInfoFillOutFields',
                            'author' => '',
                            'origin' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    'frontend.detail.config_step.DetailConfigActionSubmit' => [
                            'value' => '',
                            'translationKey' => 'frontend.detail.config_step.DetailConfigActionSubmit',
                            'author' => '',
                            'origin' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    'frontend.detail.data.priceDiscountInfo' => [
                            'value' => '',
                            'origin' => '',
                            'translationKey' => 'frontend.detail.data.priceDiscountInfo',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'frontend.detail.data.priceDiscountLabel' => [
                            'value' => '',
                            'origin' => '',
                            'translationKey' => 'frontend.detail.data.priceDiscountLabel',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'frontend.index.header.IndexMetaCopyright' => [
                            'value' => '',
                            'origin' => '',
                            'translationKey' => 'frontend.index.header.IndexMetaCopyright',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'meta.author' => [
                            'value' => '',
                            'origin' => '',
                            'translationKey' => 'meta.author',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'meta.descriptionStandard' => [
                            'value' => '',
                            'origin' => '',
                            'translationKey' => 'meta.descriptionStandard',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'meta.keywordsStandard' => [
                            'value' => '',
                            'origin' => '',
                            'translationKey' => 'meta.keywordsStandard',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                ],
        ],
];
