<?php declare(strict_types=1);

return [
    '71a916e745114d72abafbfdc51cbd9d0' => [
        'snippets' => [
            'documents.index.DocumentIndexAdviceNet' => [
                'value' => 'Please note: the recipient of the service is responsible for the tax.',
                'origin' => 'Please note: the recipient of the service is responsible for the tax.',
                'translationKey' => 'documents.index.DocumentIndexAdviceNet',
                'author' => 'Shopware',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'frontend.CheckoutArticleLessStock' => [
                'value' => 'Unfortunately, the requested product is not deliverable in the desired quantities. (#0 of #1 deliverable).',
                'origin' => 'Unfortunately, the requested product is not deliverable in the desired quantities. (#0 of #1 deliverable).',
                'translationKey' => 'frontend.CheckoutArticleLessStock',
                'author' => 'Shopware',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'frontend.CheckoutArticleNoStock' => [
                'value' => 'Unfortunately, the requested product is no longer available in the desired quantities.',
                'origin' => 'Unfortunately, the requested product is no longer available in the desired quantities.',
                'translationKey' => 'frontend.CheckoutArticleNoStock',
                'author' => 'Shopware',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'frontend.account.ajax_login.LoginInfoNew' => [
                'value' => 'No problem, a shop order is easy and secure. The registration only takes a few moments.',
                'origin' => 'No problem, a shop order is easy and secure. The registration only takes a few moments.',
                'translationKey' => 'frontend.account.ajax_login.LoginInfoNew',
                'author' => 'Shopware',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'frontend.account.login.LoginInfoNew' => [
                'value' => 'No problem! A shop order is easy and secure. The registration only takes a few minutes. ',
                'origin' => 'No problem! A shop order is easy and secure. The registration only takes a few minutes. ',
                'translationKey' => 'frontend.account.login.LoginInfoNew',
                'author' => 'Shopware',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'frontend.checkout.confirm_footer.CheckoutFinishTaxInformation' => [
                'value' => 'The recipient of the service owes the tax',
                'origin' => 'The recipient of the service owes the tax',
                'translationKey' => 'frontend.checkout.confirm_footer.CheckoutFinishTaxInformation',
                'author' => 'Shopware',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'frontend.checkout.finish_footer.CheckoutFinishTaxInformation' => [
                'value' => 'The recipient of the service owes the tax',
                'origin' => 'The recipient of the service owes the tax',
                'translationKey' => 'frontend.checkout.finish_footer.CheckoutFinishTaxInformation',
                'author' => 'Shopware',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'frontend.register.index.RegisterInfoSupplier3' => [
                'value' => 'After the registration you will be displayed the retail prices until your account has been verified.',
                'origin' => 'After the registration you will be displayed the retail prices until your account has been verified.',
                'translationKey' => 'frontend.register.index.RegisterInfoSupplier3',
                'author' => 'Shopware',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'frontend.tellafriend.index.TellAFriendHeaderSuccess' => [
                'value' => 'Thank you! The recommendation has been forwarded successfully!',
                'origin' => 'Thank you! The recommendation has been forwarded successfully!',
                'translationKey' => 'frontend.tellafriend.index.TellAFriendHeaderSuccess',
                'author' => 'Shopware',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'themes.responsive.backend.config.color_scheme_black_description' => [
                'value' => 'Configures the responsive theme with different black tones',
                'origin' => 'Configures the responsive theme with different black tones',
                'translationKey' => 'themes.responsive.backend.config.color_scheme_black_description',
                'author' => 'Shopware',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'themes.responsive.backend.config.color_scheme_blue_description' => [
                'value' => 'Configures the responsive theme with different blue tones',
                'origin' => 'Configures the responsive theme with different blue tones',
                'translationKey' => 'themes.responsive.backend.config.color_scheme_blue_description',
                'author' => 'Shopware',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'themes.responsive.backend.config.color_scheme_brown_description' => [
                'value' => 'Configures the responsive theme with different brown tones',
                'origin' => 'Configures the responsive theme with different brown tones',
                'translationKey' => 'themes.responsive.backend.config.color_scheme_brown_description',
                'author' => 'Shopware',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'themes.responsive.backend.config.color_scheme_gray_description' => [
                'value' => 'Configures the responsive theme with different gray tones',
                'origin' => 'Configures the responsive theme with different gray tones',
                'translationKey' => 'themes.responsive.backend.config.color_scheme_gray_description',
                'author' => 'Shopware',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'themes.responsive.backend.config.color_scheme_green_description' => [
                'value' => 'Configures the responsive theme with different green tones',
                'origin' => 'Configures the responsive theme with different green tones',
                'translationKey' => 'themes.responsive.backend.config.color_scheme_green_description',
                'author' => 'Shopware',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'themes.responsive.backend.config.color_scheme_orange_description' => [
                'value' => 'Configures the responsive theme with different orange tones',
                'origin' => 'Configures the responsive theme with different orange tones',
                'translationKey' => 'themes.responsive.backend.config.color_scheme_orange_description',
                'author' => 'Shopware',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'themes.responsive.backend.config.color_scheme_pink_description' => [
                'value' => 'Configures the responsive theme with different pink tones',
                'origin' => 'Configures the responsive theme with different pink tones',
                'translationKey' => 'themes.responsive.backend.config.color_scheme_pink_description',
                'author' => 'Shopware',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'themes.responsive.backend.config.color_scheme_red_description' => [
                'value' => 'Configures the responsive theme with different red tones',
                'origin' => 'Configures the responsive theme with different red tones',
                'translationKey' => 'themes.responsive.backend.config.color_scheme_red_description',
                'author' => 'Shopware',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
            'themes.responsive.backend.config.color_scheme_turquoise_description' => [
                'value' => 'Configures the responsive theme with different turquoise tones',
                'origin' => 'Configures the responsive theme with different turquoise tones',
                'translationKey' => 'themes.responsive.backend.config.color_scheme_turquoise_description',
                'author' => 'Shopware',
                'id' => null,
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
            ],
        ],
    ],
    'b8d2230a7b324e448c9c8b22ed1b89d8' => [
        'snippets' => [
            'documents.index.DocumentIndexAdviceNet' => [
                'value' => 'Hinweis: Der Empfänger der Leistung schuldet die Steuer.',
                'origin' => 'Hinweis: Der Empfänger der Leistung schuldet die Steuer.',
                'translationKey' => 'documents.index.DocumentIndexAdviceNet',
                'author' => 'Shopware',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'frontend.CheckoutArticleLessStock' => [
                'value' => 'Leider können wir den von Ihnen gewünschten Artikel nicht mehr in ausreichender Stückzahl liefern.',
                'origin' => 'Leider können wir den von Ihnen gewünschten Artikel nicht mehr in ausreichender Stückzahl liefern.',
                'translationKey' => 'frontend.CheckoutArticleLessStock',
                'author' => 'Shopware',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'frontend.CheckoutArticleNoStock' => [
                'value' => 'Das Produkt konnte nicht gefunden werden.',
                'origin' => 'Das Produkt konnte nicht gefunden werden.',
                'translationKey' => 'frontend.CheckoutArticleNoStock',
                'author' => 'Shopware',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'frontend.account.ajax_login.LoginInfoNew' => [
                'value' => 'Kein Problem, eine Shopbestellung ist einfach und sicher. Die Anmeldung dauert nur wenige Augenblicke.',
                'origin' => 'Kein Problem, eine Shopbestellung ist einfach und sicher. Die Anmeldung dauert nur wenige Augenblicke.',
                'translationKey' => 'frontend.account.ajax_login.LoginInfoNew',
                'author' => 'Shopware',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'frontend.account.login.LoginInfoNew' => [
                'value' => 'Kein Problem, eine Shopbestellung ist einfach und sicher. Die Anmeldung dauert nur wenige Augenblicke.',
                'origin' => 'Kein Problem, eine Shopbestellung ist einfach und sicher. Die Anmeldung dauert nur wenige Augenblicke.',
                'translationKey' => 'frontend.account.login.LoginInfoNew',
                'author' => 'Shopware',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'frontend.checkout.confirm_footer.CheckoutFinishTaxInformation' => [
                'value' => 'Der Empfänger der Leistung schuldet die Steuer',
                'origin' => 'Der Empfänger der Leistung schuldet die Steuer',
                'translationKey' => 'frontend.checkout.confirm_footer.CheckoutFinishTaxInformation',
                'author' => 'Shopware',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'frontend.checkout.finish_footer.CheckoutFinishTaxInformation' => [
                'value' => 'Der Empfänger der Leistung schuldet die Steuer',
                'origin' => 'Der Empfänger der Leistung schuldet die Steuer',
                'translationKey' => 'frontend.checkout.finish_footer.CheckoutFinishTaxInformation',
                'author' => 'Shopware',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'frontend.register.index.RegisterInfoSupplier3' => [
                'value' => 'Nach der Anmeldung sehen Sie bis zur Freischaltung Endkunden-Preise',
                'origin' => 'Nach der Anmeldung sehen Sie bis zur Freischaltung Endkunden-Preise',
                'translationKey' => 'frontend.register.index.RegisterInfoSupplier3',
                'author' => 'Shopware',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'frontend.tellafriend.index.TellAFriendHeaderSuccess' => [
                'value' => 'Vielen Dank. Die Weiterempfehlung wurde erfolgreich verschickt.',
                'origin' => 'Vielen Dank. Die Weiterempfehlung wurde erfolgreich verschickt.',
                'translationKey' => 'frontend.tellafriend.index.TellAFriendHeaderSuccess',
                'author' => 'Shopware',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'themes.responsive.backend.config.color_scheme_black_description' => [
                'value' => 'Konfiguriert die Farben des Responsive Themes mit unterschiedlichen Schwarz-Tönen',
                'origin' => 'Konfiguriert die Farben des Responsive Themes mit unterschiedlichen Schwarz-Tönen',
                'translationKey' => 'themes.responsive.backend.config.color_scheme_black_description',
                'author' => 'Shopware',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'themes.responsive.backend.config.color_scheme_blue_description' => [
                'value' => 'Konfiguriert die Farben des Responsive Themes mit unterschiedlichen Blau-Tönen',
                'origin' => 'Konfiguriert die Farben des Responsive Themes mit unterschiedlichen Blau-Tönen',
                'translationKey' => 'themes.responsive.backend.config.color_scheme_blue_description',
                'author' => 'Shopware',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'themes.responsive.backend.config.color_scheme_brown_description' => [
                'value' => 'Konfiguriert die Farben des Responsive Themes mit unterschiedlichen Braun-Tönen',
                'origin' => 'Konfiguriert die Farben des Responsive Themes mit unterschiedlichen Braun-Tönen',
                'translationKey' => 'themes.responsive.backend.config.color_scheme_brown_description',
                'author' => 'Shopware',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'themes.responsive.backend.config.color_scheme_gray_description' => [
                'value' => 'Konfiguriert die Farben des Responsive Themes mit unterschiedlichen Grau-Tönen',
                'origin' => 'Konfiguriert die Farben des Responsive Themes mit unterschiedlichen Grau-Tönen',
                'translationKey' => 'themes.responsive.backend.config.color_scheme_gray_description',
                'author' => 'Shopware',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'themes.responsive.backend.config.color_scheme_green_description' => [
                'value' => 'Konfiguriert die Farben des Responsive Themes mit unterschiedlichen Grün-Tönen',
                'origin' => 'Konfiguriert die Farben des Responsive Themes mit unterschiedlichen Grün-Tönen',
                'translationKey' => 'themes.responsive.backend.config.color_scheme_green_description',
                'author' => 'Shopware',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'themes.responsive.backend.config.color_scheme_orange_description' => [
                'value' => 'Konfiguriert die Farben des Responsive Themes mit unterschiedlichen Orange-Tönen',
                'origin' => 'Konfiguriert die Farben des Responsive Themes mit unterschiedlichen Orange-Tönen',
                'translationKey' => 'themes.responsive.backend.config.color_scheme_orange_description',
                'author' => 'Shopware',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'themes.responsive.backend.config.color_scheme_pink_description' => [
                'value' => 'Konfiguriert die Farben des Responsive Themes mit unterschiedlichen Pink-Tönen',
                'origin' => 'Konfiguriert die Farben des Responsive Themes mit unterschiedlichen Pink-Tönen',
                'translationKey' => 'themes.responsive.backend.config.color_scheme_pink_description',
                'author' => 'Shopware',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'themes.responsive.backend.config.color_scheme_red_description' => [
                'value' => 'Konfiguriert die Farben des Responsive Themes mit unterschiedlichen Rot-Tönen',
                'origin' => 'Konfiguriert die Farben des Responsive Themes mit unterschiedlichen Rot-Tönen',
                'translationKey' => 'themes.responsive.backend.config.color_scheme_red_description',
                'author' => 'Shopware',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
            'themes.responsive.backend.config.color_scheme_turquoise_description' => [
                'value' => 'Konfiguriert die Farben des Responsive Themes mit unterschiedlichen Türkis-Tönen',
                'origin' => 'Konfiguriert die Farben des Responsive Themes mit unterschiedlichen Türkis-Tönen',
                'translationKey' => 'themes.responsive.backend.config.color_scheme_turquoise_description',
                'author' => 'Shopware',
                'id' => null,
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
            ],
        ],
    ],
];
