<?php declare(strict_types=1);

namespace Shopware\Core\Content\Media\Path\Contract\Service;

use Shopware\Core\Framework\Log\Package;

/**
 * Updater for the storage path of media and thumbnails
 *
 * The updater is responsible to update the path of media and thumbnails in the database.
 * The path has to be generated by the configured media path strategy and triggered when the media was uploaded and already stored in the database with the current state.
 * It will be triggered when the media was uploaded and already stored in the database with the current state.
 * The corresponding locations can be fetched by the `MediaLocationBuilder`.
 *
 * @public
 */
#[Package('content')]
abstract class AbstractMediaPathUpdater
{
    /**
     * Updates the path of media
     *
     * The `updateMedia` method is called when the media was uploaded and already stored in the database with the current state.
     * It is responsible to update the path of the media in the database.
     *
     * @param array<string> $ids
     */
    abstract public function updateMedia(array $ids): void;

    /**
     * Updates the path of thumbnails
     *
     * The `updateThumbnails` method is called when the media was uploaded and already stored in the database with the current state.
     * It is responsible to update the path of the thumbnails in the database.
     *
     * @param array<string> $ids
     */
    abstract public function updateThumbnails(array $ids): void;
}
