<?php declare(strict_types=1);

namespace Shopware\Core\Content\Media\Path\Contract\Service;

/**
 * Url generator for media and thumbnails
 *
 * The url generator is called at runtime to generate the absolute urls for the media and thumbnails.
 * Generated urls are based on the stored paths in the database.
 *
 * @public
 */
abstract class AbstractUrlGenerator
{
    /**
     * Builds relative urls for the given paths
     *
     * The provided paths are the stored paths in the database. By default, shopware don't manipulate the paths at this point.
     * This entry point allows developers, to extend the path at this point
     *
     * @param array<string, string> $paths indexed by id, value contains the path
     *
     * @return array<string, string> indexed by id, value contains the relative url (e.g. media/0a/test.jpg)
     */
    abstract public function buildRelative(array $paths): array;

    /**
     * Builds absolute urls for the given paths
     *
     * The provided paths must be relative paths (e.g. media/0a/test.jpg). The absolute url is generated by the configured filesystem.
     * The relative paths are stored in the database and the absolute urls are generated on the fly.
     *
     * @param array<string, string> $paths indexed by id, value contains the path
     *
     * @return array<string, string|null> indexed by id, value contains the absolute url (e.g. https://my.shop.de/media/0a/test.jpg)
     */
    abstract public function buildAbsolute(array $paths): array;
}
