monolog:
    channels: ['elasticsearch']
    handlers:
        elasticsearch:
            type: rotating_file
            path: "%kernel.logs_dir%/elasticsearch_%kernel.environment%.log"
            max_files: 90
            level: "debug"
            channels: [ "elasticsearch"]
