@startuml "bigbankplc"
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

System_Boundary(c1, "Shopware Platform") {

    Container(core, "Core", "PHP", "Handles the data management and manipulation, provides a REST-API and a rich set of PHP Extension points")
    Container(storefront, "Storefront", "PHP,JS,SCSS", "Provides a classical Web application with template rendering and composite data loading")
    Container(admin, "Administration", "PHP,JS,SCSS", "Represents a small PHP-Bridge to the VueJS administration ")
    SystemDb(db, "Storage-Engine", "A combination of MySQL, Redis and ElasticSearch for data storage, retrieval and searching")

    Rel_D(admin, core, "uses")
    Rel_D(storefront, core, "uses")
    Rel_U(db, core, "writes/reads")
}
@enduml
