<?php

return
    [
        'id' => 243,
        'uuid' => '0',
        'supplierID' => 14,
        'name' => 'Artikel mit Emailbenachrichtigung',
        'description' => 'Mit dem besonderen Service der Emailbenachrichtigung können Kunden bei einem nicht lagernden Artikel Ihre Emailadresse angeben, damit Sie als Shopbetreiber die Kunden direkt informieren können, sobald der Artikel wieder verfügbar ist.',
        'description_long' => '<p>Mit dem besonderen Service der Emailbenachrichtigung können Kunden bei einem nicht lagernden Artikel Ihre Emailadresse angeben, damit Sie als Shopbetreiber die Kunden direkt informieren können, sobald der Artikel wieder verfügbar ist.</p>',
        'shippingtime' => NULL,
        'datum' => '2012-06-22',
        'active' => 1,
        'taxID' => 1,
        'pseudosales' => 0,
        'topseller' => 0,
        'metaTitle' => NULL,
        'keywords' => NULL,
        'changetime' => '2012-08-30 16:14:05',
        'pricegroupID' => NULL,
        'pricegroupActive' => 0,
        'filtergroupID' => NULL,
        'laststock' => 0,
        'crossbundlelook' => 0,
        'notification' => 1,
        'template' => '',
        'mode' => 0,
        'main_detail_id' => 798,
        'available_from' => NULL,
        'available_to' => NULL,
        'configurator_set_id' => NULL,
    ];
