<?php declare(strict_types=1);

return [
    'total' => 4,
    'data' => [
            'aa.aa' => [
                    0 => [
                            'value' => '1 aa bar',
                            'origin' => '1 aa bar',
                            'resetTo' => '1 aa bar',
                            'translationKey' => 'aa.aa',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'aa.aa',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'aa.aa',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '1 aa foo',
                            'origin' => '1 aa foo',
                            'resetTo' => '1 aa foo',
                            'translationKey' => 'aa.aa',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'aa.bb' => [
                    0 => [
                            'value' => '1 bb bar',
                            'origin' => '1 bb bar',
                            'resetTo' => '1 bb bar',
                            'translationKey' => 'aa.bb',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'aa.bb',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'aa.bb',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '1 bb foo',
                            'origin' => '1 bb foo',
                            'resetTo' => '1 bb foo',
                            'translationKey' => 'aa.bb',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'aa.ff' => [
                    0 => [
                            'value' => '1 ff bar',
                            'origin' => '1 ff bar',
                            'resetTo' => '1 ff bar',
                            'translationKey' => 'aa.ff',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'aa.ff',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'aa.ff',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '1 ff foo',
                            'origin' => '1 ff foo',
                            'resetTo' => '1 ff foo',
                            'translationKey' => 'aa.ff',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'aa.gg' => [
                    0 => [
                            'value' => '1 gg bar',
                            'origin' => '1 gg bar',
                            'resetTo' => '1 gg bar',
                            'translationKey' => 'aa.gg',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'aa.gg',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'aa.gg',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '1 gg foo',
                            'origin' => '1 gg foo',
                            'resetTo' => '1 gg foo',
                            'translationKey' => 'aa.gg',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
        ],
];
