<?php declare(strict_types=1);

return [
    'total' => 7,
    'data' => [
        'foo.bar.unit.test' => [
            0 => [
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                'translationKey' => 'foo.bar.unit.test',
                'value' => 'test2',
                'author' => 'user/admin',
                'id' => '6971cacc52ab4c8faecbc4143e5797e5',
                'origin' => '',
                'resetTo' => 'test2',
            ],
            1 => [
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                'translationKey' => 'foo.bar.unit.test',
                'value' => 'test1',
                'author' => 'user/admin',
                'id' => 'ed46e888a19347f1920056e859073020',
                'origin' => '',
                'resetTo' => 'test1',
            ],
            2 => [
                'value' => '',
                'translationKey' => 'foo.bar.unit.test',
                'author' => '',
                'origin' => '',
                'resetTo' => '',
                'setId' => '0d141d4373f3417e9655c9a30185481a',
                'id' => null,
            ],
            3 => [
                'value' => '',
                'translationKey' => 'foo.bar.unit.test',
                'author' => '',
                'origin' => '',
                'resetTo' => '',
                'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                'id' => null,
            ],
        ],
        'foo.bar.unit.test3' => [
            0 => [
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                'translationKey' => 'foo.bar.unit.test3',
                'value' => 'onlyEN',
                'author' => 'user/admin',
                'id' => '7a18f5d5b58c443abd1f0b86b0264ac7',
                'origin' => '',
                'resetTo' => 'onlyEN',
            ],
            1 => [
                'value' => '',
                'translationKey' => 'foo.bar.unit.test3',
                'author' => '',
                'origin' => '',
                'resetTo' => '',
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                'id' => null,
            ],
            2 => [
                'value' => '',
                'translationKey' => 'foo.bar.unit.test3',
                'author' => '',
                'origin' => '',
                'resetTo' => '',
                'setId' => '0d141d4373f3417e9655c9a30185481a',
                'id' => null,
            ],
            3 => [
                'value' => '',
                'translationKey' => 'foo.bar.unit.test3',
                'author' => '',
                'origin' => '',
                'resetTo' => '',
                'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                'id' => null,
            ],
        ],
        'foo.bar.unit.test4' => [
            0 => [
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                'translationKey' => 'foo.bar.unit.test4',
                'value' => 'onlyForUnitTests',
                'author' => 'user/admin',
                'id' => 'b517af22ebdc4849ad70cea22a49a232',
                'origin' => '',
                'resetTo' => 'onlyForUnitTests',
            ],
            1 => [
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                'translationKey' => 'foo.bar.unit.test4',
                'value' => 'nurFürUnitTests',
                'author' => 'user/admin',
                'id' => '25899065e5934c55aeccd8511e0bf88c',
                'origin' => '',
                'resetTo' => 'nurFürUnitTests',
            ],
            2 => [
                'value' => '',
                'translationKey' => 'foo.bar.unit.test4',
                'author' => '',
                'origin' => '',
                'resetTo' => '',
                'setId' => '0d141d4373f3417e9655c9a30185481a',
                'id' => null,
            ],
            3 => [
                'value' => '',
                'translationKey' => 'foo.bar.unit.test4',
                'author' => '',
                'origin' => '',
                'resetTo' => '',
                'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                'id' => null,
            ],
        ],
        'test.unit.a1' => [
            0 => [
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                'translationKey' => 'test.unit.a1',
                'value' => 'test',
                'author' => 'user/admin',
                'id' => '5e88ae48743f404ea8a0742fa8e89551',
                'origin' => '',
                'resetTo' => 'test',
            ],
            1 => [
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                'translationKey' => 'test.unit.a1',
                'value' => 'unit',
                'author' => 'user/admin',
                'id' => '523dce44343540d0ba17c27e12f17379',
                'origin' => '',
                'resetTo' => 'unit',
            ],
            2 => [
                'value' => '',
                'translationKey' => 'test.unit.a1',
                'author' => '',
                'origin' => '',
                'resetTo' => '',
                'setId' => '0d141d4373f3417e9655c9a30185481a',
                'id' => null,
            ],
            3 => [
                'value' => '',
                'translationKey' => 'test.unit.a1',
                'author' => '',
                'origin' => '',
                'resetTo' => '',
                'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                'id' => null,
            ],
        ],
        'test.unit.a2' => [
            0 => [
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                'translationKey' => 'test.unit.a2',
                'value' => 'bar',
                'author' => 'user/admin',
                'id' => '6e23c15762164d89963e2d55dcb9e34f',
                'origin' => '',
                'resetTo' => 'bar',
            ],
            1 => [
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                'translationKey' => 'test.unit.a2',
                'value' => 'foo',
                'author' => 'user/admin',
                'id' => '476acc796296496e8f5dc7ce772d5718',
                'origin' => '',
                'resetTo' => 'foo',
            ],
            2 => [
                'value' => '',
                'translationKey' => 'test.unit.a2',
                'author' => '',
                'origin' => '',
                'resetTo' => '',
                'setId' => '0d141d4373f3417e9655c9a30185481a',
                'id' => null,
            ],
            3 => [
                'value' => '',
                'translationKey' => 'test.unit.a2',
                'author' => '',
                'origin' => '',
                'resetTo' => '',
                'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                'id' => null,
            ],
        ],
        'unit.test.namespace' => [
            0 => [
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                'translationKey' => 'unit.test.namespace',
                'value' => 'test123',
                'author' => 'user/admin',
                'id' => '9ed9b9f03124459bb1c251c777db3e44',
                'origin' => '',
                'resetTo' => 'test123',
            ],
            1 => [
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                'translationKey' => 'unit.test.namespace',
                'value' => 'test123',
                'author' => 'user/admin',
                'id' => '8c1520f67e0345f5b660903ce1751904',
                'origin' => '',
                'resetTo' => 'test123',
            ],
            2 => [
                'value' => '',
                'translationKey' => 'unit.test.namespace',
                'author' => '',
                'origin' => '',
                'resetTo' => '',
                'setId' => '0d141d4373f3417e9655c9a30185481a',
                'id' => null,
            ],
            3 => [
                'value' => '',
                'translationKey' => 'unit.test.namespace',
                'author' => '',
                'origin' => '',
                'resetTo' => '',
                'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                'id' => null,
            ],
        ],
        'foo.bar.unit.test1' => [
            0 => [
                'value' => '',
                'translationKey' => 'foo.bar.unit.test1',
                'author' => '',
                'origin' => '',
                'resetTo' => '',
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                'id' => null,
            ],
            1 => [
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                'translationKey' => 'foo.bar.unit.test1',
                'value' => 'onlyDE',
                'author' => 'user/admin',
                'id' => '65aabe4e42b7451fbebd892fde10b02c',
                'origin' => '',
                'resetTo' => 'onlyDE',
            ],
            2 => [
                'value' => '',
                'translationKey' => 'foo.bar.unit.test1',
                'author' => '',
                'origin' => '',
                'resetTo' => '',
                'setId' => '0d141d4373f3417e9655c9a30185481a',
                'id' => null,
            ],
            3 => [
                'value' => '',
                'translationKey' => 'foo.bar.unit.test1',
                'author' => '',
                'origin' => '',
                'resetTo' => '',
                'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                'id' => null,
            ],
        ],
    ],
];
