<?php declare(strict_types=1);

return [
    'total' => 32,
    'data' => [
        'aa.ee' => [
            0 => [
                'value' => '1 ee bar',
                'origin' => '1 ee bar',
                'resetTo' => '1 ee bar',
                'translationKey' => 'aa.ee',
                'author' => 'bar',
                'id' => null,
                'setId' => '0d141d4373f3417e9655c9a30185481a',
            ],
            1 => [
                'value' => '',
                'translationKey' => 'aa.ee',
                'author' => '',
                'origin' => '',
                'resetTo' => '',
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                'id' => null,
            ],
            2 => [
                'value' => '',
                'translationKey' => 'aa.ee',
                'author' => '',
                'origin' => '',
                'resetTo' => '',
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                'id' => null,
            ],
            3 => [
                'value' => '1 ee foo',
                'origin' => '1 ee foo',
                'resetTo' => '1 ee foo',
                'translationKey' => 'aa.ee',
                'author' => 'foo',
                'id' => null,
                'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
            ],
        ],
        'aa.ff' => [
            0 => [
                'value' => '1 ff bar',
                'origin' => '1 ff bar',
                'resetTo' => '1 ff bar',
                'translationKey' => 'aa.ff',
                'author' => 'bar',
                'id' => null,
                'setId' => '0d141d4373f3417e9655c9a30185481a',
            ],
            1 => [
                'value' => '',
                'translationKey' => 'aa.ff',
                'author' => '',
                'origin' => '',
                'resetTo' => '',
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                'id' => null,
            ],
            2 => [
                'value' => '',
                'translationKey' => 'aa.ff',
                'author' => '',
                'origin' => '',
                'resetTo' => '',
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                'id' => null,
            ],
            3 => [
                'value' => '1 ff foo',
                'origin' => '1 ff foo',
                'resetTo' => '1 ff foo',
                'translationKey' => 'aa.ff',
                'author' => 'foo',
                'id' => null,
                'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
            ],
        ],
    ],
];
