<?php declare(strict_types=1);

return [
    'total' => 4,
    'data' => [
            'aa.dd' => [
                    0 => [
                            'value' => '1 dd bar',
                            'origin' => '1 dd bar',
                            'resetTo' => '1 dd bar',
                            'translationKey' => 'aa.dd',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'aa.dd',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'aa.dd',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '1 dd foo',
                            'origin' => '1 dd foo',
                            'resetTo' => '1 dd foo',
                            'translationKey' => 'aa.dd',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'bb.dd' => [
                    0 => [
                            'value' => '2 dd bar',
                            'origin' => '2 dd bar',
                            'resetTo' => '2 dd bar',
                            'translationKey' => 'bb.dd',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'bb.dd',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'bb.dd',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '2 dd foo',
                            'origin' => '2 dd foo',
                            'resetTo' => '2 dd foo',
                            'translationKey' => 'bb.dd',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'cc.aa.dd' => [
                    0 => [
                            'value' => '3 dd bar',
                            'origin' => '3 dd bar',
                            'resetTo' => '3 dd bar',
                            'translationKey' => 'cc.aa.dd',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'cc.aa.dd',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'cc.aa.dd',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '3 dd foo',
                            'origin' => '3 dd foo',
                            'resetTo' => '3 dd foo',
                            'translationKey' => 'cc.aa.dd',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'cc.bb.dd' => [
                    0 => [
                            'value' => '4 dd bar',
                            'origin' => '4 dd bar',
                            'resetTo' => '4 dd bar',
                            'translationKey' => 'cc.bb.dd',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'cc.bb.dd',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'cc.bb.dd',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '4 dd foo',
                            'origin' => '4 dd foo',
                            'resetTo' => '4 dd foo',
                            'translationKey' => 'cc.bb.dd',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
        ],
];
