<?php declare(strict_types=1);

return [
    'total' => 5,
    'data' => [
        'cc.bb.aa' => [
            0 => [
                'value' => '4 aa bar',
                'origin' => '4 aa bar',
                'resetTo' => '4 aa bar',
                'translationKey' => 'cc.bb.aa',
                'author' => 'bar',
                'id' => null,
                'setId' => '0d141d4373f3417e9655c9a30185481a',
            ],
            1 => [
                'value' => '',
                'translationKey' => 'cc.bb.aa',
                'author' => '',
                'origin' => '',
                'resetTo' => '',
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                'id' => null,
            ],
            2 => [
                'value' => '',
                'translationKey' => 'cc.bb.aa',
                'author' => '',
                'origin' => '',
                'resetTo' => '',
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                'id' => null,
            ],
            3 => [
                'value' => '4 aa foo',
                'origin' => '4 aa foo',
                'resetTo' => '4 aa foo',
                'translationKey' => 'cc.bb.aa',
                'author' => 'foo',
                'id' => null,
                'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
            ],
        ],
        'cc.bb.bb' => [
            0 => [
                'value' => '4 bb bar',
                'origin' => '4 bb bar',
                'resetTo' => '4 bb bar',
                'translationKey' => 'cc.bb.bb',
                'author' => 'bar',
                'id' => null,
                'setId' => '0d141d4373f3417e9655c9a30185481a',
            ],
            1 => [
                'value' => '',
                'translationKey' => 'cc.bb.bb',
                'author' => '',
                'origin' => '',
                'resetTo' => '',
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                'id' => null,
            ],
            2 => [
                'value' => '',
                'translationKey' => 'cc.bb.bb',
                'author' => '',
                'origin' => '',
                'resetTo' => '',
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                'id' => null,
            ],
            3 => [
                'value' => '4 bb foo',
                'origin' => '4 bb foo',
                'resetTo' => '4 bb foo',
                'translationKey' => 'cc.bb.bb',
                'author' => 'foo',
                'id' => null,
                'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
            ],
        ],
        'cc.bb.cc' => [
            0 => [
                'value' => '4 cc bar',
                'origin' => '4 cc bar',
                'resetTo' => '4 cc bar',
                'translationKey' => 'cc.bb.cc',
                'author' => 'bar',
                'id' => null,
                'setId' => '0d141d4373f3417e9655c9a30185481a',
            ],
            1 => [
                'value' => '',
                'translationKey' => 'cc.bb.cc',
                'author' => '',
                'origin' => '',
                'resetTo' => '',
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                'id' => null,
            ],
            2 => [
                'value' => '',
                'translationKey' => 'cc.bb.cc',
                'author' => '',
                'origin' => '',
                'resetTo' => '',
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                'id' => null,
            ],
            3 => [
                'value' => '4 cc foo',
                'origin' => '4 cc foo',
                'resetTo' => '4 cc foo',
                'translationKey' => 'cc.bb.cc',
                'author' => 'foo',
                'id' => null,
                'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
            ],
        ],
        'cc.bb.dd' => [
            0 => [
                'value' => '4 dd bar',
                'origin' => '4 dd bar',
                'resetTo' => '4 dd bar',
                'translationKey' => 'cc.bb.dd',
                'author' => 'bar',
                'id' => null,
                'setId' => '0d141d4373f3417e9655c9a30185481a',
            ],
            1 => [
                'value' => '',
                'translationKey' => 'cc.bb.dd',
                'author' => '',
                'origin' => '',
                'resetTo' => '',
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                'id' => null,
            ],
            2 => [
                'value' => '',
                'translationKey' => 'cc.bb.dd',
                'author' => '',
                'origin' => '',
                'resetTo' => '',
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                'id' => null,
            ],
            3 => [
                'value' => '4 dd foo',
                'origin' => '4 dd foo',
                'resetTo' => '4 dd foo',
                'translationKey' => 'cc.bb.dd',
                'author' => 'foo',
                'id' => null,
                'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
            ],
        ],
        'foo.bar.unit.test4' => [
            0 => [
                'value' => '',
                'translationKey' => 'foo.bar.unit.test4',
                'author' => '',
                'origin' => '',
                'resetTo' => '',
                'setId' => '0d141d4373f3417e9655c9a30185481a',
                'id' => null,
            ],
            1 => [
                'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                'translationKey' => 'foo.bar.unit.test4',
                'value' => 'onlyForUnitTests',
                'author' => 'user/admin',
                'id' => 'b517af22ebdc4849ad70cea22a49a232',
                'origin' => '',
                'resetTo' => 'onlyForUnitTests',
            ],
            2 => [
                'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                'translationKey' => 'foo.bar.unit.test4',
                'value' => 'nurFürUnitTests',
                'author' => 'user/admin',
                'id' => '25899065e5934c55aeccd8511e0bf88c',
                'origin' => '',
                'resetTo' => 'nurFürUnitTests',
            ],
            3 => [
                'value' => '',
                'translationKey' => 'foo.bar.unit.test4',
                'author' => '',
                'origin' => '',
                'resetTo' => '',
                'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                'id' => null,
            ],
        ],
    ],
];
