<?php declare(strict_types=1);

return [
    'total' => 32,
    'data' => [
            'aa.aa' => [
                    0 => [
                            'value' => '1 aa bar',
                            'origin' => '1 aa bar',
                            'resetTo' => '1 aa bar',
                            'translationKey' => 'aa.aa',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'aa.aa',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'aa.aa',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '1 aa foo',
                            'origin' => '1 aa foo',
                            'resetTo' => '1 aa foo',
                            'translationKey' => 'aa.aa',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'aa.bb' => [
                    0 => [
                            'value' => '1 bb bar',
                            'origin' => '1 bb bar',
                            'resetTo' => '1 bb bar',
                            'translationKey' => 'aa.bb',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'aa.bb',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'aa.bb',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '1 bb foo',
                            'origin' => '1 bb foo',
                            'resetTo' => '1 bb foo',
                            'translationKey' => 'aa.bb',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'aa.cc' => [
                    0 => [
                            'value' => '1 cc bar',
                            'origin' => '1 cc bar',
                            'resetTo' => '1 cc bar',
                            'translationKey' => 'aa.cc',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'aa.cc',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'aa.cc',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '1 cc foo',
                            'origin' => '1 cc foo',
                            'resetTo' => '1 cc foo',
                            'translationKey' => 'aa.cc',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'aa.dd' => [
                    0 => [
                            'value' => '1 dd bar',
                            'origin' => '1 dd bar',
                            'resetTo' => '1 dd bar',
                            'translationKey' => 'aa.dd',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'aa.dd',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'aa.dd',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '1 dd foo',
                            'origin' => '1 dd foo',
                            'resetTo' => '1 dd foo',
                            'translationKey' => 'aa.dd',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'aa.ee' => [
                    0 => [
                            'value' => '1 ee bar',
                            'origin' => '1 ee bar',
                            'resetTo' => '1 ee bar',
                            'translationKey' => 'aa.ee',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'aa.ee',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'aa.ee',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '1 ee foo',
                            'origin' => '1 ee foo',
                            'resetTo' => '1 ee foo',
                            'translationKey' => 'aa.ee',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'aa.ff' => [
                    0 => [
                            'value' => '1 ff bar',
                            'origin' => '1 ff bar',
                            'resetTo' => '1 ff bar',
                            'translationKey' => 'aa.ff',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'aa.ff',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'aa.ff',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '1 ff foo',
                            'origin' => '1 ff foo',
                            'resetTo' => '1 ff foo',
                            'translationKey' => 'aa.ff',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'aa.gg' => [
                    0 => [
                            'value' => '1 gg bar',
                            'origin' => '1 gg bar',
                            'resetTo' => '1 gg bar',
                            'translationKey' => 'aa.gg',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'aa.gg',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'aa.gg',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '1 gg foo',
                            'origin' => '1 gg foo',
                            'resetTo' => '1 gg foo',
                            'translationKey' => 'aa.gg',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'bb.aa' => [
                    0 => [
                            'value' => '2 aa bar',
                            'origin' => '2 aa bar',
                            'resetTo' => '2 aa bar',
                            'translationKey' => 'bb.aa',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'bb.aa',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'bb.aa',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '2 aa foo',
                            'origin' => '2 aa foo',
                            'resetTo' => '2 aa foo',
                            'translationKey' => 'bb.aa',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'bb.bb' => [
                    0 => [
                            'value' => '2 bb bar',
                            'origin' => '2 bb bar',
                            'resetTo' => '2 bb bar',
                            'translationKey' => 'bb.bb',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'bb.bb',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'bb.bb',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '2 bb foo',
                            'origin' => '2 bb foo',
                            'resetTo' => '2 bb foo',
                            'translationKey' => 'bb.bb',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'bb.cc' => [
                    0 => [
                            'value' => '2 cc bar',
                            'origin' => '2 cc bar',
                            'resetTo' => '2 cc bar',
                            'translationKey' => 'bb.cc',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'bb.cc',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'bb.cc',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '2 cc foo',
                            'origin' => '2 cc foo',
                            'resetTo' => '2 cc foo',
                            'translationKey' => 'bb.cc',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'bb.dd' => [
                    0 => [
                            'value' => '2 dd bar',
                            'origin' => '2 dd bar',
                            'resetTo' => '2 dd bar',
                            'translationKey' => 'bb.dd',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'bb.dd',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'bb.dd',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '2 dd foo',
                            'origin' => '2 dd foo',
                            'resetTo' => '2 dd foo',
                            'translationKey' => 'bb.dd',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'bb.ee' => [
                    0 => [
                            'value' => '2 ee bar',
                            'origin' => '2 ee bar',
                            'resetTo' => '2 ee bar',
                            'translationKey' => 'bb.ee',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'bb.ee',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'bb.ee',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '2 ee foo',
                            'origin' => '2 ee foo',
                            'resetTo' => '2 ee foo',
                            'translationKey' => 'bb.ee',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'bb.ff' => [
                    0 => [
                            'value' => '2 ff bar',
                            'origin' => '2 ff bar',
                            'resetTo' => '2 ff bar',
                            'translationKey' => 'bb.ff',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'bb.ff',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'bb.ff',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '2 ff foo',
                            'origin' => '2 ff foo',
                            'resetTo' => '2 ff foo',
                            'translationKey' => 'bb.ff',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'bb.gg' => [
                    0 => [
                            'value' => '2 gg bar',
                            'origin' => '2 gg bar',
                            'resetTo' => '2 gg bar',
                            'translationKey' => 'bb.gg',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'bb.gg',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'bb.gg',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '2 gg foo',
                            'origin' => '2 gg foo',
                            'resetTo' => '2 gg foo',
                            'translationKey' => 'bb.gg',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'cc.aa.aa' => [
                    0 => [
                            'value' => '3 aa bar',
                            'origin' => '3 aa bar',
                            'resetTo' => '3 aa bar',
                            'translationKey' => 'cc.aa.aa',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'cc.aa.aa',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'cc.aa.aa',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '3 aa foo',
                            'origin' => '3 aa foo',
                            'resetTo' => '3 aa foo',
                            'translationKey' => 'cc.aa.aa',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'cc.aa.bb' => [
                    0 => [
                            'value' => '3 bb bar',
                            'origin' => '3 bb bar',
                            'resetTo' => '3 bb bar',
                            'translationKey' => 'cc.aa.bb',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'cc.aa.bb',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'cc.aa.bb',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '3 bb foo',
                            'origin' => '3 bb foo',
                            'resetTo' => '3 bb foo',
                            'translationKey' => 'cc.aa.bb',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'cc.aa.cc' => [
                    0 => [
                            'value' => '3 cc bar',
                            'origin' => '3 cc bar',
                            'resetTo' => '3 cc bar',
                            'translationKey' => 'cc.aa.cc',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'cc.aa.cc',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'cc.aa.cc',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '3 cc foo',
                            'origin' => '3 cc foo',
                            'resetTo' => '3 cc foo',
                            'translationKey' => 'cc.aa.cc',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'cc.aa.dd' => [
                    0 => [
                            'value' => '3 dd bar',
                            'origin' => '3 dd bar',
                            'resetTo' => '3 dd bar',
                            'translationKey' => 'cc.aa.dd',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'cc.aa.dd',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'cc.aa.dd',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '3 dd foo',
                            'origin' => '3 dd foo',
                            'resetTo' => '3 dd foo',
                            'translationKey' => 'cc.aa.dd',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'cc.aa.ee' => [
                    0 => [
                            'value' => '3 ee bar',
                            'origin' => '3 ee bar',
                            'resetTo' => '3 ee bar',
                            'translationKey' => 'cc.aa.ee',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'cc.aa.ee',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'cc.aa.ee',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '3 ee foo',
                            'origin' => '3 ee foo',
                            'resetTo' => '3 ee foo',
                            'translationKey' => 'cc.aa.ee',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'cc.aa.ff' => [
                    0 => [
                            'value' => '3 ff bar',
                            'origin' => '3 ff bar',
                            'resetTo' => '3 ff bar',
                            'translationKey' => 'cc.aa.ff',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'cc.aa.ff',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'cc.aa.ff',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '3 ff foo',
                            'origin' => '3 ff foo',
                            'resetTo' => '3 ff foo',
                            'translationKey' => 'cc.aa.ff',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'cc.aa.gg' => [
                    0 => [
                            'value' => '3 gg bar',
                            'origin' => '3 gg bar',
                            'resetTo' => '3 gg bar',
                            'translationKey' => 'cc.aa.gg',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'cc.aa.gg',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'cc.aa.gg',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '3 gg foo',
                            'origin' => '3 gg foo',
                            'resetTo' => '3 gg foo',
                            'translationKey' => 'cc.aa.gg',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'cc.bb.aa' => [
                    0 => [
                            'value' => '4 aa bar',
                            'origin' => '4 aa bar',
                            'resetTo' => '4 aa bar',
                            'translationKey' => 'cc.bb.aa',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'cc.bb.aa',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'cc.bb.aa',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '4 aa foo',
                            'origin' => '4 aa foo',
                            'resetTo' => '4 aa foo',
                            'translationKey' => 'cc.bb.aa',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'cc.bb.bb' => [
                    0 => [
                            'value' => '4 bb bar',
                            'origin' => '4 bb bar',
                            'resetTo' => '4 bb bar',
                            'translationKey' => 'cc.bb.bb',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'cc.bb.bb',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'cc.bb.bb',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '4 bb foo',
                            'origin' => '4 bb foo',
                            'resetTo' => '4 bb foo',
                            'translationKey' => 'cc.bb.bb',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'cc.bb.cc' => [
                    0 => [
                            'value' => '4 cc bar',
                            'origin' => '4 cc bar',
                            'resetTo' => '4 cc bar',
                            'translationKey' => 'cc.bb.cc',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'cc.bb.cc',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'cc.bb.cc',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '4 cc foo',
                            'origin' => '4 cc foo',
                            'resetTo' => '4 cc foo',
                            'translationKey' => 'cc.bb.cc',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'cc.bb.dd' => [
                    0 => [
                            'value' => '4 dd bar',
                            'origin' => '4 dd bar',
                            'resetTo' => '4 dd bar',
                            'translationKey' => 'cc.bb.dd',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'cc.bb.dd',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'cc.bb.dd',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '4 dd foo',
                            'origin' => '4 dd foo',
                            'resetTo' => '4 dd foo',
                            'translationKey' => 'cc.bb.dd',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
        ],
];
