<?php declare(strict_types=1);

return [
    'total' => 12,
    'data' => [
            'cc.aa.aa' => [
                    0 => [
                            'value' => '3 aa bar',
                            'origin' => '3 aa bar',
                            'resetTo' => '3 aa bar',
                            'translationKey' => 'cc.aa.aa',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'cc.aa.aa',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'cc.aa.aa',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '3 aa foo',
                            'origin' => '3 aa foo',
                            'resetTo' => '3 aa foo',
                            'translationKey' => 'cc.aa.aa',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'cc.aa.bb' => [
                    0 => [
                            'value' => '3 bb bar',
                            'origin' => '3 bb bar',
                            'resetTo' => '3 bb bar',
                            'translationKey' => 'cc.aa.bb',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'cc.aa.bb',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'cc.aa.bb',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '3 bb foo',
                            'origin' => '3 bb foo',
                            'resetTo' => '3 bb foo',
                            'translationKey' => 'cc.aa.bb',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'cc.aa.cc' => [
                    0 => [
                            'value' => '3 cc bar',
                            'origin' => '3 cc bar',
                            'resetTo' => '3 cc bar',
                            'translationKey' => 'cc.aa.cc',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'cc.aa.cc',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'cc.aa.cc',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '3 cc foo',
                            'origin' => '3 cc foo',
                            'resetTo' => '3 cc foo',
                            'translationKey' => 'cc.aa.cc',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'cc.aa.dd' => [
                    0 => [
                            'value' => '3 dd bar',
                            'origin' => '3 dd bar',
                            'resetTo' => '3 dd bar',
                            'translationKey' => 'cc.aa.dd',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'cc.aa.dd',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'cc.aa.dd',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '3 dd foo',
                            'origin' => '3 dd foo',
                            'resetTo' => '3 dd foo',
                            'translationKey' => 'cc.aa.dd',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'cc.aa.ee' => [
                    0 => [
                            'value' => '3 ee bar',
                            'origin' => '3 ee bar',
                            'resetTo' => '3 ee bar',
                            'translationKey' => 'cc.aa.ee',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'cc.aa.ee',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'cc.aa.ee',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '3 ee foo',
                            'origin' => '3 ee foo',
                            'resetTo' => '3 ee foo',
                            'translationKey' => 'cc.aa.ee',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'cc.aa.ff' => [
                    0 => [
                            'value' => '3 ff bar',
                            'origin' => '3 ff bar',
                            'resetTo' => '3 ff bar',
                            'translationKey' => 'cc.aa.ff',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'cc.aa.ff',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'cc.aa.ff',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '3 ff foo',
                            'origin' => '3 ff foo',
                            'resetTo' => '3 ff foo',
                            'translationKey' => 'cc.aa.ff',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'cc.aa.gg' => [
                    0 => [
                            'value' => '3 gg bar',
                            'origin' => '3 gg bar',
                            'resetTo' => '3 gg bar',
                            'translationKey' => 'cc.aa.gg',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'cc.aa.gg',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'cc.aa.gg',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '3 gg foo',
                            'origin' => '3 gg foo',
                            'resetTo' => '3 gg foo',
                            'translationKey' => 'cc.aa.gg',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'cc.bb.aa' => [
                    0 => [
                            'value' => '4 aa bar',
                            'origin' => '4 aa bar',
                            'resetTo' => '4 aa bar',
                            'translationKey' => 'cc.bb.aa',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'cc.bb.aa',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'cc.bb.aa',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '4 aa foo',
                            'origin' => '4 aa foo',
                            'resetTo' => '4 aa foo',
                            'translationKey' => 'cc.bb.aa',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'cc.bb.bb' => [
                    0 => [
                            'value' => '4 bb bar',
                            'origin' => '4 bb bar',
                            'resetTo' => '4 bb bar',
                            'translationKey' => 'cc.bb.bb',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'cc.bb.bb',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'cc.bb.bb',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '4 bb foo',
                            'origin' => '4 bb foo',
                            'resetTo' => '4 bb foo',
                            'translationKey' => 'cc.bb.bb',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'cc.bb.cc' => [
                    0 => [
                            'value' => '4 cc bar',
                            'origin' => '4 cc bar',
                            'resetTo' => '4 cc bar',
                            'translationKey' => 'cc.bb.cc',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'cc.bb.cc',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'cc.bb.cc',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '4 cc foo',
                            'origin' => '4 cc foo',
                            'resetTo' => '4 cc foo',
                            'translationKey' => 'cc.bb.cc',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'cc.bb.dd' => [
                    0 => [
                            'value' => '4 dd bar',
                            'origin' => '4 dd bar',
                            'resetTo' => '4 dd bar',
                            'translationKey' => 'cc.bb.dd',
                            'author' => 'bar',
                            'id' => null,
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                        ],
                    1 => [
                            'value' => '',
                            'translationKey' => 'cc.bb.dd',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'id' => null,
                        ],
                    2 => [
                            'value' => '',
                            'translationKey' => 'cc.bb.dd',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'id' => null,
                        ],
                    3 => [
                            'value' => '4 dd foo',
                            'origin' => '4 dd foo',
                            'resetTo' => '4 dd foo',
                            'translationKey' => 'cc.bb.dd',
                            'author' => 'foo',
                            'id' => null,
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                        ],
                ],
            'unit.test.namespace' => [
                    0 => [
                            'value' => '',
                            'translationKey' => 'unit.test.namespace',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => '0d141d4373f3417e9655c9a30185481a',
                            'id' => null,
                        ],
                    1 => [
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                            'translationKey' => 'unit.test.namespace',
                            'value' => 'test123',
                            'author' => 'user/admin',
                            'id' => '9ed9b9f03124459bb1c251c777db3e44',
                            'origin' => '',
                            'resetTo' => 'test123',
                        ],
                    2 => [
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                            'translationKey' => 'unit.test.namespace',
                            'value' => 'test123',
                            'author' => 'user/admin',
                            'id' => '8c1520f67e0345f5b660903ce1751904',
                            'origin' => '',
                            'resetTo' => 'test123',
                        ],
                    3 => [
                            'value' => '',
                            'translationKey' => 'unit.test.namespace',
                            'author' => '',
                            'origin' => '',
                            'resetTo' => '',
                            'setId' => 'c6dcb4f9494b42208b426feb31d4aa64',
                            'id' => null,
                        ],
                ],
        ],
];
