/**
 * @sw-package framework
 */

import fs from 'fs';
import path from 'path';
import {
    BASELINE_FILE_NAME,
    buildBaseline,
    canHoldBaseline,
    diffEslint,
    diffTypeScript,
    readBaseline,
    serializeBaseline,
    writeBaselineFile,
} from './baseline';
import type { EslintFinding, TypeScriptFinding } from './baseline';
import { GENERATED_MARKER, isGeneratedContent } from './shared';
import { cleanupTempProject, createTempProject, writeFile } from './test-helpers';

const customProject = { basePath: 'custom/plugins/MyPlugin', vendor: false };

function tsFinding(overrides: Partial<TypeScriptFinding> = {}): TypeScriptFinding {
    return { file: 'custom/plugins/MyPlugin/src/main.ts', code: 'TS2322', message: 'Type mismatch.', ...overrides };
}

function eslintFinding(overrides: Partial<EslintFinding> = {}): EslintFinding {
    return {
        file: 'custom/plugins/MyPlugin/src/main.ts',
        rule: 'no-console',
        message: 'Unexpected console statement',
        severity: 'error',
        ...overrides,
    };
}

describe('scripts/extensionTooling/baseline', () => {
    let projectRoot: string;

    beforeEach(() => {
        projectRoot = createTempProject('sw-tooling-baseline-');
    });

    afterEach(() => {
        cleanupTempProject(projectRoot);
    });

    describe('canHoldBaseline', () => {
        it('admits only writable custom/plugins extensions', () => {
            expect(canHoldBaseline(customProject)).toBe(true);
            expect(canHoldBaseline({ basePath: 'vendor/acme/x', vendor: true })).toBe(false);
            // An in-repo bundle is writable and its findings are fatal, but it is
            // not a plugin — it must not collect per-developer debt files.
            expect(canHoldBaseline({ basePath: 'src/Storefront', vendor: false })).toBe(false);
            expect(canHoldBaseline({ basePath: 'custom/static-plugins/MyPlugin', vendor: false })).toBe(false);
        });
    });

    describe('readBaseline', () => {
        it('does not offer a baseline to vendor or non-custom-plugins extensions', () => {
            expect(readBaseline(projectRoot, { basePath: 'vendor/acme/x', vendor: true })).toBeNull();
            expect(readBaseline(projectRoot, { basePath: 'src/Administration', vendor: false })).toBeNull();
        });

        it('returns null when the baseline file is absent', () => {
            expect(readBaseline(projectRoot, customProject)).toBeNull();
        });

        it('ignores the marker field and normalizes missing streams', () => {
            writeFile(
                path.join(projectRoot, customProject.basePath, BASELINE_FILE_NAME),
                JSON.stringify({
                    '//': '@generated by Shopware Administration extension tooling',
                    version: 1,
                    typescript: [{ file: 'src/main.ts', code: 'TS2322', message: 'Type mismatch.', count: 1 }],
                }),
            );

            const baseline = readBaseline(projectRoot, customProject);

            expect(baseline).toEqual({
                version: 1,
                typescript: [{ file: 'src/main.ts', code: 'TS2322', message: 'Type mismatch.', count: 1 }],
                typescriptSpecs: [],
                eslint: [],
            });
        });

        it('rejects garbage and version mismatches', () => {
            const file = path.join(projectRoot, customProject.basePath, BASELINE_FILE_NAME);

            writeFile(file, 'not json');
            expect(readBaseline(projectRoot, customProject)).toBeNull();

            writeFile(file, JSON.stringify({ version: 2, typescript: [] }));
            expect(readBaseline(projectRoot, customProject)).toBeNull();
        });
    });

    describe('diffTypeScript', () => {
        it('reports every finding as new when there is no baseline', () => {
            const findings = [tsFinding()];
            const split = diffTypeScript(findings, [], customProject.basePath, 1);

            expect(split).toEqual({ newFindings: findings, baselinedFindings: [], staleCount: 0, parseMismatch: false });
        });

        it('matches findings against the baseline on a base-path-relative key', () => {
            const split = diffTypeScript(
                [tsFinding()],
                [{ file: 'src/main.ts', code: 'TS2322', message: 'Type mismatch.', count: 1 }],
                customProject.basePath,
                1,
            );

            expect(split.newFindings).toEqual([]);
            // The matched findings themselves are kept, not just a count — the
            // report lists them to say what it suppressed.
            expect(split.baselinedFindings).toEqual([tsFinding()]);
            expect(split.staleCount).toBe(0);
        });

        it('matches duplicates by count and reports the overflow as new', () => {
            const split = diffTypeScript(
                [
                    tsFinding(),
                    tsFinding(),
                ],
                [{ file: 'src/main.ts', code: 'TS2322', message: 'Type mismatch.', count: 1 }],
                customProject.basePath,
                2,
            );

            expect(split.baselinedFindings).toHaveLength(1);
            expect(split.newFindings).toHaveLength(1);
        });

        it('reports baseline entries that match nothing as stale', () => {
            const split = diffTypeScript(
                [],
                [{ file: 'src/gone.ts', code: 'TS2322', message: 'Type mismatch.', count: 2 }],
                customProject.basePath,
                0,
            );

            expect(split.staleCount).toBe(2);
            expect(split.newFindings).toEqual([]);
        });

        it('does not apply the baseline when the parse count disagrees with the counter', () => {
            const findings = [tsFinding()];
            const split = diffTypeScript(
                findings,
                [{ file: 'src/main.ts', code: 'TS2322', message: 'Type mismatch.', count: 1 }],
                customProject.basePath,
                2,
            );

            expect(split.parseMismatch).toBe(true);
            expect(split.newFindings).toEqual(findings);
            expect(split.baselinedFindings).toEqual([]);
        });
    });

    describe('diffEslint', () => {
        it('baselines only error-severity findings and ignores warnings', () => {
            const warning = eslintFinding({ rule: 'no-alert', message: 'Unexpected alert.', severity: 'warning' });
            const split = diffEslint(
                [
                    eslintFinding(),
                    warning,
                ],
                [{ file: 'src/main.ts', rule: 'no-console', message: 'Unexpected console statement', count: 1 }],
                customProject.basePath,
                2,
            );

            expect(split.baselinedFindings).toEqual([eslintFinding()]);
            expect(split.newFindings).toEqual([]);
        });

        it('treats error findings as new on a parse-count mismatch', () => {
            const split = diffEslint(
                [eslintFinding()],
                [{ file: 'src/main.ts', rule: 'no-console', message: 'Unexpected console statement', count: 1 }],
                customProject.basePath,
                5,
            );

            expect(split.parseMismatch).toBe(true);
            expect(split.newFindings).toHaveLength(1);
            expect(split.baselinedFindings).toEqual([]);
        });
    });

    describe('buildBaseline', () => {
        it('aggregates duplicates into counts, keeps spec findings separate, and drops warnings', () => {
            const baseline = buildBaseline(
                {
                    typescript: [
                        tsFinding(),
                        tsFinding(),
                    ],
                    typescriptSpecs: [tsFinding({ file: 'custom/plugins/MyPlugin/src/main.spec.ts', code: 'TS2345' })],
                    eslint: [
                        eslintFinding(),
                        eslintFinding({ severity: 'warning' }),
                    ],
                },
                customProject.basePath,
            );

            expect(baseline).toEqual({
                version: 1,
                typescript: [{ file: 'src/main.ts', code: 'TS2322', message: 'Type mismatch.', count: 2 }],
                typescriptSpecs: [{ file: 'src/main.spec.ts', code: 'TS2345', message: 'Type mismatch.', count: 1 }],
                eslint: [{ file: 'src/main.ts', rule: 'no-console', message: 'Unexpected console statement', count: 1 }],
            });
        });

        it('sorts entries canonically so committed baselines do not churn', () => {
            const baseline = buildBaseline(
                {
                    typescript: [
                        tsFinding({ file: 'custom/plugins/MyPlugin/src/z.ts' }),
                        tsFinding({ file: 'custom/plugins/MyPlugin/src/a.ts' }),
                    ],
                    typescriptSpecs: [],
                    eslint: [],
                },
                customProject.basePath,
            );

            expect(baseline.typescript.map((entry) => entry.file)).toEqual([
                'src/a.ts',
                'src/z.ts',
            ]);
        });
    });

    describe('serializeBaseline', () => {
        it('keeps the ownership marker within the first three lines so the file reads as tool-owned', () => {
            const serialized = serializeBaseline(
                buildBaseline({ typescript: [tsFinding()], typescriptSpecs: [], eslint: [] }, customProject.basePath),
            );

            expect(serialized.split(/\r?\n/, 3).join('\n')).toContain(GENERATED_MARKER);
            expect(isGeneratedContent(serialized)).toBe(true);
            // The marker rides in a "//" field, so it stays valid JSON.
            expect((JSON.parse(serialized) as { version: number }).version).toBe(1);
        });
    });

    describe('writeBaselineFile', () => {
        it('records a readable baseline and refuses none-custom-plugins projects', () => {
            const built = buildBaseline(
                { typescript: [tsFinding()], typescriptSpecs: [], eslint: [eslintFinding()] },
                customProject.basePath,
            );

            expect(writeBaselineFile(projectRoot, { basePath: 'vendor/acme/x', vendor: true }, built)).toBeNull();

            const write = writeBaselineFile(projectRoot, customProject, built);

            expect(write?.state).toBe('created');
            expect(readBaseline(projectRoot, customProject)).toEqual(built);
        });

        it('never overwrites a human-authored baseline', () => {
            const file = path.join(projectRoot, customProject.basePath, BASELINE_FILE_NAME);

            writeFile(file, '{ "version": 1, "typescript": [], "eslint": [] }');

            const write = writeBaselineFile(
                projectRoot,
                customProject,
                buildBaseline({ typescript: [tsFinding()], typescriptSpecs: [], eslint: [] }, customProject.basePath),
            );

            expect(write?.state).toBe('conflict');
            expect(fs.readFileSync(file, 'utf8')).toBe('{ "version": 1, "typescript": [], "eslint": [] }');
        });
    });
});
