/**
 * @sw-package framework
 */

import path from 'path';
import { BASELINE_FILE_NAME, diffEslint, diffTypeScript, readBaseline } from './baseline';
import type { EslintFinding, TypeScriptFinding } from './baseline';
import { cleanupTempProject, createTempProject, writeFile } from './test-helpers';

const customProject = { basePath: 'custom/plugins/MyPlugin', vendor: false };

function tsFinding(overrides: Partial<TypeScriptFinding> = {}): TypeScriptFinding {
    return { file: 'custom/plugins/MyPlugin/src/main.ts', code: 'TS2322', message: 'Type mismatch.', ...overrides };
}

function eslintFinding(overrides: Partial<EslintFinding> = {}): EslintFinding {
    return {
        file: 'custom/plugins/MyPlugin/src/main.ts',
        rule: 'no-console',
        message: 'Unexpected console statement',
        severity: 'error',
        ...overrides,
    };
}

describe('scripts/extensionTooling/baseline', () => {
    let projectRoot: string;

    beforeEach(() => {
        projectRoot = createTempProject('sw-tooling-baseline-');
    });

    afterEach(() => {
        cleanupTempProject(projectRoot);
    });

    describe('readBaseline', () => {
        it('does not offer a baseline to vendor or non-custom-plugins extensions', () => {
            expect(readBaseline(projectRoot, { basePath: 'vendor/acme/x', vendor: true })).toBeNull();
            expect(readBaseline(projectRoot, { basePath: 'src/Administration', vendor: false })).toBeNull();
        });

        it('returns null when the baseline file is absent', () => {
            expect(readBaseline(projectRoot, customProject)).toBeNull();
        });

        it('ignores the marker field and normalizes missing streams', () => {
            writeFile(
                path.join(projectRoot, customProject.basePath, BASELINE_FILE_NAME),
                JSON.stringify({
                    '//': '@generated by Shopware Administration extension tooling',
                    version: 1,
                    typescript: [{ file: 'src/main.ts', code: 'TS2322', message: 'Type mismatch.', count: 1 }],
                }),
            );

            const baseline = readBaseline(projectRoot, customProject);

            expect(baseline).toEqual({
                version: 1,
                typescript: [{ file: 'src/main.ts', code: 'TS2322', message: 'Type mismatch.', count: 1 }],
                eslint: [],
            });
        });

        it('rejects garbage and version mismatches', () => {
            const file = path.join(projectRoot, customProject.basePath, BASELINE_FILE_NAME);

            writeFile(file, 'not json');
            expect(readBaseline(projectRoot, customProject)).toBeNull();

            writeFile(file, JSON.stringify({ version: 2, typescript: [] }));
            expect(readBaseline(projectRoot, customProject)).toBeNull();
        });
    });

    describe('diffTypeScript', () => {
        it('reports every finding as new when there is no baseline', () => {
            const findings = [tsFinding()];
            const split = diffTypeScript(findings, [], customProject.basePath, 1);

            expect(split).toEqual({ newFindings: findings, baselinedCount: 0, staleCount: 0, parseMismatch: false });
        });

        it('matches findings against the baseline on a base-path-relative key', () => {
            const split = diffTypeScript(
                [tsFinding()],
                [{ file: 'src/main.ts', code: 'TS2322', message: 'Type mismatch.', count: 1 }],
                customProject.basePath,
                1,
            );

            expect(split.newFindings).toEqual([]);
            expect(split.baselinedCount).toBe(1);
            expect(split.staleCount).toBe(0);
        });

        it('matches duplicates by count and reports the overflow as new', () => {
            const split = diffTypeScript(
                [
                    tsFinding(),
                    tsFinding(),
                ],
                [{ file: 'src/main.ts', code: 'TS2322', message: 'Type mismatch.', count: 1 }],
                customProject.basePath,
                2,
            );

            expect(split.baselinedCount).toBe(1);
            expect(split.newFindings).toHaveLength(1);
        });

        it('reports baseline entries that match nothing as stale', () => {
            const split = diffTypeScript(
                [],
                [{ file: 'src/gone.ts', code: 'TS2322', message: 'Type mismatch.', count: 2 }],
                customProject.basePath,
                0,
            );

            expect(split.staleCount).toBe(2);
            expect(split.newFindings).toEqual([]);
        });

        it('does not apply the baseline when the parse count disagrees with the counter', () => {
            const findings = [tsFinding()];
            const split = diffTypeScript(
                findings,
                [{ file: 'src/main.ts', code: 'TS2322', message: 'Type mismatch.', count: 1 }],
                customProject.basePath,
                2,
            );

            expect(split.parseMismatch).toBe(true);
            expect(split.newFindings).toEqual(findings);
            expect(split.baselinedCount).toBe(0);
        });
    });

    describe('diffEslint', () => {
        it('baselines only error-severity findings and ignores warnings', () => {
            const warning = eslintFinding({ rule: 'no-alert', message: 'Unexpected alert.', severity: 'warning' });
            const split = diffEslint(
                [
                    eslintFinding(),
                    warning,
                ],
                [{ file: 'src/main.ts', rule: 'no-console', message: 'Unexpected console statement', count: 1 }],
                customProject.basePath,
                2,
            );

            expect(split.baselinedCount).toBe(1);
            expect(split.newFindings).toEqual([]);
        });

        it('treats error findings as new on a parse-count mismatch', () => {
            const split = diffEslint(
                [eslintFinding()],
                [{ file: 'src/main.ts', rule: 'no-console', message: 'Unexpected console statement', count: 1 }],
                customProject.basePath,
                5,
            );

            expect(split.parseMismatch).toBe(true);
            expect(split.newFindings).toHaveLength(1);
            expect(split.baselinedCount).toBe(0);
        });
    });
});
