/**
 * @sw-package framework
 *
 * Human-readable rendering for `admin:setup-extension-tooling`. Pure: takes the
 * setup result and returns the full report string, with color applied via
 * picocolors (support decided once at import time — FORCE_COLOR, a TTY, or
 * env.CI turn it on; NO_COLOR wins), so the specs strip ANSI before semantic
 * assertions.
 *
 * Two tables carry most of the output. COVERAGE maps each derived extension
 * state to its bucket label and the single next action; OWNERSHIP maps each
 * generated file class to its lifecycle note and whether its paths are worth
 * listing. Between them sits the root-projection block, which names the
 * host-owned project-root configs from the manifest rather than from the write
 * list, so an idempotent re-run that changes nothing still says they exist. The
 * per-file remediation is deliberately not re-derived here — the generators
 * already push it as warnings naming the exact files, which this report prints.
 */

import colors from 'picocolors';
import type { SetupExtensionToolingResult } from './setup';
import { DEFAULT_TOOLING_COMMANDS, SHIM_DIR_NAME, deriveExtensionState, firstDrift } from './shared';
import type { DerivedExtensionState, ExtensionToolingProject, OwnedConfig, ToolingCommands } from './shared';
import { describeConfigFix } from './report-guidance';

interface SetupRenderOptions {
    checkOnly?: boolean;
    /**
     * Shown on plain (flag-less) runs: composer swallows options placed before
     * "--", so this footer is both flag discovery and the safety net for a
     * swallowed flag that silently turned into a default run.
     */
    showFlagHint?: boolean;
    /** Layout-aware command invocations for printed next steps (defaults to the composer scripts). */
    commands?: ToolingCommands;
}

type StateMap = Map<string, DerivedExtensionState>;

/**
 * Ownership class of a generated path, so a developer can tell the lifecycles
 * apart: the git-ignored machine-specific bridge, the plugin's own committable
 * configs, the same files inside a composer-managed extension (local only), the
 * project-root projections, and the remaining disposable host files (IDE
 * bootstraps, the manifest). Every listed class carries a note — an unlabeled
 * line next to a `[commit this]` one reads as "unclassified", which is exactly
 * how the root projections used to get mistaken for plugin configs. Classes
 * whose file count scales with the number of extensions are summarized instead
 * of listed by path.
 */
export { renderCheckReport } from './report-check';

export type FileClass = 'bridge' | 'committable' | 'vendor-config' | 'root-projection' | 'host';

const OWNERSHIP: Record<FileClass, { list: boolean; note: string }> = {
    committable: { list: true, note: 'commit this' },
    'vendor-config': { list: true, note: 'local — restored by re-running setup' },
    'root-projection': { list: true, note: 'project-root projection — git-ignored' },
    host: { list: true, note: 'disposable — regenerated by setup' },
    bridge: { list: false, note: `git-ignored ${SHIM_DIR_NAME}/ bridge file(s) — never commit` },
};

export function classifyFile(file: string): FileClass {
    if (file.includes(`/${SHIM_DIR_NAME}/`)) {
        return 'bridge';
    }

    const base = file.split('/').pop() ?? '';

    if (base === 'tsconfig.json' || base === 'eslint.config.mjs') {
        if (file.startsWith('vendor/')) {
            return 'vendor-config';
        }

        // A bare filename is the generated root projection, not an extension's config.
        return file.includes('/') ? 'committable' : 'root-projection';
    }

    return 'host';
}

const VENDOR_NOTE =
    'Vendor extension: files under vendor/ are local only — a composer update removes them, setup restores them.';

const COVERAGE: Record<
    DerivedExtensionState,
    {
        label: string;
        paint: (value: string) => string;
        note: string;
        action?: (commands: ToolingCommands) => string[];
        /** Print the fix under each drifting config instead of once for the bucket. */
        perProjectFix?: boolean;
    }
> = {
    bridged: {
        label: '● bridged',
        paint: colors.cyan,
        note: 'own configs compose the Shopware preset',
    },
    ready: {
        label: '✔ ready',
        paint: colors.green,
        note: 'covered through the generated root projection',
    },
    'bridge-unwired': {
        label: '⚠ bridge unwired',
        paint: colors.yellow,
        note: "bridge exists — own config doesn't compose it yet",
        perProjectFix: true,
    },
    'needs-bridge': {
        label: '⚠ not bridged',
        paint: colors.yellow,
        note: 'ships own config, no bridge yet',
        action: (commands) => [
            `bridges are generated automatically — run \`${commands.setup}\`;`,
            'if a ⚠ above says why the bridge was skipped, fix that first.',
        ],
    },
    platform: {
        label: 'platform',
        paint: colors.dim,
        note: 'always checked with core tooling',
    },
};

const COVERAGE_ORDER: DerivedExtensionState[] = [
    'bridged',
    'ready',
    'bridge-unwired',
    'needs-bridge',
    'platform',
];

/**
 * Printed on every run, including the empty state. The tooling is experimental,
 * so the surfaces an extension could come to depend on — the command name, its
 * flags, the generated-file layout and the manifest format — are deliberately
 * outside the backwards-compatibility promise until it is declared stable.
 */
function renderNotice(): string[] {
    return [
        colors.yellow('  EXPERIMENTAL — not covered by the backwards-compatibility promise.'),
        colors.dim('  The command name, its flags, the generated-file layout and the manifest'),
        colors.dim('  format can change in any release. Re-run setup after a Shopware update'),
        colors.dim('  and never hand-edit generated files.'),
    ];
}

/** The first drifting config of the extension, whichever tool owns it. */
function renderProjectDetail(project: ExtensionToolingProject): string[] {
    const drift = firstDrift(project, 'tsconfig') ?? firstDrift(project, 'eslintConfig');

    return drift?.detail ? [colors.dim(`      ${project.name}: ${drift.detail}`)] : [];
}

/**
 * Every drifting config of the extension with the step that fixes *that* defect
 * underneath it. Two extensions in the same bucket can need opposite steps — add
 * an `extends`, or drop a `files` array that shadows one already there — so the
 * remediation cannot live on the bucket.
 */
function renderProjectDrifts(project: ExtensionToolingProject): string[] {
    const lines: string[] = [];

    for (const [
        tool,
        drift,
    ] of [
        [
            'TypeScript',
            firstDrift(project, 'tsconfig'),
        ],
        [
            'ESLint',
            firstDrift(project, 'eslintConfig'),
        ],
    ] as Array<['TypeScript' | 'ESLint', OwnedConfig | null]>) {
        if (!drift?.detail) {
            continue;
        }

        lines.push(
            colors.dim(`      ${project.name}: ${drift.detail}`),
            ...describeConfigFix(tool, drift).map((line) => colors.dim(`        → ${line}`)),
        );
    }

    return lines;
}

/**
 * One line per non-empty state bucket, plus that bucket's action. A bucket whose
 * remediation depends on the concrete defect carries `perProjectFix` instead and
 * prints the step under each drifting config.
 */
function renderCoverage(
    projects: ExtensionToolingProject[],
    stateOf: StateMap,
    commands: ToolingCommands,
    freshlyBridged: Set<string>,
): string[] {
    const lines = [''];

    for (const state of COVERAGE_ORDER) {
        const row = COVERAGE[state];
        const members = projects.filter((project) => stateOf.get(project.name) === state);

        if (members.length === 0) {
            continue;
        }

        const names = members
            .map((project) => (freshlyBridged.has(project.name) ? `${project.name} (new)` : project.name))
            .join(', ');

        lines.push(`  ${row.paint(row.label)}  ${names}  ${colors.dim(`(${row.note})`)}`);

        // A bucket with neither an action nor a per-config fix is already covered
        // (bridged, ready) or checked elsewhere (platform) — no remediation, and
        // no drift detail to explain one.
        if (!row.action && !row.perProjectFix) {
            continue;
        }

        if (row.action) {
            lines.push(...row.action(commands).map((line) => colors.dim(`      → ${line}`)));
        }

        for (const project of members) {
            lines.push(...(row.perProjectFix ? renderProjectDrifts(project) : renderProjectDetail(project)));
        }

        if (members.some((project) => project.vendor)) {
            lines.push(colors.dim(`      ${VENDOR_NOTE}`));
        }
    }

    return lines;
}

/**
 * The host-owned project-root configs, named from the manifest rather than from
 * the write list: they are generated on every run, so a run that changed nothing
 * must still say they exist instead of collapsing into "Configs up to date".
 *
 * Both files are described separately because they do not cover the same roots —
 * the ESLint config scopes to every discovered source root, while the tsconfig
 * only includes the roots no extension config governs (normally none, since
 * bridging scaffolds one per root) — so a shared "covers N roots" would be wrong
 * for one of them. The counts mirror the generators, which glob across every
 * discovered project, platform bundles included.
 */
function renderRootProjection(result: SetupExtensionToolingResult, own: ExtensionToolingProject[]): string[] {
    const { rootConfigs } = result.manifest;
    const targets = result.manifest.projects.flatMap((project) => project.targets);
    const uncovered = targets.filter((target) => target.tsconfig === null).length;
    // Only what this run owns: a skipped root config was never written, and a
    // user-owned one is reported by its own ⚠ plus integration instructions.
    const managed = [
        {
            file: 'tsconfig.json',
            state: rootConfigs.tsconfig,
            detail:
                uncovered === 0
                    ? 'the type-check fallback for roots no extension config governs — currently none, every root has its own'
                    : `type-checks the ${uncovered} source root(s) no extension config governs`,
        },
        {
            file: 'eslint.config.mjs',
            state: rootConfigs.eslintConfig,
            detail: `scopes ESLint to ${new Set(targets.map((target) => target.sourcePath)).size} source root(s)`,
        },
    ].filter((entry) => entry.state === 'managed');

    // With no extension of its own the report is a "nothing discovered" message;
    // a projection over the platform's own bundles would only be noise there.
    if (own.length === 0 || managed.length === 0) {
        return [];
    }

    return [
        '',
        `  ${colors.cyan('project-root projection')}  ${managed.map((entry) => entry.file).join(', ')}  ` +
            colors.dim('(git-ignored — never commit or hand-edit)'),
        ...managed.map((entry) => colors.dim(`      ${entry.file} — ${entry.detail}`)),
    ];
}

const VERBS = {
    real: { created: 'generated', updated: 'updated', removed: 'removed' },
    check: { created: 'would create', updated: 'would update', removed: 'would delete' },
};

/**
 * What the run changed — or, under `--check`, would change. Paths a developer
 * must act on are listed individually; the git-ignored bridge files, whose
 * count scales with the number of extensions, are summarized.
 */
function renderChanges(result: SetupExtensionToolingResult, checkOnly: boolean, commands: ToolingCommands): string[] {
    const verbs = checkOnly ? VERBS.check : VERBS.real;
    const changes = [
        ...result.writes
            .filter((write) => write.state === 'created')
            .map((write) => ({ verb: verbs.created, file: write.file })),
        ...result.writes
            .filter((write) => write.state === 'updated')
            .map((write) => ({ verb: verbs.updated, file: write.file })),
        ...result.staleFiles.map((file) => ({ verb: verbs.removed, file })),
    ];

    if (changes.length === 0) {
        return [colors.dim('  Configs up to date')];
    }

    const lines = checkOnly ? [colors.red(`  Setup is stale — re-run \`${commands.setup}\`:`)] : [];
    const counts = new Map<FileClass, number>();

    for (const { verb, file } of changes) {
        const fileClass = classifyFile(file);
        const { list, note } = OWNERSHIP[fileClass];

        if (list) {
            lines.push(colors.dim(`    ${verb}: ${file}`) + (note ? colors.cyan(` [${note}]`) : ''));
        } else {
            counts.set(fileClass, (counts.get(fileClass) ?? 0) + 1);
        }
    }

    for (const [
        fileClass,
        count,
    ] of counts) {
        lines.push(colors.dim(`    ${count} ${OWNERSHIP[fileClass].note}`));
    }

    return lines;
}

export function renderSetupReport(result: SetupExtensionToolingResult, options: SetupRenderOptions = {}): string {
    const { projects } = result.manifest;
    const checkOnly = options.checkOnly === true;
    const commands = options.commands ?? DEFAULT_TOOLING_COMMANDS;
    const stateOf: StateMap = new Map(
        projects.map((project) => [
            project.name,
            deriveExtensionState(project),
        ]),
    );
    const own = projects.filter((project) => stateOf.get(project.name) !== 'platform');
    const created = result.writes.filter((write) => write.state === 'created');
    const freshlyBridged = new Set(
        projects
            .filter((project) =>
                created.some(
                    (write) => write.file.startsWith(`${project.basePath}/`) && classifyFile(write.file) === 'bridge',
                ),
            )
            .map((project) => project.name),
    );
    const lines = [
        colors.bold(
            own.length === 0
                ? 'Administration extension tooling — no extensions found'
                : `Administration extension tooling — ${own.length} extension(s)`,
        ),
        ...renderNotice(),
    ];

    // The empty state must never read as a green "up to date": the most likely
    // cause is a stale var/plugins.json after installing or activating a plugin.
    if (own.length === 0) {
        lines.push(
            '',
            '  No installed extension with Administration sources was discovered.',
            '  Discovery reads var/plugins.json — refresh it after installing or activating a plugin:',
            '',
            '      bin/console bundle:dump',
        );
    }

    lines.push(...renderCoverage(projects, stateOf, commands, freshlyBridged));
    lines.push(...renderRootProjection(result, own));
    lines.push('', ...renderChanges(result, checkOnly, commands));

    for (const [
        name,
        state,
    ] of [
        [
            'tsconfig.json',
            result.manifest.rootConfigs.tsconfig,
        ],
        [
            'eslint.config.mjs',
            result.manifest.rootConfigs.eslintConfig,
        ],
    ] as const) {
        if (state === 'conflict') {
            lines.push(colors.yellow(`  ⚠ root ${name} is user-owned — integration steps below`));
        }
    }

    for (const warning of result.warnings) {
        lines.push(colors.yellow(`  ⚠ ${warning.message}`));
    }

    lines.push(
        ...result.instructions.flatMap((instruction) => [
            '',
            ...instruction.split('\n').map((line) => `  ${line}`),
        ]),
    );

    if (options.showFlagHint) {
        lines.push(colors.dim(`  Options need "--": ${commands.setup} -- --check | --help`));
    }

    return lines.join('\n');
}
