/**
 * @sw-package framework
 *
 * Bridge generation — automatic for every discovered non-platform extension. A
 * bridge is the git-ignored, machine-specific hop into the installed
 * Administration; the committed extension configs (scaffolded in setup-configs)
 * extend it. One bridge is written per directory that owns a config, so a
 * package-level config governing several Administration roots gets a single
 * shared bridge. A bridge that cannot be written (an unwritable vendor
 * directory) degrades to a warning; the extension stays covered through the
 * root projection.
 */

import fs from 'fs';
import path from 'path';
import { record, warn } from './setup-context';
import type { GeneratorContext } from './setup-context';
import { SPEC_FILE_SUFFIXES, scaffoldExtensionConfigs } from './setup-configs';
import { GENERATED_MARKER, SHIM_DIR_NAME, asRelativeSpecifier, isPlatformProject, writeManagedFile } from './shared';
import type { ExtensionToolingProject, OwnedConfig } from './shared';

/**
 * Aliases contributing to a bridge's merged `paths`. Each source's targets
 * resolve relative to its own `baseDir`, so a shared bridge can carry the
 * aliases declared beside every covered Administration root, not only one.
 */
interface AliasSource {
    aliasesPath: string;
    baseDir: string;
}

function dedupeAliasSources(sources: AliasSource[]): AliasSource[] {
    return [
        ...new Map(
            sources.map((source) => [
                source.aliasesPath,
                source,
            ]),
        ).values(),
    ];
}

/**
 * TypeScript replaces `paths` wholesale across `extends`, so a plugin that
 * declares its own aliases would erase the preset's host paths. The bridge is
 * therefore the single `paths` declarer: it merges the preset's host paths
 * (re-relativized to the bridge, machine paths are fine in generated files)
 * with plugin aliases from every `tsconfig.aliases.json` beside a covered root
 * ({ "MyPlugin/*": ["src/*"] }, targets relative to that alias file's directory).
 */
function buildShimPaths(
    context: GeneratorContext,
    shimDir: string,
    aliasSources: AliasSource[],
): Record<string, string[]> | null {
    const presentSources = aliasSources.filter((source) => fs.existsSync(source.aliasesPath));

    if (presentSources.length === 0) {
        return null;
    }

    const shimTsconfigPath = path.join(shimDir, 'tsconfig.json');
    const presetPath = path.join(context.toolingRoot, 'tsconfig.base.json');
    const preset = JSON.parse(fs.readFileSync(presetPath, 'utf8')) as {
        compilerOptions?: { paths?: Record<string, string[]> };
    };
    const presetDir = path.dirname(presetPath);
    const mergedPaths: Record<string, string[]> = {};

    for (const [
        moduleName,
        targets,
    ] of Object.entries(preset.compilerOptions?.paths ?? {})) {
        mergedPaths[moduleName] = targets.map((target) =>
            asRelativeSpecifier(shimTsconfigPath, path.resolve(presetDir, target)),
        );
    }

    for (const source of presentSources) {
        const aliases = JSON.parse(fs.readFileSync(source.aliasesPath, 'utf8')) as Record<string, string[] | string>;

        for (const [
            alias,
            targets,
        ] of Object.entries(aliases)) {
            mergedPaths[alias] = (Array.isArray(targets) ? targets : [targets]).map((target) =>
                asRelativeSpecifier(shimTsconfigPath, path.resolve(source.baseDir, target)),
            );
        }
    }

    return mergedPaths;
}

/** The README generated into every bridge so the folder explains itself when stumbled upon. */
function bridgeReadmeContent(context: GeneratorContext): string {
    return [
        `<!-- ${GENERATED_MARKER} -->`,
        '',
        '# Why this folder exists',
        '',
        `This \`${SHIM_DIR_NAME}/\` directory is the generated bridge between this extension`,
        'and the installed Shopware Administration: its `tsconfig.json` and `eslint.mjs`',
        'hold the machine-specific paths into the installed Administration, so the',
        "extension's own committed configs can stay small and portable.",
        '',
        `- Autogenerated by \`${context.commands.setup}\` and rewritten on every run —`,
        '  do not edit anything in here.',
        '- Git-ignored by design (the folder ignores itself via its own `.gitignore`)',
        '  because the contained paths only make sense on this machine — never',
        '  commit it.',
        `- After a Shopware update (or moving the project), re-run \`${context.commands.setup}\``,
        '  to regenerate it.',
        '',
    ].join('\n');
}

/**
 * Writes the git-ignored bridge files into `<bridgeParent>/.shopware/`. The
 * bridge is the machine-specific hop into the installed Administration; its
 * eslint half derives its own parent directory at runtime, so one bridge serves
 * whichever config — per-root or a shared package root — sits beside it.
 */
function writeBridge(
    context: GeneratorContext,
    bridgeParent: string,
    aliasSources: AliasSource[],
    sourcePaths: string[],
): void {
    const shimDir = path.join(bridgeParent, SHIM_DIR_NAME);
    const basePreset = path.join(context.administrationRoot, 'extension-tooling', 'tsconfig.base.json');
    const adminTypes = path.join(context.administrationRoot, 'extension-tooling', 'admin-types.d.ts');
    const specTypes = path.join(context.administrationRoot, 'extension-tooling', 'spec-types.d.ts');
    const factoryPath = path.join(context.administrationRoot, 'extension-tooling', 'eslint.mjs');
    const shimTsconfigPath = path.join(shimDir, 'tsconfig.json');
    const shimSpecTsconfigPath = path.join(shimDir, 'tsconfig.specs.json');
    const shimEslintPath = path.join(shimDir, 'eslint.mjs');
    const shimPaths = buildShimPaths(context, shimDir, aliasSources);

    record(context, writeManagedFile(path.join(shimDir, '.gitignore'), `# ${GENERATED_MARKER}\n*\n`, context.dryRun));
    record(context, writeManagedFile(path.join(shimDir, 'README.md'), bridgeReadmeContent(context), context.dryRun));
    record(
        context,
        writeManagedFile(
            shimTsconfigPath,
            `// ${GENERATED_MARKER} — machine-specific path into the installed Administration.\n${JSON.stringify(
                {
                    extends: asRelativeSpecifier(shimTsconfigPath, basePreset),
                    files: [asRelativeSpecifier(shimTsconfigPath, adminTypes)],
                    ...(shimPaths ? { compilerOptions: { paths: shimPaths } } : {}),
                },
                null,
                4,
            )}\n`,
            context.dryRun,
        ),
    );
    // The dedicated spec program: composes the runtime bridge (inheriting its
    // host paths and plugin aliases) but swaps the type surface for jest globals
    // and includes only the spec files the runtime program excludes. typeRoots
    // points at the Administration's own @types so the `jest` reference in
    // spec-types.d.ts resolves relative to this config, not to the .d.ts.
    record(
        context,
        writeManagedFile(
            shimSpecTsconfigPath,
            `// ${GENERATED_MARKER} — dedicated spec program: jest types, spec files only.\n${JSON.stringify(
                {
                    extends: asRelativeSpecifier(shimSpecTsconfigPath, shimTsconfigPath),
                    compilerOptions: {
                        typeRoots: [
                            asRelativeSpecifier(
                                shimSpecTsconfigPath,
                                path.join(context.administrationRoot, 'node_modules', '@types'),
                            ),
                        ],
                    },
                    files: [
                        asRelativeSpecifier(shimSpecTsconfigPath, adminTypes),
                        asRelativeSpecifier(shimSpecTsconfigPath, specTypes),
                    ],
                    include: sourcePaths.flatMap((sourcePath) =>
                        SPEC_FILE_SUFFIXES.map(
                            (suffix) =>
                                `${asRelativeSpecifier(
                                    shimSpecTsconfigPath,
                                    path.resolve(context.projectRoot, sourcePath),
                                )}/**/*.${suffix}`,
                        ),
                    ),
                },
                null,
                4,
            )}\n`,
            context.dryRun,
        ),
    );
    record(
        context,
        writeManagedFile(
            shimEslintPath,
            [
                `// ${GENERATED_MARKER} — machine-specific path into the installed Administration.`,
                "import path from 'node:path';",
                "import { fileURLToPath } from 'node:url';",
                `import { shopwareAdminExtension } from ${JSON.stringify(asRelativeSpecifier(shimEslintPath, factoryPath))};`,
                '',
                'const adminFolder = path.dirname(path.dirname(fileURLToPath(import.meta.url)));',
                '',
                `export * from ${JSON.stringify(asRelativeSpecifier(shimEslintPath, factoryPath))};`,
                '',
                'export function shopwareAdminExtensionConfig(options = {}) {',
                '    return shopwareAdminExtension({ tsconfigRootDir: adminFolder, ...options });',
                '}',
                '',
                'export default shopwareAdminExtensionConfig();',
                '',
            ].join('\n'),
            context.dryRun,
        ),
    );
}

/**
 * Groups an extension's source roots by the directory their bridge belongs in:
 * beside each config the extension already owns, or beside the source root
 * itself when it owns none. A package-level config governing several roots
 * therefore gets one shared bridge, independent per-root configs get one each,
 * and no layout has to be classified up front. `--root-config` overrides the
 * grouping for one extension; the config scaffolded there makes the choice
 * self-perpetuating, so nothing needs to remember it.
 */
function bridgeDirs(
    context: GeneratorContext,
    project: ExtensionToolingProject,
    explicitRootConfig?: string,
): Map<string, string[]> {
    const grouped = new Map<string, string[]>();

    for (const target of project.targets) {
        const ownedDirs = [
            target.tsconfig,
            target.eslintConfig,
        ]
            .filter((config): config is OwnedConfig => config !== null)
            .map((config) => path.dirname(path.resolve(context.projectRoot, config.path)));
        const dirs =
            explicitRootConfig !== undefined
                ? [path.resolve(context.projectRoot, project.basePath, explicitRootConfig)]
                : [...new Set(ownedDirs.length > 0 ? ownedDirs : [path.resolve(context.projectRoot, target.adminFolder)])];

        for (const dir of dirs) {
            grouped.set(dir, [
                ...(grouped.get(dir) ?? []),
                target.sourcePath,
            ]);
        }
    }

    return grouped;
}

/**
 * Bridges every discovered non-platform extension — custom and vendor alike, so
 * linting and type-checking always run through generated configs. A bridge that
 * cannot be written (an unwritable directory) is skipped with a warning instead
 * of failing the run: the extension then stays on the root projection.
 */
export function createBridges(
    context: GeneratorContext,
    projects: ExtensionToolingProject[],
    rootConfigDirs: Record<string, string>,
): void {
    for (const project of projects) {
        if (isPlatformProject(project)) {
            continue;
        }

        try {
            for (const [
                dir,
                sourcePaths,
            ] of bridgeDirs(context, project, rootConfigDirs[project.name])) {
                const aliasSources = dedupeAliasSources(
                    [
                        dir,
                        ...sourcePaths.map((sourcePath) => path.dirname(path.resolve(context.projectRoot, sourcePath))),
                    ].map((baseDir) => ({ aliasesPath: path.join(baseDir, 'tsconfig.aliases.json'), baseDir })),
                );

                writeBridge(context, dir, aliasSources, sourcePaths);
                scaffoldExtensionConfigs(context, project.name, dir, sourcePaths, project.vendor);
            }
        } catch (error) {
            warn(
                context,
                `Could not write the bridge for ${project.name} into ${project.basePath} ` +
                    `(${error instanceof Error ? error.message : String(error)}) — falling back to the root projection.`,
                project.name,
            );
        }
    }
}
