/**
 * @sw-package framework
 */

import fs from 'fs';
import path from 'path';

export const GENERATED_MARKER = '// @generated by Shopware Administration extension tooling. Do not edit.';
export const TOOLING_PACKAGE_NAME = '@shopware-ag/administration-extension-tooling';
export const BASELINE_FILE_NAME = '.shopware-admin-baseline.json';

interface BundleConfig {
    technicalName: string;
    basePath: string;
    administration?: {
        path?: string | null;
    };
}

export interface ExtensionToolingProject {
    technicalName: string;
    basePath: string;
    sourcePath: string;
    tsconfig: string | null;
    checkTsconfig: string;
    eslintConfig: string | null;
    baseline: string;
    mode: 'default' | 'custom';
}

export interface ExtensionToolingManifest {
    version: 1;
    administrationRoot: string;
    bridgePackage: string;
    rootTsconfigManaged: boolean;
    rootEslintConfigManaged: boolean;
    entitySchemaAvailable: boolean;
    projects: ExtensionToolingProject[];
}

export interface SetupExtensionToolingOptions {
    projectRoot: string;
    administrationRoot: string;
    pluginsConfigPath?: string;
}

export interface SetupExtensionToolingResult {
    manifest: ExtensionToolingManifest;
    manifestPath: string;
    warnings: string[];
}

const ESLINT_CONFIG_NAMES = [
    'eslint.config.mjs',
    'eslint.config.js',
    'eslint.config.cjs',
    'eslint.config.ts',
];

function toPosix(filePath: string): string {
    return filePath.split(path.sep).join('/');
}

function relativeToProject(projectRoot: string, filePath: string): string {
    return toPosix(path.relative(projectRoot, filePath)) || '.';
}

function asImportSpecifier(fromFile: string, targetFile: string): string {
    let relativePath = toPosix(path.relative(path.dirname(fromFile), targetFile));

    if (!relativePath.startsWith('.')) {
        relativePath = './' + relativePath;
    }

    return relativePath;
}

function isWithin(candidate: string, parent: string): boolean {
    const relativePath = path.relative(parent, candidate);

    return (
        relativePath === '' ||
        (!relativePath.startsWith('..' + path.sep) && relativePath !== '..' && !path.isAbsolute(relativePath))
    );
}

function findNearestConfig(sourcePath: string, boundaryPath: string, fileNames: string[]): string | null {
    let currentPath = sourcePath;

    while (isWithin(currentPath, boundaryPath)) {
        for (const fileName of fileNames) {
            const candidate = path.join(currentPath, fileName);

            if (fs.existsSync(candidate)) {
                return candidate;
            }
        }

        if (currentPath === boundaryPath) {
            break;
        }

        currentPath = path.dirname(currentPath);
    }

    return null;
}

function findExtensionRoot(projectRoot: string, bundleBasePath: string): string {
    let currentPath = bundleBasePath;

    while (isWithin(currentPath, projectRoot)) {
        if (fs.existsSync(path.join(currentPath, 'composer.json'))) {
            return currentPath;
        }

        if (currentPath === projectRoot) {
            break;
        }

        currentPath = path.dirname(currentPath);
    }

    return bundleBasePath;
}

function readBundleConfig(configPath: string): BundleConfig[] {
    if (!fs.existsSync(configPath)) {
        throw new Error('Administration extension config does not exist: ' + configPath);
    }

    const parsedConfig: unknown = JSON.parse(fs.readFileSync(configPath, 'utf8'));

    if (Array.isArray(parsedConfig)) {
        return parsedConfig as BundleConfig[];
    }

    if (parsedConfig && typeof parsedConfig === 'object') {
        return Object.values(parsedConfig) as BundleConfig[];
    }

    throw new Error('Administration extension config must contain an object or array: ' + configPath);
}

function discoverProjects(
    projectRoot: string,
    administrationRoot: string,
    bundles: BundleConfig[],
): ExtensionToolingProject[] {
    const administrationSourcePath = path.resolve(administrationRoot, 'src');
    const projects = new Map<string, ExtensionToolingProject>();

    for (const bundle of bundles) {
        const administrationPath = bundle.administration?.path;

        if (!administrationPath) {
            continue;
        }

        const bundleBasePath = path.isAbsolute(bundle.basePath)
            ? path.normalize(bundle.basePath)
            : path.resolve(projectRoot, bundle.basePath);
        const sourcePath = path.resolve(bundleBasePath, administrationPath);

        if (!fs.existsSync(sourcePath) || sourcePath === administrationSourcePath) {
            continue;
        }

        const extensionRoot = findExtensionRoot(projectRoot, bundleBasePath);
        const tsconfig = findNearestConfig(sourcePath, extensionRoot, ['tsconfig.json']);
        const eslintConfig = findNearestConfig(sourcePath, extensionRoot, ESLINT_CONFIG_NAMES);
        const project: ExtensionToolingProject = {
            technicalName: bundle.technicalName,
            basePath: relativeToProject(projectRoot, extensionRoot),
            sourcePath: relativeToProject(projectRoot, sourcePath),
            tsconfig: tsconfig ? relativeToProject(projectRoot, tsconfig) : null,
            checkTsconfig: tsconfig ? relativeToProject(projectRoot, tsconfig) : '',
            eslintConfig: eslintConfig ? relativeToProject(projectRoot, eslintConfig) : null,
            baseline: relativeToProject(projectRoot, path.join(extensionRoot, BASELINE_FILE_NAME)),
            mode: tsconfig || eslintConfig ? 'custom' : 'default',
        };

        projects.set(project.sourcePath, project);
    }

    return [...projects.values()].sort((left, right) => left.sourcePath.localeCompare(right.sourcePath));
}

function createProjectCheckTsconfigs(
    projectRoot: string,
    stateRoot: string,
    projects: ExtensionToolingProject[],
): ExtensionToolingProject[] {
    const projectConfigRoot = path.join(stateRoot, 'projects');

    fs.rmSync(projectConfigRoot, { recursive: true, force: true });
    fs.mkdirSync(projectConfigRoot, { recursive: true });

    return projects.map((project, index) => {
        if (project.tsconfig) {
            return project;
        }

        const safeName = project.technicalName.replace(/[^a-zA-Z0-9_-]/g, '-').toLowerCase();
        const configPath = path.join(projectConfigRoot, safeName + '-' + index + '.json');
        const sourcePath = path.resolve(projectRoot, project.sourcePath);
        const relativeSourcePath = toPosix(path.relative(path.dirname(configPath), sourcePath));

        fs.writeFileSync(
            configPath,
            JSON.stringify(
                {
                    extends: TOOLING_PACKAGE_NAME + '/tsconfig',
                    include: [
                        relativeSourcePath + '/**/*.js',
                        relativeSourcePath + '/**/*.ts',
                        relativeSourcePath + '/**/*.tsx',
                        relativeSourcePath + '/**/*.vue',
                    ],
                },
                null,
                2,
            ) + '\n',
        );

        return {
            ...project,
            checkTsconfig: relativeToProject(projectRoot, configPath),
        };
    });
}

function writeManagedFile(filePath: string, content: string): boolean {
    if (fs.existsSync(filePath)) {
        const currentContent = fs.readFileSync(filePath, 'utf8');

        if (!currentContent.startsWith(GENERATED_MARKER)) {
            return false;
        }
    }

    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, content);

    return true;
}

function createBridgePackage(projectRoot: string, administrationRoot: string): string {
    const bridgeRoot = path.join(projectRoot, 'node_modules', '@shopware-ag', 'administration-extension-tooling');
    const sourceRoot = path.join(administrationRoot, 'extension-tooling');
    const requiredFiles = [
        'eslint.mjs',
        'legacy-twig.mjs',
        'tsconfig.json',
        'types.d.ts',
        'public-api.d.ts',
    ];

    for (const requiredFile of requiredFiles) {
        if (!fs.existsSync(path.join(sourceRoot, requiredFile))) {
            throw new Error('Administration extension tooling file is missing: ' + path.join(sourceRoot, requiredFile));
        }
    }

    fs.rmSync(bridgeRoot, { recursive: true, force: true });
    fs.mkdirSync(bridgeRoot, { recursive: true });

    const eslintProxyPath = path.join(bridgeRoot, 'eslint.mjs');
    const legacyTwigProxyPath = path.join(bridgeRoot, 'legacy-twig.mjs');
    const typeProxyPath = path.join(bridgeRoot, 'types.d.ts');
    const tsconfigProxyPath = path.join(bridgeRoot, 'tsconfig.json');
    const typeSourcePath = path.join(sourceRoot, 'types.d.ts');
    const typeImportPath = asImportSpecifier(typeProxyPath, typeSourcePath).replace(/\.d\.ts$/, '');

    fs.writeFileSync(
        path.join(bridgeRoot, 'package.json'),
        JSON.stringify(
            {
                name: TOOLING_PACKAGE_NAME,
                private: true,
                type: 'module',
                types: './types.d.ts',
                exports: {
                    '.': {
                        types: './types.d.ts',
                    },
                    './eslint': './eslint.mjs',
                    './eslint/legacy-twig': './legacy-twig.mjs',
                    './tsconfig': './tsconfig.json',
                },
            },
            null,
            2,
        ) + '\n',
    );
    fs.writeFileSync(
        eslintProxyPath,
        "export * from '" +
            asImportSpecifier(eslintProxyPath, path.join(sourceRoot, 'eslint.mjs')) +
            "';\n" +
            "export { default } from '" +
            asImportSpecifier(eslintProxyPath, path.join(sourceRoot, 'eslint.mjs')) +
            "';\n",
    );
    fs.writeFileSync(
        legacyTwigProxyPath,
        "export * from '" +
            asImportSpecifier(legacyTwigProxyPath, path.join(sourceRoot, 'legacy-twig.mjs')) +
            "';\n" +
            "export { default } from '" +
            asImportSpecifier(legacyTwigProxyPath, path.join(sourceRoot, 'legacy-twig.mjs')) +
            "';\n",
    );
    fs.writeFileSync(typeProxyPath, "import '" + typeImportPath + "';\n");
    fs.writeFileSync(
        tsconfigProxyPath,
        JSON.stringify(
            {
                extends: asImportSpecifier(tsconfigProxyPath, path.join(sourceRoot, 'tsconfig.json')),
            },
            null,
            2,
        ) + '\n',
    );

    return bridgeRoot;
}

function createRootTsconfig(projectRoot: string, stateRoot: string, projects: ExtensionToolingProject[]): boolean {
    const defaultProjects = projects.filter((project) => project.tsconfig === null);
    const config: Record<string, unknown> = {
        $schema: 'https://json.schemastore.org/tsconfig',
        extends: TOOLING_PACKAGE_NAME + '/tsconfig',
    };

    if (defaultProjects.length > 0) {
        config.include = defaultProjects.flatMap((project) => [
            project.sourcePath + '/**/*.js',
            project.sourcePath + '/**/*.ts',
            project.sourcePath + '/**/*.tsx',
            project.sourcePath + '/**/*.vue',
        ]);
    } else {
        const emptyFilePath = path.join(stateRoot, 'empty.ts');
        fs.mkdirSync(stateRoot, { recursive: true });
        fs.writeFileSync(emptyFilePath, 'export {};\n');
        config.files = [relativeToProject(projectRoot, emptyFilePath)];
    }

    return writeManagedFile(
        path.join(projectRoot, 'tsconfig.json'),
        GENERATED_MARKER + '\n' + JSON.stringify(config, null, 2) + '\n',
    );
}

function createRootEslintConfig(projectRoot: string): boolean {
    const content =
        GENERATED_MARKER +
        '\n' +
        "import path from 'node:path';\n" +
        "import { fileURLToPath } from 'node:url';\n" +
        "import { shopwareAdminExtension } from '" +
        TOOLING_PACKAGE_NAME +
        "/eslint';\n\n" +
        'const tsconfigRootDir = path.dirname(fileURLToPath(import.meta.url));\n\n' +
        'export default shopwareAdminExtension({ legacyTwig: true, tsconfigRootDir });\n';

    return writeManagedFile(path.join(projectRoot, 'eslint.config.mjs'), content);
}

export function setupExtensionTooling(options: SetupExtensionToolingOptions): SetupExtensionToolingResult {
    const projectRoot = path.resolve(options.projectRoot);
    const administrationRoot = path.resolve(options.administrationRoot);
    const pluginsConfigPath = path.resolve(options.pluginsConfigPath ?? path.join(projectRoot, 'var', 'plugins.json'));
    const stateRoot = path.join(projectRoot, 'var', 'admin-extension-tooling');
    const manifestPath = path.join(stateRoot, 'manifest.json');
    const bundles = readBundleConfig(pluginsConfigPath);
    const discoveredProjects = discoverProjects(projectRoot, administrationRoot, bundles);
    const bridgeRoot = createBridgePackage(projectRoot, administrationRoot);
    const projects = createProjectCheckTsconfigs(projectRoot, stateRoot, discoveredProjects);
    const rootTsconfigManaged = createRootTsconfig(projectRoot, stateRoot, projects);
    const rootEslintConfigManaged = createRootEslintConfig(projectRoot);
    const entitySchemaPath = path.join(administrationRoot, 'src', 'entity-schema-definition.d.ts');
    const warnings: string[] = [];

    if (!rootTsconfigManaged) {
        warnings.push('Existing root tsconfig.json was preserved. Extend ' + TOOLING_PACKAGE_NAME + '/tsconfig manually.');
    }

    if (!rootEslintConfigManaged) {
        warnings.push(
            'Existing root eslint.config.mjs was preserved. Compose ' + TOOLING_PACKAGE_NAME + '/eslint manually.',
        );
    }

    if (!fs.existsSync(entitySchemaPath)) {
        warnings.push('Generated entity schema types are missing. Run composer admin:generate-entity-schema-types.');
    }

    const manifest: ExtensionToolingManifest = {
        version: 1,
        administrationRoot: relativeToProject(projectRoot, administrationRoot),
        bridgePackage: relativeToProject(projectRoot, bridgeRoot),
        rootTsconfigManaged,
        rootEslintConfigManaged,
        entitySchemaAvailable: fs.existsSync(entitySchemaPath),
        projects,
    };

    fs.mkdirSync(stateRoot, { recursive: true });
    fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n');

    return {
        manifest,
        manifestPath,
        warnings,
    };
}

function readArgument(name: string): string | undefined {
    const prefix = '--' + name + '=';
    const argument = process.argv.find((value) => value.startsWith(prefix));

    return argument?.slice(prefix.length);
}

if (require.main === module) {
    const administrationRoot = path.resolve(readArgument('administration-root') ?? path.resolve(__dirname, '../..'));
    const projectRoot = readArgument('project-root') ?? process.env.PROJECT_ROOT;

    if (!projectRoot) {
        throw new Error('PROJECT_ROOT or --project-root is required.');
    }

    const result = setupExtensionTooling({
        projectRoot,
        administrationRoot,
        pluginsConfigPath: readArgument('plugins-config'),
    });
    const defaultCount = result.manifest.projects.filter((project) => project.tsconfig === null).length;
    const customCount = result.manifest.projects.length - defaultCount;

    console.log(
        'Administration extension tooling configured for ' +
            result.manifest.projects.length +
            ' project(s): ' +
            defaultCount +
            ' zero-config, ' +
            customCount +
            ' custom.',
    );

    for (const warning of result.warnings) {
        console.warn(warning);
    }
}
