/**
 * @sw-package framework
 *
 * Shared building blocks for the Administration extension tooling:
 * manifest types, generated-file ownership, path helpers, discovery,
 * and the freshness hash.
 */

import crypto from 'crypto';
import fs from 'fs';
import path from 'path';

/**
 * Every generated file starts with a line containing this marker. Files
 * without the marker are never overwritten — they belong to a human.
 */
export const GENERATED_MARKER = '@generated by Shopware Administration extension tooling';

export const STATE_DIR = 'var/admin-extension-tooling';
export const SHIM_DIR_NAME = '.shopware-admin';

export type ConfigMode = 'managed' | 'custom' | 'unmanaged';

export type ManagedFileState = 'created' | 'updated' | 'unchanged' | 'conflict' | 'skipped';

/** File states as persisted in the manifest — free of run-specific detail so setup stays idempotent. */
export type ManifestFileState = 'managed' | 'conflict' | 'skipped';

export interface BundleConfig {
    technicalName: string;
    basePath: string;
    administration?: {
        path?: string | null;
        entryFilePath?: string | null;
    };
}

export interface ExtensionToolingProject {
    /** Folder name of the extension root (nearest composer.json), e.g. "SwagPayPal". */
    name: string;
    technicalNames: string[];
    /** Extension root relative to the project root (posix). */
    basePath: string;
    /** Administration source directories relative to the project root (posix). */
    sourcePaths: string[];
    /** Whether the extension is installed below vendor/ (read-only, non-fatal findings). */
    vendor: boolean;
    /** Path to an extension-owned tsconfig.json, if one exists. */
    tsconfig: string | null;
    /** Path to an extension-owned eslint config, if one exists. */
    eslintConfig: string | null;
    /**
     * Discovery-time mode per tool. "unmanaged" is only assigned at check
     * time, when a custom config turns out not to compose the Shopware preset.
     */
    tsMode: ConfigMode;
    eslintMode: ConfigMode;
    /** The tsconfig the check runner passes to vue-tsc (leaf or custom). */
    checkTsconfig: string;
}

export interface ExtensionToolingManifest {
    version: 1;
    adminRoot: string;
    entitySchemaAvailable: boolean;
    freshnessHash: string;
    hostModules: Record<string, string>;
    rootConfigs: {
        tsconfig: ManifestFileState;
        eslintConfig: ManifestFileState;
    };
    ideBootstraps: Record<string, ManifestFileState>;
    projects: ExtensionToolingProject[];
}

export function toPosix(filePath: string): string {
    return filePath.split(path.sep).join('/');
}

export function relativePosix(from: string, to: string): string {
    return toPosix(path.relative(from, to)) || '.';
}

/**
 * Relative path suitable as an ESM import specifier or tsconfig "extends"
 * value (always starts with "./" or "../").
 */
export function asRelativeSpecifier(fromFile: string, targetFile: string): string {
    let relativePath = toPosix(path.relative(path.dirname(fromFile), targetFile));

    if (!relativePath.startsWith('.')) {
        relativePath = `./${relativePath}`;
    }

    return relativePath;
}

export function isWithin(candidate: string, parent: string): boolean {
    const relativePath = path.relative(parent, candidate);

    return (
        relativePath === '' ||
        (!relativePath.startsWith(`..${path.sep}`) && relativePath !== '..' && !path.isAbsolute(relativePath))
    );
}

/**
 * Resolves symlinked ancestors (e.g. /var -> /private/var on macOS) so path
 * comparisons work on canonical paths even for files that do not exist yet.
 */
export function canonicalizePath(filePath: string): string {
    let existingPath = filePath;

    while (!fs.existsSync(existingPath)) {
        const parentPath = path.dirname(existingPath);

        if (parentPath === existingPath) {
            return filePath;
        }

        existingPath = parentPath;
    }

    return path.join(fs.realpathSync(existingPath), path.relative(existingPath, filePath));
}

export function findNearestConfig(startPath: string, boundaryPath: string, fileNames: string[]): string | null {
    let currentPath = startPath;

    while (isWithin(currentPath, boundaryPath)) {
        for (const fileName of fileNames) {
            const candidate = path.join(currentPath, fileName);

            if (fs.existsSync(candidate)) {
                return candidate;
            }
        }

        if (currentPath === boundaryPath) {
            break;
        }

        currentPath = path.dirname(currentPath);
    }

    return null;
}

/**
 * Walks up from a bundle base path to the nearest directory containing a
 * composer.json — the extension owner root. Multi-bundle suites group under
 * their shared composer root this way.
 */
export function findExtensionRoot(projectRoot: string, bundleBasePath: string): string {
    let currentPath = bundleBasePath;

    while (isWithin(currentPath, projectRoot)) {
        if (fs.existsSync(path.join(currentPath, 'composer.json'))) {
            return currentPath;
        }

        if (currentPath === projectRoot) {
            break;
        }

        currentPath = path.dirname(currentPath);
    }

    return bundleBasePath;
}

export function readBundleConfig(configPath: string): BundleConfig[] {
    if (!fs.existsSync(configPath)) {
        throw new Error(`The file ${configPath} could not be found. Try bin/console bundle:dump to create this file.`);
    }

    const parsedConfig: unknown = JSON.parse(fs.readFileSync(configPath, 'utf8'));

    if (Array.isArray(parsedConfig)) {
        return parsedConfig as BundleConfig[];
    }

    if (parsedConfig && typeof parsedConfig === 'object') {
        return Object.values(parsedConfig) as BundleConfig[];
    }

    throw new Error(`The file ${configPath} must contain an object or array of bundle definitions.`);
}

export function isGeneratedContent(content: string): boolean {
    const firstLines = content.split(/\r?\n/, 3).join('\n');

    return firstLines.includes(GENERATED_MARKER);
}

export interface WriteResult {
    file: string;
    state: ManagedFileState;
}

/**
 * Writes a marker-owned file. Never overwrites a file a human wrote:
 * existing files without the generated marker report a conflict instead.
 * Writes are atomic (temp file + rename) and idempotent (identical content
 * is not rewritten).
 */
export function writeManagedFile(filePath: string, content: string, dryRun = false): WriteResult {
    const file = filePath;

    if (fs.existsSync(filePath)) {
        const currentContent = fs.readFileSync(filePath, 'utf8');

        if (!isGeneratedContent(currentContent)) {
            return { file, state: 'conflict' };
        }

        if (currentContent === content) {
            return { file, state: 'unchanged' };
        }

        if (!dryRun) {
            atomicWrite(filePath, content);
        }

        return { file, state: 'updated' };
    }

    if (!dryRun) {
        atomicWrite(filePath, content);
    }

    return { file, state: 'created' };
}

/**
 * Writes a tool-owned state file (inside var/) without an ownership check —
 * pure-JSON state files cannot carry a marker comment. Idempotent.
 */
export function writeStateFile(filePath: string, content: string, dryRun = false): WriteResult {
    if (fs.existsSync(filePath)) {
        if (fs.readFileSync(filePath, 'utf8') === content) {
            return { file: filePath, state: 'unchanged' };
        }

        if (!dryRun) {
            atomicWrite(filePath, content);
        }

        return { file: filePath, state: 'updated' };
    }

    if (!dryRun) {
        atomicWrite(filePath, content);
    }

    return { file: filePath, state: 'created' };
}

export function atomicWrite(filePath: string, content: string): void {
    fs.mkdirSync(path.dirname(filePath), { recursive: true });

    const temporaryPath = `${filePath}.${process.pid}.tmp`;

    fs.writeFileSync(temporaryPath, content);
    fs.renameSync(temporaryPath, filePath);
}

export function createFreshnessHash(parts: string[]): string {
    const hash = crypto.createHash('sha256');

    for (const part of parts) {
        hash.update(part);
        hash.update(' ');
    }

    return hash.digest('hex');
}

/**
 * Inputs for the freshness hash: the bundle dump, the entity schema
 * (content or absence), and the installed Administration version. The check
 * command recomputes the hash and hard-fails when any input changed after
 * the last setup run.
 */
export function computeFreshnessHash(
    pluginsConfigPath: string,
    entitySchemaPath: string,
    administrationPackageJsonPath: string,
): string {
    const pluginsContent = fs.existsSync(pluginsConfigPath) ? fs.readFileSync(pluginsConfigPath, 'utf8') : 'absent';
    const schemaContent = fs.existsSync(entitySchemaPath) ? fs.readFileSync(entitySchemaPath, 'utf8') : 'absent';
    const packageJson = JSON.parse(fs.readFileSync(administrationPackageJsonPath, 'utf8')) as { version?: string };

    return createFreshnessHash([
        pluginsContent,
        schemaContent,
        packageJson.version ?? 'unknown',
    ]);
}

export function readCliArgument(argv: string[], name: string): string | undefined {
    const prefix = `--${name}=`;
    const argument = argv.find((value) => value.startsWith(prefix));

    return argument?.slice(prefix.length);
}

export function hasCliFlag(argv: string[], name: string): boolean {
    return argv.includes(`--${name}`);
}
