/**
 * @sw-package framework
 *
 * Shared building blocks for the Administration extension tooling:
 * manifest types, generated-file ownership, path helpers, and discovery.
 */

import fs from 'fs';
import path from 'path';

/**
 * Every generated file starts with a line containing this marker. Files
 * without the marker are never overwritten — they belong to a human.
 */
export const GENERATED_MARKER = '@generated by Shopware Administration extension tooling';

export const STATE_DIR = 'var/admin-extension-tooling';
export const SHIM_DIR_NAME = '.shopware-admin';

/**
 * Composition state of an Administration target's config, per tool:
 * - `managed`: no extension-owned config; generated host configs check it.
 * - `bridged`: extension-owned config composes the Shopware bridge/factory.
 * - `unmanaged`: extension-owned config does not compose (or fails to load).
 * `vendor`/`platform` are ownership qualifiers, not composition modes.
 */
export type ConfigMode = 'managed' | 'bridged' | 'unmanaged';

/** Why a config-owning extension resolved to `unmanaged`. */
export type ModeReason =
    | 'config-error'
    | 'files-override'
    | 'paths-override'
    | 'not-extending'
    | 'surface-not-injected'
    | 'factory-not-composed';

/**
 * Per-tool resolution of an extension's config mode. Static analysis produces
 * unverified resolutions at setup time; live tool probes (check runs) produce
 * verified ones, carried back into setup through the probe cache.
 */
export interface ModeResolution {
    mode: ConfigMode;
    reason?: ModeReason;
    /** Human sentence explaining the reason (rendered under `why:`). */
    detail?: string;
    /** Raw probe output, shown with --verbose. */
    probeOutput?: string;
    /** True when a live tool probe confirmed the mode (vs static analysis). */
    verified: boolean;
}

export type ManagedFileState = 'created' | 'updated' | 'unchanged' | 'conflict' | 'skipped';

/** File states as persisted in the manifest — free of run-specific detail so setup stays idempotent. */
export type ManifestFileState = 'managed' | 'conflict' | 'skipped';

export interface BundleConfig {
    technicalName: string;
    basePath: string;
    administration?: {
        path?: string | null;
        entryFilePath?: string | null;
    };
}

export interface AdministrationTarget {
    /** Bundle technical names that resolve to this canonical Administration source root. */
    technicalNames: string[];
    /** Administration source directory relative to the project root (posix). */
    sourcePath: string;
    /** Directory containing the Administration source root, relative to the project root (posix). */
    adminFolder: string;
    /** Whether a generated `.shopware-admin/` bridge sits beside this source root. */
    bridgePresent: boolean;
    /** Nearest extension-owned tsconfig.json governing this source root, if one exists. */
    tsconfig: string | null;
    /** Nearest extension-owned ESLint config governing this source root, if one exists. */
    eslintConfig: string | null;
    /** Per-tool mode resolution (static at discovery, verified via probe cache / check runs). */
    ts: ModeResolution;
    eslint: ModeResolution;
    /** The runtime tsconfig the check runner passes to vue-tsc (generated leaf or custom config). */
    checkTsconfig: string;
    /** Generated leaf tsconfig for the spec type-check program (Jest types + this target's specs). */
    specTsconfig: string;
}

export interface ExtensionToolingProject {
    /** Folder name of the extension root (nearest composer.json), e.g. "SwagPayPal". */
    name: string;
    /** All bundle technical names owned by this extension. */
    technicalNames: string[];
    /** Extension root relative to the project root (posix); owns reporting and the baseline. */
    basePath: string;
    /** Whether the extension is installed below vendor/ (read-only, non-fatal findings). */
    vendor: boolean;
    /** Every canonical Administration source root owned by this extension. */
    targets: AdministrationTarget[];
}

export interface ExtensionToolingManifest {
    version: 3;
    adminRoot: string;
    entitySchemaAvailable: boolean;
    hostModules: Record<string, string>;
    rootConfigs: {
        tsconfig: ManifestFileState;
        eslintConfig: ManifestFileState;
    };
    ideBootstraps: Record<string, ManifestFileState>;
    /** The managed ignore block for generated root files in the project .gitignore. */
    gitignore: {
        state: ManifestFileState;
        optedOut: boolean;
    };
    projects: ExtensionToolingProject[];
}

/** Defensive disk read of the last run's manifest — null on absence, garbage, or a version mismatch. */
export function readPreviousManifest(projectRoot: string): ExtensionToolingManifest | null {
    try {
        const parsed = JSON.parse(
            fs.readFileSync(path.join(projectRoot, STATE_DIR, 'manifest.json'), 'utf8'),
        ) as ExtensionToolingManifest;

        return parsed && parsed.version === 3 ? parsed : null;
    } catch {
        return null;
    }
}

/**
 * Display state derived from the project's facts — never stored, so setup and
 * check cannot disagree about it.
 */
export type DerivedExtensionState = 'ready' | 'needs-bridge' | 'bridge-unwired' | 'bridged' | 'platform' | 'vendor';

export function projectSourcePaths(project: ExtensionToolingProject): string[] {
    return project.targets.map((target) => target.sourcePath);
}

export function projectHasBridge(project: ExtensionToolingProject): boolean {
    return project.targets.some((target) => target.bridgePresent);
}

export function projectHasOwnedConfig(project: ExtensionToolingProject): boolean {
    return project.targets.some((target) => target.tsconfig !== null || target.eslintConfig !== null);
}

/**
 * Reduces target-level facts for the package-level report. Execution never
 * uses this aggregate: each target/effective config remains authoritative.
 */
export function aggregateModeResolution(project: ExtensionToolingProject, tool: 'ts' | 'eslint'): ModeResolution {
    const resolutions = project.targets.map((target) => target[tool]);
    const allVerified = resolutions.every((resolution) => resolution.verified);
    const firstUnmanaged = resolutions.find((resolution) => resolution.mode === 'unmanaged');

    if (firstUnmanaged) {
        return {
            ...firstUnmanaged,
            verified: allVerified,
        };
    }

    if (resolutions.some((resolution) => resolution.mode === 'bridged')) {
        return {
            mode: 'bridged',
            verified: allVerified,
        };
    }

    return { mode: 'managed', verified: true };
}

/** A target whose own config kept a tool from covering it, with the resolution that says why. */
export interface SkippedTarget {
    /** Administration source root relative to the project root (posix). */
    sourcePath: string;
    /** The extension-owned config that caused the skip (project-root-relative posix). */
    configPath: string;
    tool: 'TypeScript' | 'ESLint';
    resolution: ModeResolution;
}

/**
 * Every unmanaged target of the project, independent of whether the managed
 * remainder passed or failed. Runtime and spec TypeScript programs share one
 * entry — both key on the same target resolution.
 */
export function collectSkippedTargets(project: ExtensionToolingProject): SkippedTarget[] {
    const skipped: SkippedTarget[] = [];

    for (const target of project.targets) {
        if (target.ts.mode === 'unmanaged') {
            skipped.push({
                sourcePath: target.sourcePath,
                configPath: target.tsconfig ?? target.sourcePath,
                tool: 'TypeScript',
                resolution: target.ts,
            });
        }

        if (target.eslint.mode === 'unmanaged') {
            skipped.push({
                sourcePath: target.sourcePath,
                configPath: target.eslintConfig ?? target.sourcePath,
                tool: 'ESLint',
                resolution: target.eslint,
            });
        }
    }

    return skipped;
}

export function deriveExtensionState(project: ExtensionToolingProject): DerivedExtensionState {
    if (project.vendor) {
        return 'vendor';
    }

    if (!project.basePath.startsWith('custom/plugins/')) {
        return 'platform';
    }

    if (!projectHasOwnedConfig(project)) {
        return 'ready';
    }

    const composes = project.targets.every(
        (target) =>
            (target.tsconfig === null || target.ts.mode === 'bridged') &&
            (target.eslintConfig === null || target.eslint.mode === 'bridged'),
    );

    if (composes) {
        return 'bridged';
    }

    return projectHasBridge(project) ? 'bridge-unwired' : 'needs-bridge';
}

export function toPosix(filePath: string): string {
    return filePath.split(path.sep).join('/');
}

export function relativePosix(from: string, to: string): string {
    return toPosix(path.relative(from, to)) || '.';
}

/**
 * How a reader invokes the extension-tooling commands, adapted to the install
 * layout so printed next-step guidance is copy-pasteable in their environment.
 * A platform (monorepo) checkout wires the `composer admin:*` scripts; a
 * Composer/Flex install (Administration under `vendor/`) has no such scripts and
 * drives the tooling through the `bin/console administration:*` commands.
 */
export interface ToolingCommands {
    /** e.g. `composer admin:check-extensions` or `bin/console administration:check-extensions`. */
    check: string;
    /** e.g. `composer admin:setup-extension-tooling` or `bin/console administration:setup-extension-tooling`. */
    setup: string;
    /** e.g. `composer admin:generate-entity-schema-types` or `bin/console administration:generate-entity-schema-types`. */
    generateSchema: string;
}

/** The platform-checkout invocations — the safe default when the layout is unknown (e.g. in unit fixtures). */
export const DEFAULT_TOOLING_COMMANDS: ToolingCommands = {
    check: 'composer admin:check-extensions',
    setup: 'composer admin:setup-extension-tooling',
    generateSchema: 'composer admin:generate-entity-schema-types',
};

const CONSOLE_TOOLING_COMMANDS: ToolingCommands = {
    check: 'bin/console administration:check-extensions',
    setup: 'bin/console administration:setup-extension-tooling',
    generateSchema: 'bin/console administration:generate-entity-schema-types',
};

export function resolveToolingCommands(projectRoot: string, administrationRoot: string): ToolingCommands {
    // The Administration living under vendor/ is the Composer/Flex install signal
    // — the composer scripts exist only in a platform checkout.
    return relativePosix(projectRoot, administrationRoot).startsWith('vendor/')
        ? CONSOLE_TOOLING_COMMANDS
        : DEFAULT_TOOLING_COMMANDS;
}

/**
 * Relative path suitable as an ESM import specifier or tsconfig "extends"
 * value (always starts with "./" or "../").
 */
export function asRelativeSpecifier(fromFile: string, targetFile: string): string {
    let relativePath = toPosix(path.relative(path.dirname(fromFile), targetFile));

    if (!relativePath.startsWith('.')) {
        relativePath = `./${relativePath}`;
    }

    return relativePath;
}

export function isWithin(candidate: string, parent: string): boolean {
    const relativePath = path.relative(parent, candidate);

    return (
        relativePath === '' ||
        (!relativePath.startsWith(`..${path.sep}`) && relativePath !== '..' && !path.isAbsolute(relativePath))
    );
}

/**
 * Resolves symlinked ancestors (e.g. /var -> /private/var on macOS) so path
 * comparisons work on canonical paths even for files that do not exist yet.
 */
export function canonicalizePath(filePath: string): string {
    let existingPath = filePath;

    while (!fs.existsSync(existingPath)) {
        const parentPath = path.dirname(existingPath);

        if (parentPath === existingPath) {
            return filePath;
        }

        existingPath = parentPath;
    }

    return path.join(fs.realpathSync(existingPath), path.relative(existingPath, filePath));
}

export function findNearestConfig(startPath: string, boundaryPath: string, fileNames: string[]): string | null {
    let currentPath = startPath;

    while (isWithin(currentPath, boundaryPath)) {
        for (const fileName of fileNames) {
            const candidate = path.join(currentPath, fileName);

            if (fs.existsSync(candidate)) {
                return candidate;
            }
        }

        if (currentPath === boundaryPath) {
            break;
        }

        currentPath = path.dirname(currentPath);
    }

    return null;
}

/**
 * Walks up from a bundle base path to the nearest directory containing a
 * composer.json — the extension owner root. Multi-bundle suites group under
 * their shared composer root this way. The project root itself never counts
 * as an extension root (its composer.json is the shop, not an extension).
 */
export function findExtensionRoot(projectRoot: string, bundleBasePath: string): string {
    let currentPath = bundleBasePath;

    while (isWithin(currentPath, projectRoot) && currentPath !== projectRoot) {
        if (fs.existsSync(path.join(currentPath, 'composer.json'))) {
            return currentPath;
        }

        currentPath = path.dirname(currentPath);
    }

    return bundleBasePath;
}

export function readBundleConfig(configPath: string): BundleConfig[] {
    if (!fs.existsSync(configPath)) {
        throw new Error(`The file ${configPath} could not be found. Try bin/console bundle:dump to create this file.`);
    }

    const parsedConfig: unknown = JSON.parse(fs.readFileSync(configPath, 'utf8'));

    if (Array.isArray(parsedConfig)) {
        return parsedConfig as BundleConfig[];
    }

    if (parsedConfig && typeof parsedConfig === 'object') {
        return Object.values(parsedConfig) as BundleConfig[];
    }

    throw new Error(`The file ${configPath} must contain an object or array of bundle definitions.`);
}

export function isGeneratedContent(content: string): boolean {
    const firstLines = content.split(/\r?\n/, 3).join('\n');

    return firstLines.includes(GENERATED_MARKER);
}

export interface WriteResult {
    file: string;
    state: ManagedFileState;
}

/**
 * Writes a marker-owned file. Never overwrites a file a human wrote:
 * existing files without the generated marker report a conflict instead.
 * Writes are atomic (temp file + rename) and idempotent (identical content
 * is not rewritten).
 */
export function writeManagedFile(filePath: string, content: string, dryRun = false): WriteResult {
    if (fs.existsSync(filePath)) {
        const currentContent = fs.readFileSync(filePath, 'utf8');

        if (!isGeneratedContent(currentContent)) {
            return { file: filePath, state: 'conflict' };
        }

        if (currentContent === content) {
            return { file: filePath, state: 'unchanged' };
        }

        if (!dryRun) {
            atomicWrite(filePath, content);
        }

        return { file: filePath, state: 'updated' };
    }

    if (!dryRun) {
        atomicWrite(filePath, content);
    }

    return { file: filePath, state: 'created' };
}

/**
 * Writes a tool-owned state file (inside var/) without an ownership check —
 * pure-JSON state files cannot carry a marker comment. Idempotent.
 */
export function writeStateFile(filePath: string, content: string, dryRun = false): WriteResult {
    if (fs.existsSync(filePath)) {
        if (fs.readFileSync(filePath, 'utf8') === content) {
            return { file: filePath, state: 'unchanged' };
        }

        if (!dryRun) {
            atomicWrite(filePath, content);
        }

        return { file: filePath, state: 'updated' };
    }

    if (!dryRun) {
        atomicWrite(filePath, content);
    }

    return { file: filePath, state: 'created' };
}

/**
 * Writes a committable scaffold the developer owns from then on: created only
 * when absent, never overwritten (so edits survive re-runs). Unlike
 * writeManagedFile these carry no marker — they are the plugin's own files.
 */
export function writeScaffoldFile(filePath: string, content: string, dryRun = false): WriteResult {
    if (fs.existsSync(filePath)) {
        return { file: filePath, state: 'skipped' };
    }

    if (!dryRun) {
        atomicWrite(filePath, content);
    }

    return { file: filePath, state: 'created' };
}

export function atomicWrite(filePath: string, content: string): void {
    fs.mkdirSync(path.dirname(filePath), { recursive: true });

    const temporaryPath = `${filePath}.${process.pid}.tmp`;

    fs.writeFileSync(temporaryPath, content);
    fs.renameSync(temporaryPath, filePath);
}

export const MANAGED_BLOCK_BEGIN = `# >>> ${GENERATED_MARKER}`;
export const MANAGED_BLOCK_END = `# <<< ${GENERATED_MARKER}`;

/**
 * Owns a marker-fenced region inside a user-owned file (the one sanctioned
 * write into a user file — ownership is scoped to the fence and the initial
 * write is append-only). Everything outside the fence is preserved
 * byte-identically; a begin marker without its end reports a conflict.
 */
export function writeManagedBlock(filePath: string, blockBody: string[], dryRun = false): WriteResult {
    const block = [
        MANAGED_BLOCK_BEGIN,
        ...blockBody,
        MANAGED_BLOCK_END,
    ].join('\n');

    if (!fs.existsSync(filePath)) {
        if (!dryRun) {
            atomicWrite(filePath, `${block}\n`);
        }

        return { file: filePath, state: 'created' };
    }

    const currentContent = fs.readFileSync(filePath, 'utf8');
    const beginIndex = currentContent.indexOf(MANAGED_BLOCK_BEGIN);
    const endIndex = currentContent.indexOf(MANAGED_BLOCK_END);

    if (beginIndex === -1 && endIndex === -1) {
        const separator = currentContent === '' || currentContent.endsWith('\n') ? '\n' : '\n\n';

        if (!dryRun) {
            atomicWrite(filePath, `${currentContent}${separator}${block}\n`);
        }

        return { file: filePath, state: 'updated' };
    }

    if (beginIndex === -1 || endIndex < beginIndex) {
        return { file: filePath, state: 'conflict' };
    }

    const nextContent =
        currentContent.slice(0, beginIndex) + block + currentContent.slice(endIndex + MANAGED_BLOCK_END.length);

    if (nextContent === currentContent) {
        return { file: filePath, state: 'unchanged' };
    }

    if (!dryRun) {
        atomicWrite(filePath, nextContent);
    }

    return { file: filePath, state: 'updated' };
}

/**
 * Major version of the Administration's installed ESLint, read from its
 * package.json. Falls back to 9 when ESLint cannot be resolved.
 */
export function readEslintMajorVersion(administrationRoot: string): number {
    const eslintPackagePath = path.join(administrationRoot, 'node_modules', 'eslint', 'package.json');

    try {
        const eslintPackage = JSON.parse(fs.readFileSync(eslintPackagePath, 'utf8')) as { version: string };

        return Number(eslintPackage.version.split('.')[0]);
    } catch {
        return 9;
    }
}
