/**
 * @sw-package framework
 *
 * Shared building blocks for the Administration extension tooling:
 * manifest types, generated-file ownership, path helpers, and discovery.
 */

import fs from 'fs';
import path from 'path';

/**
 * Every generated file starts with a line containing this marker. Files
 * without the marker are never overwritten — they belong to a human.
 */
export const GENERATED_MARKER = '@generated by Shopware Administration extension tooling';

export const STATE_DIR = 'var/admin-extension-tooling';
export const SHIM_DIR_NAME = '.shopware-admin';

export type ConfigMode = 'managed' | 'custom' | 'unmanaged';

/** Why a config-owning extension resolved to `unmanaged`. */
export type ModeReason =
    | 'config-error'
    | 'files-override'
    | 'paths-override'
    | 'not-extending'
    | 'surface-not-injected'
    | 'factory-not-composed';

/**
 * Per-tool resolution of an extension's config mode. Static analysis produces
 * unverified resolutions at setup time; live tool probes (check runs) produce
 * verified ones, carried back into setup through the probe cache.
 */
export interface ModeResolution {
    mode: ConfigMode;
    reason?: ModeReason;
    /** Human sentence explaining the reason (rendered under `why:`). */
    detail?: string;
    /** Raw probe output, shown with --verbose. */
    probeOutput?: string;
    /** True when a live tool probe confirmed the mode (vs static analysis). */
    verified: boolean;
}

export type ManagedFileState = 'created' | 'updated' | 'unchanged' | 'conflict' | 'skipped';

/** File states as persisted in the manifest — free of run-specific detail so setup stays idempotent. */
export type ManifestFileState = 'managed' | 'conflict' | 'skipped';

export interface BundleConfig {
    technicalName: string;
    basePath: string;
    administration?: {
        path?: string | null;
        entryFilePath?: string | null;
    };
}

export interface ExtensionToolingProject {
    /** Folder name of the extension root (nearest composer.json), e.g. "SwagPayPal". */
    name: string;
    technicalNames: string[];
    /** Extension root relative to the project root (posix). */
    basePath: string;
    /** Administration source directories relative to the project root (posix). */
    sourcePaths: string[];
    /** Whether the extension is installed below vendor/ (read-only, non-fatal findings). */
    vendor: boolean;
    /** Whether a generated `.shopware-admin/` bridge sits next to the sources. */
    bridgePresent: boolean;
    /** Path to an extension-owned tsconfig.json, if one exists. */
    tsconfig: string | null;
    /** Path to an extension-owned eslint config, if one exists. */
    eslintConfig: string | null;
    /** Per-tool mode resolution (static at discovery, verified via probe cache / check runs). */
    ts: ModeResolution;
    eslint: ModeResolution;
    /** The tsconfig the check runner passes to vue-tsc (leaf or custom). */
    checkTsconfig: string;
    /** The generated leaf tsconfig for the spec type-check program (jest types + specs only). */
    specTsconfig: string;
}

export interface ExtensionToolingManifest {
    version: 2;
    adminRoot: string;
    entitySchemaAvailable: boolean;
    hostModules: Record<string, string>;
    rootConfigs: {
        tsconfig: ManifestFileState;
        eslintConfig: ManifestFileState;
    };
    ideBootstraps: Record<string, ManifestFileState>;
    /** The managed ignore block for generated root files in the project .gitignore. */
    gitignore: {
        state: ManifestFileState;
        optedOut: boolean;
    };
    projects: ExtensionToolingProject[];
}

/** Defensive disk read of the last run's manifest — null on absence, garbage, or a version mismatch. */
export function readPreviousManifest(projectRoot: string): ExtensionToolingManifest | null {
    try {
        const parsed = JSON.parse(
            fs.readFileSync(path.join(projectRoot, STATE_DIR, 'manifest.json'), 'utf8'),
        ) as ExtensionToolingManifest;

        return parsed && parsed.version === 2 ? parsed : null;
    } catch {
        return null;
    }
}

/**
 * Display state derived from the project's facts — never stored, so setup and
 * check cannot disagree about it.
 */
export type DerivedExtensionState = 'ready' | 'needs-bridge' | 'bridge-unwired' | 'bridged' | 'platform' | 'vendor';

export function deriveExtensionState(project: ExtensionToolingProject): DerivedExtensionState {
    if (project.vendor) {
        return 'vendor';
    }

    if (!project.basePath.startsWith('custom/plugins/')) {
        return 'platform';
    }

    if (project.tsconfig === null && project.eslintConfig === null) {
        return 'ready';
    }

    const composes =
        (project.tsconfig === null || project.ts.mode === 'custom') &&
        (project.eslintConfig === null || project.eslint.mode === 'custom');

    if (composes) {
        return 'bridged';
    }

    return project.bridgePresent ? 'bridge-unwired' : 'needs-bridge';
}

export function toPosix(filePath: string): string {
    return filePath.split(path.sep).join('/');
}

export function relativePosix(from: string, to: string): string {
    return toPosix(path.relative(from, to)) || '.';
}

/**
 * Relative path suitable as an ESM import specifier or tsconfig "extends"
 * value (always starts with "./" or "../").
 */
export function asRelativeSpecifier(fromFile: string, targetFile: string): string {
    let relativePath = toPosix(path.relative(path.dirname(fromFile), targetFile));

    if (!relativePath.startsWith('.')) {
        relativePath = `./${relativePath}`;
    }

    return relativePath;
}

export function isWithin(candidate: string, parent: string): boolean {
    const relativePath = path.relative(parent, candidate);

    return (
        relativePath === '' ||
        (!relativePath.startsWith(`..${path.sep}`) && relativePath !== '..' && !path.isAbsolute(relativePath))
    );
}

/**
 * Resolves symlinked ancestors (e.g. /var -> /private/var on macOS) so path
 * comparisons work on canonical paths even for files that do not exist yet.
 */
export function canonicalizePath(filePath: string): string {
    let existingPath = filePath;

    while (!fs.existsSync(existingPath)) {
        const parentPath = path.dirname(existingPath);

        if (parentPath === existingPath) {
            return filePath;
        }

        existingPath = parentPath;
    }

    return path.join(fs.realpathSync(existingPath), path.relative(existingPath, filePath));
}

export function findNearestConfig(startPath: string, boundaryPath: string, fileNames: string[]): string | null {
    let currentPath = startPath;

    while (isWithin(currentPath, boundaryPath)) {
        for (const fileName of fileNames) {
            const candidate = path.join(currentPath, fileName);

            if (fs.existsSync(candidate)) {
                return candidate;
            }
        }

        if (currentPath === boundaryPath) {
            break;
        }

        currentPath = path.dirname(currentPath);
    }

    return null;
}

/**
 * Walks up from a bundle base path to the nearest directory containing a
 * composer.json — the extension owner root. Multi-bundle suites group under
 * their shared composer root this way. The project root itself never counts
 * as an extension root (its composer.json is the shop, not an extension).
 */
export function findExtensionRoot(projectRoot: string, bundleBasePath: string): string {
    let currentPath = bundleBasePath;

    while (isWithin(currentPath, projectRoot) && currentPath !== projectRoot) {
        if (fs.existsSync(path.join(currentPath, 'composer.json'))) {
            return currentPath;
        }

        currentPath = path.dirname(currentPath);
    }

    return bundleBasePath;
}

export function readBundleConfig(configPath: string): BundleConfig[] {
    if (!fs.existsSync(configPath)) {
        throw new Error(`The file ${configPath} could not be found. Try bin/console bundle:dump to create this file.`);
    }

    const parsedConfig: unknown = JSON.parse(fs.readFileSync(configPath, 'utf8'));

    if (Array.isArray(parsedConfig)) {
        return parsedConfig as BundleConfig[];
    }

    if (parsedConfig && typeof parsedConfig === 'object') {
        return Object.values(parsedConfig) as BundleConfig[];
    }

    throw new Error(`The file ${configPath} must contain an object or array of bundle definitions.`);
}

export function isGeneratedContent(content: string): boolean {
    const firstLines = content.split(/\r?\n/, 3).join('\n');

    return firstLines.includes(GENERATED_MARKER);
}

export interface WriteResult {
    file: string;
    state: ManagedFileState;
}

/**
 * Writes a marker-owned file. Never overwrites a file a human wrote:
 * existing files without the generated marker report a conflict instead.
 * Writes are atomic (temp file + rename) and idempotent (identical content
 * is not rewritten).
 */
export function writeManagedFile(filePath: string, content: string, dryRun = false): WriteResult {
    const file = filePath;

    if (fs.existsSync(filePath)) {
        const currentContent = fs.readFileSync(filePath, 'utf8');

        if (!isGeneratedContent(currentContent)) {
            return { file, state: 'conflict' };
        }

        if (currentContent === content) {
            return { file, state: 'unchanged' };
        }

        if (!dryRun) {
            atomicWrite(filePath, content);
        }

        return { file, state: 'updated' };
    }

    if (!dryRun) {
        atomicWrite(filePath, content);
    }

    return { file, state: 'created' };
}

/**
 * Writes a tool-owned state file (inside var/) without an ownership check —
 * pure-JSON state files cannot carry a marker comment. Idempotent.
 */
export function writeStateFile(filePath: string, content: string, dryRun = false): WriteResult {
    if (fs.existsSync(filePath)) {
        if (fs.readFileSync(filePath, 'utf8') === content) {
            return { file: filePath, state: 'unchanged' };
        }

        if (!dryRun) {
            atomicWrite(filePath, content);
        }

        return { file: filePath, state: 'updated' };
    }

    if (!dryRun) {
        atomicWrite(filePath, content);
    }

    return { file: filePath, state: 'created' };
}

/**
 * Writes a committable scaffold the developer owns from then on: created only
 * when absent, never overwritten (so edits survive re-runs). Unlike
 * writeManagedFile these carry no marker — they are the plugin's own files.
 */
export function writeScaffoldFile(filePath: string, content: string, dryRun = false): WriteResult {
    if (fs.existsSync(filePath)) {
        return { file: filePath, state: 'skipped' };
    }

    if (!dryRun) {
        atomicWrite(filePath, content);
    }

    return { file: filePath, state: 'created' };
}

export function atomicWrite(filePath: string, content: string): void {
    fs.mkdirSync(path.dirname(filePath), { recursive: true });

    const temporaryPath = `${filePath}.${process.pid}.tmp`;

    fs.writeFileSync(temporaryPath, content);
    fs.renameSync(temporaryPath, filePath);
}

export const MANAGED_BLOCK_BEGIN = `# >>> ${GENERATED_MARKER}`;
export const MANAGED_BLOCK_END = `# <<< ${GENERATED_MARKER}`;

/**
 * Owns a marker-fenced region inside a user-owned file (the one sanctioned
 * write into a user file — ownership is scoped to the fence and the initial
 * write is append-only). Everything outside the fence is preserved
 * byte-identically; a begin marker without its end reports a conflict.
 */
export function writeManagedBlock(filePath: string, blockBody: string[], dryRun = false): WriteResult {
    const block = [
        MANAGED_BLOCK_BEGIN,
        ...blockBody,
        MANAGED_BLOCK_END,
    ].join('\n');

    if (!fs.existsSync(filePath)) {
        if (!dryRun) {
            atomicWrite(filePath, `${block}\n`);
        }

        return { file: filePath, state: 'created' };
    }

    const currentContent = fs.readFileSync(filePath, 'utf8');
    const beginIndex = currentContent.indexOf(MANAGED_BLOCK_BEGIN);
    const endIndex = currentContent.indexOf(MANAGED_BLOCK_END);

    if (beginIndex === -1 && endIndex === -1) {
        const separator = currentContent === '' || currentContent.endsWith('\n') ? '\n' : '\n\n';

        if (!dryRun) {
            atomicWrite(filePath, `${currentContent}${separator}${block}\n`);
        }

        return { file: filePath, state: 'updated' };
    }

    if (beginIndex === -1 || endIndex < beginIndex) {
        return { file: filePath, state: 'conflict' };
    }

    const nextContent =
        currentContent.slice(0, beginIndex) + block + currentContent.slice(endIndex + MANAGED_BLOCK_END.length);

    if (nextContent === currentContent) {
        return { file: filePath, state: 'unchanged' };
    }

    if (!dryRun) {
        atomicWrite(filePath, nextContent);
    }

    return { file: filePath, state: 'updated' };
}
