@startuml
' uncomment the line below if you're using computer with a retina display
' skinparam dpi 300
!define Table(name,desc) class name as "desc" << (T,#FFAAAA) >>
!define ForeignTable(name,desc) class name as "desc" << (T,#ada6a6) >>
!define TranslationTable(name,desc) class name as "desc" << (I,#4286f4) >>
' we use bold for primary key
' green color for unique
' and underscore for not_null
!define primary_key(x) <b>x</b>
!define unique(x) <color:green>x</color>
!define not_null(x) <u>x</u>
' other tags available:
' <i></i>
' <back:COLOR></color>, where color is a color name or html color code
' (#FFAACC)
' see: http://plantuml.com/classes.html#More
hide methods
hide stereotypes
hide empty members
skinparam backgroundColor #FFFFFF

' entities

Table(ShopwareCoreFrameworkPluginPluginDefinition, "plugin\n(Plugin)") {
   primary_key(id) id
   not_null(baseClass) string
   not_null(name) string
   composerName string
   not_null(autoload) json
   active bool
   managedByComposer bool
   path string
   author string
   copyright string
   license string
   not_null(version) string
   upgradeVersion string
   installedAt dateTime
   upgradedAt dateTime
   iconRaw blob
   icon string
   label translated
   description translated
   manufacturerLink translated
   supportLink translated
   changelog translated
   customFields translated
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   translated json
}
TranslationTable(ShopwareCoreFrameworkPluginAggregatePluginTranslationPluginTranslationDefinition, "plugin_translation\n((Translations))") {
   not_null(label) string
   description longText
   manufacturerLink string
   supportLink string
   changelog json
   customFields customFields
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   primary_key(pluginId) foreignKey
   primary_key(languageId) foreignKey
}
ForeignTable(ShopwareCoreCheckoutPaymentPaymentMethodDefinition, "payment_method") {
}
ForeignTable(ShopwareCoreFrameworkLanguageLanguageDefinition, "language") {
}

' relationshipd

ShopwareCoreFrameworkPluginAggregatePluginTranslationPluginTranslationDefinition --> ShopwareCoreFrameworkPluginPluginDefinition
ShopwareCoreFrameworkPluginPluginDefinition --> ShopwareCoreCheckoutPaymentPaymentMethodDefinition
ShopwareCoreFrameworkPluginAggregatePluginTranslationPluginTranslationDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
@enduml
