<?php declare(strict_types=1);

namespace Shopware\Core\Migration\V6_9;

use Doctrine\DBAL\ArrayParameterType;
use Doctrine\DBAL\Connection;
use Doctrine\DBAL\ParameterType;
use Shopware\Core\Checkout\DocumentV2\Aggregate\DocumentFile\DocumentFileDefinition;
use Shopware\Core\Checkout\DocumentV2\DocumentFormat;
use Shopware\Core\Checkout\DocumentV2\DocumentType;
use Shopware\Core\Defaults;
use Shopware\Core\Framework\Log\Package;
use Shopware\Core\Framework\Migration\MigrationStep;
use Shopware\Core\Framework\Uuid\Uuid;

/**
 * Backfills the document_file rows for documents that were generated by the legacy (v1) document
 * generation, and reassigns the legacy Zugferd document types to their base type.
 *
 * A v1 document only carries its artifacts in the two legacy media slots (document_media_file_id
 * and document_a11y_media_file_id). This migration derives one document_file row per populated slot
 * so the artifacts stay accessible once the legacy media fields are removed, mirroring the read-time
 * fallback that resolves the same rows virtually before 6.9.
 *
 * @internal
 *
 * @phpstan-type LegacyDocument array{id: string, typeName: ?string, primaryMediaId: ?string, primaryExtension: ?string, accessibilityMediaId: ?string}
 * @phpstan-type DocumentFile array{documentId: string, mediaId: string, format: string}
 */
#[Package('after-sales')]
class Migration1787292621BackfillDocumentFiles extends MigrationStep
{
    private const BATCH_SIZE = 1000;

    /**
     * @var array<string, DocumentType>
     */
    private const ZUGFERD_TYPE_REASSIGNMENT = [
        'zugferd_invoice' => DocumentType::INVOICE,
        'zugferd_embedded_invoice' => DocumentType::INVOICE,
        'zugferd_cancellation_invoice' => DocumentType::CANCELLATION_INVOICE,
        'zugferd_embedded_cancellation_invoice' => DocumentType::CANCELLATION_INVOICE,
        'zugferd_credit_note' => DocumentType::CREDIT_NOTE,
        'zugferd_embedded_credit_note' => DocumentType::CREDIT_NOTE,
    ];

    /**
     * @var array<string, DocumentFormat>
     */
    private const ZUGFERD_PRIMARY_FORMAT = [
        'zugferd_invoice' => DocumentFormat::ZUGFERD_XML,
        'zugferd_cancellation_invoice' => DocumentFormat::ZUGFERD_XML,
        'zugferd_credit_note' => DocumentFormat::ZUGFERD_XML,
        'zugferd_embedded_invoice' => DocumentFormat::ZUGFERD_EMBEDDED_PDF,
        'zugferd_embedded_cancellation_invoice' => DocumentFormat::ZUGFERD_EMBEDDED_PDF,
        'zugferd_embedded_credit_note' => DocumentFormat::ZUGFERD_EMBEDDED_PDF,
    ];

    public function getCreationTimestamp(): int
    {
        return 1787292621;
    }

    public function update(Connection $connection): void
    {
        $this->backfillDocumentFiles($connection);
        $this->reassignZugferdTypes($connection);
    }

    private function backfillDocumentFiles(Connection $connection): void
    {
        $lastId = '';

        do {
            /** @var list<LegacyDocument> $documents */
            $documents = $connection->fetchAllAssociative(
                'SELECT
                     LOWER(HEX(`document`.`id`)) AS `id`,
                     `document`.`type_name` AS `typeName`,
                     LOWER(HEX(`document`.`document_media_file_id`)) AS `primaryMediaId`,
                     `primary_media`.`file_extension` AS `primaryExtension`,
                     LOWER(HEX(`document`.`document_a11y_media_file_id`)) AS `accessibilityMediaId`
                 FROM `document`
                 LEFT JOIN `media` AS `primary_media` ON `primary_media`.`id` = `document`.`document_media_file_id`
                 WHERE `document`.`id` > :lastId
                   AND (
                         (`document`.`document_media_file_id` IS NOT NULL AND `primary_media`.`file_extension` > \'\')
                         OR `document`.`document_a11y_media_file_id` IS NOT NULL
                     )
                 ORDER BY `document`.`id`
                 LIMIT :limit',
                ['lastId' => $lastId, 'limit' => self::BATCH_SIZE],
                ['lastId' => ParameterType::BINARY, 'limit' => ParameterType::INTEGER]
            );

            foreach ($documents as $document) {
                foreach ($this->resolveFiles($document) as $file) {
                    $connection->executeStatement(
                        'INSERT IGNORE INTO `' . DocumentFileDefinition::ENTITY_NAME . '`
                            (`id`, `document_id`, `media_id`, `document_format`, `created_at`)
                         VALUES (:id, :documentId, :mediaId, :format, :createdAt)',
                        [
                            'id' => Uuid::randomBytes(),
                            'documentId' => Uuid::fromHexToBytes($file['documentId']),
                            'mediaId' => Uuid::fromHexToBytes($file['mediaId']),
                            'format' => $file['format'],
                            'createdAt' => (new \DateTimeImmutable())->format(Defaults::STORAGE_DATE_TIME_FORMAT),
                        ]
                    );
                }
            }

            $lastDocument = end($documents);

            if ($lastDocument !== false) {
                $lastId = Uuid::fromHexToBytes($lastDocument['id']);
            }
        } while (\count($documents) === self::BATCH_SIZE);
    }

    private function reassignZugferdTypes(Connection $connection): void
    {
        foreach (self::ZUGFERD_TYPE_REASSIGNMENT as $legacyType => $baseType) {
            $lastId = '';

            do {
                /** @var list<string> $ids */
                $ids = $connection->fetchFirstColumn(
                    'SELECT `id` FROM `document` WHERE `type_name` = :legacyType AND `id` > :lastId ORDER BY `id` LIMIT :limit',
                    ['legacyType' => $legacyType, 'lastId' => $lastId, 'limit' => self::BATCH_SIZE],
                    ['legacyType' => ParameterType::STRING, 'lastId' => ParameterType::BINARY, 'limit' => ParameterType::INTEGER]
                );

                if ($ids === []) {
                    break;
                }

                $connection->executeStatement(
                    'UPDATE IGNORE `document` SET `type_name` = :baseType WHERE `id` IN (:ids)',
                    ['baseType' => $baseType->value, 'ids' => $ids],
                    ['baseType' => ParameterType::STRING, 'ids' => ArrayParameterType::BINARY]
                );

                $lastId = end($ids);
            } while (\count($ids) === self::BATCH_SIZE);
        }
    }

    /**
     * @param LegacyDocument $document
     *
     * @return list<DocumentFile>
     */
    private function resolveFiles(array $document): array
    {
        $files = [];

        $primaryFormat = $this->primaryFormat(
            $document['typeName'],
            $document['primaryExtension']
        );

        if ($document['primaryMediaId'] !== null && $primaryFormat !== null) {
            $files[] = [
                'documentId' => $document['id'],
                'mediaId' => $document['primaryMediaId'],
                'format' => $primaryFormat,
            ];
        }

        $accessibilityMediaId = $document['accessibilityMediaId'];

        if ($accessibilityMediaId !== null && $accessibilityMediaId !== $document['primaryMediaId'] && $primaryFormat !== DocumentFormat::HTML->value) {
            $files[] = [
                'documentId' => $document['id'],
                'mediaId' => $accessibilityMediaId,
                'format' => DocumentFormat::HTML->value,
            ];
        }

        return $files;
    }

    private function primaryFormat(?string $typeName, ?string $fileExtension): ?string
    {
        if ($typeName !== null && isset(self::ZUGFERD_PRIMARY_FORMAT[$typeName])) {
            return self::ZUGFERD_PRIMARY_FORMAT[$typeName]->value;
        }

        return match (strtolower((string) $fileExtension)) {
            'pdf' => DocumentFormat::PDF->value,
            'html' => DocumentFormat::HTML->value,
            'xml' => DocumentFormat::ZUGFERD_XML->value,
            '' => null,
            default => strtolower((string) $fileExtension),
        };
    }
}
