imports:
  - { resource: services.yml }

framework:
  secret: ''
  default_locale: en
  http_method_override: false
  handle_all_throwables: false
  translator:
    fallbacks: [ 'en' ]
    cache_dir: null
    default_path: '%kernel.project_dir%/Resources/translations'
  session:
    name: 'shopware-recovery'
    handler_id: ~
    cookie_secure: auto
    cookie_samesite: strict
  validation:
    enabled: false
    email_validation_mode: html5
  php_errors:
    log: false

twig:
  cache: false
  default_path: '%kernel.project_dir%/Resources/views'
