name: Bug report 🐛
description: Existing feature does not behave as expected.
labels: [Bug]
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report!
    - type: input
      id: php-version
      attributes:
          label: PHP Version
      validations:
          required: true
    - type: input
      id: shopware-version
      attributes:
          label: Shopware Version
      validations:
          required: true
    - type: dropdown
      id: extension
      attributes:
          label: Affected area / extension
          description: In which area or extension of the product does the behavior occur?
          options:
            - Platform(Default)
            - Extension:B2B-Suite
            - Extension:CINEMA-Theme
            - Extension:CMS-Professional
            - Extension:Custom-Products
            - Extension:DHL-App
            - Extension:Dynamic-Access
            - Extension:Elle-Theme
            - Extension:Emporium-Theme
            - Extension:Language-Extensions
            - Extension:Migration-Tool
            - Extension:PayPal-Integration
            - Extension:Publisher
            - Extension:Shape-Theme
            - Extension:Showroom-Theme
            - Extension:Social-Shopping
      validations:
          required: true
    - type: textarea
      id: expected-behaviour
      attributes:
          label: Expected behaviour
          description: What did you expect to happen?
      validations:
          required: true
    - type: textarea
      id: actual-behaviour
      attributes:
          label: Actual behaviour
          description: Please describe the issue
      validations:
          required: true
    - type: textarea
      id: steps-to-reproduce
      attributes:
          label: How to reproduce
          description: Tell us how the bug can be reproduced
      validations:
          required: true
