parameters:
    env(SHOPWARE_USAGE_DATA_GATEWAY_BASE_URI): 'http://localhost:8888'

shopware:
    api:
        api_browser:
            auth_required: false

    media:
        enable_url_upload_feature: true
        enable_url_validation: false

    profiler:
        integrations: ['Symfony']

    usage_data:
        gateway:
            dispatch_enabled: true
            entity_dispatch_enabled: false
            consent_dispatch_enabled: true
