parameters:
    env(PRODUCT_ANALYTICS_GATEWAY_URL): ''

shopware:
    api:
        api_browser:
            auth_required: false
    cache:
        invalidation:
            delay_enabled: false
    media:
        enable_url_upload_feature: true
        enable_url_validation: false

    app_system:
        allow_unencrypted_traffic: true
        allowed_private_ip_addresses:
            - '127.0.0.1'
            - '::1'

    profiler:
        integrations: ['Symfony']

    usage_data:
        collection_enabled: true
        gateway:
            dispatch_enabled: false
            base_uri: 'http://localhost:8888'
