export default {
    id: 'sw-catalogue',
    label: 'global.sw-admin-menu.navigation.mainMenuItemCatalogue',
    color: '#57D9A3',
    icon: 'default-symbol-products',
    position: 20,
    children: [{
        id: 'sw-product',
        label: 'sw-product.general.mainMenuItemGeneral',
        color: '#57D9A3',
        path: 'sw.product.index',
        icon: 'default-symbol-products',
        parent: 'sw-catalogue',
        position: 10,
        children: []
    }, {
        id: 'sw-review',
        label: 'sw-review.general.mainMenuItemList',
        color: '#57D9A3',
        path: 'sw.review.index',
        icon: 'default-symbol-products',
        parent: 'sw-catalogue',
        position: 20,
        children: []
    }, {
        id: 'sw-category',
        path: 'sw.category.index',
        label: 'sw-category.general.mainMenuItemIndex',
        parent: 'sw-catalogue',
        position: 20,
        children: []
    }, {
        path: 'sw.product.stream.index',
        label: 'sw-product-stream.general.mainMenuItemGeneral',
        id: 'sw-product-stream',
        parent: 'sw-catalogue',
        color: '#57D9A3',
        position: 30,
        children: []
    }, {
        id: 'sw-property',
        label: 'sw-property.general.mainMenuItemGeneral',
        parent: 'sw-catalogue',
        path: 'sw.property.index',
        position: 40,
        children: []
    }, {
        path: 'sw.manufacturer.index',
        label: 'sw-manufacturer.general.mainMenuItemList',
        id: 'sw-manufacturer',
        parent: 'sw-catalogue',
        color: '#57D9A3',
        position: 50,
        children: []
    }]
};
