<?php declare(strict_types=1);

namespace Shopware\Tests\Unit\Core\Content\Media\File;

use Shopware\Core\Content\Media\File\SvgContentValidator;
use Shopware\Core\Framework\Log\Package;

/**
 * @internal
 */
#[Package('discovery')]
final class SvgValidatorTestDefaults
{
    public const ALLOWED_ELEMENTS = [
        'a',
        'circle',
        'clippath',
        'defs',
        'desc',
        'ellipse',
        'g',
        'image',
        'line',
        'lineargradient',
        'marker',
        'mask',
        'metadata',
        'path',
        'pattern',
        'polygon',
        'polyline',
        'radialgradient',
        'rect',
        'stop',
        'style',
        'svg',
        'switch',
        'symbol',
        'text',
        'title',
        'tspan',
        'use',
        'view',
    ];

    public const ALLOWED_ATTRIBUTES = [
        'alignment-baseline',
        'aria-describedby',
        'aria-hidden',
        'aria-label',
        'aria-labelledby',
        'aria-roledescription',
        'baseline-shift',
        'class',
        'clip-path',
        'clip-rule',
        'clippathunits',
        'color',
        'color-interpolation',
        'color-interpolation-filters',
        'cursor',
        'cx',
        'cy',
        'd',
        'direction',
        'display',
        'dominant-baseline',
        'dx',
        'dy',
        'fill',
        'fill-opacity',
        'fill-rule',
        'filter',
        'flood-color',
        'flood-opacity',
        'font-family',
        'font-size',
        'font-size-adjust',
        'font-stretch',
        'font-style',
        'font-variant',
        'font-weight',
        'fx',
        'fy',
        'gradienttransform',
        'gradientunits',
        'height',
        'href',
        'id',
        'image-rendering',
        'lang',
        'letter-spacing',
        'lighting-color',
        'marker',
        'marker-end',
        'marker-mid',
        'marker-start',
        'markerheight',
        'markerunits',
        'markerwidth',
        'mask',
        'mask-type',
        'maskcontentunits',
        'maskunits',
        'offset',
        'opacity',
        'orient',
        'overflow',
        'paint-order',
        'patterncontentunits',
        'patterntransform',
        'patternunits',
        'pointer-events',
        'points',
        'preserveaspectratio',
        'r',
        'refx',
        'refy',
        'role',
        'rx',
        'ry',
        'shape-rendering',
        'spreadmethod',
        'stop-color',
        'stop-opacity',
        'stroke',
        'stroke-dasharray',
        'stroke-dashoffset',
        'stroke-linecap',
        'stroke-linejoin',
        'stroke-miterlimit',
        'stroke-opacity',
        'stroke-width',
        'style',
        'text-anchor',
        'text-decoration',
        'text-overflow',
        'text-rendering',
        'transform',
        'transform-origin',
        'type',
        'unicode-bidi',
        'vector-effect',
        'version',
        'viewbox',
        'visibility',
        'white-space',
        'width',
        'word-spacing',
        'writing-mode',
        'x',
        'x1',
        'x2',
        'xlink:href',
        'xml:lang',
        'xml:space',
        'xmlns',
        'xmlns:xlink',
        'y',
        'y1',
        'y2',
    ];

    public const ALLOWED_REFERENCE_ATTRIBUTES = [
        'href',
        'xlink:href',
    ];

    public static function createValidator(): SvgContentValidator
    {
        return new SvgContentValidator(
            self::ALLOWED_ELEMENTS,
            self::ALLOWED_ATTRIBUTES,
            self::ALLOWED_REFERENCE_ATTRIBUTES,
        );
    }
}
