<?php declare(strict_types=1);

namespace Shopware\Administration\Framework\Twig;

use League\Flysystem\FilesystemException;
use League\Flysystem\FilesystemOperator;
use Pentatrion\ViteBundle\Service\FileAccessor;
use Psr\Log\LoggerInterface;
use Shopware\Core\Framework\Bundle as ShopwareBundle;
use Shopware\Core\Framework\Log\Package;
use Shopware\Core\Framework\Plugin\Util\AssetService;
use Symfony\Component\Asset\PackageInterface as AssetPackage;
use Symfony\Contracts\Cache\ItemInterface;
use Symfony\Contracts\Cache\TagAwareCacheInterface;

/**
 * @deprecated tag:v6.8.0 - class will be marked internal - reason:becomes-internal
 */
#[Package('framework')]
class ViteFileAccessorDecorator extends FileAccessor
{
    private const ONE_DAY_CACHING_TIME = 86400;

    private readonly string $assetPath;

    /**
     * @internal
     */
    public function __construct(
        private readonly array $configs,
        private readonly AssetPackage $package,
        private readonly FilesystemOperator $assetFilesystem,
        private readonly TagAwareCacheInterface $cache,
        private readonly LoggerInterface $logger,
    ) {
        $this->assetPath = $this->package->getUrl('');

        parent::__construct($this->assetPath, $configs);
    }

    public function hasFile(string $configName, string $fileType): bool
    {
        return $this->assetFilesystem->fileExists($this->getFileLocation($configName, $fileType));
    }

    /**
     * @return array<string, mixed>
     */
    public function getData(string $configName, string $fileType): array
    {
        return $this->getContent($fileType, $configName);
    }

    /**
     * @return array<string, mixed>
     */
    public function getBundleData(ShopwareBundle $bundle): array
    {
        $configName = $this->getTechnicalBundleName($bundle);
        if ($configName === 'administration') {
            $configName = '_default';
        }

        return $this->getContent(self::ENTRYPOINTS, $configName);
    }

    private function getTechnicalBundleName(ShopwareBundle $bundle): string
    {
        return str_replace('_', '-', $bundle->getContainerPrefix());
    }

    /**
     * @return array<string, mixed>
     */
    private function getContent(string $fileType, string $configName): array
    {
        // Depending on how many script tags are rendered, this method is called multiple times
        // Cache the content to avoid reading the file multiple times
        $cacheKey = \sprintf('%s-%s', $configName, $fileType);

        return $this->cache->get($cacheKey, function (ItemInterface $item) use ($fileType, $configName): array {
            $item->expiresAfter(self::ONE_DAY_CACHING_TIME);
            $item->tag(AssetService::CACHE_TAG);

            $fileLocation = $this->getFileLocation($configName, $fileType);
            try {
                $contentRaw = $this->assetFilesystem->read($fileLocation);
            } catch (FilesystemException $e) {
                $this->logger->notice(\sprintf('Could not read asset. Reason: %s', $e->getMessage()), ['exception' => $e]);

                return [];
            }

            $content = json_decode($contentRaw, true, flags: \JSON_THROW_ON_ERROR);

            // Replace the base generated by Vite with the symfony asset path
            $content['base'] = $this->assetPath;

            // Get all entrypoints for the administration
            foreach ($content['entryPoints'][$configName] ?? [] as $key => $entrypoint) {
                // The entry points also contain configuration, for example "legacy" and a boolean value
                if (!\is_array($entrypoint)) {
                    continue;
                }

                // Prepend the asset path to the every entry point
                foreach ($entrypoint as $index => $entry) {
                    $content['entryPoints'][$configName][$key][$index] = \sprintf('%s%s', $this->assetPath, $entry);
                }
            }

            return $content;
        });
    }

    private function getFileLocation(string $configName, string $fileType): string
    {
        if (!isset(self::FILES[$fileType])) {
            return '';
        }

        if (isset($this->configs[$configName]['base'])) {
            return \sprintf('%s.vite/%s', $this->configs[$configName]['base'], self::FILES[$fileType]);
        }

        return \sprintf('/bundles/%s/administration/.vite/%s', $configName, self::FILES[$fileType]);
    }
}
