/**
 * @sw-package fundamentals@after-sales
 */
import type RuleConditionService from '../service/rule-condition.service';

const { Application } = Shopware;

const RULE_SCOPES = {
    GLOBAL: 'global',
    CHECKOUT: 'checkout',
    CART: 'cart',
    LINE_ITEM: 'lineItem',
    ORDER: 'order',
} as const;

const RULE_GROUPS = {
    GENERAL: 'general',
    CUSTOMER: 'customer',
    ORDER: 'order',
    CART: 'cart',
    ITEM: 'item',
    PROMOTION: 'promotion',
} as const;

const RULE_CONDITION_COMPONENTS = {
    GENERIC: 'sw-condition-generic',
    GENERIC_LINE_ITEM: 'sw-condition-generic-line-item',
    DATE_RANGE: 'sw-condition-date-range',
    TIME_RANGE: 'sw-condition-time-range',
    BILLING_ZIP_CODE: 'sw-condition-billing-zip-code',
    SHIPPING_ZIP_CODE: 'sw-condition-shipping-zip-code',
    GOODS_COUNT: 'sw-condition-goods-count',
    GOODS_PRICE: 'sw-condition-goods-price',
    LINE_ITEM: 'sw-condition-line-item',
    LINE_ITEM_WITH_QUANTITY: 'sw-condition-line-item-with-quantity',
    IS_ALWAYS_VALID: 'sw-condition-is-always-valid',
    LINE_ITEM_PROPERTY: 'sw-condition-line-item-property',
    LINE_ITEM_IN_CATEGORY: 'sw-condition-line-item-in-category',
    LINE_ITEM_CUSTOM_FIELD: 'sw-condition-line-item-custom-field',
    CUSTOMER_CUSTOM_FIELD: 'sw-condition-customer-custom-field',
    LINE_ITEM_GOODS_TOTAL: 'sw-condition-line-item-goods-total',
    ORDER_CUSTOM_FIELD: 'sw-condition-order-custom-field',
} as const;

const RULE_CONDITION_TYPES = {
    DATE_RANGE: 'dateRange',
    TIME_RANGE: 'timeRange',
    NUMBER_OF_REVIEWS: 'numberOfReviews',
    CUSTOMER_ORDER_COUNT: 'customerOrderCount',
    CUSTOMER_DAYS_SINCE_LAST_ORDER: 'customerDaysSinceLastOrder',
    SALES_CHANNEL: 'salesChannel',
    CURRENCY: 'currency',
    LANGUAGE: 'language',
    CART_TAX_DISPLAY: 'cartTaxDisplay',
    CUSTOMER_BILLING_COUNTRY: 'customerBillingCountry',
    CUSTOMER_BILLING_STREET: 'customerBillingStreet',
    CUSTOMER_BILLING_ZIP_CODE: 'customerBillingZipCode',
    CUSTOMER_CUSTOMER_GROUP: 'customerCustomerGroup',
    CUSTOMER_REQUESTED_GROUP: 'customerRequestedGroup',
    CUSTOMER_TAG: 'customerTag',
    CUSTOMER_CUSTOMER_NUMBER: 'customerCustomerNumber',
    CUSTOMER_DIFFERENT_ADDRESSES: 'customerDifferentAddresses',
    CUSTOMER_EMAIL: 'customerEmail',
    CUSTOMER_LAST_NAME: 'customerLastName',
    CUSTOMER_IS_COMPANY: 'customerIsCompany',
    CUSTOMER_IS_GUEST: 'customerIsGuest',
    CUSTOMER_IS_NEWSLETTER_RECIPIENT: 'customerIsNewsletterRecipient',
    CUSTOMER_SHIPPING_COUNTRY: 'customerShippingCountry',
    CUSTOMER_SHIPPING_STREET: 'customerShippingStreet',
    CUSTOMER_SHIPPING_ZIP_CODE: 'customerShippingZipCode',
    CUSTOMER_LOGGED_IN: 'customerLoggedIn',
    CUSTOMER_BILLING_CITY: 'customerBillingCity',
    CUSTOMER_BILLING_STATE: 'customerBillingState',
    CUSTOMER_IS_ACTIVE: 'customerIsActive',
    CUSTOMER_SHIPPING_CITY: 'customerShippingCity',
    CUSTOMER_SHIPPING_STATE: 'customerShippingState',
    CUSTOMER_AGE: 'customerAge',
    CUSTOMER_DAYS_SINCE_LAST_LOGIN: 'customerDaysSinceLastLogin',
    CUSTOMER_DAYS_SINCE_FIRST_LOGIN: 'customerDaysSinceFirstLogin',
    CUSTOMER_AFFILIATE_CODE: 'customerAffiliateCode',
    CUSTOMER_CAMPAIGN_CODE: 'customerCampaignCode',
    ORDER_AFFILIATE_CODE: 'orderAffiliateCode',
    ORDER_CAMPAIGN_CODE: 'orderCampaignCode',
    CART_CART_AMOUNT: 'cartCartAmount',
    CART_POSITION_PRICE: 'cartPositionPrice',
    CART_GOODS_COUNT: 'cartGoodsCount',
    CART_TOTAL_PURCHASE_PRICE: 'cartTotalPurchasePrice',
    CART_GOODS_PRICE: 'cartGoodsPrice',
    CART_LINE_ITEM_OF_TYPE: 'cartLineItemOfType',
    CART_LINE_ITEM: 'cartLineItem',
    CART_LINE_ITEMS_IN_CART_COUNT: 'cartLineItemsInCartCount',
    CART_LINE_ITEM_TOTAL_PRICE: 'cartLineItemTotalPrice',
    CART_LINE_ITEM_UNIT_PRICE: 'cartLineItemUnitPrice',
    CART_LINE_ITEM_PER_ITEM_QUANTITY: 'cartLineItemPerItemQuantity',
    CART_LINE_ITEM_WITH_QUANTITY: 'cartLineItemWithQuantity',
    CART_HAS_DELIVERY_FREE_ITEM: 'cartHasDeliveryFreeItem',
    DAY_OF_WEEK: 'dayOfWeek',
    CART_WEIGHT: 'cartWeight',
    CART_VOLUME: 'cartVolume',
    CART_SHIPPING_COST: 'cartShippingCost',
    CART_LINE_ITEM_TAG: 'cartLineItemTag',
    ALWAYS_VALID: 'alwaysValid',
    CART_LINE_ITEM_PROPERTY: 'cartLineItemProperty',
    CART_LINE_ITEM_IS_NEW: 'cartLineItemIsNew',
    CART_LINE_ITEM_OF_MANUFACTURER: 'cartLineItemOfManufacturer',
    CART_LINE_ITEM_PURCHASE_PRICE: 'cartLineItemPurchasePrice',
    CART_LINE_ITEM_CREATION_DATE: 'cartLineItemCreationDate',
    CART_LINE_ITEM_RELEASE_DATE: 'cartLineItemReleaseDate',
    CART_LINE_ITEM_CLEARANCE_SALE: 'cartLineItemClearanceSale',
    CART_LINE_ITEM_PROMOTED: 'cartLineItemPromoted',
    CART_LINE_ITEM_IN_CATEGORY: 'cartLineItemInCategory',
    CART_LINE_ITEM_IN_PRODUCT_STREAM: 'cartLineItemInProductStream',
    CART_LINE_ITEM_TAXATION: 'cartLineItemTaxation',
    CART_LINE_ITEM_DIMENSION_WIDTH: 'cartLineItemDimensionWidth',
    CART_LINE_ITEM_DIMENSION_HEIGHT: 'cartLineItemDimensionHeight',
    CART_LINE_ITEM_DIMENSION_LENGTH: 'cartLineItemDimensionLength',
    CART_LINE_ITEM_DIMENSION_WEIGHT: 'cartLineItemDimensionWeight',
    CART_LINE_ITEM_DIMENSION_VOLUME: 'cartLineItemDimensionVolume',
    CART_LINE_ITEM_LIST_PRICE: 'cartLineItemListPrice',
    CART_LINE_ITEM_LIST_PRICE_RATIO: 'cartLineItemListPriceRatio',
    CART_LINE_ITEM_CUSTOM_FIELD: 'cartLineItemCustomField',
    CART_LINE_ITEM_STOCK: 'cartLineItemStock',
    CART_LINE_ITEM_ACTUAL_STOCK: 'cartLineItemActualStock',
    CUSTOMER_CUSTOM_FIELD: 'customerCustomField',
    PAYMENT_METHOD: 'paymentMethod',
    SHIPPING_METHOD: 'shippingMethod',
    CART_LINE_ITEM_GOODS_TOTAL: 'cartLineItemGoodsTotal',
    CUSTOMER_ORDER_TOTAL_AMOUNT: 'customerOrderTotalAmount',
    PROMOTION_LINE_ITEM: 'promotionLineItem',
    PROMOTION_CODE_OF_TYPE: 'promotionCodeOfType',
    PROMOTIONS_IN_CART_COUNT: 'promotionsInCartCount',
    PROMOTION_VALUE: 'promotionValue',
    CUSTOMER_BIRTHDAY: 'customerBirthday',
    CUSTOMER_CREATED_BY_ADMIN: 'customerCreatedByAdmin',
    CUSTOMER_SALUTATION: 'customerSalutation',
    CART_LINE_ITEM_PRODUCT_STATES: 'cartLineItemProductStates',
    ORDER_TAG: 'orderTag',
    ORDER_TRACKING_CODE: 'orderTrackingCode',
    ORDER_DELIVERY_STATUS: 'orderDeliveryStatus',
    ADMIN_SALES_CHANNEL_SOURCE: 'adminSalesChannelSource',
    ORDER_TRANSACTION_STATUS: 'orderTransactionStatus',
    ORDER_STATUS: 'orderStatus',
    ORDER_CREATED_BY_ADMIN: 'orderCreatedByAdmin',
    ORDER_CUSTOM_FIELD: 'orderCustomField',
    ORDER_DOCUMENT_TYPE: 'orderDocumentType',
    ORDER_DOCUMENT_TYPE_SENT: 'orderDocumentTypeSent',
    CART_LINE_ITEM_PROPERTY_VALUE: 'cartLineItemPropertyValue',
    CART_LINE_ITEM_VARIANT_VALUE: 'cartLineItemVariantValue',
} as const;

const RULE_CONDITIONS = {
    [RULE_CONDITION_TYPES.DATE_RANGE]: {
        component: RULE_CONDITION_COMPONENTS.DATE_RANGE,
        label: 'global.sw-condition.condition.dateRangeRule.label',
        scopes: [RULE_SCOPES.GLOBAL],
        group: RULE_GROUPS.GENERAL,
    },
    [RULE_CONDITION_TYPES.TIME_RANGE]: {
        component: RULE_CONDITION_COMPONENTS.TIME_RANGE,
        label: 'global.sw-condition.condition.timeRangeRule',
        scopes: [RULE_SCOPES.GLOBAL],
        group: RULE_GROUPS.GENERAL,
    },
    [RULE_CONDITION_TYPES.NUMBER_OF_REVIEWS]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.numberOfReviews',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_ORDER_COUNT]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.orderCountRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_DAYS_SINCE_LAST_ORDER]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.daysSinceLastOrderRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.SALES_CHANNEL]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.salesChannelRule',
        scopes: [RULE_SCOPES.GLOBAL],
        group: RULE_GROUPS.GENERAL,
    },
    [RULE_CONDITION_TYPES.CURRENCY]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.currencyRule',
        scopes: [RULE_SCOPES.GLOBAL],
        group: RULE_GROUPS.GENERAL,
    },
    [RULE_CONDITION_TYPES.LANGUAGE]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.languageRule',
        scopes: [RULE_SCOPES.GLOBAL],
        group: RULE_GROUPS.GENERAL,
    },
    [RULE_CONDITION_TYPES.CART_TAX_DISPLAY]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.cartTaxDisplay.label',
        scopes: [RULE_SCOPES.CART],
        group: RULE_GROUPS.GENERAL,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_BILLING_COUNTRY]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.billingCountryRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_BILLING_STREET]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.billingStreetRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_BILLING_ZIP_CODE]: {
        component: RULE_CONDITION_COMPONENTS.BILLING_ZIP_CODE,
        label: 'global.sw-condition.condition.billingZipCodeRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_CUSTOMER_GROUP]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.customerGroupRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_REQUESTED_GROUP]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.customerRequestedGroupRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_TAG]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.customerTagRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_CUSTOMER_NUMBER]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.customerNumberRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_DIFFERENT_ADDRESSES]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.differentAddressesRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_EMAIL]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.emailRule.label',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_LAST_NAME]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.lastNameRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_IS_COMPANY]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.isCompanyRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_IS_GUEST]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.isGuestRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_IS_NEWSLETTER_RECIPIENT]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.isNewsletterRecipient',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_SHIPPING_COUNTRY]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.shippingCountryRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_SHIPPING_STREET]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.shippingStreetRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_SHIPPING_ZIP_CODE]: {
        component: RULE_CONDITION_COMPONENTS.SHIPPING_ZIP_CODE,
        label: 'global.sw-condition.condition.shippingZipCodeRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_LOGGED_IN]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.customerLoggedInRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_BILLING_CITY]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.billingCityRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_BILLING_STATE]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.billingStateRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_IS_ACTIVE]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.customerIsActiveRule',
        scopes: [RULE_SCOPES.GLOBAL],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_SHIPPING_CITY]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.shippingCityRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_SHIPPING_STATE]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.shippingStateRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_AGE]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.customerAgeRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_DAYS_SINCE_LAST_LOGIN]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.customerDaysSinceLastLogin',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_DAYS_SINCE_FIRST_LOGIN]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.customerDaysSinceFirstLogin',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_AFFILIATE_CODE]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.customerAffiliateCodeRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_CAMPAIGN_CODE]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.customerCampaignCodeRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.ORDER_AFFILIATE_CODE]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.orderAffiliateCodeRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.ORDER,
    },
    [RULE_CONDITION_TYPES.ORDER_CAMPAIGN_CODE]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.orderCampaignCodeRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.ORDER,
    },
    [RULE_CONDITION_TYPES.CART_CART_AMOUNT]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.cartAmountRule',
        scopes: [RULE_SCOPES.CART],
        group: RULE_GROUPS.CART,
    },
    [RULE_CONDITION_TYPES.CART_POSITION_PRICE]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.cartPositionPrice',
        scopes: [RULE_SCOPES.CART],
        group: RULE_GROUPS.CART,
    },
    [RULE_CONDITION_TYPES.CART_GOODS_COUNT]: {
        component: RULE_CONDITION_COMPONENTS.GOODS_COUNT,
        label: 'global.sw-condition.condition.goodsCountRule',
        scopes: [RULE_SCOPES.CART],
        group: RULE_GROUPS.CART,
    },
    [RULE_CONDITION_TYPES.CART_TOTAL_PURCHASE_PRICE]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.cartTotalPurchasePrice',
        scopes: [RULE_SCOPES.CART],
        group: RULE_GROUPS.CART,
    },
    [RULE_CONDITION_TYPES.CART_GOODS_PRICE]: {
        component: RULE_CONDITION_COMPONENTS.GOODS_PRICE,
        label: 'global.sw-condition.condition.goodsPriceRule',
        scopes: [RULE_SCOPES.CART],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_OF_TYPE]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC_LINE_ITEM,
        label: 'global.sw-condition.condition.lineItemOfTypeRule.label',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM]: {
        component: RULE_CONDITION_COMPONENTS.LINE_ITEM,
        label: 'global.sw-condition.condition.lineItemRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEMS_IN_CART_COUNT]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC_LINE_ITEM,
        label: 'global.sw-condition.condition.lineItemsInCartCountRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_TOTAL_PRICE]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC_LINE_ITEM,
        label: 'global.sw-condition.condition.lineItemTotalPriceRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_UNIT_PRICE]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC_LINE_ITEM,
        label: 'global.sw-condition.condition.lineItemUnitPriceRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_PER_ITEM_QUANTITY]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC_LINE_ITEM,
        label: 'global.sw-condition.condition.lineItemPerItemQuantityRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_WITH_QUANTITY]: {
        component: RULE_CONDITION_COMPONENTS.LINE_ITEM_WITH_QUANTITY,
        label: 'global.sw-condition.condition.lineItemWithQuantityRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.CART_HAS_DELIVERY_FREE_ITEM]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC_LINE_ITEM,
        label: 'global.sw-condition.condition.hasDeliveryFreeItemRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.DAY_OF_WEEK]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.dayOfWeekRule',
        scopes: [RULE_SCOPES.GLOBAL],
        group: RULE_GROUPS.GENERAL,
    },
    [RULE_CONDITION_TYPES.CART_WEIGHT]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.weightOfCartRule',
        scopes: [RULE_SCOPES.CART],
        group: RULE_GROUPS.CART,
    },
    [RULE_CONDITION_TYPES.CART_VOLUME]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.volumeOfCartRule',
        scopes: [RULE_SCOPES.CART],
        group: RULE_GROUPS.CART,
    },
    [RULE_CONDITION_TYPES.CART_SHIPPING_COST]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.cartShippingCost',
        scopes: [RULE_SCOPES.CART],
        group: RULE_GROUPS.CART,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_TAG]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC_LINE_ITEM,
        label: 'global.sw-condition.condition.lineItemTagRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.ALWAYS_VALID]: {
        component: RULE_CONDITION_COMPONENTS.IS_ALWAYS_VALID,
        label: 'global.sw-condition.condition.alwaysValidRule',
        scopes: [RULE_SCOPES.GLOBAL],
        group: RULE_GROUPS.GENERAL,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_PROPERTY]: {
        component: RULE_CONDITION_COMPONENTS.LINE_ITEM_PROPERTY,
        label: 'global.sw-condition.condition.lineItemPropertyRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_IS_NEW]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC_LINE_ITEM,
        label: 'global.sw-condition.condition.lineItemIsNewRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_OF_MANUFACTURER]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC_LINE_ITEM,
        label: 'global.sw-condition.condition.lineItemOfManufacturerRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_PURCHASE_PRICE]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC_LINE_ITEM,
        label: 'global.sw-condition.condition.lineItemPurchasePriceRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_CREATION_DATE]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC_LINE_ITEM,
        label: 'global.sw-condition.condition.lineItemCreationDateRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_RELEASE_DATE]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC_LINE_ITEM,
        label: 'global.sw-condition.condition.lineItemReleaseDateRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_CLEARANCE_SALE]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC_LINE_ITEM,
        label: 'global.sw-condition.condition.lineItemClearanceSale',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_PROMOTED]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC_LINE_ITEM,
        label: 'global.sw-condition.condition.lineItemPromotedRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_IN_CATEGORY]: {
        component: RULE_CONDITION_COMPONENTS.LINE_ITEM_IN_CATEGORY,
        label: 'global.sw-condition.condition.lineItemInCategoryRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_IN_PRODUCT_STREAM]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC_LINE_ITEM,
        label: 'global.sw-condition.condition.lineItemInProductStreamRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_TAXATION]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC_LINE_ITEM,
        label: 'global.sw-condition.condition.lineItemTaxationRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_DIMENSION_WIDTH]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC_LINE_ITEM,
        label: 'global.sw-condition.condition.lineItemDimensionWidthRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_DIMENSION_HEIGHT]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC_LINE_ITEM,
        label: 'global.sw-condition.condition.lineItemDimensionHeightRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_DIMENSION_LENGTH]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC_LINE_ITEM,
        label: 'global.sw-condition.condition.lineItemDimensionLengthRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_DIMENSION_WEIGHT]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC_LINE_ITEM,
        label: 'global.sw-condition.condition.lineItemDimensionWeightRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_DIMENSION_VOLUME]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC_LINE_ITEM,
        label: 'global.sw-condition.condition.lineItemDimensionVolumeRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_LIST_PRICE]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC_LINE_ITEM,
        label: 'global.sw-condition.condition.lineItemListPriceRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_LIST_PRICE_RATIO]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC_LINE_ITEM,
        label: 'global.sw-condition.condition.lineItemListPriceRatioRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_CUSTOM_FIELD]: {
        component: RULE_CONDITION_COMPONENTS.LINE_ITEM_CUSTOM_FIELD,
        label: 'global.sw-condition.condition.lineItemCustomFieldRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_STOCK]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC_LINE_ITEM,
        label: 'global.sw-condition.condition.lineItemStockRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_ACTUAL_STOCK]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC_LINE_ITEM,
        label: 'global.sw-condition.condition.lineItemActualStockRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_CUSTOM_FIELD]: {
        component: RULE_CONDITION_COMPONENTS.CUSTOMER_CUSTOM_FIELD,
        label: 'global.sw-condition.condition.customerCustomFieldRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.PAYMENT_METHOD]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.paymentMethodRule',
        scopes: [RULE_SCOPES.CART],
        group: RULE_GROUPS.CART,
    },
    [RULE_CONDITION_TYPES.SHIPPING_METHOD]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.shippingMethodRule',
        scopes: [RULE_SCOPES.CART],
        group: RULE_GROUPS.CART,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_GOODS_TOTAL]: {
        component: RULE_CONDITION_COMPONENTS.LINE_ITEM_GOODS_TOTAL,
        label: 'global.sw-condition.condition.lineItemGoodsTotalRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.CART,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_ORDER_TOTAL_AMOUNT]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.orderTotalAmountRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.PROMOTION_LINE_ITEM]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC_LINE_ITEM,
        label: 'global.sw-condition.condition.promotionLineItemRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.PROMOTION,
    },
    [RULE_CONDITION_TYPES.PROMOTION_CODE_OF_TYPE]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.promotionCodeOfType',
        scopes: [RULE_SCOPES.CART],
        group: RULE_GROUPS.PROMOTION,
    },
    [RULE_CONDITION_TYPES.PROMOTIONS_IN_CART_COUNT]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.promotionsInCartCountRule',
        scopes: [RULE_SCOPES.CART],
        group: RULE_GROUPS.PROMOTION,
    },
    [RULE_CONDITION_TYPES.PROMOTION_VALUE]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.promotionValueRule',
        scopes: [RULE_SCOPES.CART],
        group: RULE_GROUPS.PROMOTION,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_BIRTHDAY]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.customerBirthdayRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_CREATED_BY_ADMIN]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.customerCreatedByAdminRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CUSTOMER_SALUTATION]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.customerSalutationRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.CUSTOMER,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_PRODUCT_STATES]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC_LINE_ITEM,
        label: 'global.sw-condition.condition.lineItemProductStates',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.ORDER_TAG]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.orderTagRule',
        scopes: [RULE_SCOPES.ORDER],
        group: RULE_GROUPS.ORDER,
    },
    [RULE_CONDITION_TYPES.ORDER_TRACKING_CODE]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.orderTrackingCodeRule',
        scopes: [RULE_SCOPES.ORDER],
        group: RULE_GROUPS.ORDER,
    },
    [RULE_CONDITION_TYPES.ORDER_DELIVERY_STATUS]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.orderDeliveryStatusRule',
        scopes: [RULE_SCOPES.ORDER],
        group: RULE_GROUPS.ORDER,
    },
    [RULE_CONDITION_TYPES.ADMIN_SALES_CHANNEL_SOURCE]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.adminSalesChannelSourceRule',
        scopes: [RULE_SCOPES.CHECKOUT],
        group: RULE_GROUPS.ORDER,
    },
    [RULE_CONDITION_TYPES.ORDER_TRANSACTION_STATUS]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.orderTransactionStatusRule',
        scopes: [RULE_SCOPES.ORDER],
        group: RULE_GROUPS.ORDER,
    },
    [RULE_CONDITION_TYPES.ORDER_STATUS]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.orderStatusRule',
        scopes: [RULE_SCOPES.ORDER],
        group: RULE_GROUPS.ORDER,
    },
    [RULE_CONDITION_TYPES.ORDER_CREATED_BY_ADMIN]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.orderCreatedByAdminRule',
        scopes: [RULE_SCOPES.ORDER],
        group: RULE_GROUPS.ORDER,
    },
    [RULE_CONDITION_TYPES.ORDER_CUSTOM_FIELD]: {
        component: RULE_CONDITION_COMPONENTS.ORDER_CUSTOM_FIELD,
        label: 'global.sw-condition.condition.orderCustomFieldRule',
        scopes: [RULE_SCOPES.ORDER],
        group: RULE_GROUPS.ORDER,
    },
    [RULE_CONDITION_TYPES.ORDER_DOCUMENT_TYPE]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.orderDocumentTypeRule',
        scopes: [RULE_SCOPES.ORDER],
        group: RULE_GROUPS.ORDER,
    },
    [RULE_CONDITION_TYPES.ORDER_DOCUMENT_TYPE_SENT]: {
        component: RULE_CONDITION_COMPONENTS.GENERIC,
        label: 'global.sw-condition.condition.orderDocumentTypeSentRule',
        scopes: [RULE_SCOPES.ORDER],
        group: RULE_GROUPS.ORDER,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_PROPERTY_VALUE]: {
        component: RULE_CONDITION_COMPONENTS.LINE_ITEM_PROPERTY,
        label: 'global.sw-condition.condition.lineItemPropertyValueRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
    [RULE_CONDITION_TYPES.CART_LINE_ITEM_VARIANT_VALUE]: {
        component: RULE_CONDITION_COMPONENTS.LINE_ITEM_PROPERTY,
        label: 'global.sw-condition.condition.lineItemVariantValueRule',
        scopes: [RULE_SCOPES.LINE_ITEM],
        group: RULE_GROUPS.ITEM,
    },
} as const;

Application.addServiceProviderDecorator('ruleConditionDataProviderService', (ruleConditionService: RuleConditionService) => {
    Object.entries(RULE_CONDITIONS).forEach(
        ([
            type,
            condition,
        ]) => {
            ruleConditionService.addCondition(type, {
                ...condition,
                scopes: [
                    ...condition.scopes,
                ],
            });
        },
    );

    ruleConditionService.addAwarenessConfiguration('personaPromotions', {
        notEquals: [
            'cartCartAmount',
            'cartShippingCost',
        ],
        equalsAny: [
            ...ruleConditionService.getRestrictionsByGroup('customer'),
            'alwaysValid',
        ],
        snippet: 'sw-restricted-rules.restrictedAssignment.personaPromotions',
    });

    ruleConditionService.addAwarenessConfiguration('orderPromotions', {
        notEquals: [
            'cartCartAmount',
            'cartShippingCost',
            ...ruleConditionService.getRestrictionsByGroup('order'),
        ],
        snippet: 'sw-restricted-rules.restrictedAssignment.orderPromotions',
    });

    ruleConditionService.addAwarenessConfiguration('cartPromotions', {
        notEquals: [
            'cartCartAmount',
            'cartShippingCost',
            ...ruleConditionService.getRestrictionsByGroup('order'),
        ],
        snippet: 'sw-restricted-rules.restrictedAssignment.cartPromotions',
    });

    ruleConditionService.addAwarenessConfiguration('promotionSetGroups', {
        notEquals: [
            'cartCartAmount',
            'cartShippingCost',
        ],
        snippet: 'sw-restricted-rules.restrictedAssignment.promotionSetGroups',
    });

    ruleConditionService.addAwarenessConfiguration('promotionDiscounts', {
        notEquals: [
            'cartCartAmount',
            'cartShippingCost',
        ],
        snippet: 'sw-restricted-rules.restrictedAssignment.promotionDiscounts',
    });

    ruleConditionService.addAwarenessConfiguration('shippingMethodPriceCalculations', {
        notEquals: [
            'cartCartAmount',
            'cartShippingCost',
        ],
        snippet: 'sw-restricted-rules.restrictedAssignment.shippingMethodPriceCalculations',
    });

    ruleConditionService.addAwarenessConfiguration('shippingMethodPrices', {
        notEquals: [
            'cartCartAmount',
            'cartShippingCost',
        ],
        snippet: 'sw-restricted-rules.restrictedAssignment.shippingMethodPrices',
    });

    return ruleConditionService;
});

/**
 * @private
 */
export { RULE_SCOPES, RULE_GROUPS, RULE_CONDITION_COMPONENTS, RULE_CONDITION_TYPES, RULE_CONDITIONS };
