services:
  web:
    ports: !override []
    environment:
      APP_ENV: prod
      APP_URL: http://web:8000
      MAILER_DSN: smtp://mailer:1025
      APP_SECRET: "def00000bb5acb32b54ff8ee130270586eec0e878f7337dc7a837acc31d3ff00f93a56b595448b4b29664847dd51991b3314ff65aeeeb761a133b0ec0e070433bff08e48"
  database:
    ports: !override []
  adminer:
    ports: !override []
  mailer:
    ports: !override []
