<?php declare(strict_types=1);

namespace Shopware\Core\Content\ProductExport\Command;

use Psr\Log\LoggerInterface;
use Shopware\Core\Content\ProductExport\ProductExportCollection;
use Shopware\Core\Content\ProductExport\ProductExportException;
use Shopware\Core\Content\ProductExport\Service\ProductExporterInterface;
use Shopware\Core\Content\ProductExport\Struct\ExportBehavior;
use Shopware\Core\Defaults;
use Shopware\Core\Framework\DataAbstractionLayer\EntityRepository;
use Shopware\Core\Framework\DataAbstractionLayer\Search\Criteria;
use Shopware\Core\Framework\DataAbstractionLayer\Search\Filter\EqualsFilter;
use Shopware\Core\Framework\Log\Package;
use Shopware\Core\Framework\Uuid\Uuid;
use Shopware\Core\System\SalesChannel\Context\AbstractSalesChannelContextFactory;
use Shopware\Core\System\SalesChannel\SalesChannelContext;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

#[Package('inventory')]
#[AsCommand(
    name: 'product-export:generate',
    description: 'Generates a product export file',
)]
class ProductExportGenerateCommand extends Command
{
    /**
     * @internal
     *
     * @param EntityRepository<ProductExportCollection> $productExportRepository
     */
    public function __construct(
        private readonly AbstractSalesChannelContextFactory $salesChannelContextFactory,
        private readonly ProductExporterInterface $productExportService,
        private readonly EntityRepository $productExportRepository,
        private readonly LoggerInterface $logger
    ) {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this
            ->addOption('force', 'f', InputOption::VALUE_NONE, 'Ignore cache and force generation')
            ->addOption('include-inactive', 'i', InputOption::VALUE_NONE, 'Include inactive exports')
            ->addArgument('sales-channel-id', InputArgument::REQUIRED, 'Sales channel ID of the corresponding Storefront sales channel to generate exports for')
            ->addArgument('product-export-id', InputArgument::OPTIONAL, 'Generate specific export ID');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);

        $productExportId = $input->getArgument('product-export-id');
        $salesChannelId = $input->getArgument('sales-channel-id');
        $forceGeneration = $input->getOption('force');
        $includeInactive = $input->getOption('include-inactive');

        $salesChannelContext = $this->salesChannelContextFactory->create(Uuid::randomHex(), $salesChannelId);

        if ($salesChannelContext->getSalesChannel()->getTypeId() !== Defaults::SALES_CHANNEL_TYPE_STOREFRONT) {
            throw ProductExportException::salesChannelNotAllowed();
        }

        if (!$forceGeneration) {
            $this->warnAboutSchedulerManagedExports($io, $salesChannelContext, $includeInactive, $productExportId);
        }

        $this->productExportService->export(
            $salesChannelContext,
            new ExportBehavior($forceGeneration, $includeInactive),
            $productExportId
        );

        return self::SUCCESS;
    }

    /**
     * Exports that are generated by the scheduler are skipped by the export service unless generation
     * is forced. Warn the operator about each of them so a "no output" run cannot be mistaken for an
     * error and continue generating the remaining exports. The scheduled task itself does not use this
     * command, so it keeps generating those exports as configured.
     */
    private function warnAboutSchedulerManagedExports(
        SymfonyStyle $io,
        SalesChannelContext $salesChannelContext,
        bool $includeInactive,
        ?string $productExportId
    ): void {
        $criteria = new Criteria();
        if ($productExportId !== null) {
            $criteria = new Criteria(array_filter([$productExportId]));
        }

        $criteria
            ->addAssociation('salesChannel')
            ->addFilter(new EqualsFilter('storefrontSalesChannelId', $salesChannelContext->getSalesChannelId()))
            ->addFilter(new EqualsFilter('generateByCronjob', true));

        if (!$includeInactive) {
            $criteria->addFilter(new EqualsFilter('salesChannel.active', true));
        }

        $schedulerManagedExports = $this->productExportRepository
            ->search($criteria, $salesChannelContext->getContext())
            ->getEntities();

        foreach ($schedulerManagedExports as $schedulerManagedExport) {
            $exception = ProductExportException::generatedByScheduler(
                $schedulerManagedExport->getId(),
                $schedulerManagedExport->getFileName()
            );

            $io->warning($exception->getMessage());
            $this->logger->warning($exception->getMessage(), ['exception' => $exception]);
        }
    }
}
