@startuml
' uncomment the line below if you're using computer with a retina display
' skinparam dpi 300
!define Table(name,desc) class name as "desc" << (T,#FFAAAA) >>
!define ForeignTable(name,desc) class name as "desc" << (T,#ada6a6) >>
!define TranslationTable(name,desc) class name as "desc" << (I,#4286f4) >>
' we use bold for primary key
' green color for unique
' and underscore for not_null
!define primary_key(x) <b>x</b>
!define unique(x) <color:green>x</color>
!define not_null(x) <u>x</u>
' other tags available:
' <i></i>
' <back:COLOR></color>, where color is a color name or html color code
' (#FFAACC)
' see: http://plantuml.com/classes.html#More
hide methods
hide stereotypes
hide empty members
skinparam backgroundColor #FFFFFF

' entities

Table(ShopwareCoreFrameworkLanguageLanguageDefinition, "language\n(Language)") {
   primary_key(id) id
   parentId parentFk
   not_null(localeId) foreignKey
   translationCodeId foreignKey
   not_null(name) string
   customFields customFields
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
ForeignTable(ShopwareCoreSystemLocaleLocaleDefinition, "locale") {
}
ForeignTable(ShopwareCoreSystemSalesChannelAggregateSalesChannelLanguageSalesChannelLanguageDefinition, "sales_channel_language") {
}
ForeignTable(ShopwareCoreSystemSalesChannelSalesChannelDefinition, "sales_channel") {
}
ForeignTable(ShopwareCoreSystemSalesChannelAggregateSalesChannelDomainSalesChannelDomainDefinition, "sales_channel_domain") {
}
ForeignTable(ShopwareCoreCheckoutCustomerCustomerDefinition, "customer") {
}
ForeignTable(ShopwareCoreContentNewsletterAggregateNewsletterRecipientNewsletterRecipientDefinition, "newsletter_recipient") {
}
ForeignTable(ShopwareCoreCheckoutOrderOrderDefinition, "order") {
}
ForeignTable(ShopwareCoreContentCategoryAggregateCategoryTranslationCategoryTranslationDefinition, "category_translation") {
}
ForeignTable(ShopwareCoreSystemCountryAggregateCountryStateTranslationCountryStateTranslationDefinition, "country_state_translation") {
}
ForeignTable(ShopwareCoreSystemCountryAggregateCountryTranslationCountryTranslationDefinition, "country_translation") {
}
ForeignTable(ShopwareCoreSystemCurrencyAggregateCurrencyTranslationCurrencyTranslationDefinition, "currency_translation") {
}
ForeignTable(ShopwareCoreCheckoutCustomerAggregateCustomerGroupTranslationCustomerGroupTranslationDefinition, "customer_group_translation") {
}
ForeignTable(ShopwareCoreSystemLocaleAggregateLocaleTranslationLocaleTranslationDefinition, "locale_translation") {
}
ForeignTable(ShopwareCoreContentMediaAggregateMediaTranslationMediaTranslationDefinition, "media_translation") {
}
ForeignTable(ShopwareCoreCheckoutPaymentAggregatePaymentMethodTranslationPaymentMethodTranslationDefinition, "payment_method_translation") {
}
ForeignTable(ShopwareCoreContentProductAggregateProductManufacturerTranslationProductManufacturerTranslationDefinition, "product_manufacturer_translation") {
}
ForeignTable(ShopwareCoreContentProductAggregateProductTranslationProductTranslationDefinition, "product_translation") {
}
ForeignTable(ShopwareCoreCheckoutShippingAggregateShippingMethodTranslationShippingMethodTranslationDefinition, "shipping_method_translation") {
}
ForeignTable(ShopwareCoreSystemUnitAggregateUnitTranslationUnitTranslationDefinition, "unit_translation") {
}
ForeignTable(ShopwareCoreContentPropertyAggregatePropertyGroupTranslationPropertyGroupTranslationDefinition, "property_group_translation") {
}
ForeignTable(ShopwareCoreContentPropertyAggregatePropertyGroupOptionTranslationPropertyGroupOptionTranslationDefinition, "property_group_option_translation") {
}
ForeignTable(ShopwareCoreSystemSalesChannelAggregateSalesChannelTranslationSalesChannelTranslationDefinition, "sales_channel_translation") {
}
ForeignTable(ShopwareCoreSystemSalesChannelAggregateSalesChannelTypeTranslationSalesChannelTypeTranslationDefinition, "sales_channel_type_translation") {
}
ForeignTable(ShopwareCoreSystemSalutationAggregateSalutationTranslationSalutationTranslationDefinition, "salutation_translation") {
}
ForeignTable(ShopwareCoreFrameworkPluginAggregatePluginTranslationPluginTranslationDefinition, "plugin_translation") {
}
ForeignTable(ShopwareCoreContentProductStreamAggregateProductStreamTranslationProductStreamTranslationDefinition, "product_stream_translation") {
}
ForeignTable(ShopwareCoreSystemStateMachineStateMachineTranslationDefinition, "state_machine_translation") {
}
ForeignTable(ShopwareCoreSystemStateMachineAggregationStateMachineStateStateMachineStateTranslationDefinition, "state_machine_state_translation") {
}
ForeignTable(ShopwareCoreContentCmsAggregateCmsPageTranslationCmsPageTranslationDefinition, "cms_page_translation") {
}
ForeignTable(ShopwareCoreContentCmsAggregateCmsSlotTranslationCmsSlotTranslationDefinition, "cms_slot_translation") {
}
ForeignTable(ShopwareCoreContentMailTemplateAggregateMailTemplateTranslationMailTemplateTranslationDefinition, "mail_template_translation") {
}
ForeignTable(ShopwareCoreContentMailTemplateAggregateMailHeaderFooterTranslationMailHeaderFooterTranslationDefinition, "mail_header_footer_translation") {
}
ForeignTable(ShopwareCoreCheckoutDocumentAggregateDocumentTypeTranslationDocumentTypeTranslationDefinition, "document_type_translation") {
}
ForeignTable(ShopwareCoreSystemNumberRangeAggregateNumberRangeTypeTranslationNumberRangeTypeTranslationDefinition, "number_range_type_translation") {
}
ForeignTable(ShopwareCoreContentDeliveryTimeAggregateDeliveryTimeTranslationDeliveryTimeTranslationDefinition, "delivery_time_translation") {
}
ForeignTable(ShopwareCoreContentProductAggregateProductSearchKeywordProductSearchKeywordDefinition, "product_search_keyword") {
}
ForeignTable(ShopwareCoreContentProductAggregateProductKeywordDictionaryProductKeywordDictionaryDefinition, "product_keyword_dictionary") {
}
ForeignTable(ShopwareCoreContentMailTemplateAggregateMailTemplateTypeTranslationMailTemplateTypeTranslationDefinition, "mail_template_type_translation") {
}
ForeignTable(ShopwareCoreCheckoutPromotionAggregatePromotionTranslationPromotionTranslationDefinition, "promotion_translation") {
}
ForeignTable(ShopwareCoreSystemNumberRangeAggregateNumberRangeTranslationNumberRangeTranslationDefinition, "number_range_translation") {
}
ForeignTable(ShopwareCoreContentProductAggregateProductReviewProductReviewDefinition, "product_review") {
}
ForeignTable(ShopwareCoreFrameworkSeoSeoUrlSeoUrlDefinition, "seo_url") {
}
ForeignTable(ShopwareStorefrontThemeAggregateThemeTranslationDefinition, "theme_translation") {
}

' relationshipd

ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreSystemLocaleLocaleDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreSystemSalesChannelAggregateSalesChannelLanguageSalesChannelLanguageDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreSystemSalesChannelSalesChannelDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreSystemSalesChannelAggregateSalesChannelDomainSalesChannelDomainDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreCheckoutCustomerCustomerDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreContentNewsletterAggregateNewsletterRecipientNewsletterRecipientDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreCheckoutOrderOrderDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreContentCategoryAggregateCategoryTranslationCategoryTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreSystemCountryAggregateCountryStateTranslationCountryStateTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreSystemCountryAggregateCountryTranslationCountryTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreSystemCurrencyAggregateCurrencyTranslationCurrencyTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreCheckoutCustomerAggregateCustomerGroupTranslationCustomerGroupTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreSystemLocaleAggregateLocaleTranslationLocaleTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreContentMediaAggregateMediaTranslationMediaTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreCheckoutPaymentAggregatePaymentMethodTranslationPaymentMethodTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreContentProductAggregateProductManufacturerTranslationProductManufacturerTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreContentProductAggregateProductTranslationProductTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreCheckoutShippingAggregateShippingMethodTranslationShippingMethodTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreSystemUnitAggregateUnitTranslationUnitTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreContentPropertyAggregatePropertyGroupTranslationPropertyGroupTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreContentPropertyAggregatePropertyGroupOptionTranslationPropertyGroupOptionTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreSystemSalesChannelAggregateSalesChannelTranslationSalesChannelTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreSystemSalesChannelAggregateSalesChannelTypeTranslationSalesChannelTypeTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreSystemSalutationAggregateSalutationTranslationSalutationTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreFrameworkPluginAggregatePluginTranslationPluginTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreContentProductStreamAggregateProductStreamTranslationProductStreamTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreSystemStateMachineStateMachineTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreSystemStateMachineAggregationStateMachineStateStateMachineStateTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreContentCmsAggregateCmsPageTranslationCmsPageTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreContentCmsAggregateCmsSlotTranslationCmsSlotTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreContentMailTemplateAggregateMailTemplateTranslationMailTemplateTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreContentMailTemplateAggregateMailHeaderFooterTranslationMailHeaderFooterTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreCheckoutDocumentAggregateDocumentTypeTranslationDocumentTypeTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreSystemNumberRangeAggregateNumberRangeTypeTranslationNumberRangeTypeTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreContentDeliveryTimeAggregateDeliveryTimeTranslationDeliveryTimeTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreContentProductAggregateProductSearchKeywordProductSearchKeywordDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreContentProductAggregateProductKeywordDictionaryProductKeywordDictionaryDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreContentMailTemplateAggregateMailTemplateTypeTranslationMailTemplateTypeTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreCheckoutPromotionAggregatePromotionTranslationPromotionTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreSystemNumberRangeAggregateNumberRangeTranslationNumberRangeTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreContentProductAggregateProductReviewProductReviewDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreFrameworkSeoSeoUrlSeoUrlDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareStorefrontThemeAggregateThemeTranslationDefinition
@enduml
