@startuml
' uncomment the line below if you're using computer with a retina display
' skinparam dpi 300
!define Table(name,desc) class name as "desc" << (T,#FFAAAA) >>
!define ForeignTable(name,desc) class name as "desc" << (T,#ada6a6) >>
!define TranslationTable(name,desc) class name as "desc" << (I,#4286f4) >>
' we use bold for primary key
' green color for unique
' and underscore for not_null
!define primary_key(x) <b>x</b>
!define unique(x) <color:green>x</color>
!define not_null(x) <u>x</u>
' other tags available:
' <i></i>
' <back:COLOR></color>, where color is a color name or html color code
' (#FFAACC)
' see: http://plantuml.com/classes.html#More
hide methods
hide stereotypes
hide empty members
skinparam backgroundColor #FFFFFF

' entities

Table(ShopwareCoreSystemLanguageLanguageDefinition, "language\n(Language)") {
   primary_key(id) id
   parentId parentFk
   not_null(localeId) foreignKey
   translationCodeId foreignKey
   not_null(name) string
   customFields customFields
   not_null(createdAt) createdAt
   updatedAt updatedAt
}
ForeignTable(ShopwareCoreSystemLocaleLocaleDefinition, "locale") {
}
ForeignTable(ShopwareCoreSystemSalesChannelAggregateSalesChannelLanguageSalesChannelLanguageDefinition, "sales_channel_language") {
}
ForeignTable(ShopwareCoreSystemSalesChannelSalesChannelDefinition, "sales_channel") {
}
ForeignTable(ShopwareCoreSystemSalesChannelAggregateSalesChannelDomainSalesChannelDomainDefinition, "sales_channel_domain") {
}
ForeignTable(ShopwareCoreCheckoutCustomerCustomerDefinition, "customer") {
}
ForeignTable(ShopwareCoreContentNewsletterAggregateNewsletterRecipientNewsletterRecipientDefinition, "newsletter_recipient") {
}
ForeignTable(ShopwareCoreCheckoutOrderOrderDefinition, "order") {
}
ForeignTable(ShopwareCoreContentCategoryAggregateCategoryTranslationCategoryTranslationDefinition, "category_translation") {
}
ForeignTable(ShopwareCoreSystemCountryAggregateCountryStateTranslationCountryStateTranslationDefinition, "country_state_translation") {
}
ForeignTable(ShopwareCoreSystemCountryAggregateCountryTranslationCountryTranslationDefinition, "country_translation") {
}
ForeignTable(ShopwareCoreSystemCurrencyAggregateCurrencyTranslationCurrencyTranslationDefinition, "currency_translation") {
}
ForeignTable(ShopwareCoreCheckoutCustomerAggregateCustomerGroupTranslationCustomerGroupTranslationDefinition, "customer_group_translation") {
}
ForeignTable(ShopwareCoreSystemLocaleAggregateLocaleTranslationLocaleTranslationDefinition, "locale_translation") {
}
ForeignTable(ShopwareCoreContentMediaAggregateMediaTranslationMediaTranslationDefinition, "media_translation") {
}
ForeignTable(ShopwareCoreCheckoutPaymentAggregatePaymentMethodTranslationPaymentMethodTranslationDefinition, "payment_method_translation") {
}
ForeignTable(ShopwareCoreContentProductAggregateProductManufacturerTranslationProductManufacturerTranslationDefinition, "product_manufacturer_translation") {
}
ForeignTable(ShopwareCoreContentProductAggregateProductTranslationProductTranslationDefinition, "product_translation") {
}
ForeignTable(ShopwareCoreCheckoutShippingAggregateShippingMethodTranslationShippingMethodTranslationDefinition, "shipping_method_translation") {
}
ForeignTable(ShopwareCoreSystemUnitAggregateUnitTranslationUnitTranslationDefinition, "unit_translation") {
}
ForeignTable(ShopwareCoreContentPropertyAggregatePropertyGroupTranslationPropertyGroupTranslationDefinition, "property_group_translation") {
}
ForeignTable(ShopwareCoreContentPropertyAggregatePropertyGroupOptionTranslationPropertyGroupOptionTranslationDefinition, "property_group_option_translation") {
}
ForeignTable(ShopwareCoreSystemSalesChannelAggregateSalesChannelTranslationSalesChannelTranslationDefinition, "sales_channel_translation") {
}
ForeignTable(ShopwareCoreSystemSalesChannelAggregateSalesChannelTypeTranslationSalesChannelTypeTranslationDefinition, "sales_channel_type_translation") {
}
ForeignTable(ShopwareCoreSystemSalutationAggregateSalutationTranslationSalutationTranslationDefinition, "salutation_translation") {
}
ForeignTable(ShopwareCoreFrameworkPluginAggregatePluginTranslationPluginTranslationDefinition, "plugin_translation") {
}
ForeignTable(ShopwareCoreContentProductStreamAggregateProductStreamTranslationProductStreamTranslationDefinition, "product_stream_translation") {
}
ForeignTable(ShopwareCoreSystemStateMachineStateMachineTranslationDefinition, "state_machine_translation") {
}
ForeignTable(ShopwareCoreSystemStateMachineAggregationStateMachineStateStateMachineStateTranslationDefinition, "state_machine_state_translation") {
}
ForeignTable(ShopwareCoreContentCmsAggregateCmsPageTranslationCmsPageTranslationDefinition, "cms_page_translation") {
}
ForeignTable(ShopwareCoreContentCmsAggregateCmsSlotTranslationCmsSlotTranslationDefinition, "cms_slot_translation") {
}
ForeignTable(ShopwareCoreContentMailTemplateAggregateMailTemplateTranslationMailTemplateTranslationDefinition, "mail_template_translation") {
}
ForeignTable(ShopwareCoreContentMailTemplateAggregateMailHeaderFooterTranslationMailHeaderFooterTranslationDefinition, "mail_header_footer_translation") {
}
ForeignTable(ShopwareCoreCheckoutDocumentAggregateDocumentTypeTranslationDocumentTypeTranslationDefinition, "document_type_translation") {
}
ForeignTable(ShopwareCoreSystemNumberRangeAggregateNumberRangeTypeTranslationNumberRangeTypeTranslationDefinition, "number_range_type_translation") {
}
ForeignTable(ShopwareCoreSystemDeliveryTimeAggregateDeliveryTimeTranslationDeliveryTimeTranslationDefinition, "delivery_time_translation") {
}
ForeignTable(ShopwareCoreContentProductAggregateProductSearchKeywordProductSearchKeywordDefinition, "product_search_keyword") {
}
ForeignTable(ShopwareCoreContentProductAggregateProductKeywordDictionaryProductKeywordDictionaryDefinition, "product_keyword_dictionary") {
}
ForeignTable(ShopwareCoreContentMailTemplateAggregateMailTemplateTypeTranslationMailTemplateTypeTranslationDefinition, "mail_template_type_translation") {
}
ForeignTable(ShopwareCoreCheckoutPromotionAggregatePromotionTranslationPromotionTranslationDefinition, "promotion_translation") {
}
ForeignTable(ShopwareCoreSystemNumberRangeAggregateNumberRangeTranslationNumberRangeTranslationDefinition, "number_range_translation") {
}
ForeignTable(ShopwareCoreContentProductAggregateProductReviewProductReviewDefinition, "product_review") {
}
ForeignTable(ShopwareCoreContentSeoSeoUrlSeoUrlDefinition, "seo_url") {
}
ForeignTable(ShopwareCoreSystemTaxAggregateTaxRuleTypeTranslationTaxRuleTypeTranslationDefinition, "tax_rule_type_translation") {
}
ForeignTable(ShopwareCoreContentProductAggregateProductCrossSellingTranslationProductCrossSellingTranslationDefinition, "product_cross_selling_translation") {
}
ForeignTable(ShopwareCoreContentImportExportImportExportProfileTranslationDefinition, "import_export_profile_translation") {
}
ForeignTable(ShopwareCoreContentProductSalesChannelSortingProductSortingTranslationDefinition, "product_sorting_translation") {
}
ForeignTable(ShopwareCoreContentProductAggregateProductFeatureSetTranslationProductFeatureSetTranslationDefinition, "product_feature_set_translation") {
}
ForeignTable(ShopwareCoreFrameworkAppAggregateAppTranslationAppTranslationDefinition, "app_translation") {
}
ForeignTable(ShopwareCoreFrameworkAppAggregateActionButtonTranslationActionButtonTranslationDefinition, "app_action_button_translation") {
}
ForeignTable(ShopwareCoreContentLandingPageAggregateLandingPageTranslationLandingPageTranslationDefinition, "landing_page_translation") {
}
ForeignTable(ShopwareCoreContentProductAggregateProductSearchConfigProductSearchConfigDefinition, "product_search_config") {
}
ForeignTable(ShopwareStorefrontThemeAggregateThemeTranslationDefinition, "theme_translation") {
}

' relationshipd

ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreSystemLanguageLanguageDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreSystemLocaleLocaleDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreSystemSalesChannelAggregateSalesChannelLanguageSalesChannelLanguageDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreSystemSalesChannelSalesChannelDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreSystemSalesChannelAggregateSalesChannelDomainSalesChannelDomainDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreCheckoutCustomerCustomerDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreContentNewsletterAggregateNewsletterRecipientNewsletterRecipientDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreCheckoutOrderOrderDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreContentCategoryAggregateCategoryTranslationCategoryTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreSystemCountryAggregateCountryStateTranslationCountryStateTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreSystemCountryAggregateCountryTranslationCountryTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreSystemCurrencyAggregateCurrencyTranslationCurrencyTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreCheckoutCustomerAggregateCustomerGroupTranslationCustomerGroupTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreSystemLocaleAggregateLocaleTranslationLocaleTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreContentMediaAggregateMediaTranslationMediaTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreCheckoutPaymentAggregatePaymentMethodTranslationPaymentMethodTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreContentProductAggregateProductManufacturerTranslationProductManufacturerTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreContentProductAggregateProductTranslationProductTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreCheckoutShippingAggregateShippingMethodTranslationShippingMethodTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreSystemUnitAggregateUnitTranslationUnitTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreContentPropertyAggregatePropertyGroupTranslationPropertyGroupTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreContentPropertyAggregatePropertyGroupOptionTranslationPropertyGroupOptionTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreSystemSalesChannelAggregateSalesChannelTranslationSalesChannelTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreSystemSalesChannelAggregateSalesChannelTypeTranslationSalesChannelTypeTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreSystemSalutationAggregateSalutationTranslationSalutationTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreFrameworkPluginAggregatePluginTranslationPluginTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreContentProductStreamAggregateProductStreamTranslationProductStreamTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreSystemStateMachineStateMachineTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreSystemStateMachineAggregationStateMachineStateStateMachineStateTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreContentCmsAggregateCmsPageTranslationCmsPageTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreContentCmsAggregateCmsSlotTranslationCmsSlotTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreContentMailTemplateAggregateMailTemplateTranslationMailTemplateTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreContentMailTemplateAggregateMailHeaderFooterTranslationMailHeaderFooterTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreCheckoutDocumentAggregateDocumentTypeTranslationDocumentTypeTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreSystemNumberRangeAggregateNumberRangeTypeTranslationNumberRangeTypeTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreSystemDeliveryTimeAggregateDeliveryTimeTranslationDeliveryTimeTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreContentProductAggregateProductSearchKeywordProductSearchKeywordDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreContentProductAggregateProductKeywordDictionaryProductKeywordDictionaryDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreContentMailTemplateAggregateMailTemplateTypeTranslationMailTemplateTypeTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreCheckoutPromotionAggregatePromotionTranslationPromotionTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreSystemNumberRangeAggregateNumberRangeTranslationNumberRangeTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreContentProductAggregateProductReviewProductReviewDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreContentSeoSeoUrlSeoUrlDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreSystemTaxAggregateTaxRuleTypeTranslationTaxRuleTypeTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreContentProductAggregateProductCrossSellingTranslationProductCrossSellingTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreContentImportExportImportExportProfileTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreContentProductSalesChannelSortingProductSortingTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreContentProductAggregateProductFeatureSetTranslationProductFeatureSetTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreFrameworkAppAggregateAppTranslationAppTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreFrameworkAppAggregateActionButtonTranslationActionButtonTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreContentLandingPageAggregateLandingPageTranslationLandingPageTranslationDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareCoreContentProductAggregateProductSearchConfigProductSearchConfigDefinition
ShopwareCoreSystemLanguageLanguageDefinition --> ShopwareStorefrontThemeAggregateThemeTranslationDefinition
@enduml
