@startuml
' uncomment the line below if you're using computer with a retina display
' skinparam dpi 300
!define Table(name,desc) class name as "desc" << (T,#FFAAAA) >>
!define ForeignTable(name,desc) class name as "desc" << (T,#ada6a6) >>
!define TranslationTable(name,desc) class name as "desc" << (I,#4286f4) >>
' we use bold for primary key
' green color for unique
' and underscore for not_null
!define primary_key(x) <b>x</b>
!define unique(x) <color:green>x</color>
!define not_null(x) <u>x</u>
' other tags available:
' <i></i>
' <back:COLOR></color>, where color is a color name or html color code
' (#FFAACC)
' see: http://plantuml.com/classes.html#More
hide methods
hide stereotypes
hide empty members
skinparam backgroundColor #FFFFFF

' entities

Table(ShopwareCoreContentMediaMediaDefinition, "media\n(Media / Files)") {
   primary_key(id) id
   userId foreignKey
   mediaFolderId foreignKey
   mimeType string
   fileExtension string
   uploadedAt dateTime
   fileName longText
   fileSize int
   mediaTypeRaw blob
   metaData json
   mediaType json
   alt translated
   title translated
   url string
   hasFile bool
   private bool
   customFields translated
   thumbnailsRo blob
   not_null(createdAt) createdAt
   updatedAt updatedAt
   translated json
}
Table(ShopwareCoreContentMediaAggregateMediaDefaultFolderMediaDefaultFolderDefinition, "media_default_folder\n(Default folders)") {
   primary_key(id) id
   not_null(associationFields) list
   not_null(entity) string
   customFields customFields
   not_null(createdAt) createdAt
   updatedAt updatedAt
}
Table(ShopwareCoreContentMediaAggregateMediaThumbnailMediaThumbnailDefinition, "media_thumbnail\n(Generated Thumbnail)") {
   primary_key(id) id
   not_null(mediaId) foreignKey
   not_null(width) int
   not_null(height) int
   url string
   customFields customFields
   not_null(createdAt) createdAt
   updatedAt updatedAt
}
TranslationTable(ShopwareCoreContentMediaAggregateMediaTranslationMediaTranslationDefinition, "media_translation\n((Translations))") {
   title string
   alt longText
   customFields customFields
   not_null(createdAt) createdAt
   updatedAt updatedAt
   primary_key(mediaId) foreignKey
   primary_key(languageId) foreignKey
}
Table(ShopwareCoreContentMediaAggregateMediaFolderMediaFolderDefinition, "media_folder\n(Folder structure)") {
   primary_key(id) id
   useParentConfiguration bool
   not_null(configurationId) foreignKey
   defaultFolderId foreignKey
   parentId parentFk
   childCount childCount
   not_null(name) string
   customFields customFields
   not_null(createdAt) createdAt
   updatedAt updatedAt
}
Table(ShopwareCoreContentMediaAggregateMediaThumbnailSizeMediaThumbnailSizeDefinition, "media_thumbnail_size\n(Generated Thumbnails)") {
   primary_key(id) id
   not_null(width) int
   not_null(height) int
   customFields customFields
   not_null(createdAt) createdAt
   updatedAt updatedAt
}
Table(ShopwareCoreContentMediaAggregateMediaFolderConfigurationMediaFolderConfigurationDefinition, "media_folder_configuration\n(Configuration)") {
   primary_key(id) id
   createThumbnails bool
   keepAspectRatio bool
   thumbnailQuality int
   private bool
   noAssociation bool
   mediaThumbnailSizesRo blob
   customFields customFields
   not_null(createdAt) createdAt
   updatedAt updatedAt
}
Table(ShopwareCoreContentMediaAggregateMediaFolderConfigurationMediaThumbnailSizeMediaFolderConfigurationMediaThumbnailSizeDefinition, "media_folder_configuration_media_thumbnail_size\n(M:N Mapping)") {
   primary_key(mediaFolderConfigurationId) foreignKey
   primary_key(mediaThumbnailSizeId) foreignKey
}
Table(ShopwareCoreContentMediaAggregateMediaTagMediaTagDefinition, "media_tag\n(M:N Mapping)") {
   primary_key(mediaId) foreignKey
   primary_key(tagId) foreignKey
}
ForeignTable(ShopwareCoreSystemUserUserDefinition, "user") {
}
ForeignTable(ShopwareCoreContentCategoryCategoryDefinition, "category") {
}
ForeignTable(ShopwareCoreContentProductAggregateProductManufacturerProductManufacturerDefinition, "product_manufacturer") {
}
ForeignTable(ShopwareCoreContentProductAggregateProductMediaProductMediaDefinition, "product_media") {
}
ForeignTable(ShopwareCoreContentPropertyAggregatePropertyGroupOptionPropertyGroupOptionDefinition, "property_group_option") {
}
ForeignTable(ShopwareCoreContentMailTemplateAggregateMailTemplateMediaMailTemplateMediaDefinition, "mail_template_media") {
}
ForeignTable(ShopwareCoreCheckoutDocumentAggregateDocumentBaseConfigDocumentBaseConfigDefinition, "document_base_config") {
}
ForeignTable(ShopwareCoreCheckoutShippingShippingMethodDefinition, "shipping_method") {
}
ForeignTable(ShopwareCoreCheckoutPaymentPaymentMethodDefinition, "payment_method") {
}
ForeignTable(ShopwareCoreContentProductAggregateProductConfiguratorSettingProductConfiguratorSettingDefinition, "product_configurator_setting") {
}
ForeignTable(ShopwareCoreCheckoutOrderAggregateOrderLineItemOrderLineItemDefinition, "order_line_item") {
}
ForeignTable(ShopwareCoreContentCmsAggregateCmsBlockCmsBlockDefinition, "cms_block") {
}
ForeignTable(ShopwareCoreContentCmsAggregateCmsSectionCmsSectionDefinition, "cms_section") {
}
ForeignTable(ShopwareCoreContentCmsCmsPageDefinition, "cms_page") {
}
ForeignTable(ShopwareCoreCheckoutDocumentDocumentDefinition, "document") {
}
ForeignTable(ShopwareStorefrontThemeThemeDefinition, "theme") {
}
ForeignTable(ShopwareStorefrontThemeAggregateThemeMediaDefinition, "theme_media") {
}
ForeignTable(ShopwareCoreSystemLanguageLanguageDefinition, "language") {
}
ForeignTable(ShopwareCoreSystemTagTagDefinition, "tag") {
}

' relationshipd

ShopwareCoreContentMediaAggregateMediaTranslationMediaTranslationDefinition --> ShopwareCoreContentMediaMediaDefinition
ShopwareCoreContentMediaAggregateMediaTagMediaTagDefinition --> ShopwareCoreContentMediaMediaDefinition
ShopwareCoreContentMediaAggregateMediaThumbnailMediaThumbnailDefinition --> ShopwareCoreContentMediaMediaDefinition
ShopwareCoreContentMediaMediaDefinition --> ShopwareCoreSystemUserUserDefinition
ShopwareCoreContentMediaMediaDefinition --> ShopwareCoreContentCategoryCategoryDefinition
ShopwareCoreContentMediaMediaDefinition --> ShopwareCoreContentProductAggregateProductManufacturerProductManufacturerDefinition
ShopwareCoreContentMediaMediaDefinition --> ShopwareCoreContentProductAggregateProductMediaProductMediaDefinition
ShopwareCoreContentMediaAggregateMediaFolderMediaFolderDefinition --> ShopwareCoreContentMediaMediaDefinition
ShopwareCoreContentMediaMediaDefinition --> ShopwareCoreContentPropertyAggregatePropertyGroupOptionPropertyGroupOptionDefinition
ShopwareCoreContentMediaMediaDefinition --> ShopwareCoreContentMailTemplateAggregateMailTemplateMediaMailTemplateMediaDefinition
ShopwareCoreContentMediaMediaDefinition --> ShopwareCoreCheckoutDocumentAggregateDocumentBaseConfigDocumentBaseConfigDefinition
ShopwareCoreContentMediaMediaDefinition --> ShopwareCoreCheckoutShippingShippingMethodDefinition
ShopwareCoreContentMediaMediaDefinition --> ShopwareCoreCheckoutPaymentPaymentMethodDefinition
ShopwareCoreContentMediaMediaDefinition --> ShopwareCoreContentProductAggregateProductConfiguratorSettingProductConfiguratorSettingDefinition
ShopwareCoreContentMediaMediaDefinition --> ShopwareCoreCheckoutOrderAggregateOrderLineItemOrderLineItemDefinition
ShopwareCoreContentMediaMediaDefinition --> ShopwareCoreContentCmsAggregateCmsBlockCmsBlockDefinition
ShopwareCoreContentMediaMediaDefinition --> ShopwareCoreContentCmsAggregateCmsSectionCmsSectionDefinition
ShopwareCoreContentMediaMediaDefinition --> ShopwareCoreContentCmsCmsPageDefinition
ShopwareCoreContentMediaMediaDefinition --> ShopwareCoreCheckoutDocumentDocumentDefinition
ShopwareCoreContentMediaMediaDefinition --> ShopwareStorefrontThemeThemeDefinition
ShopwareCoreContentMediaMediaDefinition --> ShopwareStorefrontThemeAggregateThemeMediaDefinition
ShopwareCoreContentMediaAggregateMediaFolderMediaFolderDefinition --> ShopwareCoreContentMediaAggregateMediaDefaultFolderMediaDefaultFolderDefinition
ShopwareCoreContentMediaAggregateMediaTranslationMediaTranslationDefinition --> ShopwareCoreSystemLanguageLanguageDefinition
ShopwareCoreContentMediaAggregateMediaFolderMediaFolderDefinition --> ShopwareCoreContentMediaAggregateMediaFolderMediaFolderDefinition
ShopwareCoreContentMediaAggregateMediaFolderConfigurationMediaFolderConfigurationDefinition --> ShopwareCoreContentMediaAggregateMediaFolderMediaFolderDefinition
ShopwareCoreContentMediaAggregateMediaFolderConfigurationMediaThumbnailSizeMediaFolderConfigurationMediaThumbnailSizeDefinition --> ShopwareCoreContentMediaAggregateMediaThumbnailSizeMediaThumbnailSizeDefinition
ShopwareCoreContentMediaAggregateMediaFolderConfigurationMediaThumbnailSizeMediaFolderConfigurationMediaThumbnailSizeDefinition --> ShopwareCoreContentMediaAggregateMediaFolderConfigurationMediaFolderConfigurationDefinition
ShopwareCoreContentMediaAggregateMediaTagMediaTagDefinition --> ShopwareCoreSystemTagTagDefinition
@enduml
