<?php declare(strict_types=1);

namespace Shopware\Tests\Unit\Core\Checkout\Cart\Order\Stubs;

use Shopware\Core\Checkout\Cart\LineItem\LineItem;
use Shopware\Core\Content\Product\ProductDefinition;
use Shopware\Core\Defaults;
use Shopware\Core\Framework\Feature;
use Shopware\Core\System\SalesChannel\SalesChannelDefinition;
use Shopware\Core\Test\TestDefaults;

/**
 * @internal
 */
final class CartOrderConversionStub
{
    /**
     * @return array<string, mixed>
     */
    public static function getExpectedConvertToCart(): array
    {
        return [
            'extensions' => [
                'originalOrderNumber' => [
                    'extensions' => [],
                    'id' => '10000',
                ],
            ],
            'price' => [
                'netPrice' => 19.5,
                'totalPrice' => 19.5,
                'calculatedTaxes' => [],
                'taxRules' => [],
                'positionPrice' => 19.5,
                'taxStatus' => 'tax-free',
                'rawTotal' => 19.5,
                'extensions' => [],
            ],
            'lineItems' => [
                [
                    'payload' => [
                        'productType' => ProductDefinition::TYPE_PHYSICAL,
                    ],
                    'id' => 'order-line-item-identifier',
                    'referencedId' => null,
                    'label' => 'order-line-item-label',
                    'quantity' => 1,
                    'type' => LineItem::PRODUCT_LINE_ITEM_TYPE,
                    'priceDefinition' => null,
                    'price' => null,
                    'good' => true,
                    'description' => null,
                    'cover' => null,
                    'deliveryInformation' => null,
                    'children' => [],
                    'requirement' => null,
                    'removable' => false,
                    'stackable' => true,
                    'quantityInformation' => null,
                    'modified' => false,
                    'dataTimestamp' => null,
                    'dataContextHash' => null,
                    'extensions' => [],
                    'states' => [],
                    'modifiedByApp' => false,
                    'shippingCostAware' => true,
                ],
            ],
            'errors' => [],
            'deliveries' => [
                [
                    'positions' => [
                        [
                            'lineItem' => [
                                'payload' => [
                                    'productType' => ProductDefinition::TYPE_PHYSICAL,
                                ],
                                'id' => 'order-line-item-identifier',
                                'referencedId' => null,
                                'label' => 'order-line-item-label',
                                'quantity' => 1,
                                'type' => LineItem::PRODUCT_LINE_ITEM_TYPE,
                                'priceDefinition' => null,
                                'price' => null,
                                'good' => true,
                                'description' => null,
                                'cover' => null,
                                'deliveryInformation' => null,
                                'children' => [],
                                'requirement' => null,
                                'removable' => false,
                                'stackable' => true,
                                'quantityInformation' => null,
                                'modified' => false,
                                'dataTimestamp' => null,
                                'dataContextHash' => null,
                                'extensions' => [
                                    'originalId' => [
                                        'id' => 'order-line-item-id',
                                        'extensions' => [],
                                    ],
                                ],
                                'modifiedByApp' => false,
                                'shippingCostAware' => true,
                                'states' => [],
                            ],
                            'quantity' => 1,
                            'price' => [
                                'unitPrice' => 1,
                                'quantity' => 1,
                                'totalPrice' => 1,
                                'calculatedTaxes' => [],
                                'taxRules' => [],
                                'referencePrice' => null,
                                'listPrice' => null,
                                'regulationPrice' => null,
                                'extensions' => [],
                            ],
                            'identifier' => 'order-line-item-identifier',
                            'extensions' => [
                                'originalId' => [
                                    'id' => 'order-delivery-position-id-1',
                                    'extensions' => [],
                                ],
                            ],
                        ],
                    ],
                    'location' => [
                        'country' => [
                            'name' => 'country-name',
                            'iso' => null,
                            'position' => 0,
                            'active' => true,
                            'shippingAvailable' => true,
                            'iso3' => null,
                            'displayStateInRegistration' => true,
                            'forceStateInRegistration' => true,
                            'checkVatIdPattern' => false,
                            'vatIdPattern' => null,
                            'vatIdRequired' => null,
                            'states' => null,
                            'translations' => null,
                            'orderAddresses' => null,
                            'customerAddresses' => null,
                            'salesChannelDefaultAssignments' => null,
                            'salesChannels' => null,
                            'taxRules' => null,
                            'currencyCountryRoundings' => null,
                            '_uniqueIdentifier' => 'country-id',
                            'versionId' => null,
                            'translated' => [],
                            'createdAt' => null,
                            'updatedAt' => null,
                            'extensions' => [],
                            'id' => 'country-id',
                            'customFields' => null,
                            'advancedPostalCodePattern' => null,
                            'defaultPostalCodePattern' => null,
                        ],
                        'state' => [
                            'countryId' => 'country-id',
                            'shortCode' => 'CSN',
                            'name' => 'country-state-name',
                            'position' => 0,
                            'active' => true,
                            'country' => null,
                            'translations' => null,
                            'customerAddresses' => null,
                            'orderAddresses' => null,
                            '_uniqueIdentifier' => 'country-state-id',
                            'versionId' => null,
                            'translated' => [],
                            'createdAt' => null,
                            'updatedAt' => null,
                            'extensions' => [],
                            'id' => 'country-state-id',
                            'customFields' => null,
                        ],
                        'address' => null,
                        'extensions' => [],
                    ],
                    'shippingMethod' => [
                        'name' => null,
                        'description' => null,
                        'trackingUrl' => null,
                        'deliveryTime' => null,
                        'translations' => null,
                        'orderDeliveries' => null,
                        'salesChannelDefaultAssignments' => null,
                        'salesChannels' => null,
                        'availabilityRule' => null,
                        'availabilityRuleId' => null,
                        'prices' => [],
                        'mediaId' => null,
                        'taxId' => null,
                        'media' => null,
                        'tags' => null,
                        'tax' => null,
                        'versionId' => null,
                        'translated' => [],
                        'createdAt' => null,
                        'updatedAt' => null,
                        'extensions' => [],
                        'customFields' => null,
                        'appShippingMethod' => null,
                        'active' => null,
                        'position' => null,
                    ],
                    'shippingCosts' => [
                        'unitPrice' => 1,
                        'quantity' => 1,
                        'totalPrice' => 1,
                        'calculatedTaxes' => [],
                        'taxRules' => [],
                        'referencePrice' => null,
                        'listPrice' => null,
                        'regulationPrice' => null,
                        'extensions' => [],
                    ],
                    'extensions' => [
                        'originalId' => [
                            'id' => 'order-delivery-id',
                            'extensions' => [],
                        ],
                        'originalAddressId' => [
                            'id' => 'order-address-id',
                            'extensions' => [],
                        ],
                        'originalAddressVersionId' => [
                            'id' => 'order-address-version-id',
                            'extensions' => [],
                        ],
                    ],
                ],
            ],
            'transactions' => [],
            'modified' => false,
            'customerComment' => null,
            'affiliateCode' => null,
            'campaignCode' => null,
            'source' => null,
            'hash' => null,
            'states' => [],
            'persisted' => false,
        ];
    }

    /**
     * @return array<string, mixed>
     */
    public static function getExpectedConvertToOrder(): array
    {
        if (!Feature::isActive('v6.8.0.0')) {
            return [
                'price' => [
                    'netPrice' => 0,
                    'totalPrice' => 0,
                    'calculatedTaxes' => [],
                    'taxRules' => [],
                    'positionPrice' => 0,
                    'taxStatus' => 'gross',
                    'rawTotal' => 0,
                    'extensions' => [],
                ],
                'shippingCosts' => [
                    'unitPrice' => 0,
                    'quantity' => 1,
                    'totalPrice' => 0,
                    'calculatedTaxes' => [],
                    'taxRules' => [],
                    'referencePrice' => null,
                    'listPrice' => null,
                    'regulationPrice' => null,
                    'extensions' => [],
                ],
                'currencyId' => Defaults::CURRENCY,
                'currencyFactor' => 1,
                'salesChannelId' => TestDefaults::SALES_CHANNEL,
                'lineItems' => [
                    [
                        'identifier' => 'line-item-id-1',
                        'quantity' => 1,
                        'type' => LineItem::PRODUCT_LINE_ITEM_TYPE,
                        'label' => 'line-item-label-1',
                        'good' => true,
                        'removable' => false,
                        'stackable' => false,
                        'states' => [],
                        'position' => 1,
                        'price' => [
                            'unitPrice' => 1,
                            'quantity' => 1,
                            'totalPrice' => 1,
                            'calculatedTaxes' => [],
                            'taxRules' => [],
                            'referencePrice' => null,
                            'listPrice' => null,
                            'regulationPrice' => null,
                            'extensions' => [],
                        ],
                        'payload' => [
                            'productType' => ProductDefinition::TYPE_PHYSICAL,
                        ],
                    ],
                    [
                        'identifier' => 'line-item-id-2',
                        'quantity' => 1,
                        'type' => LineItem::PRODUCT_LINE_ITEM_TYPE,
                        'label' => 'line-item-label-2',
                        'good' => true,
                        'removable' => false,
                        'stackable' => false,
                        'states' => [],
                        'position' => 2,
                        'price' => [
                            'unitPrice' => 1,
                            'quantity' => 1,
                            'totalPrice' => 1,
                            'calculatedTaxes' => [],
                            'taxRules' => [],
                            'referencePrice' => null,
                            'listPrice' => null,
                            'regulationPrice' => null,
                            'extensions' => [],
                        ],
                        'payload' => [
                            'productType' => ProductDefinition::TYPE_PHYSICAL,
                        ],
                    ],
                ],
                'deliveries' => [[
                    'positions' => [],
                    'shippingCosts' => [
                        'calculatedTaxes' => [],
                        'extensions' => [],
                        'listPrice' => null,
                        'quantity' => 1,
                        'referencePrice' => null,
                        'regulationPrice' => null,
                        'taxRules' => [],
                        'totalPrice' => 1,
                        'unitPrice' => 1,
                    ],
                    'shippingMethodId' => 'shipping-method-id',
                    'shippingOrderAddress' => [
                        'city' => 'billing-address-city',
                        'countryId' => 'billing-address-country-id',
                        'firstName' => 'billing-address-first-name',
                        'lastName' => 'billing-address-last-name',
                        'salutationId' => 'billing-address-salutation-id',
                        'street' => 'billing-address-street',
                        'zipcode' => 'billing-address-zipcode',
                    ],
                    'stateId' => '',
                ]],
                'customerComment' => null,
                'affiliateCode' => null,
                'campaignCode' => null,
                'source' => null,
                'itemRounding' => [
                    'decimals' => 2,
                    'extensions' => [],
                    'interval' => 0.01,
                    'roundForNet' => true,
                ],
                'totalRounding' => [
                    'decimals' => 2,
                    'extensions' => [],
                    'interval' => 0.01,
                    'roundForNet' => true,
                ],
                'orderCustomer' => [
                    'company' => null,
                    'customFields' => null,
                    'customer' => [
                        'id' => 'customer-id',
                        'lastPaymentMethodId' => 'payment-method-id',
                    ],
                    'customerNumber' => 'customer-number',
                    'email' => 'customer-email',
                    'firstName' => 'customer-first-name',
                    'lastName' => 'customer-last-name',
                    'remoteAddress' => null,
                    'salutationId' => 'customer-salutation-id',
                    'title' => null,
                    'vatIds' => null,
                ],
                'transactions' => [],
                'orderNumber' => '10000',
                'ruleIds' => [
                    'order-rule-id-1',
                    'order-rule-id-2',
                ],
                'taxCalculationType' => SalesChannelDefinition::CALCULATION_TYPE_HORIZONTAL,
                'addresses' => [
                    [
                        'city' => 'billing-address-city',
                        'countryId' => 'billing-address-country-id',
                        'firstName' => 'billing-address-first-name',
                        'lastName' => 'billing-address-last-name',
                        'salutationId' => 'billing-address-salutation-id',
                        'street' => 'billing-address-street',
                        'zipcode' => 'billing-address-zipcode',
                    ],
                ],
            ];
        }

        return [
            'price' => [
                'netPrice' => 0,
                'totalPrice' => 0,
                'calculatedTaxes' => [],
                'taxRules' => [],
                'positionPrice' => 0,
                'taxStatus' => 'gross',
                'rawTotal' => 0,
                'extensions' => [],
            ],
            'shippingCosts' => [
                'unitPrice' => 0,
                'quantity' => 1,
                'totalPrice' => 0,
                'calculatedTaxes' => [],
                'taxRules' => [],
                'referencePrice' => null,
                'listPrice' => null,
                'regulationPrice' => null,
                'extensions' => [],
            ],
            'currencyId' => Defaults::CURRENCY,
            'currencyFactor' => 1,
            'salesChannelId' => TestDefaults::SALES_CHANNEL,
            'lineItems' => [
                [
                    'identifier' => 'line-item-id-1',
                    'quantity' => 1,
                    'type' => LineItem::PRODUCT_LINE_ITEM_TYPE,
                    'label' => 'line-item-label-1',
                    'good' => true,
                    'removable' => false,
                    'stackable' => false,
                    'position' => 1,
                    'price' => [
                        'unitPrice' => 1,
                        'quantity' => 1,
                        'totalPrice' => 1,
                        'calculatedTaxes' => [],
                        'taxRules' => [],
                        'referencePrice' => null,
                        'listPrice' => null,
                        'regulationPrice' => null,
                        'extensions' => [],
                    ],
                    'payload' => [
                        'productType' => ProductDefinition::TYPE_PHYSICAL,
                    ],
                ],
                [
                    'identifier' => 'line-item-id-2',
                    'quantity' => 1,
                    'type' => LineItem::PRODUCT_LINE_ITEM_TYPE,
                    'label' => 'line-item-label-2',
                    'good' => true,
                    'removable' => false,
                    'stackable' => false,
                    'position' => 2,
                    'price' => [
                        'unitPrice' => 1,
                        'quantity' => 1,
                        'totalPrice' => 1,
                        'calculatedTaxes' => [],
                        'taxRules' => [],
                        'referencePrice' => null,
                        'listPrice' => null,
                        'regulationPrice' => null,
                        'extensions' => [],
                    ],
                    'payload' => [
                        'productType' => ProductDefinition::TYPE_PHYSICAL,
                    ],
                ],
            ],
            'deliveries' => [[
                'positions' => [],
                'shippingCosts' => [
                    'calculatedTaxes' => [],
                    'extensions' => [],
                    'listPrice' => null,
                    'quantity' => 1,
                    'referencePrice' => null,
                    'regulationPrice' => null,
                    'taxRules' => [],
                    'totalPrice' => 1,
                    'unitPrice' => 1,
                ],
                'shippingMethodId' => 'shipping-method-id',
                'shippingOrderAddress' => [
                    'city' => 'billing-address-city',
                    'countryId' => 'billing-address-country-id',
                    'firstName' => 'billing-address-first-name',
                    'lastName' => 'billing-address-last-name',
                    'salutationId' => 'billing-address-salutation-id',
                    'street' => 'billing-address-street',
                    'zipcode' => 'billing-address-zipcode',
                ],
                'stateId' => '',
            ]],
            'customerComment' => null,
            'affiliateCode' => null,
            'campaignCode' => null,
            'source' => null,
            'itemRounding' => [
                'decimals' => 2,
                'extensions' => [],
                'interval' => 0.01,
                'roundForNet' => true,
            ],
            'totalRounding' => [
                'decimals' => 2,
                'extensions' => [],
                'interval' => 0.01,
                'roundForNet' => true,
            ],
            'orderCustomer' => [
                'company' => null,
                'customFields' => null,
                'customer' => [
                    'id' => 'customer-id',
                    'lastPaymentMethodId' => 'payment-method-id',
                ],
                'customerNumber' => 'customer-number',
                'email' => 'customer-email',
                'firstName' => 'customer-first-name',
                'lastName' => 'customer-last-name',
                'remoteAddress' => null,
                'salutationId' => 'customer-salutation-id',
                'title' => null,
                'vatIds' => null,
            ],
            'transactions' => [],
            'orderNumber' => '10000',
            'ruleIds' => [
                'order-rule-id-1',
                'order-rule-id-2',
            ],
            'taxCalculationType' => SalesChannelDefinition::CALCULATION_TYPE_HORIZONTAL,
            'addresses' => [
                [
                    'city' => 'billing-address-city',
                    'countryId' => 'billing-address-country-id',
                    'firstName' => 'billing-address-first-name',
                    'lastName' => 'billing-address-last-name',
                    'salutationId' => 'billing-address-salutation-id',
                    'street' => 'billing-address-street',
                    'zipcode' => 'billing-address-zipcode',
                ],
            ],
        ];
    }
}
