<?php declare(strict_types=1);

namespace Shopware\Tests\Unit\Core\Framework\DataAbstractionLayer\Attribute\ManyToMany;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\TestCase;
use Shopware\Core\Framework\DataAbstractionLayer\Attribute\ManyToMany;
use Shopware\Core\Framework\DataAbstractionLayer\Attribute\OnDelete;
use Shopware\Core\Framework\DataAbstractionLayer\Field\ManyToManyAssociationField;
use Shopware\Core\Framework\Log\Package;
use Shopware\Tests\Unit\Core\Framework\DataAbstractionLayer\Attribute\AttributeTestFixtures;

/**
 * @internal
 */
#[Package('framework')]
#[CoversClass(ManyToMany::class)]
final class ManyToManyTest extends TestCase
{
    public function testExplicitMappingName(): void
    {
        $attribute = new ManyToMany(
            entity: AttributeTestFixtures::ENTITY_NAME_PRODUCT,
            mapping: 'custom_mapping'
        );

        $field = $attribute->createField(
            AttributeTestFixtures::PROPERTY_NAME_CATEGORIES,
            'categories',
            AttributeTestFixtures::ENTITY_NAME_CATEGORY
        );

        static::assertInstanceOf(ManyToManyAssociationField::class, $field);
        static::assertSame(AttributeTestFixtures::PROPERTY_NAME_CATEGORIES, $field->getPropertyName());
    }

    public function testAutoGeneratedMappingName(): void
    {
        $attribute = new ManyToMany(entity: AttributeTestFixtures::ENTITY_NAME_PRODUCT);

        $field = $attribute->createField(
            AttributeTestFixtures::PROPERTY_NAME_CATEGORIES,
            'categories',
            AttributeTestFixtures::ENTITY_NAME_CATEGORY
        );

        static::assertInstanceOf(ManyToManyAssociationField::class, $field);
    }

    public function testMappingNameWithReverseOrder(): void
    {
        $attribute = new ManyToMany(entity: AttributeTestFixtures::ENTITY_NAME_CATEGORY);

        $field = $attribute->createField(
            'products',
            'products',
            AttributeTestFixtures::ENTITY_NAME_PRODUCT
        );

        static::assertInstanceOf(ManyToManyAssociationField::class, $field);
    }

    public function testSelfReferencingMappingName(): void
    {
        $attribute = new ManyToMany(entity: AttributeTestFixtures::ENTITY_NAME_CATEGORY);

        $field = $attribute->createField(
            'children',
            'children',
            AttributeTestFixtures::ENTITY_NAME_CATEGORY
        );

        static::assertInstanceOf(ManyToManyAssociationField::class, $field);
        static::assertSame('category_category', $attribute->getMappingName(AttributeTestFixtures::ENTITY_NAME_CATEGORY));
    }

    public function testForeignKeyColumns(): void
    {
        $attribute = new ManyToMany(entity: AttributeTestFixtures::ENTITY_NAME_PRODUCT);

        $field = $attribute->createField(
            AttributeTestFixtures::PROPERTY_NAME_CATEGORIES,
            'categories',
            AttributeTestFixtures::ENTITY_NAME_CATEGORY
        );

        static::assertInstanceOf(ManyToManyAssociationField::class, $field);
        static::assertSame('category_id', $field->getMappingLocalColumn());
        static::assertSame('product_id', $field->getMappingReferenceColumn());
    }

    public function testGetFieldClass(): void
    {
        $attribute = new ManyToMany(entity: AttributeTestFixtures::ENTITY_NAME_PRODUCT);

        static::assertSame(ManyToManyAssociationField::class, $attribute->getFieldClass());
    }

    public function testGetMappingNameWithExplicitName(): void
    {
        $attribute = new ManyToMany(
            entity: AttributeTestFixtures::ENTITY_NAME_PRODUCT,
            mapping: 'custom_mapping'
        );

        static::assertSame('custom_mapping', $attribute->getMappingName(AttributeTestFixtures::ENTITY_NAME_CATEGORY));
    }

    public function testGetMappingNameAutoGenerated(): void
    {
        $attribute = new ManyToMany(entity: AttributeTestFixtures::ENTITY_NAME_PRODUCT);

        static::assertSame(
            AttributeTestFixtures::MAPPING_NAME_CATEGORY_PRODUCT,
            $attribute->getMappingName(AttributeTestFixtures::ENTITY_NAME_CATEGORY)
        );
    }

    public function testFromArray(): void
    {
        $data = [
            'entity' => AttributeTestFixtures::ENTITY_NAME_PRODUCT,
            'mapping' => 'test_mapping',
            'onDelete' => OnDelete::SET_NULL->value,
            'api' => false,
            'nullable' => true,
            'type' => ManyToMany::TYPE,
            'translated' => false,
        ];

        $attribute = ManyToMany::fromArray($data);

        static::assertSame(AttributeTestFixtures::ENTITY_NAME_PRODUCT, $attribute->entity);
        static::assertSame('test_mapping', $attribute->mapping);
        static::assertSame(OnDelete::SET_NULL, $attribute->onDelete);
        static::assertTrue($attribute->nullable);
    }

    public function testGetMappingNameWithSameEntities(): void
    {
        $attribute = new ManyToMany(entity: 'category');

        static::assertSame('category_category', $attribute->getMappingName('category'));
    }

    public function testGetMappingNameMaintainsOrder(): void
    {
        $attribute = new ManyToMany(entity: 'apple');

        static::assertSame('apple_banana', $attribute->getMappingName('banana'));
    }

    public function testGetMappingNameSortsCorrectly(): void
    {
        $attribute = new ManyToMany(entity: 'zebra');

        static::assertSame('apple_zebra', $attribute->getMappingName('apple'));
    }

    public function testToDefinition(): void
    {
        $attribute = new ManyToMany(
            entity: AttributeTestFixtures::ENTITY_NAME_PRODUCT,
            onDelete: OnDelete::CASCADE,
            api: true,
            mapping: 'custom_mapping'
        );
        $attribute->nullable = false;

        $definition = $attribute->toDefinition();

        static::assertSame([ManyToMany::class, 'fromArray'], $definition->getFactory());

        $args = $definition->getArguments();
        static::assertCount(1, $args);
        static::assertIsArray($args[0]);
        static::assertSame(AttributeTestFixtures::ENTITY_NAME_PRODUCT, $args[0]['entity']);
        static::assertSame(OnDelete::CASCADE->value, $args[0]['onDelete']);
        static::assertTrue($args[0]['api']);
        static::assertSame('custom_mapping', $args[0]['mapping']);
        static::assertFalse($args[0]['nullable']);
    }
}
