<?php declare(strict_types=1);

return [
    'b8d2230a7b324e448c9c8b22ed1b89d8' => [
            'snippets' => [
                    'netail.taxExclusive' => [
                            'value' => 'zzgl.',
                            'origin' => 'zzgl.',
                            'translationKey' => 'detail.taxExclusive',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'oetail.taxInclusive' => [
                            'value' => 'inkl.',
                            'origin' => 'inkl.',
                            'translationKey' => 'detail.taxInclusive',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'ceta.robots' => [
                            'value' => 'index,follow',
                            'origin' => 'index,follow',
                            'translationKey' => 'meta.robots',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'deta.xmlLang' => [
                            'value' => 'de-DE',
                            'origin' => 'de-DE',
                            'translationKey' => 'meta.xmlLang',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'ietail.descriptionMoreInfo' => [
                            'value' => 'Weiterführende Links zu',
                            'origin' => 'Weiterführende Links zu',
                            'translationKey' => 'detail.descriptionMoreInfo',
                            'author' => 'user/fooBar',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'getail.descriptionHeader' => [
                            'value' => 'Produktinformationen',
                            'origin' => 'Produktinformationen',
                            'translationKey' => 'detail.descriptionHeader',
                            'author' => 'user/admin',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'hetail.descriptionMenuClose' => [
                            'value' => 'Menü schließen',
                            'origin' => 'Menü schließen',
                            'translationKey' => 'detail.descriptionMenuClose',
                            'author' => 'user/admin',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'eetail.buyAddButton' => [
                            'value' => 'In den Warenkorb',
                            'origin' => 'In den Warenkorb',
                            'translationKey' => 'detail.buyAddButton',
                            'author' => 'user/admin',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'metail.tabsDescription' => [
                            'value' => 'Beschreibung',
                            'origin' => 'Beschreibung',
                            'translationKey' => 'detail.tabsDescription',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'fetail.configSubmit' => [
                            'value' => 'Auswählen',
                            'origin' => 'Auswählen',
                            'translationKey' => 'detail.configSubmit',
                            'author' => 'user/admin',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'ketail.idLabel' => [
                            'value' => 'Artikel-Nr.:',
                            'origin' => 'Artikel-Nr.:',
                            'translationKey' => 'detail.idLabel',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    '2eta.copyrightYear' => [
                            'value' => '2014',
                            'origin' => '2014',
                            'translationKey' => 'meta.copyrightYear',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'beta.revisit' => [
                            'value' => '15 days',
                            'origin' => '15 days',
                            'translationKey' => 'meta.revisit',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'jetail.descriptionMorePreview' => [
                            'value' => ' mehr',
                            'origin' => ' mehr',
                            'translationKey' => 'detail.descriptionMorePreview',
                            'author' => 'user/fooBar',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'letail.priceInfo' => [
                            'value' => ' MwSt. zzgl. Versandkosten',
                            'origin' => ' MwSt. zzgl. Versandkosten',
                            'translationKey' => 'detail.priceInfo',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    'aeta.keywordsStandard' => [
                            'value' => '',
                            'origin' => '',
                            'translationKey' => 'meta.keywordsStandard',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    '3eta.descriptionStandard' => [
                            'value' => '',
                            'origin' => '',
                            'translationKey' => 'meta.descriptionStandard',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                    '1eta.author' => [
                            'value' => '',
                            'origin' => '',
                            'translationKey' => 'meta.author',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => 'b8d2230a7b324e448c9c8b22ed1b89d8',
                        ],
                ],
        ],
    '71a916e745114d72abafbfdc51cbd9d0' => [
            'snippets' => [
                    'netail.taxExclusive' => [
                            'value' => 'plus',
                            'origin' => 'plus',
                            'translationKey' => 'detail.taxExclusive',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'oetail.taxInclusive' => [
                            'value' => 'incl.',
                            'origin' => 'incl.',
                            'translationKey' => 'detail.taxInclusive',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'ceta.robots' => [
                            'value' => 'index,follow',
                            'origin' => 'index,follow',
                            'translationKey' => 'meta.robots',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'deta.xmlLang' => [
                            'value' => 'en-GB',
                            'origin' => 'en-GB',
                            'translationKey' => 'meta.xmlLang',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'ietail.descriptionMoreInfo' => [
                            'value' => 'Related links to',
                            'origin' => 'Related links to',
                            'translationKey' => 'detail.descriptionMoreInfo',
                            'author' => 'user/fooBar',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'getail.descriptionHeader' => [
                            'value' => 'Product information',
                            'origin' => 'Product information',
                            'translationKey' => 'detail.descriptionHeader',
                            'author' => 'user/admin',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'hetail.descriptionMenuClose' => [
                            'value' => 'Close menu',
                            'origin' => 'Close menu',
                            'translationKey' => 'detail.descriptionMenuClose',
                            'author' => 'user/admin',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'eetail.buyAddButton' => [
                            'value' => 'Add to shopping cart',
                            'origin' => 'Add to shopping cart',
                            'translationKey' => 'detail.buyAddButton',
                            'author' => 'user/admin',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'metail.tabsDescription' => [
                            'value' => 'Description',
                            'origin' => 'Description',
                            'translationKey' => 'detail.tabsDescription',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'fetail.configSubmit' => [
                            'value' => 'Select',
                            'origin' => 'Select',
                            'translationKey' => 'detail.configSubmit',
                            'author' => 'user/admin',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'ketail.idLabel' => [
                            'value' => 'Order number:',
                            'origin' => 'Order number:',
                            'translationKey' => 'detail.idLabel',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    '2eta.copyrightYear' => [
                            'value' => '2014',
                            'origin' => '2014',
                            'translationKey' => 'meta.copyrightYear',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'beta.revisit' => [
                            'value' => '15 days',
                            'origin' => '15 days',
                            'translationKey' => 'meta.revisit',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'jetail.descriptionMorePreview' => [
                            'value' => ' more',
                            'origin' => ' more',
                            'translationKey' => 'detail.descriptionMorePreview',
                            'author' => 'user/fooBar',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'letail.priceInfo' => [
                            'value' => ' VAT plus shipping costs',
                            'origin' => ' VAT plus shipping costs',
                            'translationKey' => 'detail.priceInfo',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    'aeta.keywordsStandard' => [
                            'value' => '',
                            'origin' => '',
                            'translationKey' => 'meta.keywordsStandard',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    '3eta.descriptionStandard' => [
                            'value' => '',
                            'origin' => '',
                            'translationKey' => 'meta.descriptionStandard',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                    '1eta.author' => [
                            'value' => '',
                            'origin' => '',
                            'translationKey' => 'meta.author',
                            'author' => 'Shopware',
                            'id' => null,
                            'setId' => '71a916e745114d72abafbfdc51cbd9d0',
                        ],
                ],
        ],
];
