<?php declare(strict_types=1);

namespace Shopware\Core\DevOps\Docs\Script;

use Shopware\Core\Framework\Adapter\Console\ShopwareStyle;
use Shopware\Core\Framework\Context;
use Shopware\Core\Framework\Event\BusinessEventCollector;
use Shopware\Core\Framework\Log\Package;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Filesystem\Exception\IOException;
use Symfony\Component\Filesystem\Filesystem;

/**
 * @internal
 */
#[AsCommand(
    name: 'docs:generate-trigger-reference',
    description: 'Generate a Markdown table with all business/flow triggers',
)]
#[Package('framework')]
class TriggerReferenceGeneratorCommand extends Command
{
    private const EVENT_DESCRIPTIONS = __DIR__ . '/../../Resources/templates/trigger-event-description.json';
    private const OUTPUT_PATH = __DIR__ . '/../../Resources/generated/trigger-events-reference.md';

    public function __construct(
        private readonly BusinessEventCollector $collector,
        private readonly Filesystem $filesystem,
    ) {
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new ShopwareStyle($input, $output);

        $io->comment('Generating Markdown reference for business/flow triggers.');

        $events = $this->collector->collect(Context::createCLIContext());

        try {
            $descriptions = json_decode($this->filesystem->readFile(self::EVENT_DESCRIPTIONS), true, flags: \JSON_THROW_ON_ERROR);
        } catch (IOException) {
            $io->error(\sprintf(
                'Descriptions file is missing or unreadable: %s. The generated reference requires trigger-event-description.json.',
                self::EVENT_DESCRIPTIONS
            ));

            return self::FAILURE;
        }

        if (!\is_array($descriptions)) {
            $io->error('Failed to parse descriptions file: trigger-event-description.json contains invalid JSON.');

            return self::FAILURE;
        }

        // Sort events by name for stable output
        $rows = [];
        foreach ($events as $event) {
            $name = $event->getName();
            $description = $descriptions[$name] ?? $event->getClass();

            $rows[] = [
                'name' => $name,
                'description' => $description,
            ];
        }

        usort($rows, fn (array $a, array $b) => $a['name'] <=> $b['name']);

        $lines = [
            '<!--- auto generated by `bin/console docs:generate-trigger-reference` in the shopware project, don\'t edit this file manually -->',
            '',
            '# Trigger Events Reference',
            '',
            '| Event | Description |',
            '| :--- | :--- |',
        ];

        foreach ($rows as $row) {
            $lines[] = \sprintf('|`%s` | %s |', $row['name'], $row['description']);
        }

        $content = \implode(\PHP_EOL, $lines) . \PHP_EOL;
        $this->filesystem->dumpFile(self::OUTPUT_PATH, $content);

        // Also print to stdout for convenience
        foreach ($lines as $line) {
            $io->writeln($line);
        }

        $io->success(\sprintf('Trigger reference generated: %s', self::OUTPUT_PATH));

        return self::SUCCESS;
    }
}
