/** @sw-package framework */

/** @private */
export type OverrideFn<COMPONENT_NAME extends keyof ComponentPublicApiMapping & string = string> = (
    previousState: ComponentPublicApiMapping[COMPONENT_NAME],
    props: ComponentPublicApiMapping[COMPONENT_NAME],
    context?: unknown,
) => ComponentPublicApiMapping[COMPONENT_NAME];

declare module 'vue' {
    interface ComponentCustomOptions {
        /** Generated by the setup transform: maps public aliases to their shared setup binding. */
        legacyOptionsBindings?: Record<string, string>;
        /** Generated by the setup transform for native Options initialization and introspection. */
        legacyOptionsMembers?: Record<string, 'data' | 'computed' | 'writable-computed' | 'method'>;
        __swExtendable?: boolean;
    }
}
