@startuml
' uncomment the line below if you're using computer with a retina display
' skinparam dpi 300
!define Table(name,desc) class name as "desc" << (T,#FFAAAA) >>
!define ForeignTable(name,desc) class name as "desc" << (T,#ada6a6) >>
!define TranslationTable(name,desc) class name as "desc" << (I,#4286f4) >>
' we use bold for primary key
' green color for unique
' and underscore for not_null
!define primary_key(x) <b>x</b>
!define unique(x) <color:green>x</color>
!define not_null(x) <u>x</u>
' other tags available:
' <i></i>
' <back:COLOR></color>, where color is a color name or html color code
' (#FFAACC)
' see: http://plantuml.com/classes.html#More
hide methods
hide stereotypes
hide empty members
skinparam backgroundColor #FFFFFF

' entities

Table(ShopwareCoreFrameworkAttributeAttributeDefinition, "attribute\n(Attribute configuration)") {
   primary_key(id) id
   not_null(name) string
   not_null(type) string
   config json
   attributeSetId foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreFrameworkAttributeAggregateAttributeSetAttributeSetDefinition, "attribute_set\n(Attribute set/group)") {
   primary_key(id) id
   not_null(name) string
   config json
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreFrameworkAttributeAggregateAttributeSetRelationAttributeSetRelationDefinition, "attribute_set_relation\n(Set to entity relation)") {
   primary_key(id) id
   not_null(attributeSetId) foreignKey
   not_null(entityName) string
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreFrameworkEventEventActionEventActionDefinition, "event_action\n(Configurable event handling)") {
   primary_key(id) id
   not_null(eventName) string
   not_null(actionName) string
   config json
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreFrameworkMessageQueueDeadMessageDeadMessageDefinition, "dead_message\n(Failing messages)") {
   primary_key(id) id
   not_null(originalMessageClass) longText
   not_null(serializedOriginalMessage) blob
   not_null(handlerClass) longText
   not_null(encrypted) bool
   not_null(errorCount) int
   not_null(nextExecutionTime) date
   not_null(exception) longText
   not_null(exceptionMessage) longText
   not_null(exceptionFile) longText
   not_null(exceptionLine) int
   scheduledTaskId foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreFrameworkMessageQueueMessageQueueStatsDefinition, "message_queue_stats\n(Stats)") {
   primary_key(id) id
   not_null(name) string
   not_null(size) int
}
Table(ShopwareCoreFrameworkPluginPluginDefinition, "plugin\n(Plugin)") {
   primary_key(id) id
   not_null(name) string
   composerName string
   not_null(autoload) json
   active bool
   managedByComposer bool
   path string
   author string
   copyright string
   license string
   not_null(version) string
   upgradeVersion string
   installedAt date
   upgradedAt date
   iconRaw blob
   icon string
   label translated
   description translated
   manufacturerLink translated
   supportLink translated
   changelog translated
   attributes translated
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   translated json
}
TranslationTable(ShopwareCoreFrameworkPluginAggregatePluginTranslationPluginTranslationDefinition, "plugin_translation\n((Translations))") {
   not_null(label) string
   description longText
   manufacturerLink string
   supportLink string
   changelog json
   attributes attributes
   primary_key(pluginId) foreignKey
   primary_key(languageId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreFrameworkScheduledTaskScheduledTaskDefinition, "scheduled_task\n(Cron job)") {
   primary_key(id) id
   not_null(name) string
   not_null(scheduledTaskClass) string
   not_null(runInterval) int
   not_null(status) string
   lastExecutionTime date
   not_null(nextExecutionTime) date
}
Table(ShopwareCoreFrameworkTagTagDefinition, "tag\n(Taxonomy)") {
   primary_key(id) id
   not_null(name) string
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreFrameworkLanguageLanguageDefinition, "language\n(Language)") {
   primary_key(id) id
   parentId parentFk
   not_null(localeId) foreignKey
   translationCodeId foreignKey
   not_null(name) string
   attributes attributes
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreSystemSalesChannelSalesChannelDefinition, "sales_channel\n(Sales Channel)") {
   primary_key(id) id
   not_null(typeId) foreignKey
   not_null(languageId) foreignKey
   not_null(customerGroupId) foreignKey
   not_null(currencyId) foreignKey
   not_null(paymentMethodId) foreignKey
   not_null(shippingMethodId) foreignKey
   not_null(countryId) foreignKey
   navigationId foreignKey
   navigationVersionId referenceVersion
   mailHeaderFooterId foreignKey
   name translated
   shortName string
   not_null(accessKey) string
   configuration json
   active bool
   taxCalculationType string
   attributes translated
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   translated json
}
TranslationTable(ShopwareCoreSystemSalesChannelAggregateSalesChannelTranslationSalesChannelTranslationDefinition, "sales_channel_translation\n((Translations))") {
   not_null(name) string
   attributes attributes
   primary_key(salesChannelId) foreignKey
   primary_key(languageId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreSystemSalesChannelAggregateSalesChannelCountrySalesChannelCountryDefinition, "sales_channel_country\n(M:N Mapping)") {
   primary_key(salesChannelId) foreignKey
   primary_key(countryId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreSystemSalesChannelAggregateSalesChannelCurrencySalesChannelCurrencyDefinition, "sales_channel_currency\n(M:N Mapping)") {
   primary_key(salesChannelId) foreignKey
   primary_key(currencyId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreSystemSalesChannelAggregateSalesChannelDomainSalesChannelDomainDefinition, "sales_channel_domain\n(Domain names of a sales channels)") {
   primary_key(id) id
   not_null(url) string
   not_null(salesChannelId) foreignKey
   not_null(languageId) foreignKey
   not_null(currencyId) foreignKey
   not_null(snippetSetId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   attributes attributes
}
Table(ShopwareCoreSystemSalesChannelAggregateSalesChannelLanguageSalesChannelLanguageDefinition, "sales_channel_language\n(M:N Mapping)") {
   primary_key(salesChannelId) foreignKey
   primary_key(languageId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreSystemSalesChannelAggregateSalesChannelPaymentMethodSalesChannelPaymentMethodDefinition, "sales_channel_payment_method\n(M:N Mapping)") {
   primary_key(salesChannelId) foreignKey
   primary_key(paymentMethodId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreSystemSalesChannelAggregateSalesChannelShippingMethodSalesChannelShippingMethodDefinition, "sales_channel_shipping_method\n(M:N Mapping)") {
   primary_key(salesChannelId) foreignKey
   primary_key(shippingMethodId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreSystemSalesChannelAggregateSalesChannelTypeSalesChannelTypeDefinition, "sales_channel_type\n(Type)") {
   primary_key(id) id
   coverUrl string
   iconName string
   screenshotUrls list
   name translated
   manufacturer translated
   description translated
   descriptionLong translated
   attributes translated
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   translated json
}
TranslationTable(ShopwareCoreSystemSalesChannelAggregateSalesChannelTypeTranslationSalesChannelTypeTranslationDefinition, "sales_channel_type_translation\n((Translations))") {
   not_null(name) string
   manufacturer string
   description string
   descriptionLong longTextWithHtml
   attributes attributes
   primary_key(salesChannelTypeId) foreignKey
   primary_key(languageId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreSystemCountryCountryDefinition, "country\n(Country)") {
   primary_key(id) id
   name translated
   iso string
   position int
   taxFree bool
   active bool
   iso3 string
   displayStateInRegistration bool
   forceStateInRegistration bool
   attributes translated
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   translated json
}
Table(ShopwareCoreSystemCountryAggregateCountryStateCountryStateDefinition, "country_state\n(A countries state)") {
   primary_key(id) id
   not_null(countryId) foreignKey
   not_null(shortCode) string
   name translated
   position int
   active bool
   attributes translated
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   translated json
}
TranslationTable(ShopwareCoreSystemCountryAggregateCountryStateTranslationCountryStateTranslationDefinition, "country_state_translation\n((Translations))") {
   not_null(name) string
   attributes attributes
   primary_key(countryStateId) foreignKey
   primary_key(languageId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
TranslationTable(ShopwareCoreSystemCountryAggregateCountryTranslationCountryTranslationDefinition, "country_translation\n((Translations))") {
   not_null(name) string
   attributes attributes
   primary_key(countryId) foreignKey
   primary_key(languageId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreSystemCurrencyCurrencyDefinition, "currency\n(Currency)") {
   primary_key(id) id
   not_null(factor) float
   not_null(symbol) string
   shortName translated
   name translated
   not_null(decimalPrecision) int
   position int
   isDefault bool
   attributes translated
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   translated json
}
TranslationTable(ShopwareCoreSystemCurrencyAggregateCurrencyTranslationCurrencyTranslationDefinition, "currency_translation\n((Translations))") {
   not_null(shortName) string
   not_null(name) string
   attributes attributes
   primary_key(currencyId) foreignKey
   primary_key(languageId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreSystemLocaleLocaleDefinition, "locale\n(A locale)") {
   primary_key(id) id
   not_null(code) string
   name translated
   territory translated
   attributes translated
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   translated json
}
TranslationTable(ShopwareCoreSystemLocaleAggregateLocaleTranslationLocaleTranslationDefinition, "locale_translation\n((Translations))") {
   not_null(name) string
   not_null(territory) string
   attributes attributes
   primary_key(localeId) foreignKey
   primary_key(languageId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreFrameworkSnippetAggregateSnippetSetSnippetSetDefinition, "snippet_set\n(Sets of snippets)") {
   primary_key(id) id
   not_null(name) string
   not_null(baseFile) string
   not_null(iso) string
   attributes attributes
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreFrameworkSnippetSnippetDefinition, "snippet\n(Translation Strings)") {
   primary_key(id) id
   not_null(setId) foreignKey
   not_null(translationKey) string
   not_null(value) longText
   not_null(author) string
   attributes attributes
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreSystemSalutationSalutationDefinition, "salutation\n(Salutation configuration)") {
   primary_key(id) id
   not_null(salutationKey) string
   displayName translated
   letterName translated
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   translated json
}
TranslationTable(ShopwareCoreSystemSalutationAggregateSalutationTranslationSalutationTranslationDefinition, "salutation_translation\n((Translations))") {
   not_null(displayName) string
   not_null(letterName) string
   primary_key(salutationId) foreignKey
   primary_key(languageId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreSystemTaxTaxDefinition, "tax\n(Available tax settings)") {
   primary_key(id) id
   not_null(taxRate) float
   not_null(name) string
   attributes attributes
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreSystemUnitUnitDefinition, "unit\n(Measuring unit)") {
   primary_key(id) id
   shortCode translated
   name translated
   attributes translated
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   translated json
}
TranslationTable(ShopwareCoreSystemUnitAggregateUnitTranslationUnitTranslationDefinition, "unit_translation\n((Translations))") {
   not_null(shortCode) string
   not_null(name) string
   attributes attributes
   primary_key(unitId) foreignKey
   primary_key(languageId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreSystemUserUserDefinition, "user\n(Administration/ Management Account user)") {
   primary_key(id) id
   not_null(localeId) foreignKey
   avatarId foreignKey
   not_null(username) string
   not_null(password) password
   not_null(firstName) string
   not_null(lastName) string
   not_null(email) string
   active bool
   attributes attributes
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   storeToken string
}
Table(ShopwareCoreSystemUserAggregateUserAccessKeyUserAccessKeyDefinition, "user_access_key\n(oAuth access key)") {
   primary_key(id) id
   not_null(userId) foreignKey
   not_null(accessKey) string
   not_null(secretAccessKey) password
   writeAccess bool
   lastUsageAt date
   attributes attributes
   not_null(createdAt) createdAt
}
Table(ShopwareCoreSystemUserAggregateUserRecoveryUserRecoveryDefinition, "user_recovery\n(User / Account recovery process)") {
   primary_key(id) id
   not_null(hash) string
   not_null(userId) foreignKey
   not_null(createdAt) createdAt
}
Table(ShopwareCoreSystemIntegrationIntegrationDefinition, "integration\n(O-Auth integration)") {
   primary_key(id) id
   not_null(label) string
   not_null(accessKey) string
   not_null(secretAccessKey) password
   writeAccess bool
   lastUsageAt date
   attributes attributes
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreSystemStateMachineStateMachineDefinition, "state_machine\n(State machine)") {
   primary_key(id) id
   not_null(technicalName) string
   name translated
   attributes translated
   initialStateId foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   translated json
}
TranslationTable(ShopwareCoreSystemStateMachineStateMachineTranslationDefinition, "state_machine_translation\n((Translations))") {
   not_null(name) string
   attributes attributes
   primary_key(stateMachineId) foreignKey
   primary_key(languageId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreSystemStateMachineAggregationStateMachineStateStateMachineStateDefinition, "state_machine_state\n(State)") {
   primary_key(id) id
   not_null(technicalName) string
   name translated
   not_null(stateMachineId) foreignKey
   attributes translated
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   translated json
}
TranslationTable(ShopwareCoreSystemStateMachineAggregationStateMachineStateStateMachineStateTranslationDefinition, "state_machine_state_translation\n((Translations))") {
   not_null(name) string
   attributes attributes
   primary_key(stateMachineStateId) foreignKey
   primary_key(languageId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreSystemStateMachineAggregationStateMachineTransitionStateMachineTransitionDefinition, "state_machine_transition\n(State transition)") {
   primary_key(id) id
   not_null(actionName) string
   not_null(stateMachineId) foreignKey
   not_null(fromStateId) foreignKey
   not_null(toStateId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   attributes attributes
}
Table(ShopwareCoreSystemStateMachineAggregationStateMachineHistoryStateMachineHistoryDefinition, "state_machine_history\n(State transition history)") {
   primary_key(id) id
   not_null(stateMachineId) foreignKey
   not_null(entityName) string
   not_null(entityId) json
   not_null(fromStateId) foreignKey
   not_null(toStateId) foreignKey
   transitionActionName string
   userId foreignKey
   not_null(createdAt) createdAt
}
Table(ShopwareCoreSystemSystemConfigSystemConfigDefinition, "system_config\n(System configuration)") {
   primary_key(id) id
   not_null(namespace) string
   not_null(configurationKey) string
   not_null(configurationValue) longText
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   salesChannelId foreignKey
}
Table(ShopwareCoreSystemNumberRangeNumberRangeDefinition, "number_range\n(Number range)") {
   primary_key(id) id
   not_null(typeId) foreignKey
   not_null(global) bool
   name translated
   description translated
   not_null(pattern) string
   start int
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   attributes translated
   translated json
}
Table(ShopwareCoreSystemNumberRangeAggregateNumberRangeSalesChannelNumberRangeSalesChannelDefinition, "number_range_sales_channel\n(M:N Mapping)") {
   primary_key(id) id
   not_null(numberRangeId) foreignKey
   not_null(salesChannelId) foreignKey
   numberRangeTypeId foreignKey
}
Table(ShopwareCoreSystemNumberRangeAggregateNumberRangeStateNumberRangeStateDefinition, "number_range_state\n(Current number range max value)") {
   primary_key(id) id
   not_null(numberRangeId) foreignKey
   not_null(lastValue) int
}
Table(ShopwareCoreSystemNumberRangeAggregateNumberRangeTypeNumberRangeTypeDefinition, "number_range_type\n(Type)") {
   primary_key(id) id
   technicalName string
   typeName translated
   not_null(global) bool
   attributes translated
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   translated json
}
TranslationTable(ShopwareCoreSystemNumberRangeAggregateNumberRangeTypeTranslationNumberRangeTypeTranslationDefinition, "number_range_type_translation\n((Translations))") {
   not_null(typeName) string
   attributes attributes
   primary_key(numberRangeTypeId) foreignKey
   primary_key(languageId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreContentCategoryCategoryDefinition, "category\n(Category tree)") {
   primary_key(id) id
   primary_key(versionId) version
   parentId parentFk
   not_null(parentVersionId) referenceVersion
   afterCategoryId foreignKey
   not_null(afterCategoryVersionId) referenceVersion
   mediaId foreignKey
   not_null(displayNestedProducts) bool
   autoIncrement int
   path treePath
   level treeLevel
   active bool
   childCount childCount
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   name translated
   attributes translated
   translated json
}
TranslationTable(ShopwareCoreContentCategoryAggregateCategoryTranslationCategoryTranslationDefinition, "category_translation\n((Translations))") {
   not_null(name) string
   attributes attributes
   primary_key(categoryId) foreignKey
   primary_key(languageId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   primary_key(categoryVersionId) referenceVersion
}
Table(ShopwareCoreContentCategoryAggregateCategoryTagCategoryTagDefinition, "category_tag\n(M:N Mapping)") {
   primary_key(categoryId) foreignKey
   primary_key(categoryVersionId) referenceVersion
   primary_key(tagId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreContentMediaMediaDefinition, "media\n(Media / Files)") {
   primary_key(id) id
   userId foreignKey
   mediaFolderId foreignKey
   mimeType string
   fileExtension string
   uploadedAt date
   fileName longText
   fileSize int
   metaDataRaw blob
   mediaTypeRaw blob
   metaData json
   mediaType json
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   alt translated
   title translated
   url string
   attributes translated
   thumbnailsRo blob
   hasFile bool
   translated json
}
Table(ShopwareCoreContentMediaAggregateMediaDefaultFolderMediaDefaultFolderDefinition, "media_default_folder\n(Default folders)") {
   primary_key(id) id
   not_null(associationFields) list
   not_null(entity) string
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   attributes attributes
}
Table(ShopwareCoreContentMediaAggregateMediaThumbnailMediaThumbnailDefinition, "media_thumbnail\n(Generated Thumbnail)") {
   primary_key(id) id
   not_null(mediaId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   not_null(width) int
   not_null(height) int
   url string
   attributes attributes
}
TranslationTable(ShopwareCoreContentMediaAggregateMediaTranslationMediaTranslationDefinition, "media_translation\n((Translations))") {
   title string
   alt longText
   attributes attributes
   primary_key(mediaId) foreignKey
   primary_key(languageId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreContentMediaAggregateMediaFolderMediaFolderDefinition, "media_folder\n(Folder structure)") {
   primary_key(id) id
   useParentConfiguration bool
   not_null(configurationId) foreignKey
   defaultFolderId foreignKey
   parentId parentFk
   childCount childCount
   not_null(name) string
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   attributes attributes
}
Table(ShopwareCoreContentMediaAggregateMediaThumbnailSizeMediaThumbnailSizeDefinition, "media_thumbnail_size\n(Generated Thumbnails)") {
   primary_key(id) id
   not_null(width) int
   not_null(height) int
   attributes attributes
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreContentMediaAggregateMediaFolderConfigurationMediaFolderConfigurationDefinition, "media_folder_configuration\n(Configuration)") {
   primary_key(id) id
   createThumbnails bool
   keepAspectRatio bool
   thumbnailQuality int
   mediaThumbnailSizesRo blob
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   attributes attributes
}
Table(ShopwareCoreContentMediaAggregateMediaFolderConfigurationMediaThumbnailSizeMediaFolderConfigurationMediaThumbnailSizeDefinition, "media_folder_configuration_media_thumbnail_size\n(M:N Mapping)") {
   primary_key(mediaFolderConfigurationId) foreignKey
   primary_key(mediaThumbnailSizeId) foreignKey
   not_null(createdAt) createdAt
}
Table(ShopwareCoreContentMediaAggregateMediaTagMediaTagDefinition, "media_tag\n(M:N Mapping)") {
   primary_key(mediaId) foreignKey
   primary_key(tagId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreContentProductProductDefinition, "product\n(Product)") {
   primary_key(id) id
   primary_key(versionId) version
   parentId parentFk
   not_null(parentVersionId) referenceVersion
   blacklistIds blacklistRule
   whitelistIds whitelistRule
   autoIncrement int
   active bool
   not_null(stock) int
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   not_null(manufacturerId) foreignKey
   not_null(productManufacturerVersionId) referenceVersion
   unitId foreignKey
   not_null(taxId) foreignKey
   coverId foreignKey
   productMediaVersionId referenceVersion
   not_null(price) price
   listingPrices priceRulesJson
   manufacturerNumber string
   ean string
   productNumber numberRange
   isCloseout bool
   purchaseSteps int
   maxPurchase int
   minPurchase int
   purchaseUnit float
   referenceUnit float
   shippingFree bool
   purchasePrice float
   markAsTopseller bool
   weight float
   width float
   height float
   length float
   releaseDate date
   categoryTree list
   propertyIds list
   optionIds list
   minDeliveryTime int
   maxDeliveryTime int
   restockTime int
   tagIds list
   additionalText translated
   name translated
   keywords translated
   description translated
   metaTitle translated
   packUnit translated
   attributes translated
   translated json
}
Table(ShopwareCoreContentProductAggregateProductCategoryProductCategoryDefinition, "product_category\n(M:N Mapping)") {
   primary_key(productId) foreignKey
   primary_key(productVersionId) referenceVersion
   primary_key(categoryId) foreignKey
   primary_key(categoryVersionId) referenceVersion
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreContentProductAggregateProductTagProductTagDefinition, "product_tag\n(M:N Mapping)") {
   primary_key(productId) foreignKey
   primary_key(productVersionId) referenceVersion
   primary_key(tagId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreContentProductAggregateProductConfiguratorSettingProductConfiguratorSettingDefinition, "product_configurator_setting\n(The root product configurator.)") {
   primary_key(id) id
   primary_key(versionId) version
   not_null(productId) foreignKey
   not_null(productVersionId) referenceVersion
   not_null(optionId) foreignKey
   price price
   prices priceRulesJson
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   attributes attributes
}
Table(ShopwareCoreContentProductAggregateProductPriceProductPriceDefinition, "product_price\n(Staggered pricing)") {
   primary_key(id) id
   primary_key(versionId) version
   not_null(productId) foreignKey
   not_null(productVersionId) referenceVersion
   not_null(currencyId) foreignKey
   not_null(ruleId) foreignKey
   not_null(price) price
   not_null(quantityStart) int
   quantityEnd int
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   attributes attributes
}
Table(ShopwareCoreContentProductAggregateProductPropertyProductPropertyDefinition, "product_property\n(M:N Mapping)") {
   primary_key(productId) foreignKey
   not_null(productVersionId) referenceVersion
   primary_key(optionId) foreignKey
}
Table(ShopwareCoreContentProductAggregateProductManufacturerProductManufacturerDefinition, "product_manufacturer\n(Manufacturer)") {
   primary_key(id) id
   primary_key(versionId) version
   mediaId foreignKey
   link string
   not_null(updatedAt) updatedAt
   not_null(createdAt) createdAt
   name translated
   description translated
   attributes translated
   translated json
}
TranslationTable(ShopwareCoreContentProductAggregateProductManufacturerTranslationProductManufacturerTranslationDefinition, "product_manufacturer_translation\n((Translations))") {
   not_null(name) string
   description longTextWithHtml
   attributes attributes
   primary_key(productManufacturerId) foreignKey
   primary_key(languageId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   primary_key(productManufacturerVersionId) referenceVersion
}
Table(ShopwareCoreContentProductAggregateProductMediaProductMediaDefinition, "product_media\n(Product media/images)") {
   primary_key(id) id
   primary_key(versionId) version
   not_null(productId) foreignKey
   not_null(productVersionId) referenceVersion
   not_null(mediaId) foreignKey
   position int
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   attributes attributes
}
Table(ShopwareCoreFrameworkSearchSearchDocumentDefinition, "search_document\n(Composite search)") {
   primary_key(id) id
   primary_key(languageId) foreignKey
   primary_key(entityId) id
   not_null(entity) string
   not_null(keyword) string
   not_null(ranking) float
   attributes attributes
}
TranslationTable(ShopwareCoreContentProductAggregateProductTranslationProductTranslationDefinition, "product_translation\n((Translations))") {
   additionalText string
   name string
   keywords longText
   description longTextWithHtml
   metaTitle string
   packUnit string
   attributes attributes
   primary_key(productId) foreignKey
   primary_key(languageId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   primary_key(productVersionId) referenceVersion
}
Table(ShopwareCoreContentProductAggregateProductOptionProductOptionDefinition, "product_option\n(M:N Mapping)") {
   primary_key(productId) foreignKey
   not_null(productVersionId) referenceVersion
   primary_key(optionId) foreignKey
}
Table(ShopwareCoreContentProductAggregateProductCategoryTreeProductCategoryTreeDefinition, "product_category_tree\n(M:N Mapping)") {
   primary_key(productId) foreignKey
   primary_key(productVersionId) referenceVersion
   primary_key(categoryId) foreignKey
   primary_key(categoryVersionId) referenceVersion
}
Table(ShopwareCoreContentProductAggregateProductVisibilityProductVisibilityDefinition, "product_visibility\n(Visibility in sales channels)") {
   primary_key(id) id
   not_null(productId) foreignKey
   not_null(productVersionId) referenceVersion
   not_null(salesChannelId) foreignKey
   not_null(visibility) int
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreContentNavigationNavigationDefinition, "navigation\n(SalesChannel Navigation)") {
   primary_key(id) id
   primary_key(versionId) version
   parentId parentFk
   not_null(parentVersionId) referenceVersion
   categoryId foreignKey
   categoryVersionId referenceVersion
   cmsPageId foreignKey
   name translated
   slotConfig translated
   level treeLevel
   path treePath
   childCount childCount
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   translated json
}
TranslationTable(ShopwareCoreContentNavigationAggregateNavigationTranslationNavigationTranslationDefinition, "navigation_translation\n((Translations))") {
   not_null(name) string
   slotConfig json
   primary_key(navigationId) foreignKey
   primary_key(languageId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   primary_key(navigationVersionId) referenceVersion
}
Table(ShopwareCoreContentRuleRuleDefinition, "rule\n(Rule)") {
   primary_key(id) id
   not_null(name) string
   not_null(priority) int
   description longText
   payload blob
   invalid bool
   attributes attributes
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   moduleTypes json
}
Table(ShopwareCoreContentRuleAggregateRuleConditionRuleConditionDefinition, "rule_condition\n(Rule condition)") {
   primary_key(id) id
   type string
   not_null(ruleId) foreignKey
   parentId parentFk
   value json
   position int
   attributes attributes
}
Table(ShopwareCoreContentProductStreamProductStreamDefinition, "product_stream\n(Product streams)") {
   primary_key(id) id
   apiFilter json
   invalid bool
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   name translated
   description translated
   attributes translated
   translated json
}
TranslationTable(ShopwareCoreContentProductStreamAggregateProductStreamTranslationProductStreamTranslationDefinition, "product_stream_translation\n((Translations))") {
   not_null(name) string
   description longText
   attributes attributes
   primary_key(productStreamId) foreignKey
   primary_key(languageId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreContentProductStreamAggregateProductStreamFilterProductStreamFilterDefinition, "product_stream_filter\n(A Product stream filter term)") {
   primary_key(id) id
   not_null(productStreamId) foreignKey
   parentId parentFk
   not_null(type) string
   field string
   operator string
   value longText
   parameters json
   position int
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   attributes attributes
}
Table(ShopwareCoreContentPropertyPropertyGroupDefinition, "property_group\n(__EMPTY__)") {
   primary_key(id) id
   name translated
   description translated
   not_null(displayType) string
   not_null(sortingType) string
   attributes translated
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   translated json
}
Table(ShopwareCoreContentPropertyAggregatePropertyGroupOptionPropertyGroupOptionDefinition, "property_group_option\n(__EMPTY__)") {
   primary_key(id) id
   not_null(groupId) foreignKey
   name translated
   position translated
   colorHexCode string
   mediaId foreignKey
   attributes translated
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   translated json
}
TranslationTable(ShopwareCoreContentPropertyAggregatePropertyGroupOptionTranslationPropertyGroupOptionTranslationDefinition, "property_group_option_translation\n((Translations))") {
   not_null(name) string
   position int
   attributes attributes
   primary_key(propertyGroupOptionId) foreignKey
   primary_key(languageId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
TranslationTable(ShopwareCoreContentPropertyAggregatePropertyGroupTranslationPropertyGroupTranslationDefinition, "property_group_translation\n((Translations))") {
   not_null(name) string
   description longText
   attributes attributes
   primary_key(propertyGroupId) foreignKey
   primary_key(languageId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreCheckoutCustomerCustomerDefinition, "customer\n(The sales channel customer)") {
   primary_key(id) id
   not_null(groupId) foreignKey
   not_null(defaultPaymentMethodId) foreignKey
   not_null(salesChannelId) foreignKey
   not_null(languageId) foreignKey
   lastPaymentMethodId foreignKey
   not_null(defaultBillingAddressId) foreignKey
   not_null(defaultShippingAddressId) foreignKey
   autoIncrement int
   not_null(customerNumber) numberRange
   not_null(salutationId) foreignKey
   not_null(firstName) string
   not_null(lastName) string
   company string
   password password
   not_null(email) string
   title string
   active bool
   guest bool
   firstLogin date
   lastLogin date
   newsletter bool
   birthday date
   attributes attributes
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   legacyPassword string
   legacyEncoder string
}
TranslationTable(ShopwareCoreCheckoutCustomerAggregateCustomerGroupTranslationCustomerGroupTranslationDefinition, "customer_group_translation\n((Translations))") {
   not_null(name) string
   attributes attributes
   primary_key(customerGroupId) foreignKey
   primary_key(languageId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreCheckoutCustomerAggregateCustomerAddressCustomerAddressDefinition, "customer_address\n(The customer addresses.)") {
   primary_key(id) id
   not_null(customerId) foreignKey
   not_null(countryId) foreignKey
   countryStateId foreignKey
   not_null(salutationId) foreignKey
   not_null(firstName) string
   not_null(lastName) string
   not_null(zipcode) string
   not_null(city) string
   company string
   not_null(street) string
   department string
   title string
   vatId string
   phoneNumber string
   additionalAddressLine1 string
   additionalAddressLine2 string
   attributes attributes
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreCheckoutCustomerAggregateCustomerGroupCustomerGroupDefinition, "customer_group\n(Customer groups)") {
   primary_key(id) id
   name translated
   displayGross bool
   attributes translated
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   translated json
}
Table(ShopwareCoreCheckoutCustomerAggregateCustomerTagCustomerTagDefinition, "customer_tag\n(M:N Mapping)") {
   primary_key(customerId) foreignKey
   primary_key(tagId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreCheckoutOrderOrderDefinition, "order\n(Order root table)") {
   primary_key(id) id
   primary_key(versionId) version
   autoIncrement int
   orderNumber numberRange
   not_null(billingAddressId) foreignKey
   not_null(billingAddressVersionId) referenceVersion
   not_null(currencyId) foreignKey
   not_null(salesChannelId) foreignKey
   not_null(orderDate) date
   price cartPrice
   amountTotal float
   amountNet float
   positionPrice float
   taxStatus string
   shippingCosts calculatedPrice
   shippingTotal float
   not_null(currencyFactor) float
   deepLinkCode string
   not_null(stateId) foreignKey
   attributes attributes
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreCheckoutOrderAggregateOrderAddressOrderAddressDefinition, "order_address\n(Order address)") {
   primary_key(id) id
   primary_key(versionId) version
   not_null(countryId) foreignKey
   countryStateId foreignKey
   not_null(orderId) foreignKey
   not_null(orderVersionId) referenceVersion
   not_null(salutationId) foreignKey
   not_null(firstName) string
   not_null(lastName) string
   not_null(street) string
   not_null(zipcode) string
   not_null(city) string
   company string
   department string
   title string
   vatId string
   phoneNumber string
   additionalAddressLine1 string
   additionalAddressLine2 string
   attributes attributes
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreCheckoutOrderAggregateOrderCustomerOrderCustomerDefinition, "order_customer\n(Order customer)") {
   primary_key(id) id
   primary_key(versionId) version
   customerId foreignKey
   not_null(orderId) foreignKey
   not_null(orderVersionId) referenceVersion
   not_null(email) string
   not_null(salutationId) foreignKey
   not_null(firstName) string
   not_null(lastName) string
   title string
   customerNumber string
   attributes attributes
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreCheckoutOrderAggregateOrderDeliveryOrderDeliveryDefinition, "order_delivery\n(Delivery)") {
   primary_key(id) id
   primary_key(versionId) version
   not_null(orderId) foreignKey
   not_null(orderVersionId) referenceVersion
   not_null(shippingOrderAddressId) foreignKey
   not_null(shippingOrderAddressVersionId) referenceVersion
   not_null(shippingMethodId) foreignKey
   not_null(stateId) foreignKey
   trackingCode string
   not_null(shippingDateEarliest) date
   not_null(shippingDateLatest) date
   shippingCosts calculatedPrice
   attributes attributes
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreCheckoutOrderAggregateOrderDeliveryPositionOrderDeliveryPositionDefinition, "order_delivery_position\n(Delivery position)") {
   primary_key(id) id
   primary_key(versionId) version
   not_null(orderDeliveryId) foreignKey
   not_null(orderDeliveryVersionId) referenceVersion
   not_null(orderLineItemId) foreignKey
   not_null(orderLineItemVersionId) referenceVersion
   price calculatedPrice
   unitPrice float
   totalPrice float
   quantity int
   attributes attributes
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreCheckoutOrderAggregateOrderLineItemOrderLineItemDefinition, "order_line_item\n(Order line item)") {
   primary_key(id) id
   primary_key(versionId) version
   not_null(orderId) foreignKey
   not_null(orderVersionId) referenceVersion
   parentId parentFk
   not_null(parentVersionId) referenceVersion
   not_null(identifier) string
   not_null(quantity) int
   not_null(label) string
   payload json
   good bool
   removable bool
   stackable bool
   priority int
   not_null(price) calculatedPrice
   not_null(priceDefinition) priceDefinition
   unitPrice float
   totalPrice float
   description string
   type string
   attributes attributes
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreCheckoutOrderAggregateOrderTagOrderTagDefinition, "order_tag\n(M:N Mapping)") {
   primary_key(orderId) foreignKey
   primary_key(orderVersionId) referenceVersion
   primary_key(tagId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreCheckoutOrderAggregateOrderTransactionOrderTransactionDefinition, "order_transaction\n(Order transaction)") {
   primary_key(id) id
   primary_key(versionId) version
   not_null(orderId) foreignKey
   not_null(orderVersionId) referenceVersion
   not_null(paymentMethodId) foreignKey
   not_null(amount) calculatedPrice
   not_null(stateId) foreignKey
   attributes attributes
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreCheckoutPaymentPaymentMethodDefinition, "payment_method\n(Payment method)") {
   primary_key(id) id
   pluginId foreignKey
   handlerIdentifier string
   name translated
   description translated
   position int
   active bool
   attributes translated
   availabilityRuleIds list
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   translated json
}
TranslationTable(ShopwareCoreCheckoutPaymentAggregatePaymentMethodTranslationPaymentMethodTranslationDefinition, "payment_method_translation\n((Translations))") {
   not_null(name) string
   description longText
   attributes attributes
   primary_key(paymentMethodId) foreignKey
   primary_key(languageId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreCheckoutPaymentAggregatePaymentMethodRulesPaymentMethodRuleDefinition, "payment_method_rule\n(M:N Mapping)") {
   primary_key(paymentMethodId) foreignKey
   primary_key(ruleId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreCheckoutShippingShippingMethodDefinition, "shipping_method\n(Shipping method)") {
   primary_key(id) id
   not_null(bindShippingfree) bool
   name translated
   active bool
   shippingFree float
   attributes translated
   availabilityRuleId foreignKey
   mediaId foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   not_null(deliveryTimeId) foreignKey
   description translated
   translated json
}
Table(ShopwareCoreCheckoutShippingAggregateShippingMethodTagShippingMethodTagDefinition, "shipping_method_tag\n(M:N Mapping)") {
   primary_key(shippingMethodId) foreignKey
   primary_key(tagId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreCheckoutShippingAggregateShippingMethodPriceShippingMethodPriceDefinition, "shipping_method_price\n(Prices of a shipping method)") {
   primary_key(id) id
   not_null(shippingMethodId) foreignKey
   not_null(currencyId) foreignKey
   ruleId foreignKey
   calculation int
   calculationRuleId foreignKey
   quantityStart float
   quantityEnd float
   not_null(price) float
   attributes attributes
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
TranslationTable(ShopwareCoreCheckoutShippingAggregateShippingMethodTranslationShippingMethodTranslationDefinition, "shipping_method_translation\n((Translations))") {
   not_null(name) string
   description longText
   attributes attributes
   primary_key(shippingMethodId) foreignKey
   primary_key(languageId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreCheckoutDiscountSurchargeDiscountSurchargeDefinition, "discount_surcharge\n(Discounts/Surcharges)") {
   primary_key(id) id
   name translated
   not_null(ruleId) foreignKey
   not_null(type) string
   not_null(amount) float
   attributes translated
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   translated json
}
TranslationTable(ShopwareCoreCheckoutDiscountSurchargeAggregateDiscountSurchargeTranslationDiscountSurchargeTranslationDefinition, "discount_surcharge_translation\n((Translations))") {
   not_null(name) string
   attributes attributes
   primary_key(discountSurchargeId) foreignKey
   primary_key(languageId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareStorefrontFrameworkSeoSeoUrlSeoUrlDefinition, "seo_url\n(Seo urls)") {
   primary_key(id) id
   not_null(salesChannelId) foreignKey
   not_null(foreignKey) id
   not_null(routeName) string
   not_null(pathInfo) string
   not_null(seoPathInfo) string
   isCanonical bool
   isModified bool
   isDeleted bool
   isValid bool
   autoIncrement int
   attributes attributes
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   url string
}
Table(ShopwareStorefrontFrameworkSeoSeoUrlTemplateSeoUrlTemplateDefinition, "seo_url_template\n(Template)") {
   primary_key(id) id
   salesChannelId foreignKey
   not_null(entityName) string
   not_null(routeName) string
   not_null(template) string
   isValid bool
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   attributes attributes
}
ForeignTable(ShopwareCoreContentNewsletterReceiverNewsletterReceiverDefinition, "newsletter_receiver") {
}
ForeignTable(ShopwareCoreContentCmsAggregateCmsPageTranslationCmsPageTranslationDefinition, "cms_page_translation") {
}
ForeignTable(ShopwareCoreContentCmsAggregateCmsSlotTranslationCmsSlotTranslationDefinition, "cms_slot_translation") {
}
ForeignTable(ShopwareCoreContentMailTemplateAggregateMailTemplateTranslationMailTemplateTranslationDefinition, "mail_template_translation") {
}
ForeignTable(ShopwareCoreContentMailTemplateAggregateMailHeaderFooterTranslationMailHeaderFooterTranslationDefinition, "mail_header_footer_translation") {
}
ForeignTable(ShopwareCoreContentDeliveryTimeAggregateDeliveryTimeTranslationDeliveryTimeTranslationDefinition, "delivery_time_translation") {
}
ForeignTable(ShopwareCoreContentMailTemplateAggregateMailHeaderFooterMailHeaderFooterDefinition, "mail_header_footer") {
}
ForeignTable(ShopwareCoreContentMailTemplateAggregateMailTemplateSalesChannelMailTemplateSalesChannelDefinition, "mail_template_sales_channel") {
}
ForeignTable(ShopwareCoreCheckoutPromotionAggregatePromotionSalesChannelPromotionSalesChannelDefinition, "promotion_sales_channel") {
}
ForeignTable(ShopwareCoreSystemNumberRangeAggregateNumberRangeTranslationNumberRangeTranslationDefinition, "number_range_translation") {
}
ForeignTable(ShopwareCoreContentMailTemplateAggregateMailTemplateMediaMailTemplateMediaDefinition, "mail_template_media") {
}
ForeignTable(ShopwareCoreContentCmsCmsPageDefinition, "cms_page") {
}
ForeignTable(ShopwareCoreCheckoutPromotionPromotionDefinition, "promotion") {
}
ForeignTable(ShopwareCoreCheckoutDocumentDocumentDefinition, "document") {
}
ForeignTable(ShopwareCoreContentDeliveryTimeDeliveryTimeDefinition, "delivery_time") {
}

' relationshipd

ShopwareCoreFrameworkAttributeAggregateAttributeSetAttributeSetDefinition --> ShopwareCoreFrameworkAttributeAttributeDefinition
ShopwareCoreFrameworkAttributeAggregateAttributeSetRelationAttributeSetRelationDefinition --> ShopwareCoreFrameworkAttributeAggregateAttributeSetAttributeSetDefinition
ShopwareCoreFrameworkScheduledTaskScheduledTaskDefinition --> ShopwareCoreFrameworkMessageQueueDeadMessageDeadMessageDefinition
ShopwareCoreFrameworkPluginAggregatePluginTranslationPluginTranslationDefinition --> ShopwareCoreFrameworkPluginPluginDefinition
ShopwareCoreCheckoutPaymentPaymentMethodDefinition --> ShopwareCoreFrameworkPluginPluginDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreFrameworkPluginAggregatePluginTranslationPluginTranslationDefinition
ShopwareCoreContentProductAggregateProductTagProductTagDefinition --> ShopwareCoreFrameworkTagTagDefinition
ShopwareCoreContentMediaAggregateMediaTagMediaTagDefinition --> ShopwareCoreFrameworkTagTagDefinition
ShopwareCoreContentCategoryAggregateCategoryTagCategoryTagDefinition --> ShopwareCoreFrameworkTagTagDefinition
ShopwareCoreCheckoutCustomerAggregateCustomerTagCustomerTagDefinition --> ShopwareCoreFrameworkTagTagDefinition
ShopwareCoreCheckoutOrderAggregateOrderTagOrderTagDefinition --> ShopwareCoreFrameworkTagTagDefinition
ShopwareCoreCheckoutShippingAggregateShippingMethodTagShippingMethodTagDefinition --> ShopwareCoreFrameworkTagTagDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreSystemLocaleLocaleDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreSystemSalesChannelAggregateSalesChannelLanguageSalesChannelLanguageDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreSystemSalesChannelSalesChannelDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreSystemSalesChannelAggregateSalesChannelDomainSalesChannelDomainDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreCheckoutCustomerCustomerDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreContentNewsletterReceiverNewsletterReceiverDefinition
ShopwareCoreContentCategoryAggregateCategoryTranslationCategoryTranslationDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreSystemCountryAggregateCountryStateTranslationCountryStateTranslationDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreSystemCountryAggregateCountryTranslationCountryTranslationDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreSystemCurrencyAggregateCurrencyTranslationCurrencyTranslationDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreCheckoutCustomerAggregateCustomerGroupTranslationCustomerGroupTranslationDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreSystemLocaleAggregateLocaleTranslationLocaleTranslationDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreContentMediaAggregateMediaTranslationMediaTranslationDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreCheckoutPaymentAggregatePaymentMethodTranslationPaymentMethodTranslationDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreContentProductAggregateProductManufacturerTranslationProductManufacturerTranslationDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreContentProductAggregateProductTranslationProductTranslationDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreCheckoutShippingAggregateShippingMethodTranslationShippingMethodTranslationDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreSystemUnitAggregateUnitTranslationUnitTranslationDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreContentPropertyAggregatePropertyGroupTranslationPropertyGroupTranslationDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreContentPropertyAggregatePropertyGroupOptionTranslationPropertyGroupOptionTranslationDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreCheckoutDiscountSurchargeAggregateDiscountSurchargeTranslationDiscountSurchargeTranslationDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreSystemSalesChannelAggregateSalesChannelTranslationSalesChannelTranslationDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreSystemSalesChannelAggregateSalesChannelTypeTranslationSalesChannelTypeTranslationDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreSystemSalutationAggregateSalutationTranslationSalutationTranslationDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreFrameworkSearchSearchDocumentDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreContentProductStreamAggregateProductStreamTranslationProductStreamTranslationDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreSystemStateMachineStateMachineTranslationDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreSystemStateMachineAggregationStateMachineStateStateMachineStateTranslationDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreContentCmsAggregateCmsPageTranslationCmsPageTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreContentCmsAggregateCmsSlotTranslationCmsSlotTranslationDefinition
ShopwareCoreContentNavigationAggregateNavigationTranslationNavigationTranslationDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreContentMailTemplateAggregateMailTemplateTranslationMailTemplateTranslationDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreContentMailTemplateAggregateMailHeaderFooterTranslationMailHeaderFooterTranslationDefinition
ShopwareCoreSystemNumberRangeAggregateNumberRangeTypeTranslationNumberRangeTypeTranslationDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreFrameworkLanguageLanguageDefinition --> ShopwareCoreContentDeliveryTimeAggregateDeliveryTimeTranslationDeliveryTimeTranslationDefinition
ShopwareCoreSystemSalesChannelAggregateSalesChannelTypeSalesChannelTypeDefinition --> ShopwareCoreSystemSalesChannelSalesChannelDefinition
ShopwareCoreSystemSalesChannelAggregateSalesChannelTranslationSalesChannelTranslationDefinition --> ShopwareCoreSystemSalesChannelSalesChannelDefinition
ShopwareCoreSystemSalesChannelAggregateSalesChannelCurrencySalesChannelCurrencyDefinition --> ShopwareCoreSystemSalesChannelSalesChannelDefinition
ShopwareCoreSystemSalesChannelAggregateSalesChannelLanguageSalesChannelLanguageDefinition --> ShopwareCoreSystemSalesChannelSalesChannelDefinition
ShopwareCoreSystemSalesChannelAggregateSalesChannelCountrySalesChannelCountryDefinition --> ShopwareCoreSystemSalesChannelSalesChannelDefinition
ShopwareCoreSystemSalesChannelAggregateSalesChannelPaymentMethodSalesChannelPaymentMethodDefinition --> ShopwareCoreSystemSalesChannelSalesChannelDefinition
ShopwareCoreSystemSalesChannelAggregateSalesChannelShippingMethodSalesChannelShippingMethodDefinition --> ShopwareCoreSystemSalesChannelSalesChannelDefinition
ShopwareCoreCheckoutCustomerAggregateCustomerGroupCustomerGroupDefinition --> ShopwareCoreSystemSalesChannelSalesChannelDefinition
ShopwareCoreSystemCurrencyCurrencyDefinition --> ShopwareCoreSystemSalesChannelSalesChannelDefinition
ShopwareCoreCheckoutPaymentPaymentMethodDefinition --> ShopwareCoreSystemSalesChannelSalesChannelDefinition
ShopwareCoreCheckoutShippingShippingMethodDefinition --> ShopwareCoreSystemSalesChannelSalesChannelDefinition
ShopwareCoreSystemCountryCountryDefinition --> ShopwareCoreSystemSalesChannelSalesChannelDefinition
ShopwareCoreCheckoutOrderOrderDefinition --> ShopwareCoreSystemSalesChannelSalesChannelDefinition
ShopwareCoreCheckoutCustomerCustomerDefinition --> ShopwareCoreSystemSalesChannelSalesChannelDefinition
ShopwareCoreSystemSalesChannelAggregateSalesChannelDomainSalesChannelDomainDefinition --> ShopwareCoreSystemSalesChannelSalesChannelDefinition
ShopwareCoreSystemSystemConfigSystemConfigDefinition --> ShopwareCoreSystemSalesChannelSalesChannelDefinition
ShopwareCoreContentNavigationNavigationDefinition --> ShopwareCoreSystemSalesChannelSalesChannelDefinition
ShopwareCoreContentProductAggregateProductVisibilityProductVisibilityDefinition --> ShopwareCoreSystemSalesChannelSalesChannelDefinition
ShopwareCoreSystemSalesChannelSalesChannelDefinition --> ShopwareCoreContentMailTemplateAggregateMailHeaderFooterMailHeaderFooterDefinition
ShopwareCoreSystemSalesChannelSalesChannelDefinition --> ShopwareCoreContentNewsletterReceiverNewsletterReceiverDefinition
ShopwareCoreSystemSalesChannelSalesChannelDefinition --> ShopwareCoreContentMailTemplateAggregateMailTemplateSalesChannelMailTemplateSalesChannelDefinition
ShopwareCoreSystemNumberRangeAggregateNumberRangeSalesChannelNumberRangeSalesChannelDefinition --> ShopwareCoreSystemSalesChannelSalesChannelDefinition
ShopwareCoreSystemSalesChannelSalesChannelDefinition --> ShopwareCoreCheckoutPromotionAggregatePromotionSalesChannelPromotionSalesChannelDefinition
ShopwareStorefrontFrameworkSeoSeoUrlSeoUrlDefinition --> ShopwareCoreSystemSalesChannelSalesChannelDefinition
ShopwareStorefrontFrameworkSeoSeoUrlTemplateSeoUrlTemplateDefinition --> ShopwareCoreSystemSalesChannelSalesChannelDefinition
ShopwareCoreSystemCountryCountryDefinition --> ShopwareCoreSystemSalesChannelAggregateSalesChannelCountrySalesChannelCountryDefinition
ShopwareCoreSystemCurrencyCurrencyDefinition --> ShopwareCoreSystemSalesChannelAggregateSalesChannelCurrencySalesChannelCurrencyDefinition
ShopwareCoreSystemCurrencyCurrencyDefinition --> ShopwareCoreSystemSalesChannelAggregateSalesChannelDomainSalesChannelDomainDefinition
ShopwareCoreFrameworkSnippetAggregateSnippetSetSnippetSetDefinition --> ShopwareCoreSystemSalesChannelAggregateSalesChannelDomainSalesChannelDomainDefinition
ShopwareCoreCheckoutPaymentPaymentMethodDefinition --> ShopwareCoreSystemSalesChannelAggregateSalesChannelPaymentMethodSalesChannelPaymentMethodDefinition
ShopwareCoreCheckoutShippingShippingMethodDefinition --> ShopwareCoreSystemSalesChannelAggregateSalesChannelShippingMethodSalesChannelShippingMethodDefinition
ShopwareCoreSystemSalesChannelAggregateSalesChannelTypeTranslationSalesChannelTypeTranslationDefinition --> ShopwareCoreSystemSalesChannelAggregateSalesChannelTypeSalesChannelTypeDefinition
ShopwareCoreSystemCountryAggregateCountryStateCountryStateDefinition --> ShopwareCoreSystemCountryCountryDefinition
ShopwareCoreSystemCountryAggregateCountryTranslationCountryTranslationDefinition --> ShopwareCoreSystemCountryCountryDefinition
ShopwareCoreCheckoutCustomerAggregateCustomerAddressCustomerAddressDefinition --> ShopwareCoreSystemCountryCountryDefinition
ShopwareCoreCheckoutOrderAggregateOrderAddressOrderAddressDefinition --> ShopwareCoreSystemCountryCountryDefinition
ShopwareCoreSystemCountryAggregateCountryStateTranslationCountryStateTranslationDefinition --> ShopwareCoreSystemCountryAggregateCountryStateCountryStateDefinition
ShopwareCoreCheckoutCustomerAggregateCustomerAddressCustomerAddressDefinition --> ShopwareCoreSystemCountryAggregateCountryStateCountryStateDefinition
ShopwareCoreCheckoutOrderAggregateOrderAddressOrderAddressDefinition --> ShopwareCoreSystemCountryAggregateCountryStateCountryStateDefinition
ShopwareCoreSystemCurrencyAggregateCurrencyTranslationCurrencyTranslationDefinition --> ShopwareCoreSystemCurrencyCurrencyDefinition
ShopwareCoreCheckoutOrderOrderDefinition --> ShopwareCoreSystemCurrencyCurrencyDefinition
ShopwareCoreContentProductAggregateProductPriceProductPriceDefinition --> ShopwareCoreSystemCurrencyCurrencyDefinition
ShopwareCoreCheckoutShippingAggregateShippingMethodPriceShippingMethodPriceDefinition --> ShopwareCoreSystemCurrencyCurrencyDefinition
ShopwareCoreSystemLocaleAggregateLocaleTranslationLocaleTranslationDefinition --> ShopwareCoreSystemLocaleLocaleDefinition
ShopwareCoreSystemUserUserDefinition --> ShopwareCoreSystemLocaleLocaleDefinition
ShopwareCoreFrameworkSnippetSnippetDefinition --> ShopwareCoreFrameworkSnippetAggregateSnippetSetSnippetSetDefinition
ShopwareCoreSystemSalutationAggregateSalutationTranslationSalutationTranslationDefinition --> ShopwareCoreSystemSalutationSalutationDefinition
ShopwareCoreCheckoutCustomerCustomerDefinition --> ShopwareCoreSystemSalutationSalutationDefinition
ShopwareCoreCheckoutCustomerAggregateCustomerAddressCustomerAddressDefinition --> ShopwareCoreSystemSalutationSalutationDefinition
ShopwareCoreCheckoutOrderAggregateOrderCustomerOrderCustomerDefinition --> ShopwareCoreSystemSalutationSalutationDefinition
ShopwareCoreCheckoutOrderAggregateOrderAddressOrderAddressDefinition --> ShopwareCoreSystemSalutationSalutationDefinition
ShopwareCoreSystemSalutationSalutationDefinition --> ShopwareCoreContentNewsletterReceiverNewsletterReceiverDefinition
ShopwareCoreContentProductProductDefinition --> ShopwareCoreSystemTaxTaxDefinition
ShopwareCoreContentProductProductDefinition --> ShopwareCoreSystemUnitUnitDefinition
ShopwareCoreSystemUnitAggregateUnitTranslationUnitTranslationDefinition --> ShopwareCoreSystemUnitUnitDefinition
ShopwareCoreContentMediaMediaDefinition --> ShopwareCoreSystemUserUserDefinition
ShopwareCoreSystemUserAggregateUserAccessKeyUserAccessKeyDefinition --> ShopwareCoreSystemUserUserDefinition
ShopwareCoreSystemStateMachineAggregationStateMachineHistoryStateMachineHistoryDefinition --> ShopwareCoreSystemUserUserDefinition
ShopwareCoreSystemUserAggregateUserRecoveryUserRecoveryDefinition --> ShopwareCoreSystemUserUserDefinition
ShopwareCoreSystemStateMachineAggregationStateMachineStateStateMachineStateDefinition --> ShopwareCoreSystemStateMachineStateMachineDefinition
ShopwareCoreSystemStateMachineAggregationStateMachineTransitionStateMachineTransitionDefinition --> ShopwareCoreSystemStateMachineStateMachineDefinition
ShopwareCoreSystemStateMachineStateMachineTranslationDefinition --> ShopwareCoreSystemStateMachineStateMachineDefinition
ShopwareCoreSystemStateMachineAggregationStateMachineHistoryStateMachineHistoryDefinition --> ShopwareCoreSystemStateMachineStateMachineDefinition
ShopwareCoreSystemStateMachineAggregationStateMachineTransitionStateMachineTransitionDefinition --> ShopwareCoreSystemStateMachineAggregationStateMachineStateStateMachineStateDefinition
ShopwareCoreSystemStateMachineAggregationStateMachineStateStateMachineStateTranslationDefinition --> ShopwareCoreSystemStateMachineAggregationStateMachineStateStateMachineStateDefinition
ShopwareCoreCheckoutOrderAggregateOrderTransactionOrderTransactionDefinition --> ShopwareCoreSystemStateMachineAggregationStateMachineStateStateMachineStateDefinition
ShopwareCoreCheckoutOrderAggregateOrderDeliveryOrderDeliveryDefinition --> ShopwareCoreSystemStateMachineAggregationStateMachineStateStateMachineStateDefinition
ShopwareCoreCheckoutOrderOrderDefinition --> ShopwareCoreSystemStateMachineAggregationStateMachineStateStateMachineStateDefinition
ShopwareCoreSystemStateMachineAggregationStateMachineHistoryStateMachineHistoryDefinition --> ShopwareCoreSystemStateMachineAggregationStateMachineStateStateMachineStateDefinition
ShopwareCoreSystemNumberRangeAggregateNumberRangeTypeNumberRangeTypeDefinition --> ShopwareCoreSystemNumberRangeNumberRangeDefinition
ShopwareCoreSystemNumberRangeAggregateNumberRangeSalesChannelNumberRangeSalesChannelDefinition --> ShopwareCoreSystemNumberRangeNumberRangeDefinition
ShopwareCoreSystemNumberRangeAggregateNumberRangeStateNumberRangeStateDefinition --> ShopwareCoreSystemNumberRangeNumberRangeDefinition
ShopwareCoreSystemNumberRangeNumberRangeDefinition --> ShopwareCoreSystemNumberRangeAggregateNumberRangeTranslationNumberRangeTranslationDefinition
ShopwareCoreSystemNumberRangeAggregateNumberRangeTypeNumberRangeTypeDefinition --> ShopwareCoreSystemNumberRangeAggregateNumberRangeSalesChannelNumberRangeSalesChannelDefinition
ShopwareCoreSystemNumberRangeAggregateNumberRangeTypeTranslationNumberRangeTypeTranslationDefinition --> ShopwareCoreSystemNumberRangeAggregateNumberRangeTypeNumberRangeTypeDefinition
ShopwareCoreContentCategoryCategoryDefinition --> ShopwareCoreContentCategoryCategoryDefinition
ShopwareCoreContentMediaMediaDefinition --> ShopwareCoreContentCategoryCategoryDefinition
ShopwareCoreContentCategoryAggregateCategoryTranslationCategoryTranslationDefinition --> ShopwareCoreContentCategoryCategoryDefinition
ShopwareCoreContentNavigationNavigationDefinition --> ShopwareCoreContentCategoryCategoryDefinition
ShopwareCoreContentProductAggregateProductCategoryProductCategoryDefinition --> ShopwareCoreContentCategoryCategoryDefinition
ShopwareCoreContentProductAggregateProductCategoryTreeProductCategoryTreeDefinition --> ShopwareCoreContentCategoryCategoryDefinition
ShopwareCoreContentCategoryAggregateCategoryTagCategoryTagDefinition --> ShopwareCoreContentCategoryCategoryDefinition
ShopwareCoreContentProductAggregateProductManufacturerProductManufacturerDefinition --> ShopwareCoreContentMediaMediaDefinition
ShopwareCoreContentProductAggregateProductMediaProductMediaDefinition --> ShopwareCoreContentMediaMediaDefinition
ShopwareCoreContentMediaAggregateMediaTranslationMediaTranslationDefinition --> ShopwareCoreContentMediaMediaDefinition
ShopwareCoreContentMediaAggregateMediaThumbnailMediaThumbnailDefinition --> ShopwareCoreContentMediaMediaDefinition
ShopwareCoreContentMediaAggregateMediaFolderMediaFolderDefinition --> ShopwareCoreContentMediaMediaDefinition
ShopwareCoreContentPropertyAggregatePropertyGroupOptionPropertyGroupOptionDefinition --> ShopwareCoreContentMediaMediaDefinition
ShopwareCoreContentMediaAggregateMediaTagMediaTagDefinition --> ShopwareCoreContentMediaMediaDefinition
ShopwareCoreContentMediaMediaDefinition --> ShopwareCoreContentMailTemplateAggregateMailTemplateMediaMailTemplateMediaDefinition
ShopwareCoreCheckoutShippingShippingMethodDefinition --> ShopwareCoreContentMediaMediaDefinition
ShopwareCoreContentMediaAggregateMediaFolderMediaFolderDefinition --> ShopwareCoreContentMediaAggregateMediaDefaultFolderMediaDefaultFolderDefinition
ShopwareCoreContentMediaAggregateMediaFolderMediaFolderDefinition --> ShopwareCoreContentMediaAggregateMediaFolderMediaFolderDefinition
ShopwareCoreContentMediaAggregateMediaFolderConfigurationMediaFolderConfigurationDefinition --> ShopwareCoreContentMediaAggregateMediaFolderMediaFolderDefinition
ShopwareCoreContentMediaAggregateMediaFolderConfigurationMediaThumbnailSizeMediaFolderConfigurationMediaThumbnailSizeDefinition --> ShopwareCoreContentMediaAggregateMediaThumbnailSizeMediaThumbnailSizeDefinition
ShopwareCoreContentMediaAggregateMediaFolderConfigurationMediaThumbnailSizeMediaFolderConfigurationMediaThumbnailSizeDefinition --> ShopwareCoreContentMediaAggregateMediaFolderConfigurationMediaFolderConfigurationDefinition
ShopwareCoreContentProductProductDefinition --> ShopwareCoreContentProductProductDefinition
ShopwareCoreContentProductAggregateProductManufacturerProductManufacturerDefinition --> ShopwareCoreContentProductProductDefinition
ShopwareCoreContentProductAggregateProductMediaProductMediaDefinition --> ShopwareCoreContentProductProductDefinition
ShopwareCoreContentProductAggregateProductPriceProductPriceDefinition --> ShopwareCoreContentProductProductDefinition
ShopwareCoreContentProductAggregateProductPropertyProductPropertyDefinition --> ShopwareCoreContentProductProductDefinition
ShopwareCoreContentProductAggregateProductCategoryProductCategoryDefinition --> ShopwareCoreContentProductProductDefinition
ShopwareCoreContentProductAggregateProductTagProductTagDefinition --> ShopwareCoreContentProductProductDefinition
ShopwareCoreContentProductProductDefinition --> ShopwareCoreFrameworkSearchSearchDocumentDefinition
ShopwareCoreContentProductAggregateProductCategoryTreeProductCategoryTreeDefinition --> ShopwareCoreContentProductProductDefinition
ShopwareCoreContentProductAggregateProductTranslationProductTranslationDefinition --> ShopwareCoreContentProductProductDefinition
ShopwareCoreContentProductAggregateProductConfiguratorSettingProductConfiguratorSettingDefinition --> ShopwareCoreContentProductProductDefinition
ShopwareCoreContentProductAggregateProductOptionProductOptionDefinition --> ShopwareCoreContentProductProductDefinition
ShopwareCoreContentProductAggregateProductVisibilityProductVisibilityDefinition --> ShopwareCoreContentProductProductDefinition
ShopwareCoreContentProductProductDefinition --> ShopwareStorefrontFrameworkSeoSeoUrlSeoUrlDefinition
ShopwareCoreContentPropertyAggregatePropertyGroupOptionPropertyGroupOptionDefinition --> ShopwareCoreContentProductAggregateProductConfiguratorSettingProductConfiguratorSettingDefinition
ShopwareCoreContentRuleRuleDefinition --> ShopwareCoreContentProductAggregateProductPriceProductPriceDefinition
ShopwareCoreContentPropertyAggregatePropertyGroupOptionPropertyGroupOptionDefinition --> ShopwareCoreContentProductAggregateProductPropertyProductPropertyDefinition
ShopwareCoreContentProductAggregateProductManufacturerTranslationProductManufacturerTranslationDefinition --> ShopwareCoreContentProductAggregateProductManufacturerProductManufacturerDefinition
ShopwareCoreContentPropertyAggregatePropertyGroupOptionPropertyGroupOptionDefinition --> ShopwareCoreContentProductAggregateProductOptionProductOptionDefinition
ShopwareCoreContentNavigationNavigationDefinition --> ShopwareCoreContentCmsCmsPageDefinition
ShopwareCoreContentNavigationAggregateNavigationTranslationNavigationTranslationDefinition --> ShopwareCoreContentNavigationNavigationDefinition
ShopwareCoreContentNavigationNavigationDefinition --> ShopwareCoreContentNavigationNavigationDefinition
ShopwareCoreContentRuleAggregateRuleConditionRuleConditionDefinition --> ShopwareCoreContentRuleRuleDefinition
ShopwareCoreCheckoutDiscountSurchargeDiscountSurchargeDefinition --> ShopwareCoreContentRuleRuleDefinition
ShopwareCoreCheckoutShippingAggregateShippingMethodPriceShippingMethodPriceDefinition --> ShopwareCoreContentRuleRuleDefinition
ShopwareCoreCheckoutShippingShippingMethodDefinition --> ShopwareCoreContentRuleRuleDefinition
ShopwareCoreCheckoutPaymentAggregatePaymentMethodRulesPaymentMethodRuleDefinition --> ShopwareCoreContentRuleRuleDefinition
ShopwareCoreContentRuleRuleDefinition --> ShopwareCoreCheckoutPromotionPromotionDefinition
ShopwareCoreContentRuleAggregateRuleConditionRuleConditionDefinition --> ShopwareCoreContentRuleAggregateRuleConditionRuleConditionDefinition
ShopwareCoreContentProductStreamAggregateProductStreamTranslationProductStreamTranslationDefinition --> ShopwareCoreContentProductStreamProductStreamDefinition
ShopwareCoreContentProductStreamAggregateProductStreamFilterProductStreamFilterDefinition --> ShopwareCoreContentProductStreamProductStreamDefinition
ShopwareCoreContentProductStreamAggregateProductStreamFilterProductStreamFilterDefinition --> ShopwareCoreContentProductStreamAggregateProductStreamFilterProductStreamFilterDefinition
ShopwareCoreContentPropertyAggregatePropertyGroupOptionPropertyGroupOptionDefinition --> ShopwareCoreContentPropertyPropertyGroupDefinition
ShopwareCoreContentPropertyAggregatePropertyGroupTranslationPropertyGroupTranslationDefinition --> ShopwareCoreContentPropertyPropertyGroupDefinition
ShopwareCoreContentPropertyAggregatePropertyGroupOptionTranslationPropertyGroupOptionTranslationDefinition --> ShopwareCoreContentPropertyAggregatePropertyGroupOptionPropertyGroupOptionDefinition
ShopwareCoreCheckoutCustomerAggregateCustomerGroupCustomerGroupDefinition --> ShopwareCoreCheckoutCustomerCustomerDefinition
ShopwareCoreCheckoutPaymentPaymentMethodDefinition --> ShopwareCoreCheckoutCustomerCustomerDefinition
ShopwareCoreCheckoutCustomerAggregateCustomerAddressCustomerAddressDefinition --> ShopwareCoreCheckoutCustomerCustomerDefinition
ShopwareCoreCheckoutOrderAggregateOrderCustomerOrderCustomerDefinition --> ShopwareCoreCheckoutCustomerCustomerDefinition
ShopwareCoreCheckoutCustomerAggregateCustomerTagCustomerTagDefinition --> ShopwareCoreCheckoutCustomerCustomerDefinition
ShopwareCoreCheckoutCustomerAggregateCustomerGroupCustomerGroupDefinition --> ShopwareCoreCheckoutCustomerAggregateCustomerGroupTranslationCustomerGroupTranslationDefinition
ShopwareCoreCheckoutOrderAggregateOrderCustomerOrderCustomerDefinition --> ShopwareCoreCheckoutOrderOrderDefinition
ShopwareCoreCheckoutOrderAggregateOrderAddressOrderAddressDefinition --> ShopwareCoreCheckoutOrderOrderDefinition
ShopwareCoreCheckoutOrderAggregateOrderDeliveryOrderDeliveryDefinition --> ShopwareCoreCheckoutOrderOrderDefinition
ShopwareCoreCheckoutOrderAggregateOrderLineItemOrderLineItemDefinition --> ShopwareCoreCheckoutOrderOrderDefinition
ShopwareCoreCheckoutOrderAggregateOrderTransactionOrderTransactionDefinition --> ShopwareCoreCheckoutOrderOrderDefinition
ShopwareCoreCheckoutOrderOrderDefinition --> ShopwareCoreCheckoutDocumentDocumentDefinition
ShopwareCoreCheckoutOrderAggregateOrderTagOrderTagDefinition --> ShopwareCoreCheckoutOrderOrderDefinition
ShopwareCoreCheckoutOrderAggregateOrderDeliveryOrderDeliveryDefinition --> ShopwareCoreCheckoutOrderAggregateOrderAddressOrderAddressDefinition
ShopwareCoreCheckoutShippingShippingMethodDefinition --> ShopwareCoreCheckoutOrderAggregateOrderDeliveryOrderDeliveryDefinition
ShopwareCoreCheckoutOrderAggregateOrderDeliveryPositionOrderDeliveryPositionDefinition --> ShopwareCoreCheckoutOrderAggregateOrderDeliveryOrderDeliveryDefinition
ShopwareCoreCheckoutOrderAggregateOrderLineItemOrderLineItemDefinition --> ShopwareCoreCheckoutOrderAggregateOrderDeliveryPositionOrderDeliveryPositionDefinition
ShopwareCoreCheckoutOrderAggregateOrderLineItemOrderLineItemDefinition --> ShopwareCoreCheckoutOrderAggregateOrderLineItemOrderLineItemDefinition
ShopwareCoreCheckoutPaymentPaymentMethodDefinition --> ShopwareCoreCheckoutOrderAggregateOrderTransactionOrderTransactionDefinition
ShopwareCoreCheckoutPaymentAggregatePaymentMethodTranslationPaymentMethodTranslationDefinition --> ShopwareCoreCheckoutPaymentPaymentMethodDefinition
ShopwareCoreCheckoutPaymentAggregatePaymentMethodRulesPaymentMethodRuleDefinition --> ShopwareCoreCheckoutPaymentPaymentMethodDefinition
ShopwareCoreCheckoutShippingShippingMethodDefinition --> ShopwareCoreContentDeliveryTimeDeliveryTimeDefinition
ShopwareCoreCheckoutShippingAggregateShippingMethodTranslationShippingMethodTranslationDefinition --> ShopwareCoreCheckoutShippingShippingMethodDefinition
ShopwareCoreCheckoutShippingAggregateShippingMethodPriceShippingMethodPriceDefinition --> ShopwareCoreCheckoutShippingShippingMethodDefinition
ShopwareCoreCheckoutShippingAggregateShippingMethodTagShippingMethodTagDefinition --> ShopwareCoreCheckoutShippingShippingMethodDefinition
ShopwareCoreCheckoutDiscountSurchargeAggregateDiscountSurchargeTranslationDiscountSurchargeTranslationDefinition --> ShopwareCoreCheckoutDiscountSurchargeDiscountSurchargeDefinition
@enduml
