@startuml
' uncomment the line below if you're using computer with a retina display
' skinparam dpi 300
!define Table(name,desc) class name as "desc" << (T,#FFAAAA) >>
!define ForeignTable(name,desc) class name as "desc" << (T,#ada6a6) >>
!define TranslationTable(name,desc) class name as "desc" << (I,#4286f4) >>
' we use bold for primary key
' green color for unique
' and underscore for not_null
!define primary_key(x) <b>x</b>
!define unique(x) <color:green>x</color>
!define not_null(x) <u>x</u>
' other tags available:
' <i></i>
' <back:COLOR></color>, where color is a color name or html color code
' (#FFAACC)
' see: http://plantuml.com/classes.html#More
hide methods
hide stereotypes
hide empty members
skinparam backgroundColor #FFFFFF

' entities

Table(ShopwareCoreContentConfigurationConfigurationGroupDefinition, "configuration_group\n(Product variant configuration)") {
   primary_key(id) id
   name translated
   description translated
   not_null(displayType) string
   not_null(sortingType) string
   attributes translated
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   translated json
}
Table(ShopwareCoreContentConfigurationAggregateConfigurationGroupOptionConfigurationGroupOptionDefinition, "configuration_group_option\n(Product variant option)") {
   primary_key(id) id
   not_null(groupId) foreignKey
   name translated
   position translated
   colorHexCode string
   mediaId foreignKey
   attributes translated
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   translated json
}
TranslationTable(ShopwareCoreContentConfigurationAggregateConfigurationGroupOptionTranslationConfigurationGroupOptionTranslationDefinition, "configuration_group_option_translation\n((Translations))") {
   not_null(name) string
   position int
   attributes attributes
   primary_key(configurationGroupOptionId) foreignKey
   primary_key(languageId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
TranslationTable(ShopwareCoreContentConfigurationAggregateConfigurationGroupTranslationConfigurationGroupTranslationDefinition, "configuration_group_translation\n((Translations))") {
   not_null(name) string
   description longText
   attributes attributes
   primary_key(configurationGroupId) foreignKey
   primary_key(languageId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
ForeignTable(ShopwareCoreContentMediaMediaDefinition, "media") {
}
ForeignTable(ShopwareCoreContentProductAggregateProductConfiguratorProductConfiguratorDefinition, "product_configurator") {
}
ForeignTable(ShopwareCoreContentProductAggregateProductDatasheetProductDatasheetDefinition, "product_property") {
}
ForeignTable(ShopwareCoreContentProductAggregateProductVariationProductVariationDefinition, "product_variation") {
}
ForeignTable(ShopwareCoreFrameworkLanguageLanguageDefinition, "language") {
}

' relationshipd

ShopwareCoreContentConfigurationAggregateConfigurationGroupOptionConfigurationGroupOptionDefinition --> ShopwareCoreContentConfigurationConfigurationGroupDefinition
ShopwareCoreContentConfigurationAggregateConfigurationGroupTranslationConfigurationGroupTranslationDefinition --> ShopwareCoreContentConfigurationConfigurationGroupDefinition
ShopwareCoreContentConfigurationAggregateConfigurationGroupOptionConfigurationGroupOptionDefinition --> ShopwareCoreContentMediaMediaDefinition
ShopwareCoreContentConfigurationAggregateConfigurationGroupOptionTranslationConfigurationGroupOptionTranslationDefinition --> ShopwareCoreContentConfigurationAggregateConfigurationGroupOptionConfigurationGroupOptionDefinition
ShopwareCoreContentConfigurationAggregateConfigurationGroupOptionConfigurationGroupOptionDefinition --> ShopwareCoreContentProductAggregateProductConfiguratorProductConfiguratorDefinition
ShopwareCoreContentConfigurationAggregateConfigurationGroupOptionConfigurationGroupOptionDefinition --> ShopwareCoreContentProductAggregateProductDatasheetProductDatasheetDefinition
ShopwareCoreContentConfigurationAggregateConfigurationGroupOptionConfigurationGroupOptionDefinition --> ShopwareCoreContentProductAggregateProductVariationProductVariationDefinition
ShopwareCoreContentConfigurationAggregateConfigurationGroupOptionTranslationConfigurationGroupOptionTranslationDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
ShopwareCoreContentConfigurationAggregateConfigurationGroupTranslationConfigurationGroupTranslationDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
@enduml
