@startuml
' uncomment the line below if you're using computer with a retina display
' skinparam dpi 300
!define Table(name,desc) class name as "desc" << (T,#FFAAAA) >>
!define ForeignTable(name,desc) class name as "desc" << (T,#ada6a6) >>
!define TranslationTable(name,desc) class name as "desc" << (I,#4286f4) >>
' we use bold for primary key
' green color for unique
' and underscore for not_null
!define primary_key(x) <b>x</b>
!define unique(x) <color:green>x</color>
!define not_null(x) <u>x</u>
' other tags available:
' <i></i>
' <back:COLOR></color>, where color is a color name or html color code
' (#FFAACC)
' see: http://plantuml.com/classes.html#More
hide methods
hide stereotypes
hide empty members
skinparam backgroundColor #FFFFFF

' entities

Table(ShopwareCoreContentNavigationNavigationDefinition, "navigation\n(SalesChannel Navigation)") {
   primary_key(id) id
   primary_key(versionId) version
   parentId parentFk
   not_null(parentVersionId) referenceVersion
   categoryId foreignKey
   categoryVersionId referenceVersion
   cmsPageId foreignKey
   name translated
   slotConfig translated
   level treeLevel
   path treePath
   childCount childCount
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   translated json
}
TranslationTable(ShopwareCoreContentNavigationAggregateNavigationTranslationNavigationTranslationDefinition, "navigation_translation\n((Translations))") {
   not_null(name) string
   slotConfig json
   primary_key(navigationId) foreignKey
   primary_key(languageId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   primary_key(navigationVersionId) referenceVersion
}
ForeignTable(ShopwareCoreContentCategoryCategoryDefinition, "category") {
}
ForeignTable(ShopwareCoreContentCmsCmsPageDefinition, "cms_page") {
}
ForeignTable(ShopwareCoreSystemSalesChannelSalesChannelDefinition, "sales_channel") {
}
ForeignTable(ShopwareCoreFrameworkLanguageLanguageDefinition, "language") {
}

' relationshipd

ShopwareCoreContentNavigationNavigationDefinition --> ShopwareCoreContentCategoryCategoryDefinition
ShopwareCoreContentNavigationNavigationDefinition --> ShopwareCoreContentCmsCmsPageDefinition
ShopwareCoreContentNavigationAggregateNavigationTranslationNavigationTranslationDefinition --> ShopwareCoreContentNavigationNavigationDefinition
ShopwareCoreContentNavigationNavigationDefinition --> ShopwareCoreContentNavigationNavigationDefinition
ShopwareCoreContentNavigationNavigationDefinition --> ShopwareCoreSystemSalesChannelSalesChannelDefinition
ShopwareCoreContentNavigationAggregateNavigationTranslationNavigationTranslationDefinition --> ShopwareCoreFrameworkLanguageLanguageDefinition
@enduml
