enqueue:
    default:
        transport:
            dsn: "null:"
            factory_service: Shopware\Core\Framework\MessageQueue\Enqueue\ConnectionFactoryFactory
        client: ~
        consumption:
            # the time in milliseconds queue consumer waits for a message
            receive_timeout: 1000
