monolog:
    channels: [ats_context_cache_trace]
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
        ats_context_cache_trace:
            type: stream
            path: "%kernel.logs_dir%/ats-context-cache-trace.log"
            level: error
            channels: [ats_context_cache_trace]
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
