@startuml
' uncomment the line below if you're using computer with a retina display
' skinparam dpi 300
!define Table(name,desc) class name as "desc" << (T,#FFAAAA) >>
!define ForeignTable(name,desc) class name as "desc" << (T,#ada6a6) >>
!define TranslationTable(name,desc) class name as "desc" << (I,#4286f4) >>
' we use bold for primary key
' green color for unique
' and underscore for not_null
!define primary_key(x) <b>x</b>
!define unique(x) <color:green>x</color>
!define not_null(x) <u>x</u>
' other tags available:
' <i></i>
' <back:COLOR></color>, where color is a color name or html color code
' (#FFAACC)
' see: http://plantuml.com/classes.html#More
hide methods
hide stereotypes
hide empty members
skinparam backgroundColor #FFFFFF

' entities

Table(ShopwareCoreFrameworkLogging, "Shopware\Core\Framework\Log\n(__EMPTY__)") {
   log_entry Table
}
Table(ShopwareCoreFrameworkAcl, "Shopware\Core\Framework\Api\Acl\n(__EMPTY__)") {
   acl_resource Table
   acl_role Table
   acl_user_role Table
}
Table(ShopwareCoreFrameworkCustomField, "Shopware\Core\System\CustomField\n(Custom Fields/EAV)") {
   custom_field Table
   custom_field_set Table
   custom_field_set_relation Table
}
Table(ShopwareCoreFrameworkEvent, "Shopware\Core\Framework\Event\n(Business events)") {
   event_action Table
}
Table(ShopwareCoreFrameworkMessageQueue, "Shopware\Core\Framework\MessageQueue\n(Asynchronous messaging)") {
   dead_message Table
   message_queue_stats Table
}
Table(ShopwareCoreFrameworkPlugin, "Shopware\Core\Framework\Plugin\n(Plugins)") {
   plugin Table
   plugin_translation Table
}
Table(ShopwareCoreFrameworkScheduledTask, "Shopware\Core\Framework\MessageQueue\ScheduledTask\n(Scheduled messages)") {
   scheduled_task Table
}
Table(ShopwareCoreFrameworkLanguage, "Shopware\Core\System\Language\n(Languages)") {
   language Table
}
Table(ShopwareCoreFrameworkSeo, "Shopware\Core\Content\Seo\n(__EMPTY__)") {
   seo_url Table
   seo_url_template Table
   main_category Table
}
Table(ShopwareCoreSystemSalesChannel, "Shopware\Core\System\SalesChannel\n(Sales channels)") {
   sales_channel Table
   sales_channel_translation Table
   sales_channel_country Table
   sales_channel_currency Table
   sales_channel_domain Table
   sales_channel_language Table
   sales_channel_payment_method Table
   sales_channel_shipping_method Table
   sales_channel_type Table
   sales_channel_type_translation Table
}
Table(ShopwareCoreSystemCountry, "Shopware\Core\System\Country\n(Countries)") {
   country Table
   country_state Table
   country_state_translation Table
   country_translation Table
}
Table(ShopwareCoreSystemCurrency, "Shopware\Core\System\Currency\n(Currencies)") {
   currency Table
   currency_translation Table
}
Table(ShopwareCoreSystemLocale, "Shopware\Core\System\Locale\n(Locales)") {
   locale Table
   locale_translation Table
}
Table(ShopwareCoreFrameworkSnippet, "Shopware\Core\System\Snippet\n(Custom placeholder translations)") {
   snippet_set Table
   snippet Table
}
Table(ShopwareCoreSystemSalutation, "Shopware\Core\System\Salutation\n(Solutations)") {
   salutation Table
   salutation_translation Table
}
Table(ShopwareCoreSystemTax, "Shopware\Core\System\Tax\n(Taxes)") {
   tax Table
}
Table(ShopwareCoreSystemUnit, "Shopware\Core\System\Unit\n(Units)") {
   unit Table
   unit_translation Table
}
Table(ShopwareCoreSystemUser, "Shopware\Core\System\User\n(Admin Accounts)") {
   user Table
   user_access_key Table
   user_recovery Table
}
Table(ShopwareCoreSystemIntegration, "Shopware\Core\System\Integration\n(O-Auth integrations)") {
   integration Table
}
Table(ShopwareCoreSystemStateMachine, "Shopware\Core\System\StateMachine\n(State machine)") {
   state_machine Table
   state_machine_translation Table
   state_machine_state Table
   state_machine_state_translation Table
   state_machine_transition Table
   state_machine_history Table
}
Table(ShopwareCoreSystemSystemConfig, "Shopware\Core\System\SystemConfig\n(System configuration)") {
   system_config Table
}
Table(ShopwareCoreSystemNumberRange, "Shopware\Core\System\NumberRange\n(Number ranges)") {
   number_range Table
   number_range_sales_channel Table
   number_range_state Table
   number_range_type Table
   number_range_type_translation Table
   number_range_translation Table
}
Table(ShopwareCoreSystemTag, "Shopware\Core\System\Tag\n(Tags)") {
   tag Table
}
Table(ShopwareCoreContentCategory, "Shopware\Core\Content\Category\n(Categories)") {
   category Table
   category_translation Table
   category_tag Table
}
Table(ShopwareCoreContentMedia, "Shopware\Core\Content\Media\n(Media/File management)") {
   media Table
   media_default_folder Table
   media_thumbnail Table
   media_translation Table
   media_folder Table
   media_thumbnail_size Table
   media_folder_configuration Table
   media_folder_configuration_media_thumbnail_size Table
   media_tag Table
}
Table(ShopwareCoreContentProduct, "Shopware\Core\Content\Product\n(Products)") {
   product Table
   product_category Table
   product_tag Table
   product_configurator_setting Table
   product_price Table
   product_property Table
   product_search_keyword Table
   product_keyword_dictionary Table
   product_review Table
   product_manufacturer Table
   product_manufacturer_translation Table
   product_media Table
   product_translation Table
   product_option Table
   product_category_tree Table
   product_visibility Table
}
Table(ShopwareCoreContentDeliveryTime, "Shopware\Core\System\DeliveryTime\n(Delivery time)") {
   delivery_time Table
   delivery_time_translation Table
}
Table(ShopwareCoreContentNewsletter, "Shopware\Core\Content\Newsletter\n(Newsletter)") {
   newsletter_recipient Table
   newsletter_recipient_tag Table
}
Table(ShopwareCoreContentRule, "Shopware\Core\Content\Rule\n(Rules)") {
   rule Table
   rule_condition Table
}
Table(ShopwareCoreContentProductStream, "Shopware\Core\Content\ProductStream\n(Product streams)") {
   product_stream Table
   product_stream_translation Table
   product_stream_filter Table
}
Table(ShopwareCoreContentProperty, "Shopware\Core\Content\Property\n(Property)") {
   property_group Table
   property_group_option Table
   property_group_option_translation Table
   property_group_translation Table
}
Table(ShopwareCoreContentCms, "Shopware\Core\Content\Cms\n(Content Management)") {
   cms_page Table
   cms_page_translation Table
   cms_section Table
   cms_block Table
   cms_slot Table
   cms_slot_translation Table
}
Table(ShopwareCoreContentMailTemplate, "Shopware\Core\Content\MailTemplate\n(Mailing)") {
   mail_template Table
   mail_template_translation Table
   mail_template_type Table
   mail_template_type_translation Table
   mail_template_sales_channel Table
   mail_template_media Table
   mail_header_footer Table
   mail_header_footer_translation Table
}
Table(ShopwareCoreContentImportExport, "Shopware\Core\Content\ImportExport\n(Import/Export)") {
   import_export_profile Table
   import_export_log Table
   import_export_file Table
}
Table(ShopwareCoreCheckoutCustomer, "Shopware\Core\Checkout\Customer\n(Customer)") {
   customer Table
   customer_group_translation Table
   customer_address Table
   customer_group Table
   customer_tag Table
}
Table(ShopwareCoreCheckoutDocument, "Shopware\Core\Checkout\Document\n(Printed works)") {
   document Table
   document_type Table
   document_type_translation Table
   document_base_config Table
   document_base_config_sales_channel Table
}
Table(ShopwareCoreCheckoutOrder, "Shopware\Core\Checkout\Order\n(Orders)") {
   order Table
   order_address Table
   order_customer Table
   order_delivery Table
   order_delivery_position Table
   order_line_item Table
   order_tag Table
   order_transaction Table
}
Table(ShopwareCoreCheckoutPayment, "Shopware\Core\Checkout\Payment\n(Payments)") {
   payment_method Table
   payment_method_translation Table
}
Table(ShopwareCoreCheckoutPromotion, "Shopware\Core\Checkout\Promotion\n(Promotions)") {
   promotion Table
   promotion_sales_channel Table
   promotion_individual_code Table
   promotion_discount Table
   promotion_discount_rule Table
   promotion_setgroup Table
   promotion_setgroup_rule Table
   promotion_order_rule Table
   promotion_persona_customer Table
   promotion_persona_rule Table
   promotion_cart_rule Table
   promotion_translation Table
   promotion_discount_prices Table
}
Table(ShopwareCoreCheckoutShipping, "Shopware\Core\Checkout\Shipping\n(Shipping)") {
   shipping_method Table
   shipping_method_tag Table
   shipping_method_price Table
   shipping_method_translation Table
}
Table(ShopwareStorefront, "Shopware\Storefront\n(Storefront)") {
   theme Table
   theme_translation Table
   theme_sales_channel Table
   theme_media Table
}

' relationshipd

ShopwareCoreFrameworkAcl --> ShopwareCoreFrameworkAcl
ShopwareCoreSystemUser --> ShopwareCoreFrameworkAcl
ShopwareCoreFrameworkCustomField --> ShopwareCoreFrameworkCustomField
ShopwareCoreFrameworkScheduledTask --> ShopwareCoreFrameworkMessageQueue
ShopwareCoreFrameworkPlugin --> ShopwareCoreFrameworkPlugin
ShopwareCoreCheckoutPayment --> ShopwareCoreFrameworkPlugin
ShopwareCoreFrameworkLanguage --> ShopwareCoreFrameworkPlugin
ShopwareCoreFrameworkLanguage --> ShopwareCoreFrameworkLanguage
ShopwareCoreSystemLocale --> ShopwareCoreFrameworkLanguage
ShopwareCoreSystemSalesChannel --> ShopwareCoreFrameworkLanguage
ShopwareCoreCheckoutCustomer --> ShopwareCoreFrameworkLanguage
ShopwareCoreContentNewsletter --> ShopwareCoreFrameworkLanguage
ShopwareCoreCheckoutOrder --> ShopwareCoreFrameworkLanguage
ShopwareCoreContentCategory --> ShopwareCoreFrameworkLanguage
ShopwareCoreSystemCountry --> ShopwareCoreFrameworkLanguage
ShopwareCoreSystemCurrency --> ShopwareCoreFrameworkLanguage
ShopwareCoreContentMedia --> ShopwareCoreFrameworkLanguage
ShopwareCoreCheckoutPayment --> ShopwareCoreFrameworkLanguage
ShopwareCoreContentProduct --> ShopwareCoreFrameworkLanguage
ShopwareCoreCheckoutShipping --> ShopwareCoreFrameworkLanguage
ShopwareCoreSystemUnit --> ShopwareCoreFrameworkLanguage
ShopwareCoreContentProperty --> ShopwareCoreFrameworkLanguage
ShopwareCoreSystemSalutation --> ShopwareCoreFrameworkLanguage
ShopwareCoreContentProductStream --> ShopwareCoreFrameworkLanguage
ShopwareCoreSystemStateMachine --> ShopwareCoreFrameworkLanguage
ShopwareCoreContentCms --> ShopwareCoreFrameworkLanguage
ShopwareCoreContentMailTemplate --> ShopwareCoreFrameworkLanguage
ShopwareCoreCheckoutDocument --> ShopwareCoreFrameworkLanguage
ShopwareCoreSystemNumberRange --> ShopwareCoreFrameworkLanguage
ShopwareCoreContentDeliveryTime --> ShopwareCoreFrameworkLanguage
ShopwareCoreCheckoutPromotion --> ShopwareCoreFrameworkLanguage
ShopwareCoreFrameworkSeo --> ShopwareCoreFrameworkLanguage
ShopwareStorefront --> ShopwareCoreFrameworkLanguage
ShopwareCoreSystemSalesChannel --> ShopwareCoreFrameworkSeo
ShopwareCoreContentProduct --> ShopwareCoreFrameworkSeo
ShopwareCoreContentCategory --> ShopwareCoreFrameworkSeo
ShopwareCoreSystemSalesChannel --> ShopwareCoreSystemSalesChannel
ShopwareCoreCheckoutCustomer --> ShopwareCoreSystemSalesChannel
ShopwareCoreSystemCurrency --> ShopwareCoreSystemSalesChannel
ShopwareCoreCheckoutPayment --> ShopwareCoreSystemSalesChannel
ShopwareCoreCheckoutShipping --> ShopwareCoreSystemSalesChannel
ShopwareCoreSystemCountry --> ShopwareCoreSystemSalesChannel
ShopwareCoreCheckoutOrder --> ShopwareCoreSystemSalesChannel
ShopwareCoreSystemSystemConfig --> ShopwareCoreSystemSalesChannel
ShopwareCoreContentCategory --> ShopwareCoreSystemSalesChannel
ShopwareCoreContentProduct --> ShopwareCoreSystemSalesChannel
ShopwareCoreContentMailTemplate --> ShopwareCoreSystemSalesChannel
ShopwareCoreContentNewsletter --> ShopwareCoreSystemSalesChannel
ShopwareCoreSystemNumberRange --> ShopwareCoreSystemSalesChannel
ShopwareCoreCheckoutPromotion --> ShopwareCoreSystemSalesChannel
ShopwareCoreCheckoutDocument --> ShopwareCoreSystemSalesChannel
ShopwareStorefront --> ShopwareCoreSystemSalesChannel
ShopwareCoreFrameworkSnippet --> ShopwareCoreSystemSalesChannel
ShopwareCoreSystemCountry --> ShopwareCoreSystemCountry
ShopwareCoreCheckoutCustomer --> ShopwareCoreSystemCountry
ShopwareCoreCheckoutOrder --> ShopwareCoreSystemCountry
ShopwareCoreSystemCurrency --> ShopwareCoreSystemCurrency
ShopwareCoreCheckoutOrder --> ShopwareCoreSystemCurrency
ShopwareCoreCheckoutShipping --> ShopwareCoreSystemCurrency
ShopwareCoreCheckoutPromotion --> ShopwareCoreSystemCurrency
ShopwareCoreSystemLocale --> ShopwareCoreSystemLocale
ShopwareCoreSystemUser --> ShopwareCoreSystemLocale
ShopwareCoreFrameworkSnippet --> ShopwareCoreFrameworkSnippet
ShopwareCoreSystemSalutation --> ShopwareCoreSystemSalutation
ShopwareCoreCheckoutCustomer --> ShopwareCoreSystemSalutation
ShopwareCoreCheckoutOrder --> ShopwareCoreSystemSalutation
ShopwareCoreContentNewsletter --> ShopwareCoreSystemSalutation
ShopwareCoreContentProduct --> ShopwareCoreSystemTax
ShopwareCoreContentProduct --> ShopwareCoreSystemUnit
ShopwareCoreSystemUnit --> ShopwareCoreSystemUnit
ShopwareCoreContentMedia --> ShopwareCoreSystemUser
ShopwareCoreSystemUser --> ShopwareCoreSystemUser
ShopwareCoreSystemStateMachine --> ShopwareCoreSystemUser
ShopwareCoreContentImportExport --> ShopwareCoreSystemUser
ShopwareCoreSystemStateMachine --> ShopwareCoreSystemStateMachine
ShopwareCoreCheckoutOrder --> ShopwareCoreSystemStateMachine
ShopwareCoreSystemNumberRange --> ShopwareCoreSystemNumberRange
ShopwareCoreContentProduct --> ShopwareCoreSystemTag
ShopwareCoreContentMedia --> ShopwareCoreSystemTag
ShopwareCoreContentCategory --> ShopwareCoreSystemTag
ShopwareCoreCheckoutCustomer --> ShopwareCoreSystemTag
ShopwareCoreCheckoutOrder --> ShopwareCoreSystemTag
ShopwareCoreCheckoutShipping --> ShopwareCoreSystemTag
ShopwareCoreContentNewsletter --> ShopwareCoreSystemTag
ShopwareCoreContentCategory --> ShopwareCoreContentCategory
ShopwareCoreContentMedia --> ShopwareCoreContentCategory
ShopwareCoreContentProduct --> ShopwareCoreContentCategory
ShopwareCoreContentCms --> ShopwareCoreContentCategory
ShopwareCoreContentMedia --> ShopwareCoreContentMedia
ShopwareCoreContentProduct --> ShopwareCoreContentMedia
ShopwareCoreContentProperty --> ShopwareCoreContentMedia
ShopwareCoreContentMailTemplate --> ShopwareCoreContentMedia
ShopwareCoreCheckoutDocument --> ShopwareCoreContentMedia
ShopwareCoreCheckoutShipping --> ShopwareCoreContentMedia
ShopwareCoreCheckoutPayment --> ShopwareCoreContentMedia
ShopwareCoreCheckoutOrder --> ShopwareCoreContentMedia
ShopwareCoreContentCms --> ShopwareCoreContentMedia
ShopwareStorefront --> ShopwareCoreContentMedia
ShopwareCoreContentProduct --> ShopwareCoreContentProduct
ShopwareCoreContentDeliveryTime --> ShopwareCoreContentProduct
ShopwareCoreContentProperty --> ShopwareCoreContentProduct
ShopwareCoreContentRule --> ShopwareCoreContentProduct
ShopwareCoreCheckoutCustomer --> ShopwareCoreContentProduct
ShopwareCoreCheckoutShipping --> ShopwareCoreContentDeliveryTime
ShopwareCoreContentDeliveryTime --> ShopwareCoreContentDeliveryTime
ShopwareCoreContentNewsletter --> ShopwareCoreContentNewsletter
ShopwareCoreContentRule --> ShopwareCoreContentRule
ShopwareCoreCheckoutShipping --> ShopwareCoreContentRule
ShopwareCoreCheckoutPayment --> ShopwareCoreContentRule
ShopwareCoreCheckoutPromotion --> ShopwareCoreContentRule
ShopwareCoreContentProductStream --> ShopwareCoreContentProductStream
ShopwareCoreContentProperty --> ShopwareCoreContentProperty
ShopwareCoreContentCms --> ShopwareCoreContentCms
ShopwareCoreContentMailTemplate --> ShopwareCoreContentMailTemplate
ShopwareCoreContentImportExport --> ShopwareCoreContentImportExport
ShopwareCoreCheckoutCustomer --> ShopwareCoreCheckoutCustomer
ShopwareCoreCheckoutPayment --> ShopwareCoreCheckoutCustomer
ShopwareCoreCheckoutOrder --> ShopwareCoreCheckoutCustomer
ShopwareCoreCheckoutPromotion --> ShopwareCoreCheckoutCustomer
ShopwareCoreCheckoutDocument --> ShopwareCoreCheckoutDocument
ShopwareCoreCheckoutOrder --> ShopwareCoreCheckoutDocument
ShopwareCoreCheckoutOrder --> ShopwareCoreCheckoutOrder
ShopwareCoreCheckoutShipping --> ShopwareCoreCheckoutOrder
ShopwareCoreCheckoutPayment --> ShopwareCoreCheckoutOrder
ShopwareCoreCheckoutPayment --> ShopwareCoreCheckoutPayment
ShopwareCoreCheckoutPromotion --> ShopwareCoreCheckoutPromotion
ShopwareCoreCheckoutShipping --> ShopwareCoreCheckoutShipping
ShopwareStorefront --> ShopwareStorefront
@enduml
