@startuml
' uncomment the line below if you're using computer with a retina display
' skinparam dpi 300
!define Table(name,desc) class name as "desc" << (T,#FFAAAA) >>
!define ForeignTable(name,desc) class name as "desc" << (T,#ada6a6) >>
!define TranslationTable(name,desc) class name as "desc" << (I,#4286f4) >>
' we use bold for primary key
' green color for unique
' and underscore for not_null
!define primary_key(x) <b>x</b>
!define unique(x) <color:green>x</color>
!define not_null(x) <u>x</u>
' other tags available:
' <i></i>
' <back:COLOR></color>, where color is a color name or html color code
' (#FFAACC)
' see: http://plantuml.com/classes.html#More
hide methods
hide stereotypes
hide empty members
skinparam backgroundColor #FFFFFF

' entities

Table(ShopwareCoreFrameworkAclResourceAclResourceDefinition, "acl_resource\n(__EMPTY__)") {
   primary_key(resource) string
   primary_key(privilege) string
   primary_key(aclRoleId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
Table(ShopwareCoreFrameworkAclRoleAclRoleDefinition, "acl_role\n(__EMPTY__)") {
   primary_key(id) id
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
   not_null(name) string
}
Table(ShopwareCoreFrameworkAclRoleAclUserRoleDefinition, "acl_user_role\n(M:N Mapping)") {
   primary_key(userId) foreignKey
   primary_key(aclRoleId) foreignKey
   not_null(createdAt) createdAt
   not_null(updatedAt) updatedAt
}
ForeignTable(ShopwareCoreSystemUserUserDefinition, "user") {
}

' relationshipd

ShopwareCoreFrameworkAclRoleAclRoleDefinition --> ShopwareCoreFrameworkAclResourceAclResourceDefinition
ShopwareCoreFrameworkAclRoleAclUserRoleDefinition --> ShopwareCoreFrameworkAclRoleAclRoleDefinition
ShopwareCoreFrameworkAclRoleAclUserRoleDefinition --> ShopwareCoreSystemUserUserDefinition
@enduml
