
const MEDIA_GRID_PREVIEW_TYPE_LIST = 'media-grid-preview-as-list';
const MEDIA_GRID_PREVIEW_TYPE_GRID = 'media-grid-preview-as-grid';

export default {
    MEDIA_GRID_PREVIEW_TYPE_LIST: MEDIA_GRID_PREVIEW_TYPE_LIST,
    MEDIA_GRID_PREVIEW_TYPE_GRID: MEDIA_GRID_PREVIEW_TYPE_GRID
};
