<?php declare(strict_types=1);

namespace Shopware\Core\Content\ProductExport;

use Shopware\Core\Content\ProductStream\ProductStreamDefinition;
use Shopware\Core\Framework\DataAbstractionLayer\EntityDefinition;
use Shopware\Core\Framework\DataAbstractionLayer\Field\BoolField;
use Shopware\Core\Framework\DataAbstractionLayer\Field\DateTimeField;
use Shopware\Core\Framework\DataAbstractionLayer\Field\FkField;
use Shopware\Core\Framework\DataAbstractionLayer\Field\Flag\AllowHtml;
use Shopware\Core\Framework\DataAbstractionLayer\Field\Flag\DoNotUseContext;
use Shopware\Core\Framework\DataAbstractionLayer\Field\Flag\PrimaryKey;
use Shopware\Core\Framework\DataAbstractionLayer\Field\Flag\Required;
use Shopware\Core\Framework\DataAbstractionLayer\Field\IdField;
use Shopware\Core\Framework\DataAbstractionLayer\Field\IntField;
use Shopware\Core\Framework\DataAbstractionLayer\Field\LongTextField;
use Shopware\Core\Framework\DataAbstractionLayer\Field\ManyToOneAssociationField;
use Shopware\Core\Framework\DataAbstractionLayer\Field\StringField;
use Shopware\Core\Framework\DataAbstractionLayer\FieldCollection;
use Shopware\Core\Framework\Log\Package;
use Shopware\Core\System\Currency\CurrencyDefinition;
use Shopware\Core\System\SalesChannel\Aggregate\SalesChannelDomain\SalesChannelDomainDefinition;
use Shopware\Core\System\SalesChannel\SalesChannelDefinition;

#[Package('inventory')]
class ProductExportDefinition extends EntityDefinition
{
    final public const ENTITY_NAME = 'product_export';

    public function getEntityName(): string
    {
        return self::ENTITY_NAME;
    }

    public function getCollectionClass(): string
    {
        return ProductExportCollection::class;
    }

    public function getEntityClass(): string
    {
        return ProductExportEntity::class;
    }

    public function since(): ?string
    {
        return '6.1.0.0';
    }

    public function getHydratorClass(): string
    {
        return ProductExportHydrator::class;
    }

    protected function defineFields(): FieldCollection
    {
        return new FieldCollection([
            (new IdField('id', 'id'))->addFlags(new PrimaryKey(), new Required())->setDescription('Unique identity of Exported Product.'),
            (new FkField('product_stream_id', 'productStreamId', ProductStreamDefinition::class))->addFlags(new Required())->setDescription('Unique identity of product stream .'),
            (new FkField('storefront_sales_channel_id', 'storefrontSalesChannelId', SalesChannelDefinition::class))->addFlags(new Required(), new DoNotUseContext())->setDescription('Unique identity of storefront\'s Sales Channel.'),
            (new FkField('sales_channel_id', 'salesChannelId', SalesChannelDefinition::class))->addFlags(new Required())->setDescription('Unique identity of salesChannel.'),
            (new FkField('sales_channel_domain_id', 'salesChannelDomainId', SalesChannelDomainDefinition::class))->addFlags(new Required())->setDescription('Unique identity of sales Channel Domain.'),
            (new FkField('currency_id', 'currencyId', CurrencyDefinition::class))->addFlags(new Required())->setDescription('Unique identity of currency.'),
            (new StringField('file_name', 'fileName'))->addFlags(new Required())->setDescription('Name of the file.'),
            (new StringField('access_key', 'accessKey'))->addFlags(new Required())->setDescription('Access key to admin api.'),
            (new StringField('encoding', 'encoding'))->addFlags(new Required())->setDescription('Type of encoding like UTF-8 or ASCII.'),
            (new StringField('file_format', 'fileFormat'))->addFlags(new Required())->setDescription('Type of file formats or extensions like CSV or JSON.'),
            (new BoolField('include_variants', 'includeVariants'))->setDescription('Toggling the product export settings to determine whether or not to include the variants.'),
            (new BoolField('generate_by_cronjob', 'generateByCronjob'))->addFlags(new Required())->setDescription('To determine whether the product exports are generated by cron jobs or live.'),
            (new DateTimeField('generated_at', 'generatedAt'))->setDescription('Date and time when the product exports was last generated.'),
            (new IntField('interval', 'interval'))->addFlags(new Required())->setDescription('The frequency interval when the product exports are generated like every 5 min, 1 hour, etc.'),
            (new LongTextField('header_template', 'headerTemplate'))->addFlags(new AllowHtml(false))->setDescription('Property to specify the custom content displayed for the header section.'),
            (new LongTextField('body_template', 'bodyTemplate'))->addFlags(new AllowHtml(false))->setDescription('Property to specify the custom content displayed for the body section.'),
            (new LongTextField('footer_template', 'footerTemplate'))->addFlags(new AllowHtml(false))->setDescription('Property to specify the custom content displayed for the footer section.'),
            (new BoolField('paused_schedule', 'pausedSchedule'))->setDescription('ProductExport generation is paused.'),
            (new BoolField('is_running', 'isRunning'))->setDescription('ProductExport is right now generating or not.'),
            new ManyToOneAssociationField('productStream', 'product_stream_id', ProductStreamDefinition::class, 'id', false),
            new ManyToOneAssociationField('storefrontSalesChannel', 'storefront_sales_channel_id', SalesChannelDefinition::class, 'id', false),
            new ManyToOneAssociationField('salesChannel', 'sales_channel_id', SalesChannelDefinition::class, 'id', false),
            new ManyToOneAssociationField('salesChannelDomain', 'sales_channel_domain_id', SalesChannelDomainDefinition::class, 'id', false),
            new ManyToOneAssociationField('currency', 'currency_id', CurrencyDefinition::class, 'id', false),
        ]);
    }
}
