<?php declare(strict_types=1);

namespace Shopware\Core\System\Snippet;

use Shopware\Core\Framework\Log\Package;

/**
 * @internal
 */
#[Package('discovery')]
final class SnippetPatterns
{
    /**
     * Locales accepted in addition to the regular ICU locale set. Pseudo-languages
     * are typically generated by translation tools like Crowdin and used for
     * in-context translation workflows (e.g. proofreading, length checks,
     * translatability audits) — not for real customer-facing content.
     *
     * Maps each pseudo-locale code to its display name. ICU/CLDR resolution
     * (e.g. "ach" → "Acholi") is intentionally bypassed because these locales are
     * placeholders, not real languages.
     *
     * @var array<string, string>
     */
    public const ALLOWED_PSEUDO_LOCALES = [
        'ach-UG' => 'Acholi',
    ];

    /**
     * Territory label assigned to every pseudo-locale entry in the locale table.
     * Renders as `${name} (${territory})` in the admin locale picker, so e.g.
     * `ach-UG` shows up as "Acholi (Pseudo Language)".
     */
    public const PSEUDO_LOCALE_TERRITORY = 'Pseudo Language';

    /**
     * Locale pattern based on BCP 47,
     * restricted to ISO 639-1 (2-letter) language codes.
     * Excludes 3-letter prefixes like `ger` or `eng`.
     */
    public const LOCALE_PATTERN =
        '(?P<locale>' .
        '(?P<language>[a-z]{2})' .              // ISO 639-1 language prefix
        '(?:[_-](?P<script>[A-Z][a-z]{3}))?' .  // optional script (Hant, Latn, Cyrl)
        '(?:[_-](?P<region>[A-Z]{2}|\d{3}))?' . // optional region (DE, US, 419)
        ')';

    public const CORE_SNIPPET_FILE_PATTERN =
        '/^(?P<domain>.+?)\.' .                 // domain (e.g. messages, storefront, swag-cms-extensions etc.)
        self::LOCALE_PATTERN .                  // locale (e.g. en-GB, de, zh-Hant-TW)
        '(?:\.(?P<isBase>base))?\.json$/';      // optional "base" suffix and .json file extension

    public const ADMIN_SNIPPET_FILE_PATTERN = '/^' . self::LOCALE_PATTERN . '\.json$/';

    public const COMPLETE_LOCALE_PATTERN = '/^' . self::LOCALE_PATTERN . '$/';

    private function __construct()
    {
    }
}
