name: Cachix

on:
  push:
    branches:
      - trunk
    paths:
      - devenv.nix
      - devenv.yaml
      - devenv.lock

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Use Devenv Cache
        uses: cachix/cachix-action@v12
        with:
          name: devenv

      - name: Use Shopware Cache
        uses: cachix/cachix-action@v12
        with:
          name: shopware
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Install Devenv
        run: nix-env -if https://github.com/cachix/devenv/tarball/main

      - name: Warmup cache
        run: cachix watch-exec shopware devenv shell php -v
        env:
          NIXPKGS_ALLOW_UNFREE: 1

