name: Danger
on:
  pull_request_target:

jobs:
  pr:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
            ref: ${{ github.event.pull_request.base.ref }}

      - name: Danger
        uses: docker://ghcr.io/shyim/danger-php:latest
        with:
          args: ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PULL_REQUEST_ID: ${{ github.event.pull_request.number }}
