name: Qodana
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        with:
          use-caches: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
