name: Downstream

on:
  pull_request:
  workflow_dispatch:
    inputs:
      nightly:
        default: ""
  workflow_call:
    inputs:
      nightly:
        type: string
        default: ""

jobs:

  rufus:
    name: "Rufus"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: octo-sts/action@v1.0.0
        id: sts-collaborator
        with:
          scope: shopware
          identity: ReadCollaborators
      - name: Is collaborator
        id: collaborator
        env:
          GH_TOKEN: ${{ steps.sts-collaborator.outputs.token }}
        run: |
          if gh api /repos/shopware/Rufus/collaborators/${{ github.triggering_actor }}; then
            echo "IS_COLLABORATOR=1" >> $GITHUB_OUTPUT
          else
            echo "IS_COLLABORATOR=0" >> $GITHUB_OUTPUT
          fi
          ${{ github.triggering_actor }}
      - name: Rufus
        uses: shopware/github-actions/downstream@main
        if: ${{ steps.collaborator.outputs.IS_COLLABORATOR }}
        with:
          repo: shopware/rufus
          workflow: Downstream
          ref: trunk
          timeout: 15m
          env:
            NIGHTLY=${{ inputs.nightly }}
  
  commercial:
    name: Commercial
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Commercial
        uses: shopware/github-actions/downstream@main
        with:
          repo: shopware/SwagCommercial
          workflow: Downstream
          ref: trunk
          timeout: 20m
          env:
            NIGHTLY=${{ inputs.nightly }}