name: Sync Repo

on:
  push:
    branches:
      - trunk
      - 6.[0-9]*.x
      - 6.[0-9]*.[0-9]*.x
  workflow_call:

jobs:
  sync:
    runs-on: ubuntu-24.04
    if: github.repository == 'shopware/shopware'
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: shopware/octo-sts-action@main
        id: sts-shopware-private
        with:
          scope: shopware
          identity: ShopwarePrivateSync

      - name: Push to private fork
        run: |
          git config "http.https://github.com/shopware/shopware-private.git/.extraheader" "AUTHORIZATION: basic $(echo -n "x-access-token:${{ steps.sts-shopware-private.outputs.token }}" | base64)"
          git remote add private https://github.com/shopware/shopware-private.git
          git fetch private
          git push -f private ${{ github.ref }}

