name: Visual Tests

on: 
  workflow_dispatch:
    inputs:
      update-snapshots:
        description: "Update snapshots?"
        type: boolean
  

 # Allow updating snapshots during manual runs
  workflow_call:
    inputs:
      update-snapshots:
        description: "Update snapshots?"
        type: boolean

jobs:
  visual-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          - name: Platform
          - name: Install
    env:
      SHOPWARE_HTTP_CACHE_ENABLED: 0
      SHOPWARE_DISABLE_UPDATE_CHECK: "true"
      BLUE_GREEN_DEPLOYMENT: 1
      COMPOSER_ROOT_VERSION: 6.7.9999999-dev
    steps:
      - name: Setup Shopware
        uses: shopware/setup-shopware@main
        with:
          shopware-version: ${{ github.ref }}
          shopware-repository: ${{ github.repository }}
          install: true
          install-admin: true
          install-storefront: true
          env: prod

      - name: Start web server
        run: symfony server:start -d
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        working-directory: tests/acceptance
        run: npm ci
      - name: Install Playwright Browsers
        working-directory: tests/acceptance
        run: npx playwright install --with-deps chromium
      - name: Set up cache
        id: cache 
        uses: actions/cache@v4
        with:
          key: cache/${{github.repository}}/${{github.ref}}
          restore-keys: cache/${{github.repository}}/refs/heads/trunk
          path: .test/**
      - name: Initialize snapshots
        if: ${{steps.cache.outputs.cache-hit != 'true' || inputs.update-snapshots == 'true'}}
        run: npx playwright test --project=Visual --update-snapshots --reporter html
      - name: Run your tests
        continue-on-error: true
        env:
            CURRENTS_PROJECT_ID: ${{ secrets.CURRENTS_PROJECT_ID_VISUAL }}
            CURRENTS_RECORD_KEY: ${{ secrets.CURRENTS_RECORD_KEY }}
        if: ${{ !contains(github.workflow_ref, 'nightly') }}
        working-directory: tests/acceptance
        run: npx pwc --project=Visual
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.project.name }}
          path: tests/acceptance/test-results/
          retention-days: 3