# this is a CI/CD template for shopware plugins
# - SwagPluginTemplate: https://gitlab.shopware.com/shopware/6/templates/swagplugintemplate/-/blob/trunk/.gitlab-ci.yml
# - gitlab docs: https://docs.gitlab.com/ee/ci/yaml/#include

stages:
    - build
    - test
    - E2E
    - visual
    - deploy

variables:
    GIT_STRATEGY: clone
    PROJECT_ROOT: ${CI_PROJECT_DIR}
    WEB_DOCUMENT_ROOT: $CI_PROJECT_DIR/public
    LOG_STDOUT: $CI_PROJECT_DIR/var/log/stdout.log
    MYSQL_ROOT_PASSWORD: root
    DATABASE_URL: 'mysql://root:root@database:3306/root'
    APP_SECRET: 'devsecret'
    APP_URL: http://localhost:8000
    # cypress
    CYPRESS_baseUrl: http://localhost:8000
    CYPRESS_localUsage: 1
    CYPRESS_shopwareRoot: $CI_PROJECT_DIR
    SHOPWARE_HTTP_CACHE_ENABLED: 0
    CYPRESS_screenshotsFolder: $CI_PROJECT_DIR/var/log/screenshots
    # percy
    PERCY_BRANCH: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    PERCY_COMMIT: $CI_COMMIT_SHA
    # things plugins might want to override
    PLUGIN_NAME:
        value: ${CI_PROJECT_TITLE}
        description: 'Plugin name. Default is ${CI_PROJECT_TITLE}'
    PLATFORM_BRANCH:
        value: trunk
        description: 'The shopware/platform branch that is used'
    DEV_IMAGE:
        value: shopware/development:8.1-composer-2
        description: 'base docker image used. Can be changed to test other php versions. Example: shopware/development:8.0-composer-2'
    PLUGIN_SOURCE_DIR:
        value: src/
        description: 'Defines the src dir. Use "" (empty string) if it starts in the root dir.'
    MYSQL_IMAGE:
        value: mysql:5.7
        description: 'database image to use. Possible values: "mysql:8.0.19" (also change $MYSQL_CMD!), "mariadb:10.3", "mariadb:10.4"'
    MYSQL_CMD:
        value: mysqld
        description: 'Copy from $MYSQL8_CMD for mysql >= 8'
    MYSQL8_CMD:
        value: 'mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password --sql-require-primary-key=ON'
        description: 'mysql 8 needs a special auth option to work with shopware/platform'
    BROWSER:
        value: chrome
        description: 'Browser to use for cypress and percy tests. Possible values: "chrome", "firefox", "electron"'
    STOREFRONT_CYPRESS_SPEC:
        value: ''
        description: 'Can be used instead of the tagging to define which storefront spec files should be used. Example: "cypress/integration/content/**/*,cypress/integration/catalogue/**/*"'
    ADMIN_CYPRESS_SPEC:
        value: ''
        description: 'Can be used instead of the tagging to define which storefront spec files should be used. Example: "cypress/integration/content/**/*,cypress/integration/catalogue/**/*"'
    STOREFRONT_PERCY_SPEC:
        value: ''
        description: 'Can be used instead of the tagging to define which storefront spec files should be used. Example: "cypress/integration/visual/**/*,cypress/integration/catalogue/**/*"'
    ADMIN_PERCY_SPEC:
        value: ''
        description: 'Can be used instead of the tagging to define which storefront spec files should be used. Example: "cypress/integration/visual/**/*,cypress/integration/catalogue/**/*"'
    PLUGIN_DEPENDENCIES:
        value: '[]'
        description: 'Plugin dependencies. Defined in json. Example: [{ "name": "SwagPayPal", "url": "gitlab.shopware.com/shopware/6/services/paypal", "branch": "master" }]'
    COMPOSER_DEPENDENCIES:
        value: '[]'
        description: 'Additional composer dependencies. Defined in json. Example: ["theiconic/name-parser", "amzn/amazon-pay-api-sdk-php:2.2.1"]'

workflow:
    rules:
        # do not run on push
        -   if: '$CI_PIPELINE_SOURCE == "push"'
            when: never
        -   if: '$CI_MERGE_REQUEST_LABELS =~ /.*branch::platform::match.*/'
            variables:
              PLATFORM_BRANCH: ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}
        -   when: always

.install_dependencies: &install_dependencies
  - apt-get update && apt-get install -y jq
  - |
    echo "${COMPOSER_DEPENDENCIES}"
    for package in $(echo "${COMPOSER_DEPENDENCIES}" | jq -r '.[]'); do
        composer require "${package}"
    done
  - |
    echo "${PLUGIN_DEPENDENCIES}"
    for plugin64 in $(echo "${PLUGIN_DEPENDENCIES}" | jq -r '.[] | @base64'); do
        plugin="$(echo $plugin64 | base64 -d)"
        plugin_name="$(echo "$plugin" | jq -r .name)"
        plugin_url="$(echo "$plugin" | jq -r .url)"
        plugin_branch="$(echo "$plugin" | jq -r .branch)"
        git clone "https://gitlab-ci-token:${CI_JOB_TOKEN}@${plugin_url}" --branch "${plugin_branch}" "${PROJECT_ROOT}/custom/plugins/${plugin_name}"
        npm ci --prefix  "${PROJECT_ROOT}/custom/plugins/${plugin_name}/Resources/app/administration" || true
        npm ci --prefix  "${PROJECT_ROOT}/custom/plugins/${plugin_name}/src/Resources/app/administration" || true
        npm ci --prefix  "${PROJECT_ROOT}/custom/plugins/${plugin_name}/Resources/app/storefront" || true
        npm ci --prefix  "${PROJECT_ROOT}/custom/plugins/${plugin_name}/src/Resources/app/storefront" || true
    done
  - bin/console plugin:refresh
  - |
    for plugin64 in $(echo "${PLUGIN_DEPENDENCIES}" | jq -r '.[] | @base64'); do
        plugin="$(echo $plugin64 | base64 -d)"
        plugin_name="$(echo "$plugin" | jq -r .name)"
        bin/console plugin:install --activate "${plugin_name}"
    done
  - bin/console cache:clear
  - bin/console plugin:list

default:
    image: $DEV_IMAGE
    tags:
      - t3.medium
    services:
        - name: mysql:5.7
          alias: database
          entrypoint: [ "sh", "-c", "docker-entrypoint.sh $MYSQL_CMD" ]
    before_script:
        - export PLUGIN_NAME="${PLUGIN_NAME:-${CI_PROJECT_TITLE}}"
        - echo "$PLUGIN_NAME"
        - zip -rq plugin.zip .
        - mv plugin.zip /tmp/plugin.zip
        - rm -Rf .* * || true
        - echo "Checkout platform branch $PLATFORM_BRANCH"
        - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/6/product/platform.git . --branch $PLATFORM_BRANCH
        - mkdir -p custom/plugins || true
        - unzip -q /tmp/plugin.zip -d custom/plugins/$PLUGIN_NAME
        - composer install --no-interaction
        - mkdir -p config/jwt || true
        - bin/console system:generate-jwt || true
        - bin/console system:install --drop-database --basic-setup --force >/dev/null
        - bin/console plugin:refresh
        - bin/console plugin:install --activate $PLUGIN_NAME
        - >
          if bin/console debug:container --parameter kernel.plugin_infos --format json | grep -q "$PLUGIN_NAME";
            then echo "$PLUGIN_NAME is active";
            else echo "$PLUGIN_NAME is not active"; exit 1;
          fi
        - *install_dependencies
        - bin/console bundle:dump
        - bin/console assets:install
        # run php as root to prevent permission issues
        - SERVICE_PHPFPM_OPTS=--allow-to-run-as-root CONTAINER_UID=root /entrypoint supervisord > /dev/null 2>&1 &
        - cd custom/plugins/$PLUGIN_NAME
        - composer dump-autoload
        - mkdir -p vendor/shopware
        - ln -s $PROJECT_ROOT/src/Core vendor/shopware/core
        - ln -s $PROJECT_ROOT/src/Storefront vendor/shopware/storefront

.build-js: &build-js
    - $CI_PROJECT_DIR/bin/console bundle:dump
    - $CI_PROJECT_DIR/bin/console framework:schema -s 'entity-schema' $CI_PROJECT_DIR/src/Administration/Resources/app/administration/test/_mocks_/entity-schema.json
    - '(cd $CI_PROJECT_DIR/src/Administration/Resources/app/administration/ && npm ci && npm run build)'
    - '(cd $CI_PROJECT_DIR/src/Storefront/Resources/app/storefront/ && npm ci && npm run production && node copy-to-vendor.js)'
    -  $CI_PROJECT_DIR/bin/console assets:install

build zip:
    stage: build
    image:
        name: ghcr.io/friendsofshopware/platform-plugin-dev:v6.4.17
        entrypoint: [""]
    rules:
        - exists:
              - composer.json
    variables:
        ADMIN_PATH: $CI_PROJECT_DIR/src/Administration/Resources/app/administration
        STOREFRONT_PATH: $CI_PROJECT_DIR/src/Storefront/Resources/app/storefront
        SHOPWARE_ADMIN_BUILD_ONLY_EXTENSIONS: 1
    script:
        - (cd ${PLUGIN_SOURCE_DIR}Resources/app/administration && npm ci) || true
        - (cd ${PLUGIN_SOURCE_DIR}Resources/app/storefront && npm ci) || true
        - *build-js
        - rm -rf "Resources/app/administration/node_modules" || true
        - rm -rf "Resources/app/storefront/node_modules" || true
        - rm -rf vendor composer.lock || true
        - cd $CI_PROJECT_DIR/custom/plugins/$PLUGIN_NAME
        - composer config --unset 'repositories.platform-packages'
        - plugin-uploader ext:zip --strategy=plain -- "$PWD"
        - '[[ -r $PLUGIN_NAME.zip ]] || (echo "failed to create $PLUGIN_NAME.zip. Please run ./bin/init $PLUGIN_NAME" && exit 1)'
        - mv $PLUGIN_NAME.zip ${CI_PROJECT_DIR}/$PLUGIN_NAME.zip
    artifacts:
        name: '${CI_PROJECT_TITLE}.zip'
        paths:
            - '*.zip'

validate zip:
    stage: test
    image:
        name: ghcr.io/friendsofshopware/platform-plugin-dev:v6.4.17
        entrypoint: [""]
    variables:
        GIT_STRATEGY: none
    needs:
        - build zip
    rules:
        - exists:
              - composer.json
          if: '$CI_PROJECT_TITLE != "SwagPluginTemplate"'
    before_script: []
    script:
        - export PLUGIN_NAME="${PLUGIN_NAME:-${CI_PROJECT_TITLE}}"
        - plugin-uploader ext:validate $PWD/$PLUGIN_NAME.zip

phpunit:
    stage: test
    needs: []
    rules:
        - exists:
              - phpunit.xml*
    script:
        - php
            -d pcov.enabled=1 -d pcov.directory=$PWD/src -d pcov.exclude='~(vendor|tests|node_modules)~'
            ${PROJECT_ROOT}/vendor/bin/phpunit
            --configuration phpunit.xml.dist
            --log-junit ${CI_PROJECT_DIR}/phpunit.junit.xml
            --colors=never
            --coverage-cobertura ${CI_PROJECT_DIR}/cobertura.xml
            --coverage-text | grep -v -E '^Shopware\\|^  Methods:' # do not output covered files lines
    coverage: '/^\s*Lines:\s*(\d+(?:\.\d+)?%)/'
    artifacts:
        when: always
        reports:
            junit: phpunit.junit.xml
            coverage_report:
                coverage_format: cobertura
                path: cobertura.xml

phpstan:
    stage: test
    needs: []
    rules:
        - exists:
              - phpstan.neon*
    script:
        - composer dump-autoload
        - >
          if [[ -r tests/TestBootstrap.php ]]; then
              php tests/TestBootstrap.php
          fi
        - php ${PROJECT_ROOT}/src/Core/DevOps/StaticAnalyze/PHPStan/phpstan-bootstrap.php
        - ${PROJECT_ROOT}/vendor/bin/phpstan analyze --error-format=gitlab --no-progress | tee ${CI_PROJECT_DIR}/phpstan-report.json
    artifacts:
        when: always
        reports:
            codequality: phpstan-report.json

ecs:
    stage: test
    needs: []
    rules:
        - exists:
              - ecs.php
    script:
        - ${PROJECT_ROOT}/vendor/bin/ecs

validate snippets:
    stage: test
    needs: []
    rules:
        - changes:
              - '**/*.json'
    script:
        - ${PROJECT_ROOT}/bin/console snippets:validate

jest (administration):
    stage: test
    needs: []
    rules:
        # exists does not support variables, so we cannot use ${PLUGIN_SOURCE_DIR} here
        - exists:
              - src/Resources/app/administration/jest.config.js
              - Resources/app/administration/jest.config.js
    variables:
        ADMIN_PATH: $CI_PROJECT_DIR/src/Administration/Resources/app/administration
        STOREFRONT_PATH: $CI_PROJECT_DIR/src/Storefront/Resources/app/storefront
    script:
        - '(cd $ADMIN_PATH && npm ci)'
        - $CI_PROJECT_DIR/bin/console framework:schema -s 'entity-schema' $ADMIN_PATH/test/_mocks_/entity-schema.json
        - cd ${PLUGIN_SOURCE_DIR}Resources/app/administration/
        - npm ci
        - '$(npm bin)/jest --config jest.config.js --ci'
    coverage: '/^\s?All files[^|]*\|[^|]*\s+([\d\.]+)/'

jest (storefront):
    stage: test
    needs: []
    rules:
        # exists does not support variables, so we cannot use ${PLUGIN_SOURCE_DIR} here
        - exists:
              - Resources/app/storefront/jest.config.js
              - src/Resources/app/storefront/jest.config.js
    variables:
        ADMIN_PATH: $CI_PROJECT_DIR/src/Administration/Resources/app/administration
        STOREFRONT_PATH: $CI_PROJECT_DIR/src/Storefront/Resources/app/storefront
    script:
        - *build-js
        - cd ${PLUGIN_SOURCE_DIR}Resources/app/storefront/
        - npm ci
        - '$(npm bin)/jest --config jest.config.js --ci'
    coverage: '/^\s?All files[^|]*\|[^|]*\s+([\d\.]+)/'

template filled:
    stage: test
    image: bash
    needs: []
    rules:
        - exists:
              - TEMPLATE
          if: $CI_PROJECT_TITLE != "SwagPluginTemplate"
    before_script: []
    script:
        - echo "run './bin/init $CI_PROJECT_TITLE'"
        - exit 1

.e2e-prepare: &e2e-prepare
    - *build-js
    - $CI_PROJECT_DIR/bin/console theme:compile
    - $CI_PROJECT_DIR/bin/console theme:change --all Storefront
    - $CI_PROJECT_DIR/bin/console assets:install
    - APP_ENV=e2e $CI_PROJECT_DIR/bin/console e2e:dump-db
    - cd ${PLUGIN_SOURCE_DIR}${E2E_PROJECT_PATH}
    - npm ci

.base e2e:
    stage: E2E
    needs: []
    script:
        - *e2e-prepare
        - >
          if [[ -z "$CYPRESS_SPEC" ]]; then
              echo "Running non visual tests"
              APP_ENV=e2e ./node_modules/.bin/cypress run --browser $BROWSER --headless --env grep=visual,invert=1
          else
              echo "Running specs: $CYPRESS_SPEC"
              APP_ENV=e2e ./node_modules/.bin/cypress run --browser $BROWSER --headless --spec "$CYPRESS_SPEC"
          fi
    after_script:
        - export PLUGIN_NAME="${PLUGIN_NAME:-${CI_PROJECT_TITLE}}"
        - cd custom/plugins/$PLUGIN_NAME/${PLUGIN_SOURCE_DIR}${E2E_PROJECT_PATH}
        - mkdir $CI_PROJECT_DIR/var/log/e2e || true
        - mkdir -p cypress/mochareports || true
        - npx mochawesome-merge cypress/results/mocha/*.json > cypress/mochareports/report.json
        - npx marge cypress/mochareports/*.json -f report -o mochareports
        - mv cypress/results/single-reports/*.xml $CI_PROJECT_DIR/var/log/e2e/ || true
        - mv mochareports/ $CI_PROJECT_DIR/var/log/e2e/ || true
    artifacts:
        when: always
        paths:
            - var/log/*
        reports:
            junit: var/log/e2e/*.xml

cypress admin:
    extends: .base e2e
    variables:
        E2E_PROJECT_PATH: Resources/app/administration/test/e2e/
        CYPRESS_SPEC: $ADMIN_CYPRESS_SPEC
        APP_ENV: e2e
    rules:
        -   exists:
                - Resources/app/administration/test/e2e/cypress.json
                - Resources/app/administration/test/e2e/cypress.config.js
                - src/Resources/app/administration/test/e2e/cypress.json
                - src/Resources/app/administration/test/e2e/cypress.config.js

cypress storefront:
    extends: .base e2e
    variables:
        E2E_PROJECT_PATH: Resources/app/storefront/test/e2e/
        CYPRESS_SPEC: $STOREFRONT_CYPRESS_SPEC
        APP_ENV: e2e
    rules:
        -   exists:
                - Resources/app/storefront/test/e2e/cypress.json
                - Resources/app/storefront/test/e2e/cypress.config.js
                - src/Resources/app/storefront/test/e2e/cypress.json
                - src/Resources/app/storefront/test/e2e/cypress.config.js

percy admin:
    extends: cypress admin
    stage: visual
    rules:
        -   if: '$CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"'
            when: never
        -   exists:
                - Resources/app/administration/test/e2e/.percy*
                - src/Resources/app/administration/test/e2e/.percy*
            if: '$CI_PIPELINE_SOURCE == "schedule" || $CI_MERGE_REQUEST_LABELS =~ /.*visual::all.*/'
        -   exists:
                - Resources/app/storefront/test/e2e/.percy*
                - src/Resources/app/storefront/test/e2e/.percy*
            when: manual
            allow_failure: true
    variables:
        E2E_PROJECT_PATH: Resources/app/administration/test/e2e/
        CYPRESS_SPEC: $ADMIN_CYPRESS_SPEC
        APP_ENV: e2e
        CYPRESS_usePercy: 1
    script:
        - *e2e-prepare
        - >
            if [[ -z "$ADMIN_PERCY_SPEC" ]]; then
                echo "Running visual tests"
                ./node_modules/.bin/percy exec -- ./node_modules/.bin/cypress run --browser $BROWSER --headless --env grep=visual
            else
                echo "Running specs: $CYPRESS_SPEC"
                ./node_modules/.bin/percy exec -- ./node_modules/.bin/cypress run --browser $BROWSER --headless --spec "$ADMIN_PERCY_SPEC"
            fi

percy storefront:
    extends: cypress storefront
    stage: visual
    rules:
        -   if: '$CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"'
            when: never
        -   exists:
                - Resources/app/storefront/test/e2e/.percy*
                - src/Resources/app/storefront/test/e2e/.percy*
            if: '$CI_PIPELINE_SOURCE == "schedule" || $CI_MERGE_REQUEST_LABELS =~ /.*visual::all.*/'
        -   exists:
                - Resources/app/storefront/test/e2e/.percy*
                - src/Resources/app/storefront/test/e2e/.percy*
            when: manual
            allow_failure: true
    variables:
        E2E_PROJECT_PATH: Resources/app/storefront/test/e2e/
        CYPRESS_SPEC: $STOREFRONT_CYPRESS_SPEC
        APP_ENV: e2e
        CYPRESS_usePercy: 1
    script:
        - *e2e-prepare
        - >
            if [[ -z "$STOREFRONT_PERCY_SPEC" ]]; then
                echo "Running visual tests"
                ./node_modules/.bin/percy exec -- ./node_modules/.bin/cypress run --browser $BROWSER --headless --env grep=visual
            else
                echo "Running specs: $CYPRESS_SPEC"
                ./node_modules/.bin/percy exec -- ./node_modules/.bin/cypress run --browser $BROWSER --headless --spec "$STOREFRONT_PERCY_SPEC"
            fi

upload zip to store:
    stage: deploy
    allow_failure: true
    environment:
        name: account.shopware.com
        url: 'https://account.shopware.com'
    image:
        name: ghcr.io/friendsofshopware/platform-plugin-dev:v6.4.17
        entrypoint: [""]
    variables:
        GIT_STRATEGY: none
    needs:
        - build zip
    rules:
        - exists:
              - composer.json
          if: '$ACCOUNT_USER && $ACCOUNT_PASSWORD && $CI_PROJECT_TITLE != "SwagPluginTemplate"'
          when: manual
    before_script: []
    script:
        - export PLUGIN_NAME="${PLUGIN_NAME:-${CI_PROJECT_TITLE}}"
        - plugin-uploader ext:upload "$(realpath "$PLUGIN_NAME.zip")"
